[%cx2 {|clip-path: url('#clip')|}];
[%cx2 {|clip-path: inset(50%)|}];
[%cx2 {|clip-path: path('M 20 20 H 80 V 30')|}];
[%cx2 {|clip-path: polygon(50% 100%, 0 0, 100% 0)|}];
[%cx2 {|clip-path: polygon(evenodd, 0% 0%, 50% 50%, 0% 100%)|}];
[%cx2 {|clip-path: polygon(nonzero, 0% 0%, 50% 50%, 0% 100%)|}];
[%cx2 {|clip-path: border-box|}];
[%cx2 {|clip-path: padding-box|}];
[%cx2 {|clip-path: content-box|}];
[%cx2 {|clip-path: margin-box|}];
[%cx2 {|clip-path: fill-box|}];
[%cx2 {|clip-path: stroke-box|}];
[%cx2 {|clip-path: view-box|}];
[%cx2 {|clip-path: none|}];
[%cx2 {|clip-rule: nonzero|}];
[%cx2 {|clip-rule: evenodd|}];
[%cx2 {|mask-image: none|}];
[%cx2 {|mask-image: linear-gradient(45deg, #333, #000)|}];
[%cx2 {|mask-image: url(image.png)|}];
[%cx2 {|mask-mode: alpha|}];
[%cx2 {|mask-mode: luminance|}];
[%cx2 {|mask-mode: match-source|}];
[%cx2 {|mask-repeat: repeat-x|}];
[%cx2 {|mask-repeat: repeat-y|}];
[%cx2 {|mask-repeat: repeat|}];
[%cx2 {|mask-repeat: space|}];
[%cx2 {|mask-repeat: round|}];
[%cx2 {|mask-repeat: no-repeat|}];
[%cx2 {|mask-repeat: repeat repeat|}];
[%cx2 {|mask-repeat: space repeat|}];
[%cx2 {|mask-repeat: round repeat|}];
[%cx2 {|mask-repeat: no-repeat repeat|}];
[%cx2 {|mask-repeat: repeat space|}];
[%cx2 {|mask-repeat: space space|}];
[%cx2 {|mask-repeat: round space|}];
[%cx2 {|mask-repeat: no-repeat space|}];
[%cx2 {|mask-repeat: repeat round|}];
[%cx2 {|mask-repeat: space round|}];
[%cx2 {|mask-repeat: round round|}];
[%cx2 {|mask-repeat: no-repeat round|}];
[%cx2 {|mask-repeat: repeat no-repeat|}];
[%cx2 {|mask-repeat: space no-repeat|}];
[%cx2 {|mask-repeat: round no-repeat|}];
[%cx2 {|mask-repeat: no-repeat no-repeat|}];
[%cx2 {|mask-position: center|}];
[%cx2 {|mask-position: center center|}];
[%cx2 {|mask-position: left 50%|}];
[%cx2 {|mask-position: bottom 10px right 20px|}];
[%cx2 {|mask-position: 1rem 1rem, center|}];
[%cx2 {|mask-clip: border-box|}];
[%cx2 {|mask-clip: padding-box|}];
[%cx2 {|mask-clip: content-box|}];
[%cx2 {|mask-clip: margin-box|}];
[%cx2 {|mask-clip: fill-box|}];
[%cx2 {|mask-clip: stroke-box|}];
[%cx2 {|mask-clip: view-box|}];
[%cx2 {|mask-clip: no-clip|}];
[%cx2 {|mask-origin: border-box|}];
[%cx2 {|mask-origin: padding-box|}];
[%cx2 {|mask-origin: content-box|}];
[%cx2 {|mask-origin: margin-box|}];
[%cx2 {|mask-origin: fill-box|}];
[%cx2 {|mask-origin: stroke-box|}];
[%cx2 {|mask-origin: view-box|}];
[%cx2 {|mask-size: auto|}];
[%cx2 {|mask-size: 10px|}];
[%cx2 {|mask-size: cover|}];
[%cx2 {|mask-size: contain|}];
[%cx2 {|mask-size: 10px|}];
[%cx2 {|mask-size: 50%|}];
[%cx2 {|mask-size: 10px auto|}];
[%cx2 {|mask-size: auto 10%|}];
[%cx2 {|mask-size: 50em 50%|}];
[%cx2 {|mask-composite: add|}];
[%cx2 {|mask-composite: subtract|}];
[%cx2 {|mask-composite: intersect|}];
[%cx2 {|mask-composite: exclude|}];
[%cx2 {|mask: top|}];
[%cx2 {|mask: space|}];
[%cx2 {|mask: url(image.png)|}];
[%cx2 {|mask: url(image.png) luminance|}];
[%cx2 {|mask: url(image.png) luminance top space|}];
[%cx2 {|mask-border-source: none|}];
[%cx2 {|mask-border-source: url(image.png)|}];
[%cx2 {|mask-border-slice: 0 fill|}];
[%cx2 {|mask-border-slice: 50% fill|}];
[%cx2 {|mask-border-slice: 1.1 fill|}];
[%cx2 {|mask-border-slice: 0 1 fill|}];
[%cx2 {|mask-border-slice: 0 1 2 fill|}];
[%cx2 {|mask-border-slice: 0 1 2 3 fill|}];
[%cx2 {|mask-border-width: auto|}];
[%cx2 {|mask-border-width: 10px|}];
[%cx2 {|mask-border-width: 50%|}];
[%cx2 {|mask-border-width: 1|}];
[%cx2 {|mask-border-width: 1.0|}];
[%cx2 {|mask-border-width: auto 1|}];
[%cx2 {|mask-border-width: auto 1 50%|}];
[%cx2 {|mask-border-width: auto 1 50% 1.1|}];
[%cx2 {|mask-border-outset: 0|}];
[%cx2 {|mask-border-outset: 1.1|}];
[%cx2 {|mask-border-outset: 0 1|}];
[%cx2 {|mask-border-outset: 0 1 2|}];
[%cx2 {|mask-border-outset: 0 1 2 3|}];
[%cx2 {|mask-border-repeat: stretch|}];
[%cx2 {|mask-border-repeat: repeat|}];
[%cx2 {|mask-border-repeat: round|}];
[%cx2 {|mask-border-repeat: space|}];
[%cx2 {|mask-border-repeat: stretch stretch|}];
[%cx2 {|mask-border-repeat: repeat stretch|}];
[%cx2 {|mask-border-repeat: round stretch|}];
[%cx2 {|mask-border-repeat: space stretch|}];
[%cx2 {|mask-border-repeat: stretch repeat|}];
[%cx2 {|mask-border-repeat: repeat repeat|}];
[%cx2 {|mask-border-repeat: round repeat|}];
[%cx2 {|mask-border-repeat: space repeat|}];
[%cx2 {|mask-border-repeat: stretch round|}];
[%cx2 {|mask-border-repeat: repeat round|}];
[%cx2 {|mask-border-repeat: round round|}];
[%cx2 {|mask-border-repeat: space round|}];
[%cx2 {|mask-border-repeat: stretch space|}];
[%cx2 {|mask-border-repeat: repeat space|}];
[%cx2 {|mask-border-repeat: round space|}];
[%cx2 {|mask-border-repeat: space space|}];
[%cx2 {|mask-border: url(image.png)|}];
[%cx2 {|mask-type: luminance|}];
[%cx2 {|mask-type: alpha|}];
