The atom-slot-keys class-name format (`_a_`, see
`Class_format`/`Hash_class.slot_class`) hashes its value only within one
(context, family[, mask]) bucket, not globally - so two atoms that
coincidentally land on the same class name but render different CSS must
be a hard build error, the same way two different `_id_` identities
colliding on the same hash already are (see identity-collision.t).

  $ cat > a.ml <<EOF
  > [@@@css "._a_abchgt{color:red;}"]
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css "._a_abchgt{color:blue;}"]
  > EOF

  $ styled-ppx.generate a.ml b.ml
  styled-ppx: atom class collision: "._a_abchgt{color:red;}" and "._a_abchgt{color:blue;}" both use class "_a_abchgt" but render different CSS - a value-hash collision (astronomically unlikely by chance; rerun with a different --namespace on one side, or file an issue).
  [1]

Same class, same content (the ordinary "same module compiled twice" case -
native + melange `copy_files`, vendoring) is not a collision: it dedups to
one rule like any other, same as today.

  $ cat > e.ml <<EOF
  > [@@@css "._a_same{color:green;}"]
  > EOF

  $ cat > f.ml <<EOF
  > [@@@css "._a_same{color:green;}"]
  > EOF

  $ styled-ppx.generate e.ml f.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_same{color:green;}
  }

A `_id_` (identity class) collision is a different, pre-existing check
(identity-collision.t) - this one only looks at `_a_` atom classes, so a
`_id_` clash alone doesn't trip it.

  $ cat > g.ml <<EOF
  > [@@@css "._id_shared{color:red;}"]
  > EOF

  $ cat > h.ml <<EOF
  > [@@@css "._id_shared{color:blue;}"]
  > EOF

  $ styled-ppx.generate g.ml h.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  ._id_shared{color:red;}
  ._id_shared{color:blue;}
  }

A `_in_` (interpolation-bundle) class sharing its name across different
content is NOT a collision - `Css_file.re`'s bundling already, legitimately,
puts several different declarations from one binding under one shared
class when they all carry a `$(...)` interpolation (this is exactly the
real shape `minify-interpolation.t` and the `reason-cx-*` snapshot tests
depend on - see the plan's "Collision check" notes for why the OLD,
unconditional version of this check broke them). The collision check must
recognize the `_in_` prefix and skip it entirely, in both directions.

  $ cat > i.ml <<EOF
  > [@@@css "._in_bundled{margin:var(--mySize-1);}"]
  > EOF

  $ cat > j.ml <<EOF
  > [@@@css "._in_bundled{padding:var(--mySize-2);}"]
  > EOF

  $ styled-ppx.generate i.ml j.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._in_bundled{margin:var(--mySize-1);}
  ._in_bundled{padding:var(--mySize-2);}
  }
