The atom-slot-keys class-name format (`css-`/`csi-`, see
`Class_format`/`Hash_class.slot_class`) hashes its value only within one
(context, family[, mask]) bucket, not globally - so two atoms that
coincidentally land on the same class name but render different CSS must
be a hard build error, the same way two different `cid-` identities
colliding on the same hash already are (see identity-collision.t).

  $ cat > a.ml <<EOF
  > [@@@css ".css-abchgt{color:red;}"]
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".css-abchgt{color:blue;}"]
  > EOF

  $ styled-ppx.generate a.ml b.ml
  styled-ppx: atom class collision: ".css-abchgt{color:red;}" and ".css-abchgt{color:blue;}" both use class "css-abchgt" but render different CSS - a value-hash collision (astronomically unlikely by chance; rerun with a different --namespace on one side, or file an issue).
  [1]

The `csi-` (`!important`) prefix is checked the same way.

  $ cat > c.ml <<EOF
  > [@@@css ".csi-abchgt{color:red !important;}"]
  > EOF

  $ cat > d.ml <<EOF
  > [@@@css ".csi-abchgt{color:blue !important;}"]
  > EOF

  $ styled-ppx.generate c.ml d.ml
  styled-ppx: atom class collision: ".csi-abchgt{color:red !important;}" and ".csi-abchgt{color:blue !important;}" both use class "csi-abchgt" but render different CSS - a value-hash collision (astronomically unlikely by chance; rerun with a different --namespace on one side, or file an issue).
  [1]

Same class, same content (the ordinary "same module compiled twice" case -
native + melange `copy_files`, vendoring) is not a collision: it dedups to
one rule like any other, same as today.

  $ cat > e.ml <<EOF
  > [@@@css ".css-same{color:green;}"]
  > EOF

  $ cat > f.ml <<EOF
  > [@@@css ".css-same{color:green;}"]
  > EOF

  $ styled-ppx.generate e.ml f.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-same{color:green;}

A `cid-` (identity class) collision is a different, pre-existing check
(identity-collision.t) - this one only looks at `css-`/`csi-` atom classes,
so a `cid-` clash alone doesn't trip it.

  $ cat > g.ml <<EOF
  > [@@@css ".cid-shared{color:red;}"]
  > EOF

  $ cat > h.ml <<EOF
  > [@@@css ".cid-shared{color:blue;}"]
  > EOF

  $ styled-ppx.generate g.ml h.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .cid-shared{color:red;}
  .cid-shared{color:blue;}

A `csv-` (interpolation-bundle) class sharing its name across different
content is NOT a collision - `Css_file.re`'s bundling already, legitimately,
puts several different declarations from one binding under one shared
class when they all carry a `$(...)` interpolation (this is exactly the
real shape `minify-interpolation.t` and the `reason-cx-*` snapshot tests
depend on - see the plan's "Collision check" notes for why the OLD,
unconditional version of this check broke them). The collision check must
recognize the `csv-` prefix and skip it entirely, in both directions.

  $ cat > i.ml <<EOF
  > [@@@css ".csv-bundled{margin:var(--mySize-1);}"]
  > EOF

  $ cat > j.ml <<EOF
  > [@@@css ".csv-bundled{padding:var(--mySize-2);}"]
  > EOF

  $ styled-ppx.generate i.ml j.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .csv-bundled{margin:var(--mySize-1);}
  .csv-bundled{padding:var(--mySize-2);}
