Fixed condition order: two pseudo-classes on the same compound selector
(`:hover`, `:focus`, `:active`) carry EQUAL specificity ((0,2,0) each), so
`rule_tier` buckets both as
`Conditional` and `sort_by_shorthand_first`'s own two keys (descendant-shape,
depth) tie. Before this change, the tie fell through to `List.stable_sort`,
which kept whichever order the rules already had when they reached the sort -
"first file, alphabetically by filename, wins"
(`order_modules_within_scope`'s `Order.sort ~key:(fun h -> h.filename)`
tie-break; see its doc). `sort_conditional_rules` now breaks it with a fixed
pseudo-class priority (StyleX's `PSEUDO_CLASS_PRIORITIES`, ported verbatim):
`:hover` (130) always sorts before `:focus` (150) and before `:active`
(170), so the higher-priority pseudo is always textually last and wins,
regardless of which file the generator reads first, and regardless of
either file's own declaration order - the fixed order applies even inside
one block too, see `tiers-condition-tie-single-block.t`.

Two library modules style the same kind of element the same way: module
`aaa` (read first - alphabetically before `zzz`) writes `:focus` before
`:hover` (its own intent, one block, plain CSS reading: hover overrides
focus); module `zzz` writes the opposite, `:hover` before `:focus` (its
own intent: focus overrides hover). Both use the SAME two atoms (same
declarations, so the same classes - the common case: two components
sharing one "danger" hover/focus color reuse the same atomized rule).

  $ cat > aaa_focus_then_hover.ml <<EOF
  > [@@@css "._a_2focusclr:focus{color:blue;}"]
  > [@@@css "._a_1hoverclr:hover{color:red;}"]
  > EOF

  $ cat > zzz_hover_then_focus.ml <<EOF
  > [@@@css "._a_1hoverclr:hover{color:red;}"]
  > [@@@css "._a_2focusclr:focus{color:blue;}"]
  > EOF

Passing the modules in either CLI order gives the SAME sheet - the fixed
pseudo priority, not file order, decides:

  $ styled-ppx.generate aaa_focus_then_hover.ml zzz_hover_then_focus.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_1hoverclr:hover{color:red;}
  ._a_2focusclr:focus{color:blue;}

  $ styled-ppx.generate zzz_hover_then_focus.ml aaa_focus_then_hover.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_1hoverclr:hover{color:red;}
  ._a_2focusclr:focus{color:blue;}

Both runs emit `:hover` then `:focus` - `:focus` (150) always outranks
`:hover` (130), so `:focus` is textually last and wins. For an element that
is BOTH hovered and focused: `color: blue` (focus) wins, in both modules,
regardless of either module's own written order.

A second, equal-specificity pair with different atoms (no dedup involved,
so this is not a dedup artifact - it is the sort's own tie-break):
`:hover` vs `:active`. `:active` (170) outranks `:hover` (130), so `:hover`
always sorts first and `:active` always wins, regardless of file or
argument order:

  $ cat > aaa_active_then_hover.ml <<EOF
  > [@@@css "._a_6activebg:active{background:green;}"]
  > [@@@css "._a_5hoverbg:hover{background:red;}"]
  > EOF

  $ cat > zzz_hover_then_active.ml <<EOF
  > [@@@css "._a_5hoverbg:hover{background:red;}"]
  > [@@@css "._a_6activebg:active{background:green;}"]
  > EOF

  $ styled-ppx.generate zzz_hover_then_active.ml aaa_active_then_hover.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_5hoverbg:hover{background:red;}
  ._a_6activebg:active{background:green;}

`:active` (green) wins for an element that is hovered AND active at once,
in both modules, whether or not that module's own source asked for it.

**Not a cross-block-only rule.** `packages/generate/test/tiers-condition-
tie-single-block.t` pins the SAME `:focus`/`:hover` pair inside ONE file:
the fixed order applies there too, reversing what plain CSS "last
declaration wins" would otherwise give for that one, unambiguous block.
See that file, and `documents/how-merging-works.md`'s "Known limits" for
the trade-off this accepts.
