Two different longidents that hash to the SAME identity (e.g. two
libraries' modules sharing a basename and binding name, with no
distinguishing `--namespace`) are a real collision only when their
atomized content differs. The aggregator reports both input files, both
longidents, the shared identity, and the `--namespace` remedy, then
exits 1.

  $ cat > a.ml <<EOF
  > [@@@css ".css-a{color:red;}"]
  > [@@@css.bindings [("A.marker", "cid-shared", "css-a")]]
  > let marker = CSS.make "cid-shared css-a" []
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".css-b{color:blue;}"]
  > [@@@css.bindings [("B.marker", "cid-shared", "css-b")]]
  > let marker = CSS.make "cid-shared css-b" []
  > EOF

  $ styled-ppx.generate a.ml b.ml
  styled-ppx: b.ml: malformed [@@@css.bindings]: identity collision: "A.marker" (in a.ml) and "B.marker" (in b.ml) both hash to identity cid-shared, but carry different CSS ("css-a" vs "css-b"). Pass `--namespace <name>` to one library's (pps styled-ppx ...) stanza, identically on its native and melange stanzas.
  [1]

Same identity with the SAME atomized content is not a collision - it is
the ordinary "same module compiled twice" case (native + melange
`copy_files`, vendoring): the later occurrence is accepted and the
index keeps resolving references against it.

  $ cat > c.ml <<EOF
  > [@@@css ".css-c{color:green;}"]
  > [@@@css.bindings [("C.marker", "cid-same", "css-c")]]
  > let marker = CSS.make "cid-same css-c" []
  > EOF

  $ cat > d.ml <<EOF
  > [@@@css ".css-c{color:green;}"]
  > [@@@css.bindings [("D.marker", "cid-same", "css-c")]]
  > let marker = CSS.make "cid-same css-c" []
  > EOF

  $ cat > e.ml <<EOF
  > [@@@css ".target.\000D.marker\000{padding:1rem;}"]
  > [@@@css.refs [("D.marker", "e.ml", 1, 0, 9)]]
  > let _ = D.marker
  > EOF

  $ styled-ppx.generate c.ml d.ml e.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  .css-c{color:green;}
  .target.cid-same{padding:1rem;}
  }
