  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ refmt --parse ml --print re output.ml
  let css = (right, bottom, left) =>
    CSS.make(
      "css-17vxl0k css-1641h1j css-1uzc9um",
      [
        ("--var-j35jbq", CSS.get_value_from_rule(CSS.margin(right))),
        ("--var-15kzvoi", CSS.get_value_from_rule(CSS.margin(bottom))),
        ("--var-oyh7mz", CSS.get_value_from_rule(CSS.margin(left))),
        (
          "--var-1xt8d8f",
          CSS.get_value_from_rule(CSS.backgroundColor(CSS.black)),
        ),
      ],
    );
  <div
    className={fst(css(CSS.px(10), CSS.px(10), CSS.px(10)))}
    style={snd(css(CSS.px(10), CSS.px(10), CSS.px(10)))}
  />;
  <span
    className={fst(CSS.make("css-17vxl0k", []))}
    style={snd(CSS.make("css-17vxl0k", []))}
  />;

  $ styled-ppx.extract output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-17vxl0k { display: flex; }
  .css-1641h1j { margin: 8px var(--var-j35jbq) var(--var-15kzvoi) var(--var-oyh7mz); }
  .css-1uzc9um { background-color: var(--var-1xt8d8f); }
  
