Test interpolation support for various properties in cx2

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --justifyContent-4qveqt{syntax:"*";inherits:false;}
  @property --alignItems-521j9v{syntax:"*";inherits:false;}
  @property --alignSelf-ljwnlg{syntax:"*";inherits:false;}
  @property --alignContent-13ah8fi{syntax:"*";inherits:false;}
  @property --justifyItems-1excenu{syntax:"*";inherits:false;}
  @property --justifySelf-67xw19{syntax:"*";inherits:false;}
  @property --flexDirection-vyhh8o{syntax:"*";inherits:false;}
  @property --flexWrap-mf3oja{syntax:"*";inherits:false;}
  @property --flexGrow-fuzkbv{syntax:"*";inherits:false;}
  @property --flexShrink-1pv1ijl{syntax:"*";inherits:false;}
  @property --flexBasis-oh1idl{syntax:"*";inherits:false;}
  @property --display-jduo1l{syntax:"*";inherits:false;}
  @property --visibility-10dikjf{syntax:"*";inherits:false;}
  @property --overflow-1mtk7mf{syntax:"*";inherits:false;}
  @property --overflowX-15s3tw{syntax:"*";inherits:false;}
  @property --overflowY-1y5cikq{syntax:"*";inherits:false;}
  @property --position-1cfm5dq{syntax:"*";inherits:false;}
  @property --top-13gl08v{syntax:"*";inherits:false;}
  @property --right-xeiqea{syntax:"*";inherits:false;}
  @property --bottom-q421ib{syntax:"*";inherits:false;}
  @property --left-1s2hr3z{syntax:"*";inherits:false;}
  @property --zIndex-umrllj{syntax:"*";inherits:false;}
  @property --width-18c1xss{syntax:"*";inherits:false;}
  @property --height-1n9troi{syntax:"*";inherits:false;}
  @property --minWidth-lb9cvd{syntax:"*";inherits:false;}
  @property --maxWidth-1rew851{syntax:"*";inherits:false;}
  @property --minHeight-1o3pcp1{syntax:"*";inherits:false;}
  @property --maxHeight-1xgmjux{syntax:"*";inherits:false;}
  @property --margin-n8c989{syntax:"*";inherits:false;}
  @property --marginTop-1s6a92v{syntax:"*";inherits:false;}
  @property --marginRight-9awpa7{syntax:"*";inherits:false;}
  @property --marginBottom-zo090i{syntax:"*";inherits:false;}
  @property --marginLeft-fktxvd{syntax:"*";inherits:false;}
  @property --padding-46h8wl{syntax:"*";inherits:false;}
  @property --paddingTop-1ib1hlz{syntax:"*";inherits:false;}
  @property --paddingRight-1k98iat{syntax:"*";inherits:false;}
  @property --paddingBottom-1p77ug6{syntax:"*";inherits:false;}
  @property --paddingLeft-m9e4k3{syntax:"*";inherits:false;}
  @property --color-1a279q8{syntax:"*";inherits:false;}
  @property --backgroundColor-ov3le6{syntax:"*";inherits:false;}
  @property --fontSize-12ul4b0{syntax:"*";inherits:false;}
  @property --fontWeight-1a3ztf6{syntax:"*";inherits:false;}
  @property --fontStyle-7pegjp{syntax:"*";inherits:false;}
  @property --textAlign-on0gms{syntax:"*";inherits:false;}
  @property --textDecoration-8qw7r7{syntax:"*";inherits:false;}
  @property --textTransform-1fmhxkq{syntax:"*";inherits:false;}
  @property --lineHeight-1bmakb2{syntax:"*";inherits:false;}
  @property --letterSpacing-19zr9ga{syntax:"*";inherits:false;}
  @property --wordSpacing-k2h9ex{syntax:"*";inherits:false;}
  @property --whiteSpace-1h12mku{syntax:"*";inherits:false;}
  @property --borderStyle-1763oiz{syntax:"*";inherits:false;}
  @property --borderWidth-1231nny{syntax:"*";inherits:false;}
  @property --borderColor-vdrhmb{syntax:"*";inherits:false;}
  @property --borderRadius-br4a6q{syntax:"*";inherits:false;}
  @property --backgroundRepeat-3sra9y{syntax:"*";inherits:false;}
  @property --backgroundPosition-1nm342w{syntax:"*";inherits:false;}
  @property --backgroundSize-nk11f3{syntax:"*";inherits:false;}
  @property --outlineStyle-1c46eti{syntax:"*";inherits:false;}
  @property --outlineWidth-6upc5w{syntax:"*";inherits:false;}
  @property --outlineColor-rydsxk{syntax:"*";inherits:false;}
  @property --cursor-t4uqgd{syntax:"*";inherits:false;}
  @property --pointerEvents-1hbyrkf{syntax:"*";inherits:false;}
  @property --opacity-1hgminq{syntax:"*";inherits:false;}
  @property --gridAutoFlow-16d9clt{syntax:"*";inherits:false;}
  @property --gap-py3nvz{syntax:"*";inherits:false;}
  @property --rowGap-1l1vram{syntax:"*";inherits:false;}
  @property --columnGap-ie3e74{syntax:"*";inherits:false;}
  @property --marginBlock-v40cvv{syntax:"*";inherits:false;}
  @property --marginInline-ivw2py{syntax:"*";inherits:false;}
  @property --paddingBlock-1vcjdwn{syntax:"*";inherits:false;}
  @property --paddingInline-g6xu1o{syntax:"*";inherits:false;}
  @property --insetBlock-wjjqml{syntax:"*";inherits:false;}
  @property --insetInline-1j66x1{syntax:"*";inherits:false;}
  @property --boxSizing-10uflvg{syntax:"*";inherits:false;}
  @property --order-c6v3oy{syntax:"*";inherits:false;}
  @property --float-14frksg{syntax:"*";inherits:false;}
  @property --clear-nri6r2{syntax:"*";inherits:false;}
  @property --tableLayout-ppjcli{syntax:"*";inherits:false;}
  @property --borderCollapse-ymv550{syntax:"*";inherits:false;}
  @property --verticalAlign-1sq6hcv{syntax:"*";inherits:false;}
  @property --objectFit-1j5ekwa{syntax:"*";inherits:false;}
  @property --resize-1uakrfb{syntax:"*";inherits:false;}
  @property --userSelect-u3nmy1{syntax:"*";inherits:false;}
  @property --transformOrigin-1l4toj3{syntax:"*";inherits:false;}
  @property --backfaceVisibility-57rop4{syntax:"*";inherits:false;}
  @property --perspective-1966aww{syntax:"*";inherits:false;}
  @property --wordBreak-15gd7xg{syntax:"*";inherits:false;}
  @property --overflowWrap-5mv03s{syntax:"*";inherits:false;}
  @property --hyphens-viajao{syntax:"*";inherits:false;}
  @property --listStyleType-wes33f{syntax:"*";inherits:false;}
  @property --listStylePosition-1gexoze{syntax:"*";inherits:false;}
  @property --content-188dugn{syntax:"*";inherits:false;}
  @property --isolation-1ad21a4{syntax:"*";inherits:false;}
  @property --mixBlendMode-1gh357x{syntax:"*";inherits:false;}
  @property --backgroundBlendMode-1ubdfn4{syntax:"*";inherits:false;}
  @property --columnCount-1vrfrhd{syntax:"*";inherits:false;}
  @property --breakBefore-1uz2974{syntax:"*";inherits:false;}
  @property --breakAfter-1ppm471{syntax:"*";inherits:false;}
  @property --breakInside-1jjp0ej{syntax:"*";inherits:false;}
  @property --appearance-39c8ha{syntax:"*";inherits:false;}
  @property --touchAction-1px8y2f{syntax:"*";inherits:false;}
  @property --scrollBehavior-1ji12j4{syntax:"*";inherits:false;}
  @property --overscrollBehavior-17qcsbs{syntax:"*";inherits:false;}
  @property --accentColor-mn7yh{syntax:"*";inherits:false;}
  @property --caretColor-zmu88x{syntax:"*";inherits:false;}
  .csv-1w9k6fd{justify-content:var(--justifyContent-4qveqt);}
  .csv-t00r6u{align-items:var(--alignItems-521j9v);}
  .csv-1pjpxby{align-self:var(--alignSelf-ljwnlg);}
  .csv-fk4yx2{align-content:var(--alignContent-13ah8fi);}
  .csv-1uipwmx{justify-items:var(--justifyItems-1excenu);}
  .csv-b4fvf2{justify-self:var(--justifySelf-67xw19);}
  .csv-1ve9kvu{-webkit-flex-direction:var(--flexDirection-vyhh8o);-ms-flex-direction:var(--flexDirection-vyhh8o);flex-direction:var(--flexDirection-vyhh8o);}
  .csv-i4drze{flex-wrap:var(--flexWrap-mf3oja);}
  .csv-1wfu6xw{flex-grow:var(--flexGrow-fuzkbv);}
  .csv-y8wsqe{flex-shrink:var(--flexShrink-1pv1ijl);}
  .csv-1h2oefs{flex-basis:var(--flexBasis-oh1idl);}
  .csv-1ubpg0g{display:var(--display-jduo1l);}
  .csv-1h3jrd3{visibility:var(--visibility-10dikjf);}
  .csv-1wkkydf{overflow:var(--overflow-1mtk7mf);}
  .csv-5voc5h{overflow-x:var(--overflowX-15s3tw);}
  .csv-1j6f0e0{overflow-y:var(--overflowY-1y5cikq);}
  .csv-3b8onb{position:var(--position-1cfm5dq);}
  .csv-18nf8gj{top:var(--top-13gl08v);}
  .csv-rb0eke{right:var(--right-xeiqea);}
  .csv-arxtx2{bottom:var(--bottom-q421ib);}
  .csv-1jcegw0{left:var(--left-1s2hr3z);}
  .csv-2a1pdf{z-index:var(--zIndex-umrllj);}
  .csv-1dfkyy8{width:var(--width-18c1xss);}
  .csv-q0vooa{height:var(--height-1n9troi);}
  .csv-1m9y0n{min-width:var(--minWidth-lb9cvd);}
  .csv-1a3t8nq{max-width:var(--maxWidth-1rew851);}
  .csv-39d7lc{min-height:var(--minHeight-1o3pcp1);}
  .csv-k1vy9j{max-height:var(--maxHeight-1xgmjux);}
  .csv-l5c3av{margin:var(--margin-n8c989);}
  .csv-uwdxtd{margin-top:var(--marginTop-1s6a92v);}
  .csv-1ppx1jv{margin-right:var(--marginRight-9awpa7);}
  .csv-12h0uhk{margin-bottom:var(--marginBottom-zo090i);}
  .csv-102d6mo{margin-left:var(--marginLeft-fktxvd);}
  .csv-1bsx5yj{padding:var(--padding-46h8wl);}
  .csv-hs8vsl{padding-top:var(--paddingTop-1ib1hlz);}
  .csv-mldvp2{padding-right:var(--paddingRight-1k98iat);}
  .csv-1gpt8ag{padding-bottom:var(--paddingBottom-1p77ug6);}
  .csv-1r6vhda{padding-left:var(--paddingLeft-m9e4k3);}
  .csv-kusjgz{color:var(--color-1a279q8);}
  .csv-160vrad{background-color:var(--backgroundColor-ov3le6);}
  .csv-1jqo2b0{font-size:var(--fontSize-12ul4b0);}
  .csv-13c02s8{font-weight:var(--fontWeight-1a3ztf6);}
  .csv-7bbnrz{font-style:var(--fontStyle-7pegjp);}
  .csv-6atdos{text-align:var(--textAlign-on0gms);}
  .csv-1gg5e36{-webkit-text-decoration:var(--textDecoration-8qw7r7);text-decoration:var(--textDecoration-8qw7r7);}
  .csv-15c1q3l{text-transform:var(--textTransform-1fmhxkq);}
  .csv-72qf9h{line-height:var(--lineHeight-1bmakb2);}
  .csv-osopak{letter-spacing:var(--letterSpacing-19zr9ga);}
  .csv-hxjlgs{word-spacing:var(--wordSpacing-k2h9ex);}
  .csv-17va1ep{white-space:var(--whiteSpace-1h12mku);}
  .csv-1ihjzh8{border-style:var(--borderStyle-1763oiz);}
  .csv-veu872{border-width:var(--borderWidth-1231nny);}
  .csv-172cluv{border-color:var(--borderColor-vdrhmb);}
  .csv-1eq9x1x{border-radius:var(--borderRadius-br4a6q);}
  .csv-1j7ipa5{background-repeat:var(--backgroundRepeat-3sra9y);}
  .csv-1web4if{background-position:var(--backgroundPosition-1nm342w);}
  .csv-1h6p6rq{background-size:var(--backgroundSize-nk11f3);}
  .csv-1o1idah{outline-style:var(--outlineStyle-1c46eti);}
  .csv-938xcq{outline-width:var(--outlineWidth-6upc5w);}
  .csv-1x7q72v{outline-color:var(--outlineColor-rydsxk);}
  .csv-17mrzdo{cursor:var(--cursor-t4uqgd);}
  .csv-17tret{pointer-events:var(--pointerEvents-1hbyrkf);}
  .csv-myvp00{opacity:var(--opacity-1hgminq);}
  .csv-lmw8xd{grid-auto-flow:var(--gridAutoFlow-16d9clt);}
  .csv-zzuf95{gap:var(--gap-py3nvz);}
  .csv-zzftvm{row-gap:var(--rowGap-1l1vram);}
  .csv-9sg4ax{-webkit-column-gap:var(--columnGap-ie3e74);column-gap:var(--columnGap-ie3e74);}
  .csv-12valzm{margin-block:var(--marginBlock-v40cvv);}
  .csv-18svqz5{margin-inline:var(--marginInline-ivw2py);}
  .csv-1jxlw87{padding-block:var(--paddingBlock-1vcjdwn);}
  .csv-5p4nfz{padding-inline:var(--paddingInline-g6xu1o);}
  .csv-nvikxv{inset-block:var(--insetBlock-wjjqml);}
  .csv-1kes0wu{inset-inline:var(--insetInline-1j66x1);}
  .csv-1rw5ea0{box-sizing:var(--boxSizing-10uflvg);}
  .csv-t6ylua{order:var(--order-c6v3oy);}
  .csv-1w17pkf{float:var(--float-14frksg);}
  .csv-l8g2wc{clear:var(--clear-nri6r2);}
  .csv-cjia00{table-layout:var(--tableLayout-ppjcli);}
  .csv-dfpgx7{border-collapse:var(--borderCollapse-ymv550);}
  .csv-nm6wx2{vertical-align:var(--verticalAlign-1sq6hcv);}
  .csv-1ft9f0p{object-fit:var(--objectFit-1j5ekwa);}
  .csv-evhl29{resize:var(--resize-1uakrfb);}
  .csv-vx8b8c{-webkit-user-select:var(--userSelect-u3nmy1);-moz-user-select:var(--userSelect-u3nmy1);-ms-user-select:var(--userSelect-u3nmy1);user-select:var(--userSelect-u3nmy1);}
  .csv-17vc5lx{transform-origin:var(--transformOrigin-1l4toj3);}
  .csv-hxk4zy{-webkit-backface-visibility:var(--backfaceVisibility-57rop4);backface-visibility:var(--backfaceVisibility-57rop4);}
  .csv-1uqg06o{perspective:var(--perspective-1966aww);}
  .csv-1dkaxj{word-break:var(--wordBreak-15gd7xg);}
  .csv-fn2bbj{overflow-wrap:var(--overflowWrap-5mv03s);}
  .csv-ppjxyo{-webkit-hyphens:var(--hyphens-viajao);-moz-hyphens:var(--hyphens-viajao);-ms-hyphens:var(--hyphens-viajao);hyphens:var(--hyphens-viajao);}
  .csv-1mo4owk{list-style-type:var(--listStyleType-wes33f);}
  .csv-llr375{list-style-position:var(--listStylePosition-1gexoze);}
  .csv-meuk7{content:var(--content-188dugn);}
  .csv-18e2xt3{isolation:var(--isolation-1ad21a4);}
  .csv-l589er{mix-blend-mode:var(--mixBlendMode-1gh357x);}
  .csv-nw727u{background-blend-mode:var(--backgroundBlendMode-1ubdfn4);}
  .csv-wf0ec3{-webkit-column-count:var(--columnCount-1vrfrhd);column-count:var(--columnCount-1vrfrhd);}
  .csv-5sg6ew{break-before:var(--breakBefore-1uz2974);}
  .csv-1odh63b{break-after:var(--breakAfter-1ppm471);}
  .csv-251x2b{break-inside:var(--breakInside-1jjp0ej);}
  .csv-wlxzs9{-webkit-appearance:var(--appearance-39c8ha);-moz-appearance:var(--appearance-39c8ha);-ms-appearance:var(--appearance-39c8ha);appearance:var(--appearance-39c8ha);}
  .csv-1dapsgl{touch-action:var(--touchAction-1px8y2f);}
  .csv-rc8i0o{scroll-behavior:var(--scrollBehavior-1ji12j4);}
  .csv-b1r0ae{overscroll-behavior:var(--overscrollBehavior-17qcsbs);}
  .csv-18eqgla{accent-color:var(--accentColor-mn7yh);}
  .csv-cf8xpc{caret-color:var(--caretColor-zmu88x);}
