Test interpolation support for various properties in cx2

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --justifyContent-4qveqt{syntax:"*";inherits:false;}
  @property --alignItems-521j9v{syntax:"*";inherits:false;}
  @property --alignSelf-ljwnlg{syntax:"*";inherits:false;}
  @property --alignContent-13ah8fi{syntax:"*";inherits:false;}
  @property --justifyItems-1excenu{syntax:"*";inherits:false;}
  @property --justifySelf-67xw19{syntax:"*";inherits:false;}
  @property --flexDirection-vyhh8o{syntax:"*";inherits:false;}
  @property --flexWrap-mf3oja{syntax:"*";inherits:false;}
  @property --flexGrow-fuzkbv{syntax:"*";inherits:false;}
  @property --flexShrink-1pv1ijl{syntax:"*";inherits:false;}
  @property --flexBasis-oh1idl{syntax:"*";inherits:false;}
  @property --display-jduo1l{syntax:"*";inherits:false;}
  @property --visibility-10dikjf{syntax:"*";inherits:false;}
  @property --overflow-1mtk7mf{syntax:"*";inherits:false;}
  @property --overflowX-15s3tw{syntax:"*";inherits:false;}
  @property --overflowY-1y5cikq{syntax:"*";inherits:false;}
  @property --position-1cfm5dq{syntax:"*";inherits:false;}
  @property --top-13gl08v{syntax:"*";inherits:false;}
  @property --right-xeiqea{syntax:"*";inherits:false;}
  @property --bottom-q421ib{syntax:"*";inherits:false;}
  @property --left-1s2hr3z{syntax:"*";inherits:false;}
  @property --zIndex-umrllj{syntax:"*";inherits:false;}
  @property --width-18c1xss{syntax:"*";inherits:false;}
  @property --height-1n9troi{syntax:"*";inherits:false;}
  @property --minWidth-lb9cvd{syntax:"*";inherits:false;}
  @property --maxWidth-1rew851{syntax:"*";inherits:false;}
  @property --minHeight-1o3pcp1{syntax:"*";inherits:false;}
  @property --maxHeight-1xgmjux{syntax:"*";inherits:false;}
  @property --margin-n8c989{syntax:"*";inherits:false;}
  @property --marginTop-1s6a92v{syntax:"*";inherits:false;}
  @property --marginRight-9awpa7{syntax:"*";inherits:false;}
  @property --marginBottom-zo090i{syntax:"*";inherits:false;}
  @property --marginLeft-fktxvd{syntax:"*";inherits:false;}
  @property --padding-46h8wl{syntax:"*";inherits:false;}
  @property --paddingTop-1ib1hlz{syntax:"*";inherits:false;}
  @property --paddingRight-1k98iat{syntax:"*";inherits:false;}
  @property --paddingBottom-1p77ug6{syntax:"*";inherits:false;}
  @property --paddingLeft-m9e4k3{syntax:"*";inherits:false;}
  @property --color-1a279q8{syntax:"*";inherits:false;}
  @property --backgroundColor-ov3le6{syntax:"*";inherits:false;}
  @property --fontSize-12ul4b0{syntax:"*";inherits:false;}
  @property --fontWeight-1a3ztf6{syntax:"*";inherits:false;}
  @property --fontStyle-7pegjp{syntax:"*";inherits:false;}
  @property --textAlign-on0gms{syntax:"*";inherits:false;}
  @property --textDecoration-8qw7r7{syntax:"*";inherits:false;}
  @property --textTransform-1fmhxkq{syntax:"*";inherits:false;}
  @property --lineHeight-1bmakb2{syntax:"*";inherits:false;}
  @property --letterSpacing-19zr9ga{syntax:"*";inherits:false;}
  @property --wordSpacing-k2h9ex{syntax:"*";inherits:false;}
  @property --whiteSpace-1h12mku{syntax:"*";inherits:false;}
  @property --borderStyle-1763oiz{syntax:"*";inherits:false;}
  @property --borderWidth-1231nny{syntax:"*";inherits:false;}
  @property --borderColor-vdrhmb{syntax:"*";inherits:false;}
  @property --borderRadius-br4a6q{syntax:"*";inherits:false;}
  @property --backgroundRepeat-3sra9y{syntax:"*";inherits:false;}
  @property --backgroundPosition-1nm342w{syntax:"*";inherits:false;}
  @property --backgroundSize-nk11f3{syntax:"*";inherits:false;}
  @property --outlineStyle-1c46eti{syntax:"*";inherits:false;}
  @property --outlineWidth-6upc5w{syntax:"*";inherits:false;}
  @property --outlineColor-rydsxk{syntax:"*";inherits:false;}
  @property --cursor-t4uqgd{syntax:"*";inherits:false;}
  @property --pointerEvents-1hbyrkf{syntax:"*";inherits:false;}
  @property --opacity-1hgminq{syntax:"*";inherits:false;}
  @property --gridAutoFlow-16d9clt{syntax:"*";inherits:false;}
  @property --gap-py3nvz{syntax:"*";inherits:false;}
  @property --rowGap-1l1vram{syntax:"*";inherits:false;}
  @property --columnGap-ie3e74{syntax:"*";inherits:false;}
  @property --marginBlock-v40cvv{syntax:"*";inherits:false;}
  @property --marginInline-ivw2py{syntax:"*";inherits:false;}
  @property --paddingBlock-1vcjdwn{syntax:"*";inherits:false;}
  @property --paddingInline-g6xu1o{syntax:"*";inherits:false;}
  @property --insetBlock-wjjqml{syntax:"*";inherits:false;}
  @property --insetInline-1j66x1{syntax:"*";inherits:false;}
  @property --boxSizing-10uflvg{syntax:"*";inherits:false;}
  @property --order-c6v3oy{syntax:"*";inherits:false;}
  @property --float-14frksg{syntax:"*";inherits:false;}
  @property --clear-nri6r2{syntax:"*";inherits:false;}
  @property --tableLayout-ppjcli{syntax:"*";inherits:false;}
  @property --borderCollapse-ymv550{syntax:"*";inherits:false;}
  @property --verticalAlign-1sq6hcv{syntax:"*";inherits:false;}
  @property --objectFit-1j5ekwa{syntax:"*";inherits:false;}
  @property --resize-1uakrfb{syntax:"*";inherits:false;}
  @property --userSelect-u3nmy1{syntax:"*";inherits:false;}
  @property --transformOrigin-1l4toj3{syntax:"*";inherits:false;}
  @property --backfaceVisibility-57rop4{syntax:"*";inherits:false;}
  @property --perspective-1966aww{syntax:"*";inherits:false;}
  @property --wordBreak-15gd7xg{syntax:"*";inherits:false;}
  @property --overflowWrap-5mv03s{syntax:"*";inherits:false;}
  @property --hyphens-viajao{syntax:"*";inherits:false;}
  @property --listStyleType-wes33f{syntax:"*";inherits:false;}
  @property --listStylePosition-1gexoze{syntax:"*";inherits:false;}
  @property --content-188dugn{syntax:"*";inherits:false;}
  @property --isolation-1ad21a4{syntax:"*";inherits:false;}
  @property --mixBlendMode-1gh357x{syntax:"*";inherits:false;}
  @property --backgroundBlendMode-1ubdfn4{syntax:"*";inherits:false;}
  @property --columnCount-1vrfrhd{syntax:"*";inherits:false;}
  @property --breakBefore-1uz2974{syntax:"*";inherits:false;}
  @property --breakAfter-1ppm471{syntax:"*";inherits:false;}
  @property --breakInside-1jjp0ej{syntax:"*";inherits:false;}
  @property --appearance-39c8ha{syntax:"*";inherits:false;}
  @property --touchAction-1px8y2f{syntax:"*";inherits:false;}
  @property --scrollBehavior-1ji12j4{syntax:"*";inherits:false;}
  @property --overscrollBehavior-17qcsbs{syntax:"*";inherits:false;}
  @property --accentColor-mn7yh{syntax:"*";inherits:false;}
  @property --caretColor-zmu88x{syntax:"*";inherits:false;}
  .a-9h002k6fd{justify-content:var(--justifyContent-4qveqt);}
  .a-9i0010r6u{align-items:var(--alignItems-521j9v);}
  .a-9j001pxby{align-self:var(--alignSelf-ljwnlg);}
  .a-9h0014yx2{align-content:var(--alignContent-13ah8fi);}
  .a-9i002pwmx{justify-items:var(--justifyItems-1excenu);}
  .a-9j002fvf2{justify-self:var(--justifySelf-67xw19);}
  .a-610019kvu{-webkit-flex-direction:var(--flexDirection-vyhh8o);-ms-flex-direction:var(--flexDirection-vyhh8o);flex-direction:var(--flexDirection-vyhh8o);}
  .a-61002drze{flex-wrap:var(--flexWrap-mf3oja);}
  .a-60002u6xw{flex-grow:var(--flexGrow-fuzkbv);}
  .a-60004wsqe{flex-shrink:var(--flexShrink-1pv1ijl);}
  .a-60001oefs{flex-basis:var(--flexBasis-oh1idl);}
  .a-5rpg0g{display:var(--display-jduo1l);}
  .a-e0jrd3{visibility:var(--visibility-10dikjf);}
  .a-8rkydf{overflow:var(--overflow-1mtk7mf);}
  .a-8r001oc5h{overflow-x:var(--overflowX-15s3tw);}
  .a-8r002f0e0{overflow-y:var(--overflowY-1y5cikq);}
  .a-9l8onb{position:var(--position-1cfm5dq);}
  .a-71008f8gj{top:var(--top-13gl08v);}
  .a-710040eke{right:var(--right-xeiqea);}
  .a-71001xtx2{bottom:var(--bottom-q421ib);}
  .a-71002egw0{left:var(--left-1s2hr3z);}
  .a-ek1pdf{z-index:var(--zIndex-umrllj);}
  .a-eckyy8{width:var(--width-18c1xss);}
  .a-6lvooa{height:var(--height-1n9troi);}
  .a-8c9y0n{min-width:var(--minWidth-lb9cvd);}
  .a-88t8nq{max-width:var(--maxWidth-1rew851);}
  .a-8ad7lc{min-height:var(--minHeight-1o3pcp1);}
  .a-85vy9j{max-height:var(--maxHeight-1xgmjux);}
  .a-7pc3av{margin:var(--margin-n8c989);}
  .a-7p008dxtd{margin-top:var(--marginTop-1s6a92v);}
  .a-7p004x1jv{margin-right:var(--marginRight-9awpa7);}
  .a-7p0010uhk{margin-bottom:var(--marginBottom-zo090i);}
  .a-7p002d6mo{margin-left:var(--marginLeft-fktxvd);}
  .a-94x5yj{padding:var(--padding-46h8wl);}
  .a-940088vsl{padding-top:var(--paddingTop-1ib1hlz);}
  .a-94004dvp2{padding-right:var(--paddingRight-1k98iat);}
  .a-94001t8ag{padding-bottom:var(--paddingBottom-1p77ug6);}
  .a-94002vhda{padding-left:var(--paddingLeft-m9e4k3);}
  .a-4esjgz{color:var(--color-1a279q8);}
  .a-39004vrad{background-color:var(--backgroundColor-ov3le6);}
  .a-6500wo2b0{font-size:var(--fontSize-12ul4b0);}
  .a-65m9s02s8{font-weight:var(--fontWeight-1a3ztf6);}
  .a-65074bnrz{font-style:var(--fontStyle-7pegjp);}
  .a-c5tdos{text-align:var(--textAlign-on0gms);}
  .a-cf5e36{-webkit-text-decoration:var(--textDecoration-8qw7r7);text-decoration:var(--textDecoration-8qw7r7);}
  .a-d11q3l{text-transform:var(--textTransform-1fmhxkq);}
  .a-658jkqf9h{line-height:var(--lineHeight-1bmakb2);}
  .a-7iopak{letter-spacing:var(--letterSpacing-19zr9ga);}
  .a-egjlgs{word-spacing:var(--wordSpacing-k2h9ex);}
  .a-e9a1ep{white-space:var(--whiteSpace-1h12mku);}
  .a-3hsuajzh8{border-style:var(--borderStyle-1763oiz);}
  .a-3hloku872{border-width:var(--borderWidth-1231nny);}
  .a-3hef5cluv{border-color:var(--borderColor-vdrhmb);}
  .a-3n9x1x{border-radius:var(--borderRadius-br4a6q);}
  .a-3903kipa5{background-repeat:var(--backgroundRepeat-3sra9y);}
  .a-3902ob4if{background-position:var(--backgroundPosition-1nm342w);}
  .a-39074p6rq{background-size:var(--backgroundSize-nk11f3);}
  .a-8p002idah{outline-style:var(--outlineStyle-1c46eti);}
  .a-8p0048xcq{outline-width:var(--outlineWidth-6upc5w);}
  .a-8p001q72v{outline-color:var(--outlineColor-rydsxk);}
  .a-5lrzdo{cursor:var(--cursor-t4uqgd);}
  .a-9ktret{pointer-events:var(--pointerEvents-1hbyrkf);}
  .a-8mvp00{opacity:var(--opacity-1hgminq);}
  .a-6i002w8xd{grid-auto-flow:var(--gridAutoFlow-16d9clt);}
  .a-6fuf95{gap:var(--gap-py3nvz);}
  .a-6f002ftvm{row-gap:var(--rowGap-1l1vram);}
  .a-6f001g4ax{-webkit-column-gap:var(--columnGap-ie3e74);column-gap:var(--columnGap-ie3e74);}
  .a-7qalzm{margin-block:var(--marginBlock-v40cvv);}
  .a-7rvqz5{margin-inline:var(--marginInline-ivw2py);}
  .a-95lw87{padding-block:var(--paddingBlock-1vcjdwn);}
  .a-964nfz{padding-inline:var(--paddingInline-g6xu1o);}
  .a-73ikxv{inset-block:var(--insetBlock-wjjqml);}
  .a-74s0wu{inset-inline:var(--insetInline-1j66x1);}
  .a-415ea0{box-sizing:var(--boxSizing-10uflvg);}
  .a-8nylua{order:var(--order-c6v3oy);}
  .a-627pkf{float:var(--float-14frksg);}
  .a-4ag2wc{clear:var(--clear-nri6r2);}
  .a-c4ia00{table-layout:var(--tableLayout-ppjcli);}
  .a-3jpgx7{border-collapse:var(--borderCollapse-ymv550);}
  .a-dt6wx2{vertical-align:var(--verticalAlign-1sq6hcv);}
  .a-8i9f0p{object-fit:var(--objectFit-1j5ekwa);}
  .a-9yhl29{resize:var(--resize-1uakrfb);}
  .a-dr8b8c{-webkit-user-select:var(--userSelect-u3nmy1);-moz-user-select:var(--userSelect-u3nmy1);-ms-user-select:var(--userSelect-u3nmy1);user-select:var(--userSelect-u3nmy1);}
  .a-dkc5lx{transform-origin:var(--transformOrigin-1l4toj3);}
  .a-38k4zy{-webkit-backface-visibility:var(--backfaceVisibility-57rop4);backface-visibility:var(--backfaceVisibility-57rop4);}
  .a-9fg06o{perspective:var(--perspective-1966aww);}
  .a-eekaxj{word-break:var(--wordBreak-15gd7xg);}
  .a-8x2bbj{overflow-wrap:var(--overflowWrap-5mv03s);}
  .a-6rjxyo{-webkit-hyphens:var(--hyphens-viajao);-moz-hyphens:var(--hyphens-viajao);-ms-hyphens:var(--hyphens-viajao);hyphens:var(--hyphens-viajao);}
  .a-7o0044owk{list-style-type:var(--listStyleType-wes33f);}
  .a-7o002r375{list-style-position:var(--listStylePosition-1gexoze);}
  .a-4weuk7{content:var(--content-188dugn);}
  .a-7a2xt3{isolation:var(--isolation-1ad21a4);}
  .a-8d89er{mix-blend-mode:var(--mixBlendMode-1gh357x);}
  .a-3a727u{background-blend-mode:var(--backgroundBlendMode-1ubdfn4);}
  .a-4o0010ec3{-webkit-column-count:var(--columnCount-1vrfrhd);column-count:var(--columnCount-1vrfrhd);}
  .a-43g6ew{break-before:var(--breakBefore-1uz2974);}
  .a-42h63b{break-after:var(--breakAfter-1ppm471);}
  .a-441x2b{break-inside:var(--breakInside-1jjp0ej);}
  .a-33xzs9{-webkit-appearance:var(--appearance-39c8ha);-moz-appearance:var(--appearance-39c8ha);-ms-appearance:var(--appearance-39c8ha);appearance:var(--appearance-39c8ha);}
  .a-dhpsgl{touch-action:var(--touchAction-1px8y2f);}
  .a-aa8i0o{scroll-behavior:var(--scrollBehavior-1ji12j4);}
  .a-8zr0ae{overscroll-behavior:var(--overscrollBehavior-17qcsbs);}
  .a-2tqgla{accent-color:var(--accentColor-mn7yh);}
  .a-488xpc{caret-color:var(--caretColor-zmu88x);}
