One block, `:focus` written first, `:hover` written second - a check that
the fixed pseudo-class priority reads the atom's own pseudo chain
correctly against a REAL rendered selector (`._a_...:focus{...}`, no space
between the atom's class and its pseudo), not just a hand-written
`[@@@css "..."]` fixture. `:focus` outranks `:hover`, so `:focus` sorts
last and wins when both apply, regardless of which one this block wrote
last.

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css "._a_0lub34ebzcl:focus{color:blue;}"]
  [@@@css "._a_qyw7u4ego80:hover{color:red;}"]
  [@@@css.bindings
    [("Input.danger", "_id_47cxs7", "_a_0lub34ebzcl _a_qyw7u4ego80")]]
  let danger =
    CSS.make "label:danger _id_47cxs7 _a_0lub34ebzcl _a_qyw7u4ego80" []
  let _ = danger

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_qyw7u4ego80:hover{color:red;}
  ._a_0lub34ebzcl:focus{color:blue;}
