Cross-module reference into a nested submodule (`M.Css.marker`). The
aggregator's index walker tracks nested `module X = struct ... end`
declarations and indexes bindings under their fully-qualified path.

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_mgr9994ygwf._id_y5baf4{padding:1rem;}
  }
