`!important` needs no special handling for a `base`-vs-`conditional`
pair: both share the one `styled-ppx.atoms` layer, so importance is
compared before specificity or position exactly once, then two
`!important` declarations on the same property compete exactly like two
plain ones would - specificity first, emission position (tier order,
then the shorthand-depth sort) as the tie-break. Round 7 shipped a
SEPARATE mechanism for this (three more `!important`-only mirror layers,
`i-global`/`i-base`/`i-conditional`, because CSS reverses layer priority
for `!important` declarations) - collapsing `base` and `conditional`
into one shared layer for round 7b removes the need for it entirely
between THEM: with only one layer between the two, there is no
layer-priority reversal to work around in the first place. The
`global`-vs-`atoms` boundary is different - `global` keeps its own,
separate, lower layer (see `layers-global-tier.t`), so `!important`
DOES still reverse priority there (an `!important` global beats an
`!important` atom, since `global` is the earlier-declared layer).

`label:noSidePadding` (monorepo report, round 7's own regression): a
component's base padding, marked `!important` so a consumer's own CSS
cannot accidentally override it, narrowed under a media query with its
OWN `!important` override of the same two properties, one class each.

  $ cat > no_side_padding.ml <<EOF
  > [@@@css "._in_nospad_base{padding-left:40px !important;padding-right:40px !important;}"]
  > [@@@css "@media (min-width:768px) and (max-width:1279px){._in_nospad_tablet{padding-left:24px !important;padding-right:24px !important;}}"]
  > EOF

  $ styled-ppx.generate no_side_padding.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._in_nospad_base{padding-left:40px !important;padding-right:40px !important;}
  @media (min-width:768px) and (max-width:1279px){._in_nospad_tablet{padding-left:24px !important;padding-right:24px !important;}}
  }

What the browser does now, and why: both rules are `!important` and
equally specific (one class each), so the browser applies whichever one
is textually LAST among those that currently match. `generate.ml` emits
the base-tier rule before the conditional-tier one (see "Cascade tiers"
in `generate.ml`), so between 768 and 1279px, where the media query
matches, the narrower `._in_nospad_tablet` override wins - restoring the
responsive override `!important` on its own cannot break, without any
`!important`-specific machinery at all.
