A `[%styled.global]` rule (`*{box-sizing:inherit;}` here -
`html`/`body`/`*`/`*::before` are the same shape) carries no atom class, so
it is `global`, emitted before every atom (see "Cascade tiers" in
`generate.ml`) - but with no `@layer` around either group, that position is
only ever a tie-break: ordinary CSS specificity decides first, same as any
two plain, unlayered rules.

  $ cat > box_sizing.ml <<EOF
  > [@@@css "*{box-sizing:inherit;}"]
  > [@@@css "._a_box9k{box-sizing:content-box;}"]
  > EOF

  $ styled-ppx.generate box_sizing.ml
  /* This file is generated by styled-ppx, do not edit manually */
  *{box-sizing:inherit;}
  ._a_box9k{box-sizing:content-box;}

What the browser does now, and why: `*` has ZERO specificity, (0,0,0);
`._a_box9k` is one class, (0,1,0) - strictly more specific, so the atom
wins regardless of which one is textually later. Global-then-atom emission
order never enters into it here; it would even if the order were reversed.

A global selector with HIGHER specificity than an atom wins outright - an
accepted consequence of neither being layered: specificity is compared
before position, and position only ever breaks a specificity tie.

  $ cat > specificity.ml <<EOF
  > [@@@css ".theme-dark .card{color:green;}"]
  > [@@@css "._a_cardown{color:blue;}"]
  > EOF

  $ styled-ppx.generate specificity.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .theme-dark .card{color:green;}
  ._a_cardown{color:blue;}

What the browser does now, and why: `.theme-dark .card` is two classes,
(0,2,0); `._a_cardown` is one class, (0,1,0) - the global rule is more
specific, so it wins, even though the atom is textually later. A theme
class can always override a component's own atom this way, if it happens
to be more specific - a real, documented limit: an author whose atom
must still win either raises its own specificity or uses `!important`
(below).

`!important` needs no special handling now that neither rule is layered:
importance is compared first, exactly like any two plain declarations,
before specificity ever enters into it.

  $ cat > important_global.ml <<EOF
  > [@@@css "*{box-sizing:inherit !important;}"]
  > [@@@css "._a_box9k2{box-sizing:content-box;}"]
  > EOF

  $ styled-ppx.generate important_global.ml
  /* This file is generated by styled-ppx, do not edit manually */
  *{box-sizing:inherit !important;}
  ._a_box9k2{box-sizing:content-box;}

What the browser does here, and why: `*{box-sizing:inherit !important;}`
is `!important`, `._a_box9k2{box-sizing:content-box;}` is not - importance
alone decides, so the global wins despite being far less specific. Same
plain-CSS rule as always: an author whose global default must truly win
over a more specific, non-`!important` rule uses `!important`.

Two `!important` declarations on the same property compete by
specificity again, same as two plain ones would.

  $ cat > important_both.ml <<EOF
  > [@@@css "*{box-sizing:inherit !important;}"]
  > [@@@css "._a_box9k3{box-sizing:content-box !important;}"]
  > EOF

  $ styled-ppx.generate important_both.ml
  /* This file is generated by styled-ppx, do not edit manually */
  *{box-sizing:inherit !important;}
  ._a_box9k3{box-sizing:content-box !important;}

What the browser does here, and why: both declarations are `!important`,
so importance does not decide - specificity does, same as the
non-`!important` case above: `._a_box9k3` (0,1,0) beats `*` (0,0,0). A
more specific atom out-specifies a global default even under
`!important`, the same as plain CSS always allows.

`@property`/`@keyframes`/`@font-face` registrations are unaffected - they
take no part in tiering at all, so they are unchanged by any of this.

  $ cat > registration.ml <<EOF
  > [@@@css "@property --brand{syntax:\"<color>\";inherits:false;initial-value:red;}"]
  > [@@@css "@keyframes spin{to{transform:rotate(360deg);}}"]
  > [@@@css "@font-face{font-family:\"Body\";src:url(\"body.woff2\");}"]
  > [@@@css "._a_registered{color:blue;}"]
  > EOF

  $ styled-ppx.generate registration.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --brand{syntax:"<color>";inherits:false;initial-value:red;}
  @keyframes spin{to{transform:rotate(360deg);}}
  @font-face{font-family:"Body";src:url("body.woff2");}
  ._a_registered{color:blue;}
