Regression guard: cross-module [%styled.global] value interpolation does not
collide.

Two modules each declare `body { color: $(primary) }` as a global. This
confirms the global path is free of the atomic class/var collision that
affected [%css] backgrounds.

A global's interpolation variable is namespaced by kind+module+scope
(`Hash_class.scoped_namespace`), so the two modules - `A` and `B` - get
distinct variables (`--var-xeebq` vs `--var-t1uddx`). The namespace is keyed on
the compilation-unit module name rather than the physical file path, which is
what keeps the same module's two builds (e.g. native SSR + Melange client of a
`copy_files`-shared stylesheet) agreeing on one variable name. Crucially each
module emits BOTH halves of its pair together: the extracted
`body{color:var(--var-X)}` rule AND the `:root{--var-X: <value>}` setter inside
that module's `to_string`. A variable is owned by exactly one module; no module
references a variable another module defines, so there is no
undefined-custom-property collision.

The only cross-module interaction is the ordinary CSS cascade: two `body{}`
rules of equal specificity, last one wins - exactly what two literal
`body{color:...}` globals would do, and a user concern rather than a hashing
bug. (The `:root` blocks are supplied at runtime by mounting each
`<Theme />`; they are deliberately absent from styles.css.)

  $ refmt --parse re --print ml a.re > a.ml
  $ ../../standalone.exe --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ ../../standalone.exe --impl b.ml -o b.ml
  $ cat a.ml
  [@@@css "body{color:var(--primary-xeebq);}"]
  let primary = CSS.red
  module Theme =
    struct
      let to_string () =
        (((":root{" ^ "--primary-xeebq:") ^ (CSS.Types.Color.toString primary))
           ^ ";")
          ^ "}"
      let makeProps ?key () = Js.Obj.empty ()[@@warning "-27-32"]
      let make _props = CSS.global_style_tag (to_string ())
    end
  $ cat b.ml
  [@@@css "body{color:var(--primary-t1uddx);}"]
  let primary = CSS.hex "0000ff"
  module Theme =
    struct
      let to_string () =
        (((":root{" ^ "--primary-t1uddx:") ^ (CSS.Types.Color.toString primary))
           ^ ";")
          ^ "}"
      let makeProps ?key () = Js.Obj.empty ()[@@warning "-27-32"]
      let make _props = CSS.global_style_tag (to_string ())
    end
  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  body{color:var(--primary-xeebq);}
  body{color:var(--primary-t1uddx);}
