Regression guard: cross-module [%styled.global] value interpolation does not
collide.

Two modules each declare `body { color: $(primary) }` as a global. This
confirms the global path is free of the atomic class/var collision that
affected [%css] backgrounds.

A global's interpolation variable is namespaced by kind+file+scope
(`Hash_class.scoped_namespace`), so the two modules get distinct variables
(`--var-17xndl5` vs `--var-1oo8j6u`). Crucially each module emits BOTH halves
of its pair together: the extracted `body{color:var(--var-X)}` rule AND the
`:root{--var-X: <value>}` setter inside that module's `to_string`. A variable
is owned by exactly one module; no module references a variable another module
defines, so there is no undefined-custom-property collision.

The only cross-module interaction is the ordinary CSS cascade: two `body{}`
rules of equal specificity, last one wins - exactly what two literal
`body{color:...}` globals would do, and a user concern rather than a hashing
bug. (The `:root` blocks are supplied at runtime by mounting each
`<Theme />`; they are deliberately absent from styles.css.)

  $ refmt --parse re --print ml a.re > a.ml
  $ standalone --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ standalone --impl b.ml -o b.ml
  $ cat a.ml
  [@@@css "body{color:var(--var-17xndl5);}"]
  let primary = CSS.red
  module Theme =
    struct
      let to_string () =
        (((":root{" ^ "--var-17xndl5:") ^ (CSS.Types.Color.toString primary)) ^
           ";")
          ^ "}"
      let makeProps ?key () = ()[@@warning "-27-32"]
      let make _props = CSS.global_style_tag (to_string ())
    end
  $ cat b.ml
  [@@@css "body{color:var(--var-1oo8j6u);}"]
  let primary = CSS.hex "0000ff"
  module Theme =
    struct
      let to_string () =
        (((":root{" ^ "--var-1oo8j6u:") ^ (CSS.Types.Color.toString primary)) ^
           ";")
          ^ "}"
      let makeProps ?key () = ()[@@warning "-27-32"]
      let make _props = CSS.global_style_tag (to_string ())
    end
  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  body{color:var(--var-17xndl5);}
  body{color:var(--var-1oo8j6u);}
