#!/bin/bash

# A hook script to verify that the code is about to be pushed is properly formatted.
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

set -e -u

esy build

echo "Run ppx snapshot tests"
esy test_ppx_snapshot

echo "Run Typecheck tests"
esy test_typecheck

echo "Run CSS Support tests"
esy test_css_support

echo "Run CSS Lexer tests"
esy test_css_lexer

echo "Run CSS Lexer 2 tests"
esy test_css_lexer_2

echo "Run CSS Parser tests"
esy test_css_parser

echo "Run CSS Spec Parser tests"
esy test_css_spec_parser

echo "Run BuckleScript tests"
yarn test_bs

exit 0
