#!/bin/bash

# A hook script to verify that the code is about to be pushed is properly formatted.
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#

set -e -u

echo "Run ppx Native tests";
esy test_native;

echo "Run CSS Support tests";
esy test_css_support;

echo "Run ppx Native snapshot tests";
esy test_snapshot;

echo "Run runtests for Parser, vds & Lexer";
esy test;

echo "Run BuckleScript tests";
yarn test_bs;

exit 0
