External module aliases are canonicalized for aggregator lookup. The user writes
`$(Styles.marker)`, but the sentinel records `M.Css.marker` so the aggregator
can resolve it against M's exported [@@@css.bindings].

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

  $ cat n.ml
  [@@@css ".a-mgr994ev1t1.\000M.Css.marker\000{color:blue;}"]
  [@@@css.bindings [("N.wrapper", "id-1axkmel", "a-mgr994ev1t1")]]
  [@@@css.refs [("M.Css.marker", "n.ml", 3, 6, 19)]]
  let _ = M.Css.marker
  module Styles = M.Css
  let wrapper = CSS.make "label:wrapper id-1axkmel a-mgr994ev1t1" []

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-mgr994ev1t1.id-y5baf4{color:blue;}
  }
