This test ensures the ppx generates minified CSS with interpolations

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --myColor-1sirjyy{syntax:"*";inherits:false;}@property --mySize-10o2eri{syntax:"*";inherits:false;}@property --mySize-x1ix8a{syntax:"*";inherits:false;}@property --bgColor-vilhl2{syntax:"*";inherits:false;}@property --myColor-1ixhi5r{syntax:"*";inherits:false;}@layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;@layer styled-ppx.base{._a_4emdyk{color:var(--myColor-1sirjyy);}._in_1ewbqaj{margin:var(--mySize-10o2eri);}._in_1ewbqaj{padding:var(--mySize-x1ix8a);}._a_39004pvpe{background-color:var(--bgColor-vilhl2);}._a_3h18t6{border:1px solid var(--myColor-1ixhi5r);}}

