This test ensures the ppx generates minified CSS with interpolations

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-13tmdyk{color:var(--var-1sirjyy);}
  .css-6mj81u{margin:var(--var-jm31d1);}
  .css-6hxgin{padding:var(--var-1d8c7xy);}
  .css-v2pvpe{background-color:var(--var-vilhl2);}
  .css-jp18t6{border:1px solid var(--var-1ixhi5r);}

