This test ensures the ppx generates minified CSS with interpolations

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --myColor-1sirjyy{syntax:"*";inherits:false;}@property --mySize-10o2eri{syntax:"*";inherits:false;}@property --mySize-x1ix8a{syntax:"*";inherits:false;}@property --bgColor-1s32y0{syntax:"*";inherits:false;}@property --myColor-6ycy2b{syntax:"*";inherits:false;}.css-13tmdyk{color:var(--myColor-1sirjyy);}.css-1ewbqaj{margin:var(--mySize-10o2eri);}.css-1ewbqaj{padding:var(--mySize-x1ix8a);}.css-1pjfgwu{background-color:var(--bgColor-1s32y0);}.css-1pjfgwu{border:1px solid var(--myColor-6ycy2b);}

