A file with no `library` key in its `[@@@css.config]` falls back to its
directory as its group. `z_base/z_base.ml` carries no config at all, so
its group is the directory `z_base`; the dependency edge from `a_app`
still resolves against that fallback group and orders it first.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css ".base-widget{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library", "a_app")]]
  > [@@@css ".app-main{color:blue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .base-widget{color:red;}
  .app-main{color:blue;}

Deterministic: running it again produces byte-identical output.

  $ styled-ppx.generate a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .base-widget{color:red;}
  .app-main{color:blue;}
