This test verifies that statement at-rules (`;`-terminated, no block) flow
through [%styled.global] and the aggregator the same way block at-rules
already do, including a name (`@layer`) that previously had no lexer
allowlist entry for the statement form.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  styled-ppx: output.ml: dropping @charset: the output already starts with a leading comment, so @charset could never be the first bytes of the stylesheet; output is UTF-8 regardless.
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @import url("reset.css");
  @namespace svg url("http://www.w3.org/2000/svg");
  @layer utilities;
  @layer a, b;
  @layer base {.example{color:red;}}
  @media (min-width: 1px) {.responsive{color:blue;}}
  @font-face {font-family:"Inter";}
  body{margin:0;}
