The --env flag is a preset over the individual ppx flags: `development`
equals --dev (marker classes), `production` equals --minify (minified CSS,
no markers). Class names are `a-<hash(content)>` in both modes - --minify
only strips CSS whitespace, it never changes a class name.

  $ refmt --parse re --print ml input.re > input.ml

With --env development, classNames carry a label:<binding> marker, and no
[@@@css.config] is emitted (absence means development).

  $ ../../standalone.exe --env development --impl input.ml -o dev.ml
  $ grep "css.config" dev.ml
  [1]
  $ styled-ppx.generate dev.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-5r08qs{display:flex;}
  .a-94zrbw{padding:12px;}
  .a-4ekvmb{color:red;}
  }
  $ grep "CSS.make" dev.ml
  let layout = CSS.make "label:layout id-1jj5tmt a-5r08qs a-94zrbw" []
  let button = CSS.make "label:button id-l55coe a-4ekvmb" []

With --env production, the same class names appear without markers, and the
PPX declares the environment in the wire protocol so styled-ppx.generate
minifies its output without any flag.

  $ ../../standalone.exe --env production --impl input.ml -o prod.ml
  $ grep "css.config" prod.ml
  [@@@css.config [("env", "production")]]
  $ styled-ppx.generate prod.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;@layer styled-ppx.base{.a-5r08qs{display:flex;}.a-94zrbw{padding:12px;}.a-4ekvmb{color:red;}}
  $ grep "CSS.make" prod.ml
  let layout = CSS.make "id-1jj5tmt a-5r08qs a-94zrbw" []
  let button = CSS.make "id-l55coe a-4ekvmb" []

An unknown environment is rejected by the driver.

  $ ../../standalone.exe --env staging --impl input.ml -o out.ml 2>&1 | grep -o "wrong argument.*"
  wrong argument 'staging'; option '--env' expects one of: development production.
