The --env flag is a preset over the individual ppx flags: `development`
equals --dev (marker classes + readable label suffixes), `production`
equals --minify (no labels, minified CSS, no markers). The hashes are the
same in both modes, only the cosmetic parts differ.

  $ refmt --parse re --print ml input.re > input.ml

With --env development, classNames carry a cx-<binding> marker, the
extracted rules keep the -<label> suffix, and no [@@@css.config] is
emitted (absence means development).

  $ ../../standalone.exe --env development --impl input.ml -o dev.ml
  $ grep "css.config" dev.ml
  [1]
  $ styled-ppx.generate dev.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-k008qs-layout{display:flex;}
  .css-38zrbw-layout{padding:12px;}
  .css-tokvmb-button{color:red;}
  $ grep "CSS.make" dev.ml
  let layout = CSS.make "cx-layout css-k008qs-layout css-38zrbw-layout" []
  let button = CSS.make "cx-button css-tokvmb-button" []

With --env production, the same hashes appear without label suffixes and
without markers, and the PPX declares the environment in the wire
protocol so styled-ppx.generate minifies its output without any flag.

  $ ../../standalone.exe --env production --impl input.ml -o prod.ml
  $ grep "css.config" prod.ml
  [@@@css.config [("env", "production")]]
  $ styled-ppx.generate prod.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-k008qs{display:flex;}.css-38zrbw{padding:12px;}.css-tokvmb{color:red;}
  $ grep "CSS.make" prod.ml
  let layout = CSS.make "css-k008qs css-38zrbw" []
  let button = CSS.make "css-tokvmb" []

An unknown environment is rejected by the driver.

  $ ../../standalone.exe --env staging --impl input.ml -o out.ml 2>&1 | grep -o "wrong argument.*"
  wrong argument 'staging'; option '--env' expects one of: development production.
