Identical CSS rules across files are emitted exactly once.

  $ cat > a.ml <<EOF
  > [@@@css ".a{color:red;}"]
  > [@@@css ".shared{padding:1rem;}"]
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".b{color:blue;}"]
  > [@@@css ".shared{padding:1rem;}"]
  > EOF

  $ styled-ppx.generate a.ml b.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
  .b{color:blue;}
  .shared{padding:1rem;}
