`--layers` emits a layer only for a group that still owns a rule once every
rule is resolved and deduplicated. A module with no `[%css]` carries no
`[@@@css.config]`, so it falls back to its directory as its group. Such a
group used to get an empty `@layer name {}` block and a name in the order
statement, and two rule-less directories with the same last segment (`doc`,
`src`, `types`) raised a name-collision warning about groups that had
nothing to merge.

  $ mkdir -p a_app z_base plain/doc other/doc

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base")]]
  > [@@@css ".base-widget{color:red;}"]
  > let widget () = ()
  > EOF

The rule-less module still takes part in dependency ordering: `a_app`
reaches `z_base` only through `Plain`, and `z_base` is still emitted first.

  $ cat > plain/doc/plain.ml <<EOF
  > let widget = Z_base.widget
  > EOF

  $ cat > other/doc/notes.ml <<EOF
  > let notes = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app")]]
  > [@@@css ".app-main{color:blue;}"]
  > let _ = Plain.widget
  > EOF

  $ styled-ppx.generate --layers --log info a_app/main.ml z_base/z_base.ml plain/doc/plain.ml other/doc/notes.ml
  styled-ppx: output file: stdout
  styled-ppx: library order: other/doc, z_base, plain/doc, a_app
  styled-ppx: order: other/doc: Notes
  styled-ppx: order: z_base: Z_base
  styled-ppx: order: plain/doc: Plain
  styled-ppx: order: a_app: Main
  styled-ppx: layers: z_base, a_app
  styled-ppx: environment: development
  /* This file is generated by styled-ppx, do not edit manually */
  @layer z_base, a_app;
  @layer z_base {
  .base-widget{color:red;}
  }
  @layer a_app {
  .app-main{color:blue;}
  }

A library whose only rules are `@property` or `@keyframes` registrations owns
nothing to layer either: the registrations stay ahead of the layers as
before, and no empty block is emitted for it.

  $ mkdir spin

  $ cat > spin/spin.ml <<EOF
  > [@@@css.config [("library-name", "spin")]]
  > [@@@css "@keyframes spin { to { transform: rotate(360deg); } }"]
  > EOF

  $ styled-ppx.generate --layers a_app/main.ml z_base/z_base.ml plain/doc/plain.ml spin/spin.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @keyframes spin { to { transform: rotate(360deg); } }
  @layer z_base, a_app;
  @layer z_base {
  .base-widget{color:red;}
  }
  @layer a_app {
  .app-main{color:blue;}
  }
