Regression guard: cross-module [%keyframe] interpolation does not collide.

Two modules define the byte-identical interpolated keyframe `grow` plus a
`[%css animation-name: $(grow)]` binding, differing only in a sibling
declaration. This confirms the keyframe path is free of the atomic class/var
collision that affected [%css] backgrounds.

Two hashing schemes meet here, both routed through Hash_class.
First, the `animation-name: $(grow)` atom is hashed from its own declaration
content (Hash_class.bundle_class_and_namespace - it interpolates a value, so
it is an `in-` bundle atom), so its class (in-14rjjsz-box) AND
its variable (--var-1ugf6s8) are identical in both modules and the aggregator
dedupes the rule to a single line.
Second, the keyframe itself is namespaced by kind+module+scope
(Hash_class.scoped_namespace), so its internal height variables - and thus its
content-hashed k-<hash> name - differ per module (k-1h1i3op vs
k-1arknxa); the two keyframes are emitted under distinct names. The
namespace is keyed on the compilation-unit module name, not the physical file
path, so the same module compiled from two paths agrees on one keyframe name.

Why this is safe: custom properties resolve per element. Each module's `grow`
sets the shared `--var-1ugf6s8` to ITS OWN keyframe name and, on the same
element, sets that keyframe's internal height variables. Every element thus
resolves the animation-name variable and the keyframe body against values it
actually set - no element references a variable it did not set. The
per-module divergence lives in the keyframe NAME (a value), never in a shared
class pointing at a missing variable.

  $ refmt --parse re --print ml a.re > a.ml
  $ ../../standalone.exe --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ ../../standalone.exe --impl b.ml -o b.ml
  $ cat a.ml
  [@@@css
    "@keyframes k-1h1i3op{0%{height:var(--h0-9tm5yy);}100%{height:var(--h1-mjt56l);}}"]
  [@@@css
    ".in-14rjjsz{-webkit-animation-name:var(--grow-1ugf6s8);animation-name:var(--grow-1ugf6s8);}"]
  [@@@css ".a-k008qs{display:flex;}"]
  [@@@css.bindings [("A.box", "id-1v8d5b9", "in-14rjjsz a-k008qs")]]
  let h0 = `px 0
  let h1 = `px 100
  let grow =
    CSS.Types.AnimationName.make
      ~vars:[("--h0-9tm5yy", (CSS.Types.Height.toString h0));
            ("--h1-mjt56l", (CSS.Types.Height.toString h1))] "k-1h1i3op"
  let box =
    CSS.make "label:box id-1v8d5b9 in-14rjjsz a-k008qs"
      (CSS.Types.AnimationName.toStyleVars "--grow-1ugf6s8" grow)
  $ cat b.ml
  [@@@css
    "@keyframes k-1arknxa{0%{height:var(--h0-yrpn7p);}100%{height:var(--h1-1oxv8aa);}}"]
  [@@@css
    ".in-14rjjsz{-webkit-animation-name:var(--grow-1ugf6s8);animation-name:var(--grow-1ugf6s8);}"]
  [@@@css ".a-hpgf8j{padding:8px;}"]
  [@@@css.bindings [("B.box", "id-p1cefd", "in-14rjjsz a-hpgf8j")]]
  let h0 = `px 0
  let h1 = `px 100
  let grow =
    CSS.Types.AnimationName.make
      ~vars:[("--h0-yrpn7p", (CSS.Types.Height.toString h0));
            ("--h1-1oxv8aa", (CSS.Types.Height.toString h1))] "k-1arknxa"
  let box =
    CSS.make "label:box id-p1cefd in-14rjjsz a-hpgf8j"
      (CSS.Types.AnimationName.toStyleVars "--grow-1ugf6s8" grow)
  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @keyframes k-1h1i3op{0%{height:var(--h0-9tm5yy);}100%{height:var(--h1-mjt56l);}}
  .in-14rjjsz{-webkit-animation-name:var(--grow-1ugf6s8);animation-name:var(--grow-1ugf6s8);}
  .a-k008qs{display:flex;}
  @keyframes k-1arknxa{0%{height:var(--h0-yrpn7p);}100%{height:var(--h1-1oxv8aa);}}
  .a-hpgf8j{padding:8px;}
