blockA and blockB set the same property (color) under the same two
`@media (min-width: ...)` conditions, which overlap (both are true at
widths >= 900px). blockA writes them mobile-first, 600px then 900px, so
red should show at 600-899px and blue should win at >=900px. blockB
writes the identical two declarations in the opposite source order,
900px then 600px - by the same "later declaration overrides at equal
specificity" rule the design docs state for one block, blockB's author
intends red (the 600px rule, written last) to win at >=900px instead.

Before the media rewrite, both @media rules were byte-identical between
the two blocks (same condition, same property, same value), so they
atomized to the same two classes and dedup kept only the first-sighted
copy of each rule position - blockB silently got blockA's order. After
the rewrite each block's own atoms carry their own negated condition, so
the two blocks no longer collide and each keeps its own author order.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css
    "@media (min-width: 600px) and (not (min-width: 900px)){._a_izob04e6zo5{color:red;}}"]
  [@@@css "@media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}"]
  [@@@css
    "@media (min-width: 900px) and (not (min-width: 600px)){._a_mp5mk4exhzt{color:blue;}}"]
  [@@@css "@media (min-width: 600px) {._a_izob04e698n{color:red;}}"]
  [@@@css.bindings
    [("Output.blockA", "_id_bitm25", "_a_izob04e6zo5 _a_mp5mk4et4n8");
    ("Output.blockB", "_id_1kl48f", "_a_mp5mk4exhzt _a_izob04e698n")]]
  let blockA =
    CSS.make "label:blockA _id_bitm25 _a_izob04e6zo5 _a_mp5mk4et4n8" []
  let blockB =
    CSS.make "label:blockB _id_1kl48f _a_mp5mk4exhzt _a_izob04e698n" []
  let _ = (blockA, blockB)

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 600px) and (not (min-width: 900px)){._a_izob04e6zo5{color:red;}}
  @media (min-width: 900px) and (not (min-width: 600px)){._a_mp5mk4exhzt{color:blue;}}
  @media (min-width: 600px) {._a_izob04e698n{color:red;}}
  @media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}
