Passing the same input file twice terminates and emits its rules once.

  $ cat > a.ml <<EOF
  > [@@@css ".a{color:red;}"]
  > EOF

  $ styled-ppx.generate a.ml a.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  .a{color:red;}
  }
