Passing the same input file twice terminates and emits its rules once.

  $ cat > a.ml <<EOF
  > [@@@css ".a{color:red;}"]
  > EOF

  $ styled-ppx.generate a.ml a.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
