Test box-shadow and text-shadow interpolation support in cx2

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-bddc{box-shadow:var(--singleShadow-2ra8gi);}
  .css-dm7kax{box-shadow:var(--shadowArray-16v4cs);}
  .css-gokeqi{box-shadow:none;}
  .css-12b85tv{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1);}
  .css-oixlo4{text-shadow:var(--textShadowValue-1g9u54a);}
  .css-n95t96{text-shadow:var(--textShadowArray-ptx88i);}
  .css-1f9ql9z{text-shadow:none;}
  .css-1x6ky98{box-shadow:var(--insetShadow-ae1kx4);}


