Multi-class cross-module fan-out: when `M.marker` mints multiple classes
(one per atomized declaration), the cross-module reference must resolve
to a chained compound `.cssA.cssB` so the consumer's rule fires only when
every atom of `M.marker` is present on the element.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-1443u2l-marker{background:red;}
  .css-17s01vz-container.css-1443u2l-marker.css-kbn7if-marker{padding:1rem;}
  .css-kbn7if-marker{color:white;}
