Two named bindings whose declarations are byte-identical now mint the same
atom, because the class name is a pure hash of the content with no `-<label>`
suffix to tell them apart. The PPX ships the rule once (one `[@@@css ...]`
attribute, not one per binding) and both `CSS.make` calls carry the same
atom class. The aggregated stylesheet dedups the same way, down to one rule.

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ grep -c '@@@css "' output.ml
  1
  $ grep 'CSS.make' output.ml
  let a = CSS.make ~label:"a" "cid-fo0igp css-tokvmb" []
  let b = CSS.make ~label:"b" "cid-mkba68 css-tokvmb" []

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-tokvmb{color:red;}
