Two named bindings whose declarations are byte-identical now mint the same
atom, because the class name is a pure hash of the content with no `-<label>`
suffix to tell them apart. The PPX ships the rule once (one `[@@@css ...]`
attribute, not one per binding) and both `CSS.make` calls carry the same
atom class. The aggregated stylesheet dedups the same way, down to one rule.

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ grep -c '@@@css "' output.ml
  1
  $ grep 'CSS.make' output.ml
  let a = CSS.make "label:a id-fo0igp a-4ekvmb" []
  let b = CSS.make "label:b id-mkba68 a-4ekvmb" []

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-4ekvmb{color:red;}
  }
