`styled-ppx.generate` emits no `@layer` at all: a page that links this
output alongside anything else competes by ordinary CSS specificity and
position, like plain CSS with no layers ever existing (see "Cascade tiers"
in `generate.ml`, and `global-tier.t`/`descendant-tier.t` for the
consequences that accepts). The output order is still fixed - globals,
then base atoms, then conditional atoms, each group sorted by
parent-to-child shape then shorthand depth - but nothing wraps any of it
in a cascade layer, so that order is only ever a tie-break, never an
unconditional priority.

One input carrying all three kinds at once: a `[%styled.global]` rule
(`*{box-sizing:inherit;}`, no atom class), an unconditional atom (`base`),
and an atom wrapped in `@media` (`conditional`).

  $ cat > combo.ml <<EOF
  > [@@@css "*{box-sizing:inherit;}"]
  > [@@@css "._a_basewidget{color:red;}"]
  > [@@@css "@media (min-width:768px){._a_condwidget:hover{color:blue;}}"]
  > EOF

  $ styled-ppx.generate combo.ml
  /* This file is generated by styled-ppx, do not edit manually */
  *{box-sizing:inherit;}
  ._a_basewidget{color:red;}
  @media (min-width:768px){._a_condwidget:hover{color:blue;}}

No `@layer` line anywhere in that output - the full dump above is the
whole file.

The order holds even when the three kinds appear in the opposite order in
the source, and split across declaration order within one input: the
conditional atom is declared first here, then the global, then the base
atom, but the emitted order is still global, base, conditional.

  $ cat > reordered.ml <<EOF
  > [@@@css "@media (min-width:768px){._a_condwidget:hover{color:blue;}}"]
  > [@@@css "*{box-sizing:inherit;}"]
  > [@@@css "._a_basewidget{color:red;}"]
  > EOF

  $ styled-ppx.generate reordered.ml
  /* This file is generated by styled-ppx, do not edit manually */
  *{box-sizing:inherit;}
  ._a_basewidget{color:red;}
  @media (min-width:768px){._a_condwidget:hover{color:blue;}}
