/* CSS Box Alignment Module Level 3 */
[%cx2 {|align-self: auto|}];
[%cx2 {|align-self: normal|}];
[%cx2 {|align-self: stretch|}];
[%cx2 {|align-self: baseline|}];
[%cx2 {|align-self: first baseline|}];
[%cx2 {|align-self: last baseline|}];
[%cx2 {|align-self: center|}];
[%cx2 {|align-self: start|}];
[%cx2 {|align-self: end|}];
[%cx2 {|align-self: self-start|}];
[%cx2 {|align-self: self-end|}];
[%cx2 {|align-self: unsafe start|}];
[%cx2 {|align-self: safe start|}];
[%cx2 {|align-items: normal|}];
[%cx2 {|align-items: stretch|}];
[%cx2 {|align-items: baseline|}];
[%cx2 {|align-items: first baseline|}];
[%cx2 {|align-items: last baseline|}];
[%cx2 {|align-items: center|}];
[%cx2 {|align-items: start|}];
[%cx2 {|align-items: end|}];
[%cx2 {|align-items: self-start|}];
[%cx2 {|align-items: self-end|}];
[%cx2 {|align-items: unsafe start|}];
[%cx2 {|align-items: safe start|}];
[%cx2 {|align-content: normal|}];
[%cx2 {|align-content: baseline|}];
[%cx2 {|align-content: first baseline|}];
[%cx2 {|align-content: last baseline|}];
[%cx2 {|align-content: space-between|}];
[%cx2 {|align-content: space-around|}];
[%cx2 {|align-content: space-evenly|}];
[%cx2 {|align-content: stretch|}];
[%cx2 {|align-content: center|}];
[%cx2 {|align-content: start|}];
[%cx2 {|align-content: end|}];
[%cx2 {|align-content: flex-start|}];
[%cx2 {|align-content: flex-end|}];
[%cx2 {|align-content: unsafe start|}];
[%cx2 {|align-content: safe start|}];
[%cx2 {|justify-self: auto|}];
[%cx2 {|justify-self: normal|}];
[%cx2 {|justify-self: stretch|}];
[%cx2 {|justify-self: baseline|}];
[%cx2 {|justify-self: first baseline|}];
[%cx2 {|justify-self: last baseline|}];
[%cx2 {|justify-self: center|}];
[%cx2 {|justify-self: start|}];
[%cx2 {|justify-self: end|}];
[%cx2 {|justify-self: self-start|}];
[%cx2 {|justify-self: self-end|}];
[%cx2 {|justify-self: unsafe start|}];
[%cx2 {|justify-self: safe start|}];
[%cx2 {|justify-self: left|}];
[%cx2 {|justify-self: right|}];
[%cx2 {|justify-self: safe right|}];
[%cx2 {|justify-items: normal|}];
[%cx2 {|justify-items: stretch|}];
[%cx2 {|justify-items: baseline|}];
[%cx2 {|justify-items: first baseline|}];
[%cx2 {|justify-items: last baseline|}];
[%cx2 {|justify-items: center|}];
[%cx2 {|justify-items: start|}];
[%cx2 {|justify-items: end|}];
[%cx2 {|justify-items: self-start|}];
[%cx2 {|justify-items: self-end|}];
[%cx2 {|justify-items: unsafe start|}];
[%cx2 {|justify-items: safe start|}];
[%cx2 {|justify-items: left|}];
[%cx2 {|justify-items: right|}];
[%cx2 {|justify-items: safe right|}];
[%cx2 {|justify-items: legacy|}];
[%cx2 {|justify-items: legacy left|}];
[%cx2 {|justify-items: legacy right|}];
[%cx2 {|justify-items: legacy center|}];
[%cx2 {|justify-content: normal|}];
[%cx2 {|justify-content: space-between|}];
[%cx2 {|justify-content: space-around|}];
[%cx2 {|justify-content: space-evenly|}];
[%cx2 {|justify-content: stretch|}];
[%cx2 {|justify-content: center|}];
[%cx2 {|justify-content: start|}];
[%cx2 {|justify-content: end|}];
[%cx2 {|justify-content: flex-start|}];
[%cx2 {|justify-content: flex-end|}];
[%cx2 {|justify-content: unsafe start|}];
[%cx2 {|justify-content: safe start|}];
[%cx2 {|justify-content: left|}];
[%cx2 {|justify-content: right|}];
[%cx2 {|justify-content: safe right|}];
[%cx2 {|place-content: normal|}];
[%cx2 {|place-content: baseline|}];
[%cx2 {|place-content: first baseline|}];
[%cx2 {|place-content: last baseline|}];
[%cx2 {|place-content: space-between|}];
[%cx2 {|place-content: space-around|}];
[%cx2 {|place-content: space-evenly|}];
[%cx2 {|place-content: stretch|}];
[%cx2 {|place-content: center|}];
[%cx2 {|place-content: start|}];
[%cx2 {|place-content: end|}];
[%cx2 {|place-content: flex-start|}];
[%cx2 {|place-content: flex-end|}];
[%cx2 {|place-content: unsafe start|}];
[%cx2 {|place-content: safe start|}];
[%cx2 {|place-content: normal normal|}];
[%cx2 {|place-content: baseline normal|}];
[%cx2 {|place-content: first baseline normal|}];
[%cx2 {|place-content: space-between normal|}];
[%cx2 {|place-content: center normal|}];
[%cx2 {|place-content: unsafe start normal|}];
[%cx2 {|place-content: normal stretch|}];
[%cx2 {|place-content: baseline stretch|}];
[%cx2 {|place-content: first baseline stretch|}];
[%cx2 {|place-content: center stretch|}];
[%cx2 {|place-content: unsafe start stretch|}];
[%cx2 {|place-content: normal safe right|}];
[%cx2 {|place-content: baseline safe right|}];
[%cx2 {|place-content: first baseline safe right|}];
[%cx2 {|place-content: space-between safe right|}];
[%cx2 {|place-content: center safe right|}];
[%cx2 {|place-content: unsafe start safe right|}];
[%cx2 {|place-items: normal|}];
[%cx2 {|place-items: stretch|}];
[%cx2 {|place-items: baseline|}];
[%cx2 {|place-items: first baseline|}];
[%cx2 {|place-items: last baseline|}];
[%cx2 {|place-items: center|}];
[%cx2 {|place-items: start|}];
[%cx2 {|place-items: end|}];
[%cx2 {|place-items: self-start|}];
[%cx2 {|place-items: self-end|}];
[%cx2 {|place-items: unsafe start|}];
[%cx2 {|place-items: safe start|}];
[%cx2 {|place-items: normal normal|}];
[%cx2 {|place-items: stretch normal|}];
[%cx2 {|place-items: baseline normal|}];
[%cx2 {|place-items: first baseline normal|}];
[%cx2 {|place-items: self-start normal|}];
[%cx2 {|place-items: unsafe start normal|}];
[%cx2 {|place-items: normal stretch|}];
[%cx2 {|place-items: stretch stretch|}];
[%cx2 {|place-items: baseline stretch|}];
[%cx2 {|place-items: first baseline stretch|}];
[%cx2 {|place-items: self-start stretch|}];
[%cx2 {|place-items: unsafe start stretch|}];
[%cx2 {|place-items: normal last baseline|}];
[%cx2 {|place-items: stretch last baseline|}];
[%cx2 {|place-items: baseline last baseline|}];
[%cx2 {|place-items: first baseline last baseline|}];
[%cx2 {|place-items: self-start last baseline|}];
[%cx2 {|place-items: unsafe start last baseline|}];
[%cx2 {|place-items: normal legacy left|}];
[%cx2 {|place-items: stretch legacy left|}];
[%cx2 {|place-items: baseline legacy left|}];
[%cx2 {|place-items: first baseline legacy left|}];
[%cx2 {|place-items: self-start legacy left|}];
[%cx2 {|place-items: unsafe start legacy left|}];

[%cx2 {|gap: 0 0|}];
[%cx2 {|gap: 0 1em|}];
[%cx2 {|gap: 1em|}];
[%cx2 {|gap: 1em 1em|}];
[%cx2 {|column-gap: 0|}];
[%cx2 {|column-gap: 1em|}];
[%cx2 {|column-gap: normal|}];
[%cx2 {|row-gap: 0|}];
[%cx2 {|row-gap: 1em|}];

/* CSS Box Model Module Level 4 */
[%cx2 {|margin-trim: none|}];
[%cx2 {|margin-trim: in-flow|}];
[%cx2 {|margin-trim: all|}];
