This test ensures the ppx generates the correct output against styled-ppx.native
If this test fail means that the module is not in sync with the ppx
  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > EOF

  $ cat > dune << EOF
  > (executable
  >  (name input)
  >  (libraries styled-ppx.native)
  >  (preprocess (pps styled-ppx)))
  > EOF

  $ dune build

  $ dune describe pp ./input.re | sed '1,/^];$/d'
  [@css ".css-28lqh0{align-self:auto;}"];
  [@css ".css-1oa5str{align-self:normal;}"];
  [@css ".css-fzqoy4{align-self:stretch;}"];
  [@css ".css-chwum8{align-self:baseline;}"];
  [@css ".css-1lz2ze6{align-self:first baseline;}"];
  [@css ".css-ko0zg2{align-self:last baseline;}"];
  [@css ".css-hoe9xz{align-self:center;}"];
  [@css ".css-1hcehcy{align-self:start;}"];
  [@css ".css-1fuqp3k{align-self:end;}"];
  [@css ".css-sobvnc{align-self:self-start;}"];
  [@css ".css-6bhf65{align-self:self-end;}"];
  [@css ".css-lsgsxr{align-self:unsafe start;}"];
  [@css ".css-n6q3l2{align-self:safe start;}"];
  [@css ".css-1l47rk4{align-items:normal;}"];
  [@css ".css-k51ack{align-items:stretch;}"];
  [@css ".css-1y3jl3a{align-items:baseline;}"];
  [@css ".css-1v63wj4{align-items:first baseline;}"];
  [@css ".css-1par88q{align-items:last baseline;}"];
  [@css ".css-zcxndt{align-items:center;}"];
  [@css ".css-thqn8b{align-items:start;}"];
  [@css ".css-h812ai{align-items:end;}"];
  [@css ".css-1iymgp6{align-items:self-start;}"];
  [@css ".css-piyf6q{align-items:self-end;}"];
  [@css ".css-1con9n2{align-items:unsafe start;}"];
  [@css ".css-9x8fld{align-items:safe start;}"];
  [@css ".css-1ph82qi{align-content:normal;}"];
  [@css ".css-m6tf19{align-content:baseline;}"];
  [@css ".css-129e56e{align-content:first baseline;}"];
  [@css ".css-197bvxk{align-content:last baseline;}"];
  [@css ".css-1c5t6ef{align-content:space-between;}"];
  [@css ".css-1okulzr{align-content:space-around;}"];
  [@css ".css-oazzqp{align-content:space-evenly;}"];
  [@css ".css-zssg0i{align-content:stretch;}"];
  [@css ".css-1a5ho4p{align-content:center;}"];
  [@css ".css-zf62g1{align-content:start;}"];
  [@css ".css-1u0otui{align-content:end;}"];
  [@css ".css-1crvgc7{align-content:flex-start;}"];
  [@css ".css-4zx96o{align-content:flex-end;}"];
  [@css ".css-gr6jw8{align-content:unsafe start;}"];
  [@css ".css-5j2jhg{align-content:safe start;}"];
  [@css ".css-mxnscv{justify-self:auto;}"];
  [@css ".css-9a0v6u{justify-self:normal;}"];
  [@css ".css-1j4yvex{justify-self:stretch;}"];
  [@css ".css-ow3z27{justify-self:baseline;}"];
  [@css ".css-1hf5zq0{justify-self:first baseline;}"];
  [@css ".css-18k0186{justify-self:last baseline;}"];
  [@css ".css-tddfjc{justify-self:center;}"];
  [@css ".css-85bxzs{justify-self:start;}"];
  [@css ".css-v1pv54{justify-self:end;}"];
  [@css ".css-rkab6k{justify-self:self-start;}"];
  [@css ".css-e4zxgz{justify-self:self-end;}"];
  [@css ".css-2nobw4{justify-self:unsafe start;}"];
  [@css ".css-le5sda{justify-self:safe start;}"];
  [@css ".css-vv4swf{justify-self:left;}"];
  [@css ".css-9b5rli{justify-self:right;}"];
  [@css ".css-1uhakos{justify-self:safe right;}"];
  [@css ".css-1s3t02p{justify-items:normal;}"];
  [@css ".css-osw19q{justify-items:stretch;}"];
  [@css ".css-178sd3r{justify-items:baseline;}"];
  [@css ".css-g3oxkb{justify-items:first baseline;}"];
  [@css ".css-1d1nqwq{justify-items:last baseline;}"];
  [@css ".css-hghncw{justify-items:center;}"];
  [@css ".css-g27xd1{justify-items:start;}"];
  [@css ".css-c4d6ik{justify-items:end;}"];
  [@css ".css-1rxujby{justify-items:self-start;}"];
  [@css ".css-1npjls5{justify-items:self-end;}"];
  [@css ".css-1lfkxpa{justify-items:unsafe start;}"];
  [@css ".css-u1igov{justify-items:safe start;}"];
  [@css ".css-5whueq{justify-items:left;}"];
  [@css ".css-butw7a{justify-items:right;}"];
  [@css ".css-1uhzryg{justify-items:safe right;}"];
  [@css ".css-1phqp4r{justify-items:legacy;}"];
  [@css ".css-6d6jur{justify-items:legacy left;}"];
  [@css ".css-av1n9p{justify-items:legacy right;}"];
  [@css ".css-b18x1c{justify-items:legacy center;}"];
  [@css ".css-18dm5u{justify-content:normal;}"];
  [@css ".css-x4dmss{justify-content:space-between;}"];
  [@css ".css-kp4oss{justify-content:space-around;}"];
  [@css ".css-1ku462w{justify-content:space-evenly;}"];
  [@css ".css-x208ak{justify-content:stretch;}"];
  [@css ".css-1tyndxa{justify-content:center;}"];
  [@css ".css-k1xozo{justify-content:start;}"];
  [@css ".css-1b1rfkc{justify-content:end;}"];
  [@css ".css-1fn0841{justify-content:flex-start;}"];
  [@css ".css-1a9getn{justify-content:flex-end;}"];
  [@css ".css-t0ygzb{justify-content:unsafe start;}"];
  [@css ".css-1d6pp7h{justify-content:safe start;}"];
  [@css ".css-d5dmac{justify-content:left;}"];
  [@css ".css-dajo9q{justify-content:right;}"];
  [@css ".css-vp89l6{justify-content:safe right;}"];
  [@css ".css-6lqrgx{place-content:normal;}"];
  [@css ".css-1k2zktz{place-content:baseline;}"];
  [@css ".css-kd0k3s{place-content:first baseline;}"];
  [@css ".css-123lpj3{place-content:last baseline;}"];
  [@css ".css-1jag07y{place-content:space-between;}"];
  [@css ".css-fhn9tt{place-content:space-around;}"];
  [@css ".css-1lz8p3p{place-content:space-evenly;}"];
  [@css ".css-auwium{place-content:stretch;}"];
  [@css ".css-gdqw8{place-content:center;}"];
  [@css ".css-16c5dhv{place-content:start;}"];
  [@css ".css-16pnyc7{place-content:end;}"];
  [@css ".css-tdrdu{place-content:flex-start;}"];
  [@css ".css-1v2nttj{place-content:flex-end;}"];
  [@css ".css-bj71ck{place-content:unsafe start;}"];
  [@css ".css-1u7qxqj{place-content:safe start;}"];
  [@css ".css-yo3qoo{place-content:normal normal;}"];
  [@css ".css-ednuac{place-content:baseline normal;}"];
  [@css ".css-1ly0fds{place-content:first baseline normal;}"];
  [@css ".css-1lnhpg7{place-content:space-between normal;}"];
  [@css ".css-6kzrg5{place-content:center normal;}"];
  [@css ".css-ccz0tb{place-content:unsafe start normal;}"];
  [@css ".css-pgi3io{place-content:normal stretch;}"];
  [@css ".css-e1fbzg{place-content:baseline stretch;}"];
  [@css ".css-hf8zlv{place-content:first baseline stretch;}"];
  [@css ".css-1tb4shn{place-content:center stretch;}"];
  [@css ".css-1ogf3b8{place-content:unsafe start stretch;}"];
  [@css ".css-11cb47q{place-content:normal safe right;}"];
  [@css ".css-1e2wp5i{place-content:baseline safe right;}"];
  [@css ".css-1s7pafp{place-content:first baseline safe right;}"];
  [@css ".css-1phtr2b{place-content:space-between safe right;}"];
  [@css ".css-m6hl56{place-content:center safe right;}"];
  [@css ".css-ys288f{place-content:unsafe start safe right;}"];
  [@css ".css-o9u5yn{place-items:normal;}"];
  [@css ".css-dnwgtc{place-items:stretch;}"];
  [@css ".css-yzp3r0{place-items:baseline;}"];
  [@css ".css-u3jtjp{place-items:first baseline;}"];
  [@css ".css-nbmap8{place-items:last baseline;}"];
  [@css ".css-yoym04{place-items:center;}"];
  [@css ".css-racea0{place-items:start;}"];
  [@css ".css-16qqbga{place-items:end;}"];
  [@css ".css-1v9cfae{place-items:self-start;}"];
  [@css ".css-ji4r6c{place-items:self-end;}"];
  [@css ".css-11xk81w{place-items:unsafe start;}"];
  [@css ".css-uhboah{place-items:safe start;}"];
  [@css ".css-117oh71{place-items:normal normal;}"];
  [@css ".css-1mvk8n{place-items:stretch normal;}"];
  [@css ".css-162m489{place-items:baseline normal;}"];
  [@css ".css-11lbjab{place-items:first baseline normal;}"];
  [@css ".css-bdz5p3{place-items:self-start normal;}"];
  [@css ".css-pd2at7{place-items:unsafe start normal;}"];
  [@css ".css-1rt9qwi{place-items:normal stretch;}"];
  [@css ".css-qg7oz{place-items:stretch stretch;}"];
  [@css ".css-asecxz{place-items:baseline stretch;}"];
  [@css ".css-gndtd3{place-items:first baseline stretch;}"];
  [@css ".css-12jtjgd{place-items:self-start stretch;}"];
  [@css ".css-b824mg{place-items:unsafe start stretch;}"];
  [@css ".css-11znfmq{place-items:normal last baseline;}"];
  [@css ".css-u7203s{place-items:stretch last baseline;}"];
  [@css ".css-tbq0j0{place-items:baseline last baseline;}"];
  [@css ".css-1xqsgia{place-items:first baseline last baseline;}"];
  [@css ".css-x25oxa{place-items:self-start last baseline;}"];
  [@css ".css-8rf3bh{place-items:unsafe start last baseline;}"];
  [@css ".css-x3o9xj{place-items:normal legacy left;}"];
  [@css ".css-yuaufw{place-items:stretch legacy left;}"];
  [@css ".css-19o4fdy{place-items:baseline legacy left;}"];
  [@css ".css-1allg27{place-items:first baseline legacy left;}"];
  [@css ".css-1um6nyr{place-items:self-start legacy left;}"];
  [@css ".css-1ogsbzm{place-items:unsafe start legacy left;}"];
  [@css ".css-z39awh{gap:0 0;}"];
  [@css ".css-1m20ra0{gap:0 1em;}"];
  [@css ".css-bd6cki{gap:1em;}"];
  [@css ".css-f0kubh{gap:1em 1em;}"];
  [@css ".css-zqzqln{column-gap:0;}"];
  [@css ".css-602mee{column-gap:1em;}"];
  [@css ".css-mz5ixr{column-gap:normal;}"];
  [@css ".css-1j42sqe{row-gap:0;}"];
  [@css ".css-28i0al{row-gap:1em;}"];
  [@css ".css-xyx8z6{margin-trim:none;}"];
  [@css ".css-s28oi1{margin-trim:in-flow;}"];
  [@css ".css-1fk011{margin-trim:all;}"];
  
  CSS.make("css-28lqh0", []);
  CSS.make("css-1oa5str", []);
  CSS.make("css-fzqoy4", []);
  CSS.make("css-chwum8", []);
  CSS.make("css-1lz2ze6", []);
  CSS.make("css-ko0zg2", []);
  CSS.make("css-hoe9xz", []);
  CSS.make("css-1hcehcy", []);
  CSS.make("css-1fuqp3k", []);
  CSS.make("css-sobvnc", []);
  CSS.make("css-6bhf65", []);
  CSS.make("css-lsgsxr", []);
  CSS.make("css-n6q3l2", []);
  CSS.make("css-1l47rk4", []);
  CSS.make("css-k51ack", []);
  CSS.make("css-1y3jl3a", []);
  CSS.make("css-1v63wj4", []);
  CSS.make("css-1par88q", []);
  CSS.make("css-zcxndt", []);
  CSS.make("css-thqn8b", []);
  CSS.make("css-h812ai", []);
  CSS.make("css-1iymgp6", []);
  CSS.make("css-piyf6q", []);
  CSS.make("css-1con9n2", []);
  CSS.make("css-9x8fld", []);
  CSS.make("css-1ph82qi", []);
  CSS.make("css-m6tf19", []);
  CSS.make("css-129e56e", []);
  CSS.make("css-197bvxk", []);
  CSS.make("css-1c5t6ef", []);
  CSS.make("css-1okulzr", []);
  CSS.make("css-oazzqp", []);
  CSS.make("css-zssg0i", []);
  CSS.make("css-1a5ho4p", []);
  CSS.make("css-zf62g1", []);
  CSS.make("css-1u0otui", []);
  CSS.make("css-1crvgc7", []);
  CSS.make("css-4zx96o", []);
  CSS.make("css-gr6jw8", []);
  CSS.make("css-5j2jhg", []);
  CSS.make("css-mxnscv", []);
  CSS.make("css-9a0v6u", []);
  CSS.make("css-1j4yvex", []);
  CSS.make("css-ow3z27", []);
  CSS.make("css-1hf5zq0", []);
  CSS.make("css-18k0186", []);
  CSS.make("css-tddfjc", []);
  CSS.make("css-85bxzs", []);
  CSS.make("css-v1pv54", []);
  CSS.make("css-rkab6k", []);
  CSS.make("css-e4zxgz", []);
  CSS.make("css-2nobw4", []);
  CSS.make("css-le5sda", []);
  CSS.make("css-vv4swf", []);
  CSS.make("css-9b5rli", []);
  CSS.make("css-1uhakos", []);
  CSS.make("css-1s3t02p", []);
  CSS.make("css-osw19q", []);
  CSS.make("css-178sd3r", []);
  CSS.make("css-g3oxkb", []);
  CSS.make("css-1d1nqwq", []);
  CSS.make("css-hghncw", []);
  CSS.make("css-g27xd1", []);
  CSS.make("css-c4d6ik", []);
  CSS.make("css-1rxujby", []);
  CSS.make("css-1npjls5", []);
  CSS.make("css-1lfkxpa", []);
  CSS.make("css-u1igov", []);
  CSS.make("css-5whueq", []);
  CSS.make("css-butw7a", []);
  CSS.make("css-1uhzryg", []);
  CSS.make("css-1phqp4r", []);
  CSS.make("css-6d6jur", []);
  CSS.make("css-av1n9p", []);
  CSS.make("css-b18x1c", []);
  CSS.make("css-18dm5u", []);
  CSS.make("css-x4dmss", []);
  CSS.make("css-kp4oss", []);
  CSS.make("css-1ku462w", []);
  CSS.make("css-x208ak", []);
  CSS.make("css-1tyndxa", []);
  CSS.make("css-k1xozo", []);
  CSS.make("css-1b1rfkc", []);
  CSS.make("css-1fn0841", []);
  CSS.make("css-1a9getn", []);
  CSS.make("css-t0ygzb", []);
  CSS.make("css-1d6pp7h", []);
  CSS.make("css-d5dmac", []);
  CSS.make("css-dajo9q", []);
  CSS.make("css-vp89l6", []);
  CSS.make("css-6lqrgx", []);
  CSS.make("css-1k2zktz", []);
  CSS.make("css-kd0k3s", []);
  CSS.make("css-123lpj3", []);
  CSS.make("css-1jag07y", []);
  CSS.make("css-fhn9tt", []);
  CSS.make("css-1lz8p3p", []);
  CSS.make("css-auwium", []);
  CSS.make("css-gdqw8", []);
  CSS.make("css-16c5dhv", []);
  CSS.make("css-16pnyc7", []);
  CSS.make("css-tdrdu", []);
  CSS.make("css-1v2nttj", []);
  CSS.make("css-bj71ck", []);
  CSS.make("css-1u7qxqj", []);
  CSS.make("css-yo3qoo", []);
  CSS.make("css-ednuac", []);
  CSS.make("css-1ly0fds", []);
  CSS.make("css-1lnhpg7", []);
  CSS.make("css-6kzrg5", []);
  CSS.make("css-ccz0tb", []);
  CSS.make("css-pgi3io", []);
  CSS.make("css-e1fbzg", []);
  CSS.make("css-hf8zlv", []);
  CSS.make("css-1tb4shn", []);
  CSS.make("css-1ogf3b8", []);
  CSS.make("css-11cb47q", []);
  CSS.make("css-1e2wp5i", []);
  CSS.make("css-1s7pafp", []);
  CSS.make("css-1phtr2b", []);
  CSS.make("css-m6hl56", []);
  CSS.make("css-ys288f", []);
  CSS.make("css-o9u5yn", []);
  CSS.make("css-dnwgtc", []);
  CSS.make("css-yzp3r0", []);
  CSS.make("css-u3jtjp", []);
  CSS.make("css-nbmap8", []);
  CSS.make("css-yoym04", []);
  CSS.make("css-racea0", []);
  CSS.make("css-16qqbga", []);
  CSS.make("css-1v9cfae", []);
  CSS.make("css-ji4r6c", []);
  CSS.make("css-11xk81w", []);
  CSS.make("css-uhboah", []);
  CSS.make("css-117oh71", []);
  CSS.make("css-1mvk8n", []);
  CSS.make("css-162m489", []);
  CSS.make("css-11lbjab", []);
  CSS.make("css-bdz5p3", []);
  CSS.make("css-pd2at7", []);
  CSS.make("css-1rt9qwi", []);
  CSS.make("css-qg7oz", []);
  CSS.make("css-asecxz", []);
  CSS.make("css-gndtd3", []);
  CSS.make("css-12jtjgd", []);
  CSS.make("css-b824mg", []);
  CSS.make("css-11znfmq", []);
  CSS.make("css-u7203s", []);
  CSS.make("css-tbq0j0", []);
  CSS.make("css-1xqsgia", []);
  CSS.make("css-x25oxa", []);
  CSS.make("css-8rf3bh", []);
  CSS.make("css-x3o9xj", []);
  CSS.make("css-yuaufw", []);
  CSS.make("css-19o4fdy", []);
  CSS.make("css-1allg27", []);
  CSS.make("css-1um6nyr", []);
  CSS.make("css-1ogsbzm", []);
  
  CSS.make("css-z39awh", []);
  CSS.make("css-1m20ra0", []);
  CSS.make("css-bd6cki", []);
  CSS.make("css-f0kubh", []);
  CSS.make("css-zqzqln", []);
  CSS.make("css-602mee", []);
  CSS.make("css-mz5ixr", []);
  CSS.make("css-1j42sqe", []);
  CSS.make("css-28i0al", []);
  
  CSS.make("css-xyx8z6", []);
  CSS.make("css-s28oi1", []);
  CSS.make("css-1fk011", []);
