[%styled.global] output is author-controlled CSS: it keeps source order in
the globals bucket, including at-rule-wrapped globals and rules targeting
element/id selectors. Only PPX-minted `.css-` atoms are re-ordered.

  $ cat > globals.ml <<EOF
  > [@@@css ".css-atom{color:red;}"]
  > [@@@css "html{box-sizing:border-box;}"]
  > [@@@css "@media (min-width: 700px) {body{font-size:18px;}}"]
  > [@@@css "body{margin:0;}"]
  > [@@@css "@font-face {font-family:\"Inter\";src:url(\"/inter.woff2\");}"]
  > [@@@css "#root{padding:0;}"]
  > EOF

  $ styled-ppx.generate globals.ml
  /* This file is generated by styled-ppx, do not edit manually */
  html{box-sizing:border-box;}
  @media (min-width: 700px) {body{font-size:18px;}}
  body{margin:0;}
  @font-face {font-family:"Inter";src:url("/inter.woff2");}
  #root{padding:0;}
  .css-atom{color:red;}

A global @media wrapping a body rule stays in the globals bucket (source
order), while a @media wrapping a .css- atom moves to the media bucket:
the discriminator is the innermost selector.

  $ cat > mixed.ml <<EOF
  > [@@@css "@media (min-width: 500px) {.css-x{color:red;}}"]
  > [@@@css "@media (min-width: 100px) {body{color:gray;}}"]
  > [@@@css ".css-y{color:blue;}"]
  > EOF

  $ styled-ppx.generate mixed.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 100px) {body{color:gray;}}
  .css-y{color:blue;}
  @media (min-width: 500px) {.css-x{color:red;}}
