/* CSS Transforms Module Level 1 */
[%cx2 {|transform: none|}];
[%cx2 {|transform: translate(5px)|}];
[%cx2 {|transform: translate(5px, 10px)|}];
[%cx2 {|transform: translateY(5px)|}];
[%cx2 {|transform: translateX(5px)|}];
[%cx2 {|transform: translateY(5%)|}];
[%cx2 {|transform: translateX(5%)|}];
[%cx2 {|transform: scale(2)|}];
[%cx2 {|transform: scale(2, -1)|}];
[%cx2 {|transform: scaleX(2)|}];
[%cx2 {|transform: scaleY(2.5)|}];
[%cx2 {|transform: rotate(45deg)|}];
[%cx2 {|transform: skew(45deg)|}];
[%cx2 {|transform: skew(45deg, 15deg)|}];
[%cx2 {|transform: skewX(45deg)|}];
[%cx2 {|transform: skewY(45deg)|}];
// [%cx2 {|transform: matrix(1,-.2,0,1,0,0)|}];
// [%cx2 {|transform: matrix(1,-.2,0,1,10,10)|}];
[%cx2 {|transform: translate(50px, -24px) skew(0, 22.5deg)|}];
[%cx2 {|transform: translate3d(0, 0, 5px)|}];
[%cx2 {|transform: translateZ(5px)|}];
[%cx2 {|transform: scale3d(1, 0, -1)|}];
[%cx2 {|transform: scaleZ(1.5)|}];
[%cx2 {|transform: rotate3d(1, 1, 1, 45deg)|}];
[%cx2 {|transform: rotateX(-45deg)|}];
[%cx2 {|transform: rotateY(-45deg)|}];
[%cx2 {|transform: rotateZ(-45deg)|}];
// [%cx2 {|transform: matrix3d(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)|}];
// [%cx2 {|transform: matrix3d(0,0,0,0,0,0,0,0,0,0,1,0,10,10,0,1)|}];
[%css
  {|transform: translate3d(50px, -24px, 5px) rotate3d(1, 2, 3, 180deg) scale3d(-1, 0, .5)|}
];
[%cx2 {|transform: perspective(600px)|}];
[%cx2 {|transform-origin: 10px|}];
[%cx2 {|transform-origin: top|}];
[%cx2 {|transform-origin: top left|}];
[%cx2 {|transform-origin: 50% 100%|}];
[%cx2 {|transform-origin: left 0%|}];
[%cx2 {|transform-origin: left 50% 0|}];
[%cx2 {|transform-box: border-box|}];
[%cx2 {|transform-box: fill-box|}];
[%cx2 {|transform-box: view-box|}];
[%cx2 {|transform-box: content-box|}];
[%cx2 {|transform-box: stroke-box|}];

/* CSS Transforms Module Level 2 */
[%cx2 {|translate: none|}];
[%cx2 {|translate: 50%|}];
[%cx2 {|translate: 50% 50%|}];
[%cx2 {|translate: 50% 50% 10px|}];
[%cx2 {|scale: none|}];
[%cx2 {|scale: 2|}];
[%cx2 {|scale: 2 2|}];
[%cx2 {|scale: 2 2 2|}];
[%cx2 {|rotate: none|}];
[%cx2 {|rotate:  45deg|}];
[%cx2 {|rotate: x 45deg|}];
[%cx2 {|rotate: y 45deg|}];
[%cx2 {|rotate: z 45deg|}];
[%cx2 {|rotate: -1 0 2 45deg|}];
[%cx2 {|rotate: 45deg x|}];
[%cx2 {|rotate: 45deg y|}];
[%cx2 {|rotate: 45deg z|}];
[%cx2 {|rotate: 45deg -1 0 2|}];
[%cx2 {|transform-style: flat|}];
[%cx2 {|transform-style: preserve-3d|}];
[%cx2 {|perspective: none|}];
[%cx2 {|perspective: 600px|}];
[%cx2 {|perspective-origin: 10px|}];
[%cx2 {|perspective-origin: top|}];
[%cx2 {|perspective-origin: top left|}];
[%cx2 {|perspective-origin: 50% 100%|}];
[%cx2 {|perspective-origin: left 0%|}];
[%cx2 {|backface-visibility: visible|}];
[%cx2 {|backface-visibility: hidden|}];
