When every contributing file across DIFFERENT libraries declares
`env=production`, rules still concatenate with no separator ACROSS the
library boundary, not just within one file (`css-config.t` only covers
one file with two rules).

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base"); ("env", "production")]]
  > [@@@css "._a_basewidget{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app"); ("env", "production")]]
  > [@@@css "._a_appmain{color:blue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_basewidget{color:red;}._a_appmain{color:blue;}
