Mixed same-module + cross-module references in one selector. Same-module
refs (`$(localFlag)`) resolve at PPX time, baking the resolved class
literally into the rendered CSS. Cross-module refs (`$(M.marker)`)
remain as sentinels until aggregation.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

The post-PPX `n.ml` shows only the cross-module ref as a sentinel — the
same-module `localFlag` is already resolved to its class.

  $ grep "css-" n.ml | head -3
    ".css-djuldm-container.css-0-localFlag.\000M.marker\000{color:blue;}"]
    [("N.localFlag", "css-0-localFlag");
    ("N.container", "css-djuldm-container")]]

The aggregator resolves `M.marker`. Final output matches what an inlined
same-module reference would produce.

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-djuldm-container.css-0-localFlag.css-0-marker{color:blue;}
