Mixed same-module + cross-module references in one selector. Same-module
refs (`$(localFlag)`) resolve at PPX time, baking the resolved class
literally into the rendered CSS. Cross-module refs (`$(M.marker)`)
remain as sentinels until aggregation.

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

The post-PPX `n.ml` shows only the cross-module ref as a sentinel — the
same-module `localFlag` is already resolved to its class.

  $ cat n.ml
  [@@@css "._a_brk8p4evyfi._id_1026km9.\000M.marker\000{color:blue;}"]
  [@@@css.bindings
    [("N.localFlag", "_id_1026km9", "");
    ("N.container", "_id_1ov2ckq", "_a_brk8p4evyfi")]]
  [@@@css.refs [("M.marker", "n.ml", 4, 19, 27)]]
  let _ = M.marker
  let localFlag = CSS.make "label:localFlag _id_1026km9" []
  let container = CSS.make "label:container _id_1ov2ckq _a_brk8p4evyfi" []

The aggregator resolves `M.marker`. Final output matches what an inlined
same-module reference would produce.

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_brk8p4evyfi._id_1026km9._id_12qpfnx{color:blue;}
