Mixed same-module + cross-module references in one selector. Same-module
refs (`$(localFlag)`) resolve at PPX time, baking the resolved class
literally into the rendered CSS. Cross-module refs (`$(M.marker)`)
remain as sentinels until aggregation.

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

The post-PPX `n.ml` shows only the cross-module ref as a sentinel — the
same-module `localFlag` is already resolved to its class.

  $ grep "djuldm" n.ml | head -3

The aggregator resolves `M.marker`. Final output matches what an inlined
same-module reference would produce.

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_brk8p4evyfi._id_1026km9._id_12qpfnx{color:blue;}
  }
