CSS.width(`rem(5.));
CSS.width(`ch(5.));
CSS.width(`vw(5.));
CSS.width(`vh(5.));
CSS.width(`vmin(5.));
CSS.width(`vmax(5.));
CSS.width(`calc(`add((`pxFloat(1.), `pxFloat(2.)))));
CSS.width(`calc(`mult((`pxFloat(5.), `num(2.)))));
CSS.width(`calc(`mult((`pxFloat(5.), `num(2.)))));
CSS.width(`calc(`sub((`pxFloat(5.), `pxFloat(10.)))));
CSS.width(`calc(`sub((`vw(1.), `pxFloat(1.)))));
CSS.width(`percent(100.));
CSS.padding(`rem(5.));
CSS.padding(`ch(5.));
CSS.padding(`vw(5.));
CSS.padding(`vh(5.));
CSS.padding(`vmin(5.));
CSS.padding(`vmax(5.));

/* Missing length units via [%css ...] */
[%css {|width: 1cap|}];
[%css {|width: 1ic|}];
[%css {|width: 1lh|}];
[%css {|width: 1rcap|}];
[%css {|width: 1rch|}];
[%css {|width: 1rex|}];
[%css {|width: 1ric|}];
[%css {|width: 1rlh|}];
[%css {|width: 50vb|}];
[%css {|width: 50vi|}];
[%css {|width: 40Q|}];
