CssJs.width(`rem(5.));
CssJs.width(`ch(5.));
CssJs.width(`vw(5.));
CssJs.width(`vh(5.));
CssJs.width(`vmin(5.));
CssJs.width(`vmax(5.));
CssJs.width(`calc(`add((`pxFloat(1.), `pxFloat(2.)))));
CssJs.width(`calc(`mult((`pxFloat(5.), `num(2.)))));
CssJs.width(`calc(`mult((`pxFloat(5.), `num(2.)))));
CssJs.width(`calc(`sub((`pxFloat(5.), `pxFloat(10.)))));
CssJs.width(`calc(`sub((`vw(1.), `pxFloat(1.)))));
CssJs.width(`percent(100.));
CssJs.padding(`rem(5.));
CssJs.padding(`ch(5.));
CssJs.padding(`vw(5.));
CssJs.padding(`vh(5.));
CssJs.padding(`vmin(5.));
CssJs.padding(`vmax(5.));
