The aggregator with no input files emits a header comment only.

  $ styled-ppx.generate
  /* This file is generated by styled-ppx, do not edit manually */

A single empty file (no [@@@css ...]) also emits just the header.

  $ cat > empty.ml <<EOF
  > let x = 1
  > EOF

  $ styled-ppx.generate empty.ml
  /* This file is generated by styled-ppx, do not edit manually */
