A query carrying a media type CAN be rewritten, but only when every
member of the group shares the exact same bare-or-`only` type prefix
(`screen` is by far the most common in practice): the shared prefix is
carried through unchanged, only each member's own feature chain is
negated. `screen` and `only screen` are rewritten; `not screen` is
deliberately left untouched, same as the other unsafe shapes below -
`not` inverts the WHOLE query (type and condition together), so folding
a negation into just the condition part produces a genuinely wrong
result: the earlier rule would fire at widths where neither original
rule applied. Three shapes stay untouched: a comma
list mixing a typed and an untyped branch (no single, unambiguous type
to carry through), two DIFFERENT types (`screen` vs `print` - keep
mixed or other types untouched), and a `not`-prefixed type.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css
    "@media screen and (max-width: 992px) and (not (max-width: 480px)){._a_eod994eqxej{color:red;}}"]
  [@@@css
    "@media screen and (max-width: 480px) {._a_41qk84ejnqp{color:blue;}}"]
  [@@@css
    "@media only screen and (max-width: 992px) and (not (max-width: 480px)){._a_hi5p16500waktn{font-size:14px;}}"]
  [@@@css
    "@media only screen and (max-width: 480px) {._a_vgp386500wjlif{font-size:12px;}}"]
  [@@@css
    "@media not screen and (max-width: 992px) {._a_2qk2neczkzc{width:1px;}}"]
  [@@@css
    "@media not screen and (max-width: 480px) {._a_wd785ecogb2{width:2px;}}"]
  [@@@css "@media screen, (min-width: 600px) {._a_mxhpf6luuex{height:1px;}}"]
  [@@@css "@media (min-width: 900px) {._a_mp5mk6l2v22{height:2px;}}"]
  [@@@css
    "@media screen and (max-width: 992px) {._a_eod993hlokug7y{border-width:1px;}}"]
  [@@@css
    "@media print and (max-width: 480px) {._a_iy5ye3hlokcoyl{border-width:2px;}}"]
  [@@@css.bindings
    [("Output.screenPair", "_id_dbqz2g", "_a_eod994eqxej _a_41qk84ejnqp");
    ("Output.onlyPair", "_id_1qnsba9", "_a_hi5p16500waktn _a_vgp386500wjlif");
    ("Output.notScreenPair", "_id_1u5eua8", "_a_2qk2neczkzc _a_wd785ecogb2");
    ("Output.commaMixedTypes", "_id_1vmtjrt", "_a_mxhpf6luuex _a_mp5mk6l2v22");
    ("Output.differentTypesPair", "_id_rrgrr1",
      "_a_eod993hlokug7y _a_iy5ye3hlokcoyl")]]
  let screenPair =
    CSS.make "label:screenPair _id_dbqz2g _a_eod994eqxej _a_41qk84ejnqp" []
  let onlyPair =
    CSS.make "label:onlyPair _id_1qnsba9 _a_hi5p16500waktn _a_vgp386500wjlif"
      []
  let notScreenPair =
    CSS.make "label:notScreenPair _id_1u5eua8 _a_2qk2neczkzc _a_wd785ecogb2" []
  let commaMixedTypes =
    CSS.make "label:commaMixedTypes _id_1vmtjrt _a_mxhpf6luuex _a_mp5mk6l2v22"
      []
  let differentTypesPair =
    CSS.make
      "label:differentTypesPair _id_rrgrr1 _a_eod993hlokug7y _a_iy5ye3hlokcoyl"
      []
  let _ =
    (screenPair, onlyPair, notScreenPair, commaMixedTypes, differentTypesPair)

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media screen and (max-width: 992px) and (not (max-width: 480px)){._a_eod994eqxej{color:red;}}
  @media screen and (max-width: 480px) {._a_41qk84ejnqp{color:blue;}}
  @media not screen and (max-width: 992px) {._a_2qk2neczkzc{width:1px;}}
  @media not screen and (max-width: 480px) {._a_wd785ecogb2{width:2px;}}
  @media screen, (min-width: 600px) {._a_mxhpf6luuex{height:1px;}}
  @media (min-width: 900px) {._a_mp5mk6l2v22{height:2px;}}
  @media only screen and (max-width: 992px) and (not (max-width: 480px)){._a_hi5p16500waktn{font-size:14px;}}
  @media only screen and (max-width: 480px) {._a_vgp386500wjlif{font-size:12px;}}
  @media screen and (max-width: 992px) {._a_eod993hlokug7y{border-width:1px;}}
  @media print and (max-width: 480px) {._a_iy5ye3hlokcoyl{border-width:2px;}}
