An ambiguity-induced cycle. Like order-ambiguous-name.t, two directories
both define Util; dir1/x.ml's reference to "Util" resolves to its own
sibling dir1/util.ml by path proximity, not dir2's. But dir1/util.ml also
references X, and X has only one candidate file, so that edge is
unambiguous. The two edges close a cycle between dir1/util.ml and dir1/x.ml
that a real OCaml build could never produce on its own (dune wouldn't have
compiled a genuine circular dependency) — it only exists because this
generator resolves same-named modules by path proximity instead of real
library membership (PR 2 fixes that). The sort breaks the cycle
deterministically instead of failing the build.

  $ mkdir dir1 dir2

  $ cat > dir1/util.ml <<EOF
  > [@@@css ".dir1-util{color:red;}"]
  > let _ = X.x
  > EOF

  $ cat > dir1/x.ml <<EOF
  > [@@@css ".x{color:blue;}"]
  > let _ = Util.x
  > EOF

  $ cat > dir2/util.ml <<EOF
  > [@@@css ".dir2-util{color:green;}"]
  > EOF

  $ styled-ppx.generate dir1/util.ml dir1/x.ml dir2/util.ml
  styled-ppx: dependency cycle among dir1/util.ml, dir1/x.ml; dropping the edge from dir1/x.ml to dir1/util.ml to keep a deterministic order
  /* This file is generated by styled-ppx, do not edit manually */
  .x{color:blue;}
  .dir1-util{color:red;}
  .dir2-util{color:green;}

Deterministic: running it again produces byte-identical output, including
the warning.

  $ styled-ppx.generate dir1/util.ml dir1/x.ml dir2/util.ml
  styled-ppx: dependency cycle among dir1/util.ml, dir1/x.ml; dropping the edge from dir1/x.ml to dir1/util.ml to keep a deterministic order
  /* This file is generated by styled-ppx, do not edit manually */
  .x{color:blue;}
  .dir1-util{color:red;}
  .dir2-util{color:green;}
