Fixed condition order: two `@media (min-width: ...)` breakpoints for one
property, at DIFFERENT widths, wrap two DIFFERENT single-class rules of
equal specificity ((0,1,0) each -
one class, no pseudo, no combinator). Both land in `Conditional`, and
`sort_by_shorthand_first`'s own two keys tie them (same descendant-shape:
false; same depth: `width` is a depth-0 leaf for both). Before this change
the tie fell through to stable order, i.e. "whichever file the generator
reads first, alphabetically" (same as `tiers-condition-tie-pseudo-class.t`).
`sort_conditional_rules` now breaks it with a width-aware key
(`media_width_bound`, StyleX's `min-width` ascending / `max-width`
descending rule): the two `@media` rules sort ascending by their own
`min-width` value, independent of which file wrote which order, so the
wider, later-declared breakpoint is always textually last and always wins
when both match.

Module `aaa` (read first) writes the breakpoints DESCENDING - 900px
first, 600px second - meaning (plain CSS, read top to bottom) its own
INTENT is "at >=600px, use 50%, overriding the >=900px rule". Module `zzz`
(read second) writes the classic ascending, mobile-first order - 600px
first, 900px second - meaning its own intent is the opposite: at >=900px,
33% (the narrower, later breakpoint) should win.

  $ cat > aaa_descending.ml <<EOF
  > [@@@css "@media (min-width:900px){._a_4widthnin{width:33%;}}"]
  > [@@@css "@media (min-width:600px){._a_3widthsix{width:50%;}}"]
  > EOF

  $ cat > zzz_ascending.ml <<EOF
  > [@@@css "@media (min-width:600px){._a_3widthsix{width:50%;}}"]
  > [@@@css "@media (min-width:900px){._a_4widthnin{width:33%;}}"]
  > EOF

  $ styled-ppx.generate aaa_descending.ml zzz_ascending.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width:600px){._a_3widthsix{width:50%;}}
  @media (min-width:900px){._a_4widthnin{width:33%;}}

  $ styled-ppx.generate zzz_ascending.ml aaa_descending.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width:600px){._a_3widthsix{width:50%;}}
  @media (min-width:900px){._a_4widthnin{width:33%;}}

Both class atoms already existed before either file was written (this is
not a dedup artifact - `_a_4widthnin` and `_a_3widthsix` are two distinct
classes), so this is the sort's own tie-break, not content sharing. The
sheet is now ascending (600 before 900) regardless of argument order and
regardless of which module wrote which order: at >=900px BOTH rules match,
and 900 is textually last, so `width: 33%` wins - `zzz`'s own mobile-first
intent, the direction `tiers-slider.t` already documents as "the desktop
query, textually LAST, wins".

The width-aware key is also needed when two blocks each write a single
`@media` condition that reaches one element - see
`tiers-condition-tie-single-condition-per-block.t`.
