  $ standalone --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css ":root{--primary-color:blue;}"]
  [@@@css "body{margin:0;font-family:system-ui, sans-serif;}"]
  [@@@css ".css-k008qs{display:flex;}"]
  [@@@css ".css-1tyndxa{justify-content:center;}"]
  [@@@css ".css-kusjgz{color:var(--var-sj55zd);}"]
  [@@@css ".css-15ikb3s{margin-block:var(--var-m7rmhk);}"]
  [@@@css ".css-1io86c2{margin-inline:var(--var-m7rmhk);}"]
  [@@@css ".css-bcg5v8{padding-block-start:var(--var-m7rmhk);}"]
  [@@@css ".css-1ifadwg{padding-inline-end:var(--var-m7rmhk);}"]
  [@@@css ".css-kdjpx{inset-block-start:var(--var-m7rmhk);}"]
  [@@@css ".css-zqnfaz:hover{opacity:0.8;}"]
  [@@@css ".css-osffsa .child{flex:1;}"]
  [@@@css "@media (max-width: 768px) {.css-1ruz0a1{display:block;}}"]
  [@@@css ".css-6xix1i{font-size:16px;}"]
  [@@@css "@media (max-width: 768px) {.css-1l3vtdj{font-size:14px;}}"]
  [@@@css "@media (max-width: 480px) {.css-2b7vub{font-size:12px;}}"]
  [@@@css ".css-5ivle1 .item{flex:1;}"]
  [@@@css "@media (max-width: 768px) {.css-1cemfq6{flex-direction:column;}}"]
  [@@@css "@media (max-width: 768px) {.css-1l7frkw .item{flex:none;}}"]
  [@@@css ".css-lgj0h8{display:grid;}"]
  [@@@css
    "@media screen and (min-width: 768px) and (max-width: 1024px) {.css-mhiow9{display:flex;}}"]
  [@@@css
    "@media (prefers-color-scheme: dark) {.css-1nm9mde{background-color:#1a1a1a;}}"]
  [@@@css "@media (max-width: 768px) {.css-11qknlj{opacity:0.8;}}"]
  [@@@css "@keyframes keyframe-jw9oix{from{opacity:0;}to{opacity:1;}}"]
  [@@@css
    "@keyframes keyframe-waibjx{0%{transform:translateY(100%);}100%{transform:translateY(0);}}"]
  [@@@css ".css-b6lny7{color:var(--var-bxenxf);}"]
  [@@@css ".css-12udlbg{background-color:var(--var-1czls49);}"]
  [@@@css ".css-u661at{font-size:var(--var-1kwx24p);}"]
  [@@@css ".css-nk32ej{padding:10px;}"]
  [@@@css ".css-bghlac{grid-template-columns:1fr 2fr 1fr;}"]
  [@@@css ".css-16610y9{gap:20px;}"]
  [@@@css ".css-pdjuhq{scroll-behavior:smooth;}"]
  [@@@css ".css-13v3rg8{overflow-y:auto;}"]
  let staticCss = CSS.make "css-k008qs css-1tyndxa" []
  let dynamicCss color =
    CSS.make "css-kusjgz css-k008qs"
      [("--var-sj55zd", (CSS.Types.Color.toString color))]
  let logicalProps spacing =
    CSS.make "css-15ikb3s css-1io86c2 css-bcg5v8 css-1ifadwg css-kdjpx"
      [("--var-m7rmhk", (CSS.Types.MarginBlock.toString spacing))]
  let nestedCss = CSS.make "css-k008qs css-zqnfaz css-osffsa" []
  let responsiveCss = CSS.make "css-k008qs css-1ruz0a1" []
  let multipleMediaQueries = CSS.make "css-6xix1i css-1l3vtdj css-2b7vub" []
  let mediaWithSelector =
    CSS.make "css-k008qs css-5ivle1 css-1cemfq6 css-1l7frkw" []
  let complexMedia = CSS.make "css-lgj0h8 css-mhiow9 css-1nm9mde" []
  let mediaWithInterpolation color =
    CSS.make "css-kusjgz css-11qknlj"
      [("--var-sj55zd", (CSS.Types.Color.toString color))]
  let fadeIn = CSS.Types.AnimationName.make "keyframe-jw9oix"
  let slideUp = CSS.Types.AnimationName.make "keyframe-waibjx"
  let () = ()
  let multiVar primary secondary size =
    CSS.make "css-b6lny7 css-12udlbg css-u661at css-nk32ej"
      [("--var-bxenxf", (CSS.Types.Color.toString primary));
      ("--var-1czls49", (CSS.Types.Color.toString secondary));
      ("--var-1kwx24p", (CSS.Types.FontSize.toString size))]
  let gridCss = CSS.make "css-lgj0h8 css-bghlac css-16610y9" []
  let scrollCss = CSS.make "css-pdjuhq css-13v3rg8" []
  let _ = ReactDOM.jsx "div" (ReactDOM.domProps ~className:(fst staticCss) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst (dynamicCss CSS.red))
         ~style:(snd (dynamicCss CSS.red)) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst (logicalProps (CSS.px 20)))
         ~style:(snd (logicalProps (CSS.px 20))) ())
  let _ =
    ReactDOM.jsx "div" (ReactDOM.domProps ~className:(fst responsiveCss) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst multipleMediaQueries) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst mediaWithSelector) ())
  let _ =
    ReactDOM.jsx "div" (ReactDOM.domProps ~className:(fst complexMedia) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst (mediaWithInterpolation CSS.blue))
         ~style:(snd (mediaWithInterpolation CSS.blue)) ())

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-12udlbg{background-color:var(--var-1czls49);}
  .css-13v3rg8{overflow-y:auto;}
  .css-15ikb3s{margin-block:var(--var-m7rmhk);}
  .css-16610y9{gap:20px;}
  .css-1ifadwg{padding-inline-end:var(--var-m7rmhk);}
  .css-1io86c2{margin-inline:var(--var-m7rmhk);}
  .css-1tyndxa{justify-content:center;}
  .css-5ivle1 .item{flex:1;}
  .css-6xix1i{font-size:16px;}
  .css-b6lny7{color:var(--var-bxenxf);}
  .css-bcg5v8{padding-block-start:var(--var-m7rmhk);}
  .css-bghlac{grid-template-columns:1fr 2fr 1fr;}
  .css-k008qs{display:flex;}
  .css-kdjpx{inset-block-start:var(--var-m7rmhk);}
  .css-kusjgz{color:var(--var-sj55zd);}
  .css-lgj0h8{display:grid;}
  .css-nk32ej{padding:10px;}
  .css-osffsa .child{flex:1;}
  .css-pdjuhq{scroll-behavior:smooth;}
  .css-u661at{font-size:var(--var-1kwx24p);}
  .css-zqnfaz:hover{opacity:0.8;}
  :root{--primary-color:blue;}
  @keyframes keyframe-jw9oix{from{opacity:0;}to{opacity:1;}}
  @keyframes keyframe-waibjx{0%{transform:translateY(100%);}100%{transform:translateY(0);}}
  @media (max-width: 480px) {.css-2b7vub{font-size:12px;}}
  @media (max-width: 768px) {.css-11qknlj{opacity:0.8;}}
  @media (max-width: 768px) {.css-1cemfq6{flex-direction:column;}}
  @media (max-width: 768px) {.css-1l3vtdj{font-size:14px;}}
  @media (max-width: 768px) {.css-1l7frkw .item{flex:none;}}
  @media (max-width: 768px) {.css-1ruz0a1{display:block;}}
  @media (prefers-color-scheme: dark) {.css-1nm9mde{background-color:#1a1a1a;}}
  @media screen and (min-width: 768px) and (max-width: 1024px) {.css-mhiow9{display:flex;}}
  body{margin:0;font-family:system-ui, sans-serif;}

