  $ standalone --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css
    ":root { --primary-color: blue; }\nbody { margin: 0; font-family: system-ui, sans-serif; }\n.css-17vxl0k { display: flex; }\n.css-w5s1ik { justify-content: center; }\n.css-181w2g5 { color: var(--var-sj55zd); }\n.css-1lg7g64 { margin-block: var(--var-m7rmhk); }\n.css-y6hur2 { margin-inline: var(--var-m7rmhk); }\n.css-d54jju { padding-block-start: var(--var-m7rmhk); }\n.css-137t8x8 { padding-inline-end: var(--var-m7rmhk); }\n.css-lhtqxk { inset-block-start: var(--var-m7rmhk); }\n.css-1qv6lt2:hover { opacity: 0.8; }\n.css-1e5ggi .child { flex: 1; }\n@media (max-width: 768px) { .css-416bgw { display: block; } }\n.css-3yit0z { font-size: 16px; }\n@media (max-width: 768px) { .css-11nyjd1 { font-size: 14px; } }\n@media (max-width: 480px) { .css-1ysjspj { font-size: 12px; } }\n.css-k54vzb .item { flex: 1; }\n@media (max-width: 768px) { .css-1x3ovde { flex-direction: column; } }\n@media (max-width: 768px) { .css-jka677 .item { flex: none; } }\n.css-1d7rma { display: grid; }\n@media screen and (min-width: 768px) and (max-width: 1024px) { .css-xgdaq3 { display: flex; } }\n@media (prefers-color-scheme: dark) { .css-1dynx94 { background-color: #1a1a1a; } }\n@media (max-width: 768px) { .css-5yf2v8 { opacity: 0.8; } }\n@keyframes keyframe-85bkd1 { from { opacity: 0; } to { opacity: 1; } }\n@keyframes keyframe-jqop05 { 0% { transform: translateY(100%); } 100% { transform: translateY(0); } }\n.css-yu2afn { color: var(--var-bxenxf); }\n.css-46asp6 { background-color: var(--var-1czls49); }\n.css-6gmcrz { font-size: var(--var-1kwx24p); }\n.css-avoblm { padding: 10px; }\n.css-r1hwfz { grid-template-columns: 1fr 2fr 1fr; }\n.css-1xitwk4 { gap: 20px; }\n.css-15d85rl { scroll-behavior: smooth; }\n.css-1xbs9vq { overflow-y: auto; }\n"]
  let staticCss = CSS.make "css-17vxl0k css-w5s1ik" []
  let dynamicCss color =
    CSS.make "css-181w2g5 css-17vxl0k"
      [("--var-sj55zd", (CSS.Types.Color.toString color))]
  let logicalProps spacing =
    CSS.make "css-1lg7g64 css-y6hur2 css-d54jju css-137t8x8 css-lhtqxk"
      [("--var-m7rmhk", (CSS.Types.MarginBlock.toString spacing))]
  let nestedCss = CSS.make "css-17vxl0k css-1qv6lt2 css-1e5ggi" []
  let responsiveCss = CSS.make "css-17vxl0k css-416bgw" []
  let multipleMediaQueries = CSS.make "css-3yit0z css-11nyjd1 css-1ysjspj" []
  let mediaWithSelector =
    CSS.make "css-17vxl0k css-k54vzb css-1x3ovde css-jka677" []
  let complexMedia = CSS.make "css-1d7rma css-xgdaq3 css-1dynx94" []
  let mediaWithInterpolation color =
    CSS.make "css-181w2g5 css-5yf2v8"
      [("--var-sj55zd", (CSS.Types.Color.toString color))]
  let fadeIn = "keyframe-85bkd1"
  let slideUp = "keyframe-jqop05"
  let () = ()
  let multiVar primary secondary size =
    CSS.make "css-yu2afn css-46asp6 css-6gmcrz css-avoblm"
      [("--var-bxenxf", (CSS.Types.Color.toString primary));
      ("--var-1czls49", (CSS.Types.Color.toString secondary));
      ("--var-1kwx24p", (CSS.Types.FontSize.toString size))]
  let gridCss = CSS.make "css-1d7rma css-r1hwfz css-1xitwk4" []
  let scrollCss = CSS.make "css-15d85rl css-1xbs9vq" []
  let _ = ReactDOM.jsx "div" (ReactDOM.domProps ~className:(fst staticCss) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst (dynamicCss CSS.red))
         ~style:(snd (dynamicCss CSS.red)) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst (logicalProps (CSS.px 20)))
         ~style:(snd (logicalProps (CSS.px 20))) ())
  let _ =
    ReactDOM.jsx "div" (ReactDOM.domProps ~className:(fst responsiveCss) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst multipleMediaQueries) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst mediaWithSelector) ())
  let _ =
    ReactDOM.jsx "div" (ReactDOM.domProps ~className:(fst complexMedia) ())
  let _ =
    ReactDOM.jsx "div"
      (ReactDOM.domProps ~className:(fst (mediaWithInterpolation CSS.blue))
         ~style:(snd (mediaWithInterpolation CSS.blue)) ())

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  :root { --primary-color: blue; }
  body { margin: 0; font-family: system-ui, sans-serif; }
  .css-17vxl0k { display: flex; }
  .css-w5s1ik { justify-content: center; }
  .css-181w2g5 { color: var(--var-sj55zd); }
  .css-1lg7g64 { margin-block: var(--var-m7rmhk); }
  .css-y6hur2 { margin-inline: var(--var-m7rmhk); }
  .css-d54jju { padding-block-start: var(--var-m7rmhk); }
  .css-137t8x8 { padding-inline-end: var(--var-m7rmhk); }
  .css-lhtqxk { inset-block-start: var(--var-m7rmhk); }
  .css-1qv6lt2:hover { opacity: 0.8; }
  .css-1e5ggi .child { flex: 1; }
  @media (max-width: 768px) { .css-416bgw { display: block; } }
  .css-3yit0z { font-size: 16px; }
  @media (max-width: 768px) { .css-11nyjd1 { font-size: 14px; } }
  @media (max-width: 480px) { .css-1ysjspj { font-size: 12px; } }
  .css-k54vzb .item { flex: 1; }
  @media (max-width: 768px) { .css-1x3ovde { flex-direction: column; } }
  @media (max-width: 768px) { .css-jka677 .item { flex: none; } }
  .css-1d7rma { display: grid; }
  @media screen and (min-width: 768px) and (max-width: 1024px) { .css-xgdaq3 { display: flex; } }
  @media (prefers-color-scheme: dark) { .css-1dynx94 { background-color: #1a1a1a; } }
  @media (max-width: 768px) { .css-5yf2v8 { opacity: 0.8; } }
  @keyframes keyframe-85bkd1 { from { opacity: 0; } to { opacity: 1; } }
  @keyframes keyframe-jqop05 { 0% { transform: translateY(100%); } 100% { transform: translateY(0); } }
  .css-yu2afn { color: var(--var-bxenxf); }
  .css-46asp6 { background-color: var(--var-1czls49); }
  .css-6gmcrz { font-size: var(--var-1kwx24p); }
  .css-avoblm { padding: 10px; }
  .css-r1hwfz { grid-template-columns: 1fr 2fr 1fr; }
  .css-1xitwk4 { gap: 20px; }
  .css-15d85rl { scroll-behavior: smooth; }
  .css-1xbs9vq { overflow-y: auto; }

