Two libraries whose only connection is a wrapped-alias ambiguity: `lib_a`
references `Lib_b.y`, and `lib_b` references `Lib_a.x`. Neither library
has a file literally named after the other, so both edges come from the
capitalized-library-name alias rule, closing a cycle a real dune graph
could never produce (a library can't depend on itself both ways). The
library sort breaks it deterministically instead of failing the build.

  $ mkdir lib_a lib_b

  $ cat > lib_a/x.ml <<EOF
  > [@@@css.config [("library-name", "lib_a")]]
  > [@@@css ".lib-a-x{color:red;}"]
  > let _ = Lib_b.y
  > EOF

  $ cat > lib_b/y.ml <<EOF
  > [@@@css.config [("library-name", "lib_b")]]
  > [@@@css ".b-y{color:blue;}"]
  > let _ = Lib_a.x
  > EOF

  $ styled-ppx.generate lib_a/x.ml lib_b/y.ml
  styled-ppx: dependency cycle among lib_a, lib_b; dropping the edge from lib_b to lib_a to keep a deterministic order
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  .b-y{color:blue;}
  .lib-a-x{color:red;}
  }
