/* CSS Scroll Snap Module Level 1 */
[%cx2 {|scroll-margin: 0px|}];
[%cx2 {|scroll-margin: 6px 5px|}];
[%cx2 {|scroll-margin: 10px 20px 30px|}];
[%cx2 {|scroll-margin: 10px 20px 30px 40px|}];
[%cx2 {|scroll-margin: 20px 3em 1in 5rem|}];
[%cx2 {|scroll-margin: calc(2px)|}];
[%cx2 {|scroll-margin: calc(3 * 25px)|}];
[%cx2 {|scroll-margin: calc(3 * 25px) 5px 10em calc(1vw - 5px)|}];
[%cx2 {|scroll-margin-block: 10px|}];
[%cx2 {|scroll-margin-block: 10px 10px|}];
[%cx2 {|scroll-margin-block-end: 10px|}];
[%cx2 {|scroll-margin-block-start: 10px|}];
[%cx2 {|scroll-margin-bottom: 10px|}];
[%cx2 {|scroll-margin-inline: 10px|}];
[%cx2 {|scroll-margin-inline: 10px 10px|}];
[%cx2 {|scroll-margin-inline-start: 10px|}];
[%cx2 {|scroll-margin-inline-end: 10px|}];
[%cx2 {|scroll-margin-left: 10px|}];
[%cx2 {|scroll-margin-right: 10px|}];
[%cx2 {|scroll-margin-top: 10px|}];
[%cx2 {|scroll-padding: auto|}];
[%cx2 {|scroll-padding: 0px|}];
[%cx2 {|scroll-padding: 6px 5px|}];
[%cx2 {|scroll-padding: 10px 20px 30px|}];
[%cx2 {|scroll-padding: 10px 20px 30px 40px|}];
[%cx2 {|scroll-padding: 10px auto 30px auto|}];
[%cx2 {|scroll-padding: 10%|}];
[%cx2 {|scroll-padding: 20% 3em 1in 5rem|}];
[%cx2 {|scroll-padding: calc(2px)|}];
[%cx2 {|scroll-padding: calc(50%)|}];
[%cx2 {|scroll-padding: calc(3 * 25px)|}];
[%cx2 {|scroll-padding: calc(3 * 25px) 5px 10% calc(10% - 5px)|}];
[%cx2 {|scroll-padding-block: 10px|}];
[%cx2 {|scroll-padding-block: 50%|}];
[%cx2 {|scroll-padding-block: 10px 50%|}];
[%cx2 {|scroll-padding-block: 50% 50%|}];
[%cx2 {|scroll-padding-block-end: 10px|}];
[%cx2 {|scroll-padding-block-end: 50%|}];
[%cx2 {|scroll-padding-block-start: 10px|}];
[%cx2 {|scroll-padding-block-start: 50%|}];
[%cx2 {|scroll-padding-bottom: 10px|}];
[%cx2 {|scroll-padding-bottom: 50%|}];
[%cx2 {|scroll-padding-inline: 10px|}];
[%cx2 {|scroll-padding-inline: 50%|}];
[%cx2 {|scroll-padding-inline: 10px 50%|}];
[%cx2 {|scroll-padding-inline: 50% 50%|}];
[%cx2 {|scroll-padding-inline-end: 10px|}];
[%cx2 {|scroll-padding-inline-end: 50%|}];
[%cx2 {|scroll-padding-inline-start: 10px|}];
[%cx2 {|scroll-padding-inline-start: 50%|}];
[%cx2 {|scroll-padding-left: 10px|}];
[%cx2 {|scroll-padding-left: 50%|}];
[%cx2 {|scroll-padding-right: 10px|}];
[%cx2 {|scroll-padding-right: 50%|}];
[%cx2 {|scroll-padding-top: 10px|}];
[%cx2 {|scroll-padding-top: 50%|}];
[%cx2 {|scroll-snap-align: none|}];
[%cx2 {|scroll-snap-align: start|}];
[%cx2 {|scroll-snap-align: end|}];
[%cx2 {|scroll-snap-align: center|}];
[%cx2 {|scroll-snap-align: none start|}];
[%cx2 {|scroll-snap-align: end center|}];
[%cx2 {|scroll-snap-align: center start|}];
[%cx2 {|scroll-snap-align: end none|}];
[%cx2 {|scroll-snap-align: center center|}];
[%cx2 {|scroll-snap-stop: normal|}];
[%cx2 {|scroll-snap-stop: always|}];
[%cx2 {|scroll-snap-type: none|}];
[%cx2 {|scroll-snap-type: x mandatory|}];
[%cx2 {|scroll-snap-type: y mandatory|}];
[%cx2 {|scroll-snap-type: block mandatory|}];
[%cx2 {|scroll-snap-type: inline mandatory|}];
[%cx2 {|scroll-snap-type: both mandatory|}];
[%cx2 {|scroll-snap-type: x proximity|}];
[%cx2 {|scroll-snap-type: y proximity|}];
[%cx2 {|scroll-snap-type: block proximity|}];
[%cx2 {|scroll-snap-type: inline proximity|}];
[%cx2 {|scroll-snap-type: both proximity|}];
