Cross-module reference into a nested submodule (`M.Css.marker`). The
aggregator's index walker tracks nested `module X = struct ... end`
declarations and indexes bindings under their fully-qualified path.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-1crg7ag-container.css-0-marker{padding:1rem;}
