Multi-class binding, cross-module reference: when `M.marker` mints multiple
atomized classes, a cross-module reference to it still resolves to ONE
class - `marker`'s identity - regardless of how many atoms it minted. A
reference means "carries that binding", not "reproduces its exact
declarations".

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_393u2l{background:red;}
  ._a_4en7if{color:white;}
  ._a_gnp5r94ccud._id_12qpfnx{padding:1rem;}
  }
