Stress test for the shorthand-before-longhand sort's correctness, not just one
worked example: `sort_by_shorthand_first` keys every rule by a TOTAL,
per-rule shorthand depth (`Slot_key.depth_of`), not a pairwise "do these two
rules share a property family" comparison - a pairwise comparator that
treats two family-unrelated rules as equal is not a transitive relation, so
a stable sort built on it can leave a real shorthand stranded after its own
longhand whenever enough family-unrelated rules happen to separate them in
the pre-sort (dependency) order.

This fixture pins one arrangement (30 rules: four genuine shorthand/longhand
families - `padding`, `margin`, `border-width`, `inset`; sixteen unrelated
singleton declarations shuffled between them once, with a fixed seed, and
committed here rather than generated at test time) where a pairwise family
comparator gets 5 of the 9 shorthand/longhand pairs below wrong (the
shorthand emitted AFTER its own longhand). Depth orders every one of them
correctly, regardless of how many unrelated rules separate them.

`border-width` is also the property that pins WHY depth must be the
LONGEST path from a root, not the shortest: `border-top-width` is a direct
longhand of both `border-top` (its own, parent-less shorthand - depth 0)
and `border-width` (itself a longhand of `border` - depth 1). The shortest
path (through `border-top`) would put `border-top-width` at depth 1, tying
it with `border-width` and leaving their relative order to chance; the
longest path puts it at depth 2, strictly above BOTH parents, so
`border-width` (1) always sorts before `border-top-width` (2) here.

  $ cat > stress.ml <<EOF
  > [@@@css "._a_stress22{overflow:hidden;}"]
  > [@@@css "._a_stress6{margin-top:0;}"]
  > [@@@css "._a_stress16{display:flex;}"]
  > [@@@css "._a_stress30{letter-spacing:1px;}"]
  > [@@@css "._a_stress8{margin-right:2px;}"]
  > [@@@css "._a_stress29{font-weight:bold;}"]
  > [@@@css "._a_stress10{border-top-width:2px;}"]
  > [@@@css "._a_stress1{padding:4px 8px;}"]
  > [@@@css "._a_stress14{left:2px;}"]
  > [@@@css "._a_stress9{border-width:1px;}"]
  > [@@@css "._a_stress28{background-color:blue;}"]
  > [@@@css "._a_stress23{visibility:hidden;}"]
  > [@@@css "._a_stress27{box-sizing:border-box;}"]
  > [@@@css "._a_stress15{color:red;}"]
  > [@@@css "._a_stress24{white-space:nowrap;}"]
  > [@@@css "._a_stress25{text-align:center;}"]
  > [@@@css "._a_stress20{line-height:1.5;}"]
  > [@@@css "._a_stress7{margin-left:1px;}"]
  > [@@@css "._a_stress17{opacity:0.5;}"]
  > [@@@css "._a_stress26{vertical-align:top;}"]
  > [@@@css "._a_stress19{font-size:12px;}"]
  > [@@@css "._a_stress12{inset:0;}"]
  > [@@@css "._a_stress4{padding-right:2px;}"]
  > [@@@css "._a_stress18{z-index:1;}"]
  > [@@@css "._a_stress3{padding-left:1px;}"]
  > [@@@css "._a_stress2{padding-top:0;}"]
  > [@@@css "._a_stress21{cursor:pointer;}"]
  > [@@@css "._a_stress13{top:1px;}"]
  > [@@@css "._a_stress5{margin:4px 8px;}"]
  > [@@@css "._a_stress11{border-left-width:3px;}"]
  > EOF

  $ styled-ppx.generate stress.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_stress22{overflow:hidden;}
  ._a_stress16{display:flex;}
  ._a_stress30{letter-spacing:1px;}
  ._a_stress1{padding:4px 8px;}
  ._a_stress23{visibility:hidden;}
  ._a_stress27{box-sizing:border-box;}
  ._a_stress15{color:red;}
  ._a_stress24{white-space:nowrap;}
  ._a_stress25{text-align:center;}
  ._a_stress17{opacity:0.5;}
  ._a_stress26{vertical-align:top;}
  ._a_stress12{inset:0;}
  ._a_stress18{z-index:1;}
  ._a_stress21{cursor:pointer;}
  ._a_stress5{margin:4px 8px;}
  ._a_stress6{margin-top:0;}
  ._a_stress8{margin-right:2px;}
  ._a_stress29{font-weight:bold;}
  ._a_stress14{left:2px;}
  ._a_stress9{border-width:1px;}
  ._a_stress28{background-color:blue;}
  ._a_stress20{line-height:1.5;}
  ._a_stress7{margin-left:1px;}
  ._a_stress19{font-size:12px;}
  ._a_stress4{padding-right:2px;}
  ._a_stress3{padding-left:1px;}
  ._a_stress2{padding-top:0;}
  ._a_stress13{top:1px;}
  ._a_stress10{border-top-width:2px;}
  ._a_stress11{border-left-width:3px;}
  }

Check: `padding` (stress1) before all three of `padding-top`/`-right`/`-left`
(stress2/4/3); `margin` (stress5) before all three of `margin-top`/`-right`/
`-left` (stress6/8/7); `border-width` (stress9) before both
`border-top-width`/`border-left-width` (stress10/11); `inset` (stress12)
before both `top`/`left` (stress13/14) - every one of the nine pairs holds,
in a single generated sheet where the pre-sort (dependency) order
interleaved every shorthand with several unrelated declarations first.
