One block, four `@media (min-width: 600px)` occurrences - four SEPARATE
AST nodes with identical rendered text, so a table keyed by that text
(or by source location, if two ever coincided) could confuse them. The
rewrite table is keyed by physical identity instead, so each is looked
up independently:
- `color`'s pair (600/900) needs a rewrite: the 600px rule gets `and (not (min-width: 900px))`.
- `width`'s lone `@media (min-width: 600px)` is a singleton for its own family - it must print byte-identical to source, NOT pick up `color`'s rewritten condition even though the text matches exactly before rewriting.
- The outermost `@media (min-width: 600px)` wrapping the nested `orientation` pair is further-nested content (`media_atom_slot` returns `None` for it - two nested at-rules, not one clean unit), so it is never a candidate either, independently of the other two.
- The nested `orientation` pair, one level down, still gets its OWN independent rewrite (`landscape` excludes `portrait`).

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css
    "@media (min-width: 600px) and (not (min-width: 900px)){._a_izob04e6zo5{color:red;}}"]
  [@@@css "@media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}"]
  [@@@css "@media (min-width: 600px) {._a_izob0ec7x8k{width:10px;}}"]
  [@@@css
    "@media (min-width: 600px) and (orientation: landscape) and (not (orientation: portrait)){._a_58at36l1y01{height:1px;}}"]
  [@@@css
    "@media (min-width: 600px) and (orientation: portrait) {._a_p439r6lwrcv{height:2px;}}"]
  [@@@css.bindings
    [("Output.block", "_id_ovbeuh",
       "_a_izob04e6zo5 _a_mp5mk4et4n8 _a_izob0ec7x8k _a_58at36l1y01 _a_p439r6lwrcv")]]
  let block =
    CSS.make
      "label:block _id_ovbeuh _a_izob04e6zo5 _a_mp5mk4et4n8 _a_izob0ec7x8k _a_58at36l1y01 _a_p439r6lwrcv"
      []
  let _ = block

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 600px) and (not (min-width: 900px)){._a_izob04e6zo5{color:red;}}
  @media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}
  @media (min-width: 600px) {._a_izob0ec7x8k{width:10px;}}
  @media (min-width: 600px) and (orientation: landscape) and (not (orientation: portrait)){._a_58at36l1y01{height:1px;}}
  @media (min-width: 600px) and (orientation: portrait) {._a_p439r6lwrcv{height:2px;}}
