A wrapped library has no file named after the library itself; it's
referenced through its alias module (dune's `(wrapped true)` case, the
default). Library `zlib` only has a module `Inner`, but `consumer`
references `Zlib.Inner.x`. The reference resolves to the library through
`String.capitalize_ascii "zlib" = "Zlib"`, matching the alias module.

  $ mkdir consumer zlib

  $ cat > zlib/inner.ml <<EOF
  > [@@@css.config [("library-name", "zlib")]]
  > [@@@css ".zlib-inner{color:green;}"]
  > let x = 1
  > EOF

  $ cat > consumer/main.ml <<EOF
  > [@@@css.config [("library-name", "consumer")]]
  > [@@@css ".consumer-main{color:blue;}"]
  > let _ = Zlib.Inner.x
  > EOF

  $ styled-ppx.generate consumer/main.ml zlib/inner.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  .zlib-inner{color:green;}
  .consumer-main{color:blue;}
  }
