A bare `$(row)` selector reference in [%styled.global] is resolved against
the FULLY resolved rule text before `push_global` computes its dedup key
(unlike [%css]'s atomized path before this fix), so two modules with the
same local binding name and the same global selector shape were never at
risk of this collision - this pins that a `%styled.global` block using
`row` in A and B, with different content, emits two distinct global rules
rather than being silently merged into one.

  $ refmt --parse re --print ml a.re > a.ml
  $ ../../standalone.exe --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ ../../standalone.exe --impl b.ml -o b.ml

  $ cat a.ml
  [@@@css ".id-qqjiik{cursor:pointer;}"]
  [@@@css ".a-4ekvmb{color:red;}"]
  [@@@css.bindings [("A.row", "id-qqjiik", "a-4ekvmb")]]
  let row = CSS.make "label:row id-qqjiik a-4ekvmb" []
  module Globals =
    struct
      let to_string () = ""
      let makeProps ?key () = Js.Obj.empty ()[@@warning "-27-32"]
      let make _props = CSS.global_style_tag (to_string ())
    end

  $ cat b.ml
  [@@@css ".id-avtt0b{cursor:pointer;}"]
  [@@@css ".a-4esm7b{color:blue;}"]
  [@@@css.bindings [("B.row", "id-avtt0b", "a-4esm7b")]]
  let row = CSS.make "label:row id-avtt0b a-4esm7b" []
  module Globals =
    struct
      let to_string () = ""
      let makeProps ?key () = Js.Obj.empty ()[@@warning "-27-32"]
      let make _props = CSS.global_style_tag (to_string ())
    end

  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  .id-qqjiik{cursor:pointer;}
  .id-avtt0b{cursor:pointer;}
  }
  @layer styled-ppx.base {
  .a-4ekvmb{color:red;}
  .a-4esm7b{color:blue;}
  }
