  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ refmt --parse ml --print re output.ml
  [@css
    ".css-17vxl0k { display: flex; }\n.css-1lr2y8 .lola { display: flex; }\n@media (max-width: 100px) { .css-38xfim .lola { display: none; } }\n"
  ];
  let _ = CSS.make("css-17vxl0k css-1lr2y8 css-38xfim", []);

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-17vxl0k { display: flex; }
  .css-1lr2y8 .lola { display: flex; }
  @media (max-width: 100px) { .css-38xfim .lola { display: none; } }
