Source declaration order must be preserved through the aggregator.

When [%css] atomizes `margin: 10px; margin-top: 20px;` into two rules,
the longhand override must be emitted *after* the shorthand so the cascade
picks the user's intended winner. Previously, the aggregator deduped
through `Set.Make(String)`, which sorted by the rendered rule's hash
prefix — destroying source order and silently miscompiling.

  $ cat > a.ml <<EOF
  > [@@@css ".css-eaeacs-x{margin:10px;}"]
  > [@@@css ".css-1xaekgw-x{margin-top:20px;}"]
  > [@@@css.bindings [("A.x", "css-eaeacs-x css-1xaekgw-x")]]
  > EOF

  $ styled-ppx.generate a.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-eaeacs-x{margin:10px;}
  .css-1xaekgw-x{margin-top:20px;}

Repeated property within a single binding: "blue" must win.

  $ cat > b.ml <<EOF
  > [@@@css ".css-A-y{color:red;}"]
  > [@@@css ".css-B-y{color:blue;}"]
  > [@@@css.bindings [("B.y", "css-A-y css-B-y")]]
  > EOF

  $ styled-ppx.generate b.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-A-y{color:red;}
  .css-B-y{color:blue;}

Cross-file: file order is the order dune passes them. Within a file,
[@@@css ...] declaration order is preserved.

  $ cat > c.ml <<EOF
  > [@@@css ".second{color:red;}"]
  > [@@@css ".first{color:red;}"]
  > EOF

  $ cat > d.ml <<EOF
  > [@@@css ".third{color:red;}"]
  > EOF

  $ styled-ppx.generate c.ml d.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .second{color:red;}
  .first{color:red;}
  .third{color:red;}

Identical rules across files are still deduped to first occurrence,
preserving source order at the position of first sight.

  $ cat > e.ml <<EOF
  > [@@@css ".shared{color:red;}"]
  > [@@@css ".only-e{color:blue;}"]
  > EOF

  $ cat > f.ml <<EOF
  > [@@@css ".only-f{color:green;}"]
  > [@@@css ".shared{color:red;}"]
  > EOF

  $ styled-ppx.generate e.ml f.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .shared{color:red;}
  .only-e{color:blue;}
  .only-f{color:green;}
