Dependency order is the default (`--order dependency`). Files that don't
reference each other have no edges between them, so the sort's tiebreak
(alphabetically smallest path among ready nodes) reduces to input order.

  $ cat > m1.ml <<EOF
  > [@@@css ".one{color:red;}"]
  > EOF

  $ cat > m2.ml <<EOF
  > [@@@css ".two{color:blue;}"]
  > EOF

  $ cat > m3.ml <<EOF
  > [@@@css ".three{color:green;}"]
  > EOF

  $ styled-ppx.generate m1.ml m2.ml m3.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .one{color:red;}
  .two{color:blue;}
  .three{color:green;}
