Fixed condition order: a rule wrapped in `@supports (...)` and a rule
wrapped in `@media (...)` around a bare, single-class selector each have
specificity (0,1,0) - equal, because
`@supports`/`@media` contribute nothing to specificity, only to WHEN the
inner rule applies. Both land in `Conditional`; `sort_by_shorthand_first`'s
own two keys tie them (same descendant-shape, same depth). Before this
change the tie fell through to stable order, i.e. "whichever file is read
first, alphabetically". `sort_conditional_rules` now breaks it with a fixed
at-rule-kind priority (StyleX's relative order `@supports` < `@media` <
`@container`): `@media` always outranks `@supports`, so `@supports` is
always textually first and `@media` always wins, regardless of source
order.

Module `aaa` (read first - alphabetically before `zzz`) writes `@media`
before `@supports` (its own intent: `@supports` overrides `@media`);
module `zzz` writes the opposite (its own intent: `@media` overrides
`@supports`).

  $ cat > aaa_media_then_supports.ml <<EOF
  > [@@@css "@media (min-width:600px){._a_8mediacol{color:blue;}}"]
  > [@@@css "@supports (display:grid){._a_7suppcol{color:red;}}"]
  > EOF

  $ cat > zzz_supports_then_media.ml <<EOF
  > [@@@css "@supports (display:grid){._a_7suppcol{color:red;}}"]
  > [@@@css "@media (min-width:600px){._a_8mediacol{color:blue;}}"]
  > EOF

  $ styled-ppx.generate aaa_media_then_supports.ml zzz_supports_then_media.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @supports (display:grid){._a_7suppcol{color:red;}}
  @media (min-width:600px){._a_8mediacol{color:blue;}}

  $ styled-ppx.generate zzz_supports_then_media.ml aaa_media_then_supports.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @supports (display:grid){._a_7suppcol{color:red;}}
  @media (min-width:600px){._a_8mediacol{color:blue;}}

`@supports` is always textually first and `@media` always wins, regardless
of argument order and regardless of which module wrote which order. On a
browser that supports `display: grid` and matches the 600px breakpoint at
once, `color: blue` (the `@media` rule) now wins in both modules - matching
`zzz`'s own intent, overriding `aaa`'s (the reverse of the file-order
tie-break this fixed priority replaces).
