/* CSS Flexible Box Layout Module Level 1 */
[%css {|align-content: flex-start|}];
[%css {|align-content: flex-end|}];
[%css {|align-content: space-between|}];
[%css {|align-content: space-around|}];
[%css {|align-items: flex-start|}];
[%css {|align-items: flex-end|}];
[%css {|align-self: flex-start|}];
[%css {|align-self: flex-end|}];
[%css {|display: flex|}];
[%css {|display: inline-flex|}];
[%css {|flex: none|}];
[%css {|flex: 5 7 10%|}];
[%css {|flex: 2;|}];
[%css {|flex: 10em;|}];
[%css {|flex: 30%;|}];
[%css {|flex: min-content;|}];
[%css {|flex: 1 30px;|}];
[%css {|flex: 2 2;|}];
[%css {|flex: 2 2 10%;|}];
[%css {|flex: $(X.value);|}];
[%css {|flex: $(X.value) $(X.value);|}];
[%css {|flex: $(X.value) $(X.value) $(X.value);|}];
[%css {|flex-basis: auto|}];
[%css {|flex-basis: content|}];
[%css {|flex-basis: 1px|}];
[%css {|flex-direction: row|}];
[%css {|flex-direction: row-reverse|}];
[%css {|flex-direction: column|}];
[%css {|flex-direction: column-reverse|}];
[%css {|flex-flow: row|}];
[%css {|flex-flow: row-reverse|}];
[%css {|flex-flow: column|}];
[%css {|flex-flow: column-reverse|}];
[%css {|flex-flow: wrap|}];
[%css {|flex-flow: wrap-reverse|}];
[%css {|flex-grow: 0|}];
[%css {|flex-grow: 5|}];
[%css {|flex-shrink: 1|}];
[%css {|flex-shrink: 10|}];
[%css {|flex-wrap: nowrap|}];
[%css {|flex-wrap: wrap|}];
[%css {|flex-wrap: wrap-reverse|}];
[%css {|justify-content: flex-start|}];
[%css {|justify-content: flex-end|}];
[%css {|justify-content: space-between|}];
[%css {|justify-content: space-around|}];
[%css {|min-height: auto|}];
[%css {|min-width: auto|}];
[%css {|order: 0|}];
[%css {|order: 1|}];
