Known gap: negating a later query is only safe when every feature it
tests resolves to a definite true/false in every supported browser
(`min-width`/`max-width`/`min-height`/`max-height` with a literal
px/em/rem length, or `orientation`). `calc(1000px - 2%)` mixes an
absolute length with a percentage, which is not a valid `<length>` in a
media feature - the browser resolves that single feature test to
permanently "false", but wrapping it in `not (...)` does NOT flip it to
permanently "true": three-valued "unknown" propagates through `not`
instead of inverting to a definite value the way real boolean negation
would, so the negated form stays permanently "false" too. Rewriting the
earlier (calc(2px+1px)) rule to `and (not (calc(1000px - 2%)))` would
therefore make the EARLIER rule permanently false too - a real,
user-visible regression: before this guard, the earlier rule applied
(and showed red) at every normal viewport width; naively rewritten, it
would never apply again. This group is left completely untouched
instead.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css "@media (min-width: calc(2px + 1px)) {._a_aveay4e5m2e{color:red;}}"]
  [@@@css
    "@media (min-width: calc(1000px - 2%)) {._a_h4c6e4el0w0{color:red;}}"]
  [@@@css.bindings
    [("Output.block", "_id_ovbeuh", "_a_aveay4e5m2e _a_h4c6e4el0w0")]]
  let block =
    CSS.make "label:block _id_ovbeuh _a_aveay4e5m2e _a_h4c6e4el0w0" []
  let _ = block

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: calc(2px + 1px)) {._a_aveay4e5m2e{color:red;}}
  @media (min-width: calc(1000px - 2%)) {._a_h4c6e4el0w0{color:red;}}
