This test ensures that cross-file CSS extraction deduplicates identical rules.

When two files both use [%css "display: flex"] and [%css "color: blue"], the
generated CSS should contain each rule only once, while preserving rules
unique to each file.

  $ refmt --parse re --print ml input_a.re > output_a.ml
  $ ../../standalone.exe --impl output_a.ml -o output_a.ml
  $ refmt --parse re --print ml input_b.re > output_b.ml
  $ ../../standalone.exe --impl output_b.ml -o output_b.ml
  $ styled-ppx.generate output_a.ml output_b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-k008qs{display:flex;}
  .css-14ksm7b{color:blue;}
  .css-eaeacs{margin:10px;}
  .css-1ruxp1v{padding:20px;}
