  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --debug
  [styled-ppx] CSS output path: styled-ppx-css/styles.css
  [styled-ppx] File doesn't exist
  [styled-ppx] CSS file created at: styled-ppx-css/styles.css
  $ refmt --parse ml --print re output.ml
  let css = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={css(CSS.red)} />;

Show the generated CSS file:
  $ cat styled-ppx-css/styles.css
  /* Generated by styled-ppx */
  /* This file is auto-generated, do not edit manually */
  
  .css-ljjfp7 {
    /* Generated from [%cx] in output.ml at line 3 */
    color: $(main);
    background-color: $(CSS.black);
    display: flex;
  
  }

  $ rm input.re

  $ cat > input.re << 'EOF'
  > let styles = main => [%cx
  >   {|
  >   color: $(main);
  >   background-color: $(CSS.black);
  >   display: flex;
  > |}
  > ];
  > 
  > <div className={styles(CSS.red)} />;
  > EOF

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --debug
  [styled-ppx] CSS output path: styled-ppx-css/styles.css
  [styled-ppx] File content unchanged, skipping write
  $ refmt --parse ml --print re output.ml
  let styles = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={styles(CSS.red)} />;

Test 2: Add new rule - file should be updated:
  $ cat > input.re << 'EOF'
  > let styles = main => [%cx
  >   {|
  >   color: $(main);
  >   background-color: $(CSS.black);
  >   display: flex;
  >   padding: 10px;
  > |}
  > ];
  > 
  > <div className={styles(CSS.red)} />;
  > EOF
  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --debug
  [styled-ppx] CSS output path: styled-ppx-css/styles.css
  [styled-ppx] File content changed, updating file
  [styled-ppx] CSS file updated at: styled-ppx-css/styles.css
  $ refmt --parse ml --print re output.ml
  let styles = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
      CSS.padding(`pxFloat(10.)),
    |]);
  <div className={styles(CSS.red)} />;

  $ cat styled-ppx-css/styles.css
  /* Generated by styled-ppx */
  /* This file is auto-generated, do not edit manually */
  
  .css-y0loj0 {
    /* Generated from [%cx] in output.ml at line 3 */
    color: $(main);
    background-color: $(CSS.black);
    display: flex;
    padding: 10px;
  
  }
