  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  CSS file generated at: styled-ppx-css/styles.css
  $ refmt --parse ml --print re output.ml
  let css = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={css(CSS.red)} />;

Show the generated CSS file:
  $ cat styled-ppx-css/styles.css
  /* Generated by styled-ppx */
  /* This file is auto-generated, do not edit manually */
  
  .css_42a550cf {
    /* Generated from [%cx] at cx_inline */
    color: $(main);
    background-color: $(CSS.black);
    display: flex;
  
  }

Test 1: Change variable name but keep the same CSS - file should be unchanged:
  $ cat > input.re << 'EOF'
  > let styles = main => [%cx
  >   {|
  >   color: $(main);
  >   background-color: $(CSS.black);
  >   display: flex;
  > |}
  > ];
  > 
  > <div className={styles(CSS.red)} />;
  > EOF
  input.re: Permission denied
  [1]
  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  CSS file unchanged: styled-ppx-css/styles.css
  $ refmt --parse ml --print re output.ml
  let css = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={css(CSS.red)} />;

Test 2: Add new CSS - file should be updated:
  $ cat > input.re << 'EOF'
  > let styles = main => [%cx
  >   {|
  >   color: $(main);
  >   background-color: $(CSS.black);
  >   display: flex;
  >   padding: 10px;
  > |}
  > ];
  > 
  > <div className={styles(CSS.red)} />;
  > EOF
  input.re: Permission denied
  [1]
  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  CSS file unchanged: styled-ppx-css/styles.css
  $ refmt --parse ml --print re output.ml
  let css = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={css(CSS.red)} />;

Show the updated CSS file:
  $ cat styled-ppx-css/styles.css
  /* Generated by styled-ppx */
  /* This file is auto-generated, do not edit manually */
  
  .css_42a550cf {
    /* Generated from [%cx] at cx_inline */
    color: $(main);
    background-color: $(CSS.black);
    display: flex;
  
  }
