(* Generates css_types_witnesses.ml: the runtime witness conformance check.

   Every property in the css-grammar registry can declare a runtime witness
   ([%spec_module "...", (module Css_types.X)]). The witness survives only as
   a string ([runtime_module_path]), which the PPX bakes into user code as
   [CSS.Types.<Module>.toString(value)] for interpolated values (see
   packages/ppx/src/Property_to_types.re). Nothing ties that string to the
   runtime, so a renamed or deleted Css_types module silently breaks user
   code instead of this repository.

   This executable walks the registry, collects every property-level
   [runtime_module_path], and prints one witness reference per path. Dune
   compiles the output against styled-ppx.native, so a stale or missing
   witness path is a compile error. Output is sorted and free of timestamps
   to keep the generated file stable across runs. *)

module String_set = Set.Make (String)

(* Witness modules whose [toString] is intentionally not [t -> string]:
   Css_types.Border and its runtime aliases (BorderBlock, BorderInline, ...)
   expose the ternary border shorthand printer (width -> style -> color ->
   string) instead of the unary printer the PPX call contract expects. The
   grammar generator special-cases border shorthands so interpolation
   branches don't call their [toString] directly (see the Css_types.Border
   case in packages/css-grammar/ppx/Generate.re). For these we only check
   that the module exists. *)
let existence_only =
  String_set.of_list
    [
      "Css_types.Border";
      "Css_types.BorderBlock";
      "Css_types.BorderBlockEnd";
      "Css_types.BorderBlockStart";
      "Css_types.BorderInline";
      "Css_types.BorderInlineEnd";
      "Css_types.BorderInlineStart";
      "Css_types.WebkitBorderBefore";
    ]

let property_witness_paths : String_set.t =
  List.fold_left
    (fun acc entry ->
      match entry with
      | ( Css_grammar.Property _,
          Css_grammar.Pack_rule { runtime_module_path = Some path; _ } ) ->
        String_set.add path acc
      | _ -> acc)
    String_set.empty Css_grammar.registry

let () =
  if String_set.is_empty property_witness_paths then (
    prerr_endline
      "gen_css_types_witnesses: the css-grammar registry yielded no \
       property-level witness paths; the conformance check would be vacuous";
    exit 1);
  print_endline
    "(* Generated by gen_css_types_witnesses.exe \
     (packages/runtime/test/witness). Do not edit: dune regenerates this file \
     from the css-grammar registry.";
  print_endline
    "   Each line references a property-level runtime witness. Compiling this \
     file proves the module exists in the runtime and exposes the unary \
     [toString] that PPX-generated code calls as CSS.Types.<Module>.toString \
     (see packages/ppx/src/Property_to_types.re). *)";
  print_newline ();
  String_set.iter
    (fun path ->
      if String_set.mem path existence_only then
        Printf.printf "module _ = %s\n" path
      else Printf.printf "let _ : _ -> string = %s.toString\n" path)
    property_witness_paths;
  print_newline ();
  Printf.printf
    "let () =\n\
    \  print_endline\n\
    \    \"css-types witness conformance: %d property-level witness paths \
     verified\"\n"
    (String_set.cardinal property_witness_paths)
