(* Generates compile-time checks for property-level runtime witness paths.
   Compiling the references against styled-ppx.native catches missing modules
   and, where required, incompatible unary [toString] functions. *)

module String_set = Set.Make (String)

(* Border shorthand modules expose curried [toString] functions, so this
   audit checks only that the modules exist. *)
let existence_only =
  String_set.of_list
    [
      "Css_types.Border";
      "Css_types.BorderBlock";
      "Css_types.BorderBlockEnd";
      "Css_types.BorderBlockStart";
      "Css_types.BorderInline";
      "Css_types.BorderInlineEnd";
      "Css_types.BorderInlineStart";
      "Css_types.WebkitBorderBefore";
    ]

let property_witness_paths : String_set.t =
  List.fold_left
    (fun acc entry ->
      match entry with
      | ( Css_grammar.Property _,
          Css_grammar.Pack_rule { runtime_module_path = Some path; _ } ) ->
        String_set.add path acc
      | _ -> acc)
    String_set.empty Css_grammar.registry

let () =
  if String_set.is_empty property_witness_paths then (
    prerr_endline
      "gen_css_types_witnesses: the css-grammar registry yielded no \
       property-level witness paths; the conformance check would be vacuous";
    exit 1);
  print_endline "(* Generated by gen_css_types_witnesses.exe. Do not edit.";
  print_endline
    "   Each reference checks that a property runtime witness module exists; \
     most also require a unary [toString]. *)";
  print_newline ();
  String_set.iter
    (fun path ->
      if String_set.mem path existence_only then
        Printf.printf "module _ = %s\n" path
      else Printf.printf "let _ : _ -> string = %s.toString\n" path)
    property_witness_paths;
  print_newline ();
  Printf.printf
    "let () =\n\
    \  print_endline\n\
    \    \"css-types witness conformance: %d property-level witness paths \
     verified\"\n"
    (String_set.cardinal property_witness_paths)
