A case that a per-block rewrite of overlapping `@media` rules cannot reach:
such a rewrite only applies to several `@media` rules for one property IN
ONE BLOCK. When each of TWO blocks writes only ONE `@media` condition for
the same property, there is nothing to rewrite in EITHER block - each condition is left exactly as written, and if both
resulting classes ever apply to one element (a component that composes
another's `className` by plain string concatenation, without
`CSS.merge` - or even WITH `CSS.merge`: `Merge_key`'s rule only ever
drops a class when the two share the same CONTEXT, and a different
`@media` condition is a different context by construction, so `merge`
never drops either side here regardless), `media_width_bound` now decides
the tie by width, not by which file the generator happened to read first.

Block `p` (module `aaa`, read first, alphabetically) sets `color: red`
under `@media (min-width:600px)` - nothing else for `color` in this
block. Block `q` (module `zzz`) sets `color: blue` under `@media
(min-width:900px)` - nothing else for `color` either. Both classes reach
one element (however that composition happens - `CSS.merge` or not, per
the paragraph above).

  $ cat > aaa_single_600.ml <<EOF
  > [@@@css "@media (min-width:600px){._a_psinglecond{color:red;}}"]
  > EOF

  $ cat > zzz_single_900.ml <<EOF
  > [@@@css "@media (min-width:900px){._a_qsinglecond{color:blue;}}"]
  > EOF

  $ styled-ppx.generate aaa_single_600.ml zzz_single_900.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width:600px){._a_psinglecond{color:red;}}
  @media (min-width:900px){._a_qsinglecond{color:blue;}}

  $ styled-ppx.generate zzz_single_900.ml aaa_single_600.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width:600px){._a_psinglecond{color:red;}}
  @media (min-width:900px){._a_qsinglecond{color:blue;}}

`p` (600px) always sorts before `q` (900px) - ascending by `min-width`,
independent of argument order and independent of which filename sorts
first alphabetically. At a width `>=900px`, both conditions match, and
`q` (textually last) wins - `color: blue`.

Renaming so the 900px block is the one that sorts alphabetically first no
longer flips the winner - the width, not the filename, now decides:

  $ cat > aaa_single_900.ml <<EOF
  > [@@@css "@media (min-width:900px){._a_qsinglecond{color:blue;}}"]
  > EOF

  $ cat > zzz_single_600.ml <<EOF
  > [@@@css "@media (min-width:600px){._a_psinglecond{color:red;}}"]
  > EOF

  $ styled-ppx.generate aaa_single_900.ml zzz_single_600.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width:600px){._a_psinglecond{color:red;}}
  @media (min-width:900px){._a_qsinglecond{color:blue;}}

Same sheet as the first two runs: `p` (600px, red) first, `q` (900px,
blue) last, so at `>=900px` the winner is still `color: blue` - the exact
same two CSS blocks, same properties, same widths, same winner, regardless
of which source file the generator happens to read first alphabetically.
A per-block rewrite of overlapping `@media` rules has nothing to say about
this shape (each block has only one condition for `color` - there is no
overlap WITHIN either block to remove); `media_width_bound` is the fix
regardless of whether such a rewrite exists.
