  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --output=./$TEST_OUTPUT/generated
  $ refmt --parse ml --print re output.ml
  let woo = CSS.make("css-17vxl0k", []);
  let css = main =>
    CSS.make(
      "css-3tpy8b css-1uzc9um css-17vxl0k",
      [
        ("--main", CSS.get_value_from_rule(CSS.color(main))),
        (
          "--css-black",
          CSS.get_value_from_rule(CSS.backgroundColor(CSS.black)),
        ),
      ],
    );
  <div className={fst(css(CSS.red))} style={snd(css(CSS.red))} />;
  let maybe_css = Some(CSS.make("css-17vxl0k", []));
  <div className=?{fst(maybe_css)} style=?{snd(maybe_css)} />;

  $ cat generated/styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  
  .css-17vxl0k { display: flex; }
  .css-3tpy8b { color: var(--main); }
  .css-1uzc9um { background-color: var(--css-black); }
  
