  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ refmt --parse ml --print re output.ml
  let css = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={css(CSS.red)} />;

Show the generated CSS file:
  $ cat styled-ppx-css/styles.css
  /* Generated by styled-ppx */
  /* This file is auto-generated, do not edit manually */
  
  .css-ljjfp7 {
  color:var(--main);background-color:var(--css-black);display:flex;
  }
