The full bucket taxonomy, declared shuffled in one file, must come out in
canonical order: @property, @keyframes, globals, atomic base, structural
pseudos, :link, :visited, :focus-within, :hover, :focus, :focus-visible,
:active, pseudo-elements, @supports, @media, @container, @starting-style.

  $ cat > shuffled.ml <<EOF
  > [@@@css "@starting-style {.css-p{opacity:0;}}"]
  > [@@@css "@container (width > 400px) {.css-o{color:teal;}}"]
  > [@@@css "@media (min-width: 400px) {.css-n{color:red;}}"]
  > [@@@css "@supports (display: flex) {.css-m{color:blue;}}"]
  > [@@@css ".css-l::before{content:\"*\";}"]
  > [@@@css ".css-k:active{color:pink;}"]
  > [@@@css ".css-j:focus-visible{outline:2px solid;}"]
  > [@@@css ".css-i:focus{outline:1px solid;}"]
  > [@@@css ".css-h:hover{color:green;}"]
  > [@@@css ".css-g:focus-within{border:1px solid;}"]
  > [@@@css ".css-f:visited{color:purple;}"]
  > [@@@css ".css-e:link{color:orange;}"]
  > [@@@css ".css-d:nth-child(odd){color:gray;}"]
  > [@@@css ".css-c{color:black;}"]
  > [@@@css "body{margin:0;}"]
  > [@@@css "@keyframes keyframe-abc{0%{opacity:0;}100%{opacity:1;}}"]
  > [@@@css "@property --x-1{syntax:\"*\";inherits:false;}"]
  > EOF

  $ styled-ppx.generate shuffled.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --x-1{syntax:"*";inherits:false;}
  @keyframes keyframe-abc{0%{opacity:0;}100%{opacity:1;}}
  body{margin:0;}
  .css-c{color:black;}
  .css-d:nth-child(odd){color:gray;}
  .css-e:link{color:orange;}
  .css-f:visited{color:purple;}
  .css-g:focus-within{border:1px solid;}
  .css-h:hover{color:green;}
  .css-i:focus{outline:1px solid;}
  .css-j:focus-visible{outline:2px solid;}
  .css-k:active{color:pink;}
  .css-l::before{content:"*";}
  @supports (display: flex) {.css-m{color:blue;}}
  @media (min-width: 400px) {.css-n{color:red;}}
  @container (width > 400px) {.css-o{color:teal;}}
  @starting-style {.css-p{opacity:0;}}

Descendant selectors with pseudo-classes rank by their highest pseudo:
`.css-x a:link` is a :link rule, `.css-x .child` is base. Pseudo-classes
inside at-rules order within the conditional bucket at equal breakpoints.

  $ cat > nested.ml <<EOF
  > [@@@css "@media (min-width: 400px) {.css-b:hover{color:red;}}"]
  > [@@@css "@media (min-width: 400px) {.css-a{color:blue;}}"]
  > [@@@css ".css-y a:link{color:orange;}"]
  > [@@@css ".css-z .child{font-weight:bold;}"]
  > EOF

  $ styled-ppx.generate nested.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-z .child{font-weight:bold;}
  .css-y a:link{color:orange;}
  @media (min-width: 400px) {.css-a{color:blue;}}
  @media (min-width: 400px) {.css-b:hover{color:red;}}

Within one bucket, order is first occurrence (stable sort): the documented
"define base styles before overrides" convention still decides ties.

  $ cat > stable.ml <<EOF
  > [@@@css ".css-first{color:red;}"]
  > [@@@css ".css-second{color:blue;}"]
  > [@@@css ".css-m{margin:10px;}"]
  > [@@@css ".css-mt{margin-top:20px;}"]
  > EOF

  $ styled-ppx.generate stable.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-first{color:red;}
  .css-second{color:blue;}
  .css-m{margin:10px;}
  .css-mt{margin-top:20px;}
