When every contributing file declares `env=production`, `--layers` output
has no newlines at all except after the header comment, matching today's
minified behaviour for the unlayered case.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base"); ("env", "production")]]
  > [@@@css "@property --z-base-color { syntax: '<color>'; inherits: false; initial-value: red; }"]
  > [@@@css "._a_basewidget{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app"); ("env", "production")]]
  > [@@@css "._a_appmain{color:blue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate --layers a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --z-base-color { syntax: '<color>'; inherits: false; initial-value: red; }@layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;@layer styled-ppx.base{@layer z_base, a_app;@layer z_base{._a_basewidget{color:red;}}@layer a_app{._a_appmain{color:blue;}}}
