The /pricing shape (`featureCell`/`featureTitleCell`, monorepo report
"Round 3 analysis"): `merge(featureCell{padding: 4px $(gap)}, featureTitleCell{padding-top:
0; padding-bottom: 0})` - `featureTitleCell` is meant to override
`featureCell`'s vertical padding. `featureCell`'s block has a SECOND
interpolated declaration too (its own accent color), so its
`padding: 4px $(gap)` is a genuine two-declaration `_in_` bundle - opaque to
`CSS.merge`, which can't see a property inside a bundle to drop it. Real
sheet positions put `featureTitleCell`'s longhand atoms EARLIER (2564,
5488) than `featureCell`'s bundle (7082): same specificity, so the LATER
rule - the bundle's own `padding: 4px 16px` - wins over the two `0`
overrides that were supposed to override it, even though `merge`'s call
order means `featureTitleCell` should win.

  $ cat > pricing.ml <<EOF
  > [@@@css "._a_titlepad1{padding-top:0;}"]
  > [@@@css "._a_titlepad2{padding-bottom:0;}"]
  > [@@@css "._in_pricingcell{padding:4px 16px;}"]
  > [@@@css "._in_pricingcell{color:var(--accent);}"]
  > EOF

  $ styled-ppx.generate pricing.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._in_pricingcell{padding:4px 16px;}
  ._in_pricingcell{color:var(--accent);}
  ._a_titlepad1{padding-top:0;}
  ._a_titlepad2{padding-bottom:0;}
  }

None of these four rules are conditional (no `@media`/pseudo-class/pseudo-
element), so all four land in one tier - `styled-ppx.base` - and the tier
alone changes nothing between them. The sort, inside that one tier, keys
each rule by its own shorthand DEPTH (`Slot_key.depth_of`: 0 shorthand
levels above a property, counted through the css-grammar shorthand
graph) rather than by matching families pairwise: `padding` is a
top-level shorthand, depth 0; `color` is a plain, family-less leaf, ALSO
depth 0 (nothing sits above it either); `padding-top`/`padding-bottom`
are direct longhands of `padding`, depth 1. Both depth-0 rules - the
bundle's `padding` line AND its unrelated `color` line - sort before
both depth-1 rules, in their original relative order (a stable sort
never reorders equal keys) - `color` ending up next to `padding` rather
than last is a side effect of depth being a total, transitive order now
(an earlier, pairwise "do these two rules share a family" comparator
left `color` whever dedup happened to place it, since it shared no
family with anything to compare against - see shorthand-depth-stress.t
for why that was a real, provable bug, not just a style choice) -
harmless either way, since `color` never competes with
`padding`/`padding-top`/`padding-bottom` for the same box side. What the
browser does now, and why: same tier, so ordinary CSS source order
inside `styled-ppx.base` decides - `padding-top: 0`/`padding-bottom: 0`
are textually AFTER `padding: 4px 16px` and win on those two sides,
`padding: 4px 16px`'s left/right value stays effective on the sides
`featureTitleCell` never touched, matching what
`merge(featureCell, featureTitleCell)`'s call order intends - restored by
stylesheet position, since `CSS.merge` itself still can't see one property
inside a bundle sitting next to another.
