The /pricing shape (`featureCell`/`featureTitleCell`, monorepo report
"Round 3 analysis"): `merge(featureCell{padding: 4px $(gap)}, featureTitleCell{padding-top:
0; padding-bottom: 0})` - `featureTitleCell` is meant to override
`featureCell`'s vertical padding. `featureCell`'s block has a SECOND
interpolated declaration too (its own accent color), so its
`padding: 4px $(gap)` is a genuine two-declaration `in-` bundle - opaque to
`CSS.merge`, which can't see a property inside a bundle to drop it. Real
sheet positions put `featureTitleCell`'s longhand atoms EARLIER (2564,
5488) than `featureCell`'s bundle (7082): same specificity, so the LATER
rule - the bundle's own `padding: 4px 16px` - wins over the two `0`
overrides that were supposed to override it, even though `merge`'s call
order means `featureTitleCell` should win.

  $ cat > pricing.ml <<EOF
  > [@@@css ".a-titlepad1{padding-top:0;}"]
  > [@@@css ".a-titlepad2{padding-bottom:0;}"]
  > [@@@css ".in-pricingcell{padding:4px 16px;}"]
  > [@@@css ".in-pricingcell{color:var(--accent);}"]
  > EOF

  $ styled-ppx.generate pricing.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .in-pricingcell{padding:4px 16px;}
  .a-titlepad1{padding-top:0;}
  .a-titlepad2{padding-bottom:0;}
  .in-pricingcell{color:var(--accent);}
  }

None of these four rules are conditional (no `@media`/pseudo-class/pseudo-
element), so all four land in one tier - `styled-ppx.base` - and the tier
alone changes nothing between them. The shorthand-before-longhand sort,
inside that one tier, does: `padding` covers all four physical sides (the
family's full mask) while `padding-top`/`padding-bottom` cover only one
side each (a narrower mask of the SAME family, "padding"), so the sort
moves the `padding`-covering bundle rule before both narrower longhand
atoms, regardless of where dedup originally placed it. `color` shares no
family with any of the other three, so the comparator treats it as equal
to all of them and a plain stable sort is free to place it wherever the
merge happens to leave it (here, last) - harmless, since it never competes
with `padding`/`padding-top`/`padding-bottom` for the same box side; the
sort's only real job is keeping same-family rules in the right relative
order, never reordering unrelated properties for its own sake. What the
browser does now, and why: same tier, so ordinary CSS source order inside
`styled-ppx.base` decides - `padding-top: 0`/`padding-bottom: 0` are now
textually AFTER `padding: 4px 16px` and win on those two sides,
`padding: 4px 16px`'s left/right value stays effective on the sides
`featureTitleCell` never touched, matching what
`merge(featureCell, featureTitleCell)`'s call order intends - restored by
stylesheet position, since `CSS.merge` itself still can't see one property
inside a bundle sitting next to another.
