The aggregator has no mode flag: output minification follows the
[@@@css.config] attributes the PPX embeds in its input files. The PPX
emits [("env", "production")] when it runs with production settings and
omits the attribute in development.

  $ cat > dev.ml <<EOF
  > [@@@css ".a{color:red;}"]
  > [@@@css ".b{color:blue;}"]
  > EOF

Without any config (development), each rule is on its own line.

  $ styled-ppx.generate dev.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
  .b{color:blue;}

When every contributing file declares env=production, rules are
concatenated with no separator.

  $ cat > prod.ml <<EOF
  > [@@@css.config [("env", "production")]]
  > [@@@css ".a{color:red;}"]
  > [@@@css ".b{color:blue;}"]
  > EOF

  $ styled-ppx.generate prod.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}.b{color:blue;}

Unknown config keys are ignored (forward compatibility).

  $ cat > future.ml <<EOF
  > [@@@css.config [("some-future-key", "whatever"); ("env", "production")]]
  > [@@@css ".c{color:green;}"]
  > EOF

  $ styled-ppx.generate future.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .c{color:green;}

Mixed inputs — some files compiled for production, some not — warn and
fall back to readable output. This is visible by default (--log warning).

  $ styled-ppx.generate prod.ml dev.ml
  styled-ppx: input files disagree on their [@@@css.config] environment: prod.ml was compiled for production but dev.ml was not; emitting non-minified output. Pass the same environment to every (pps styled-ppx ...) stanza.
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
  .b{color:blue;}

The warning can be silenced with --log error.

  $ styled-ppx.generate --log error prod.ml dev.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
  .b{color:blue;}

A file that only carries a config (no rules) still counts as contributing,
so a production-only marker file cannot silently flip the mode of a
development build.

  $ cat > marker.ml <<EOF
  > [@@@css.config [("env", "production")]]
  > EOF

  $ styled-ppx.generate marker.ml dev.ml
  styled-ppx: input files disagree on their [@@@css.config] environment: marker.ml was compiled for production but dev.ml was not; emitting non-minified output. Pass the same environment to every (pps styled-ppx ...) stanza.
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
  .b{color:blue;}

The old mode flags are gone; unknown flags are rejected.

  $ styled-ppx.generate --minify dev.ml
  styled-ppx: unknown flag "--minify"
  [2]

  $ styled-ppx.generate --env production dev.ml
  styled-ppx: unknown flag "--env"
  [2]

A trailing value-taking flag without its value is rejected too.

  $ styled-ppx.generate dev.ml --output
  styled-ppx: missing value for flag "--output"
  [2]
