`--order source` bypasses library grouping entirely, the same way it
bypasses module-level ordering: files are emitted exactly in the order
they're passed, dependency or not.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base")]]
  > [@@@css ".base-widget{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app")]]
  > [@@@css ".app-main{color:blue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate --order source a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.global {
  .app-main{color:blue;}
  .base-widget{color:red;}
  }
