  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --native --impl output.ml -o output.ml
  $ refmt --parse ml --print re output.ml
  module DynamicComponentWithDefaultValue = {
    let getOrEmpty = str =>
      switch (str) {
      | Some(str) => " " ++ str
      | None => ""
      };
    let styles = (~var=CssJs.hex("333"), _) =>
      CssJs.style([|
        CssJs.label("DynamicComponentWithDefaultValue"),
        CssJs.display(`block),
        (CssJs.color(var): CssJs.rule),
      |]);
    let make =
        (
          ~key as _: option(string)=?,
          ~innerRef=?,
          ~as_=?,
          ~children=React.null,
          ~about: option(string)=?,
          ~accentHeight: option(string)=?,
          ~accept: option(string)=?,
          ~acceptCharset: option(string)=?,
          ~accessKey: option(string)=?,
          ~accumulate: option(string)=?,
          ~action: option(string)=?,
          ~additive: option(string)=?,
          ~alignmentBaseline: option(string)=?,
          ~allowFullScreen: option(bool)=?,
          ~allowReorder: option(string)=?,
          ~alphabetic: option(string)=?,
          ~alt: option(string)=?,
          ~amplitude: option(string)=?,
          ~arabicForm: option(string)=?,
          ~ariaActivedescendant: option(string)=?,
          ~ariaAtomic: option(bool)=?,
          ~ariaBusy: option(bool)=?,
          ~ariaColcount: option(int)=?,
          ~ariaColindex: option(int)=?,
          ~ariaColspan: option(int)=?,
          ~ariaControls: option(string)=?,
          ~ariaDescribedby: option(string)=?,
          ~ariaDetails: option(string)=?,
          ~ariaDisabled: option(bool)=?,
          ~ariaErrormessage: option(string)=?,
          ~ariaExpanded: option(bool)=?,
          ~ariaFlowto: option(string)=?,
          ~ariaGrabbed: option(bool)=?,
          ~ariaHidden: option(bool)=?,
          ~ariaKeyshortcuts: option(string)=?,
          ~ariaLabel: option(string)=?,
          ~ariaLabelledby: option(string)=?,
          ~ariaLevel: option(int)=?,
          ~ariaModal: option(bool)=?,
          ~ariaMultiline: option(bool)=?,
          ~ariaMultiselectable: option(bool)=?,
          ~ariaOwns: option(string)=?,
          ~ariaPlaceholder: option(string)=?,
          ~ariaPosinset: option(int)=?,
          ~ariaReadonly: option(bool)=?,
          ~ariaRelevant: option(string)=?,
          ~ariaRequired: option(bool)=?,
          ~ariaRoledescription: option(string)=?,
          ~ariaRowcount: option(int)=?,
          ~ariaRowindex: option(int)=?,
          ~ariaRowspan: option(int)=?,
          ~ariaSelected: option(bool)=?,
          ~ariaSetsize: option(int)=?,
          ~ariaSort: option(string)=?,
          ~ariaValuemax: option(float)=?,
          ~ariaValuemin: option(float)=?,
          ~ariaValuenow: option(float)=?,
          ~ariaValuetext: option(string)=?,
          ~ascent: option(string)=?,
          ~async: option(bool)=?,
          ~attributeName: option(string)=?,
          ~attributeType: option(string)=?,
          ~autoComplete: option(string)=?,
          ~autoFocus: option(bool)=?,
          ~autoPlay: option(bool)=?,
          ~autoReverse: option(string)=?,
          ~azimuth: option(string)=?,
          ~baseFrequency: option(string)=?,
          ~baselineShift: option(string)=?,
          ~baseProfile: option(string)=?,
          ~bbox: option(string)=?,
          ~begin_: option(string)=?,
          ~bias: option(string)=?,
          ~by: option(string)=?,
          ~calcMode: option(string)=?,
          ~capHeight: option(string)=?,
          ~challenge: option(string)=?,
          ~charSet: option(string)=?,
          ~checked: option(bool)=?,
          ~cite: option(string)=?,
          ~className: option(string)=?,
          ~clip: option(string)=?,
          ~clipPath: option(string)=?,
          ~clipPathUnits: option(string)=?,
          ~clipRule: option(string)=?,
          ~colorInterpolation: option(string)=?,
          ~colorInterpolationFilters: option(string)=?,
          ~colorProfile: option(string)=?,
          ~colorRendering: option(string)=?,
          ~cols: option(int)=?,
          ~colSpan: option(int)=?,
          ~content: option(string)=?,
          ~contentEditable: option(bool)=?,
          ~contentScriptType: option(string)=?,
          ~contentStyleType: option(string)=?,
          ~contextMenu: option(string)=?,
          ~controls: option(bool)=?,
          ~coords: option(string)=?,
          ~crossOrigin: option(string)=?,
          ~cursor: option(string)=?,
          ~cx: option(string)=?,
          ~cy: option(string)=?,
          ~d: option(string)=?,
          ~data: option(string)=?,
          ~datatype: option(string)=?,
          ~dateTime: option(string)=?,
          ~decelerate: option(string)=?,
          ~default: option(bool)=?,
          ~defaultChecked: option(bool)=?,
          ~defaultValue: option(string)=?,
          ~defer: option(bool)=?,
          ~descent: option(string)=?,
          ~diffuseConstant: option(string)=?,
          ~dir: option(string)=?,
          ~direction: option(string)=?,
          ~disabled: option(bool)=?,
          ~display: option(string)=?,
          ~divisor: option(string)=?,
          ~dominantBaseline: option(string)=?,
          ~download: option(string)=?,
          ~draggable: option(bool)=?,
          ~dur: option(string)=?,
          ~dx: option(string)=?,
          ~dy: option(string)=?,
          ~edgeMode: option(string)=?,
          ~elevation: option(string)=?,
          ~enableBackground: option(string)=?,
          ~encType: option(string)=?,
          ~end_: option(string)=?,
          ~exponent: option(string)=?,
          ~externalResourcesRequired: option(string)=?,
          ~fill: option(string)=?,
          ~fillOpacity: option(string)=?,
          ~fillRule: option(string)=?,
          ~filter: option(string)=?,
          ~filterRes: option(string)=?,
          ~filterUnits: option(string)=?,
          ~floodColor: option(string)=?,
          ~floodOpacity: option(string)=?,
          ~focusable: option(string)=?,
          ~fomat: option(string)=?,
          ~fontFamily: option(string)=?,
          ~fontSize: option(string)=?,
          ~fontSizeAdjust: option(string)=?,
          ~fontStretch: option(string)=?,
          ~fontStyle: option(string)=?,
          ~fontVariant: option(string)=?,
          ~fontWeight: option(string)=?,
          ~form: option(string)=?,
          ~formAction: option(string)=?,
          ~formMethod: option(string)=?,
          ~formTarget: option(string)=?,
          ~from: option(string)=?,
          ~fx: option(string)=?,
          ~fy: option(string)=?,
          ~g1: option(string)=?,
          ~g2: option(string)=?,
          ~glyphName: option(string)=?,
          ~glyphOrientationHorizontal: option(string)=?,
          ~glyphOrientationVertical: option(string)=?,
          ~glyphRef: option(string)=?,
          ~gradientTransform: option(string)=?,
          ~gradientUnits: option(string)=?,
          ~hanging: option(string)=?,
          ~headers: option(string)=?,
          ~height: option(string)=?,
          ~hidden: option(bool)=?,
          ~high: option(int)=?,
          ~horizAdvX: option(string)=?,
          ~horizOriginX: option(string)=?,
          ~href: option(string)=?,
          ~hrefLang: option(string)=?,
          ~htmlFor: option(string)=?,
          ~httpEquiv: option(string)=?,
          ~icon: option(string)=?,
          ~id: option(string)=?,
          ~ideographic: option(string)=?,
          ~imageRendering: option(string)=?,
          ~in_: option(string)=?,
          ~in2: option(string)=?,
          ~inlist: option(string)=?,
          ~inputMode: option(string)=?,
          ~integrity: option(string)=?,
          ~intercept: option(string)=?,
          ~itemID: option(string)=?,
          ~itemProp: option(string)=?,
          ~itemRef: option(string)=?,
          ~itemScope: option(bool)=?,
          ~itemType: option(string)=?,
          ~k: option(string)=?,
          ~k1: option(string)=?,
          ~k2: option(string)=?,
          ~k3: option(string)=?,
          ~k4: option(string)=?,
          ~kernelMatrix: option(string)=?,
          ~kernelUnitLength: option(string)=?,
          ~kerning: option(string)=?,
          ~keyPoints: option(string)=?,
          ~keySplines: option(string)=?,
          ~keyTimes: option(string)=?,
          ~keyType: option(string)=?,
          ~kind: option(string)=?,
          ~label: option(string)=?,
          ~lang: option(string)=?,
          ~lengthAdjust: option(string)=?,
          ~letterSpacing: option(string)=?,
          ~lightingColor: option(string)=?,
          ~limitingConeAngle: option(string)=?,
          ~list: option(string)=?,
          ~local: option(string)=?,
          ~loop: option(bool)=?,
          ~low: option(int)=?,
          ~manifest: option(string)=?,
          ~markerEnd: option(string)=?,
          ~markerHeight: option(string)=?,
          ~markerMid: option(string)=?,
          ~markerStart: option(string)=?,
          ~markerUnits: option(string)=?,
          ~markerWidth: option(string)=?,
          ~mask: option(string)=?,
          ~maskContentUnits: option(string)=?,
          ~maskUnits: option(string)=?,
          ~mathematical: option(string)=?,
          ~max: option(string)=?,
          ~maxLength: option(int)=?,
          ~media: option(string)=?,
          ~mediaGroup: option(string)=?,
          ~min: option(string)=?,
          ~minLength: option(int)=?,
          ~mode: option(string)=?,
          ~multiple: option(bool)=?,
          ~muted: option(bool)=?,
          ~name: option(string)=?,
          ~nonce: option(string)=?,
          ~noValidate: option(bool)=?,
          ~numOctaves: option(string)=?,
          ~offset: option(string)=?,
          ~opacity: option(string)=?,
          ~open_: option(bool)=?,
          ~operator: option(string)=?,
          ~optimum: option(int)=?,
          ~order: option(string)=?,
          ~orient: option(string)=?,
          ~orientation: option(string)=?,
          ~origin: option(string)=?,
          ~overflow: option(string)=?,
          ~overflowX: option(string)=?,
          ~overflowY: option(string)=?,
          ~overlinePosition: option(string)=?,
          ~overlineThickness: option(string)=?,
          ~paintOrder: option(string)=?,
          ~panose1: option(string)=?,
          ~pathLength: option(string)=?,
          ~pattern: option(string)=?,
          ~patternContentUnits: option(string)=?,
          ~patternTransform: option(string)=?,
          ~patternUnits: option(string)=?,
          ~placeholder: option(string)=?,
          ~pointerEvents: option(string)=?,
          ~points: option(string)=?,
          ~pointsAtX: option(string)=?,
          ~pointsAtY: option(string)=?,
          ~pointsAtZ: option(string)=?,
          ~poster: option(string)=?,
          ~prefix: option(string)=?,
          ~preload: option(string)=?,
          ~preserveAlpha: option(string)=?,
          ~preserveAspectRatio: option(string)=?,
          ~primitiveUnits: option(string)=?,
          ~property: option(string)=?,
          ~r: option(string)=?,
          ~radioGroup: option(string)=?,
          ~radius: option(string)=?,
          ~readOnly: option(bool)=?,
          ~refX: option(string)=?,
          ~refY: option(string)=?,
          ~rel: option(string)=?,
          ~renderingIntent: option(string)=?,
          ~repeatCount: option(string)=?,
          ~repeatDur: option(string)=?,
          ~required: option(bool)=?,
          ~requiredExtensions: option(string)=?,
          ~requiredFeatures: option(string)=?,
          ~resource: option(string)=?,
          ~restart: option(string)=?,
          ~result: option(string)=?,
          ~reversed: option(bool)=?,
          ~role: option(string)=?,
          ~rotate: option(string)=?,
          ~rows: option(int)=?,
          ~rowSpan: option(int)=?,
          ~rx: option(string)=?,
          ~ry: option(string)=?,
          ~sandbox: option(string)=?,
          ~scale: option(string)=?,
          ~scope: option(string)=?,
          ~scoped: option(bool)=?,
          ~scrolling: option(string)=?,
          ~seed: option(string)=?,
          ~selected: option(bool)=?,
          ~shape: option(string)=?,
          ~shapeRendering: option(string)=?,
          ~size: option(int)=?,
          ~sizes: option(string)=?,
          ~slope: option(string)=?,
          ~spacing: option(string)=?,
          ~span: option(int)=?,
          ~specularConstant: option(string)=?,
          ~specularExponent: option(string)=?,
          ~speed: option(string)=?,
          ~spellCheck: option(bool)=?,
          ~spreadMethod: option(string)=?,
          ~src: option(string)=?,
          ~srcDoc: option(string)=?,
          ~srcLang: option(string)=?,
          ~srcSet: option(string)=?,
          ~start: option(int)=?,
          ~startOffset: option(string)=?,
          ~stdDeviation: option(string)=?,
          ~stemh: option(string)=?,
          ~stemv: option(string)=?,
          ~step: option(float)=?,
          ~stitchTiles: option(string)=?,
          ~stopColor: option(string)=?,
          ~stopOpacity: option(string)=?,
          ~strikethroughPosition: option(string)=?,
          ~strikethroughThickness: option(string)=?,
          ~stroke: option(string)=?,
          ~strokeDasharray: option(string)=?,
          ~strokeDashoffset: option(string)=?,
          ~strokeLinecap: option(string)=?,
          ~strokeLinejoin: option(string)=?,
          ~strokeMiterlimit: option(string)=?,
          ~strokeOpacity: option(string)=?,
          ~strokeWidth: option(string)=?,
          ~style: option(ReactDOM.Style.t)=?,
          ~summary: option(string)=?,
          ~suppressContentEditableWarning: option(bool)=?,
          ~surfaceScale: option(string)=?,
          ~systemLanguage: option(string)=?,
          ~tabIndex: option(int)=?,
          ~tableValues: option(string)=?,
          ~target: option(string)=?,
          ~targetX: option(string)=?,
          ~targetY: option(string)=?,
          ~textAnchor: option(string)=?,
          ~textDecoration: option(string)=?,
          ~textLength: option(string)=?,
          ~textRendering: option(string)=?,
          ~title: option(string)=?,
          ~to_: option(string)=?,
          ~transform: option(string)=?,
          ~type_: option(string)=?,
          ~typeof: option(string)=?,
          ~u1: option(string)=?,
          ~u2: option(string)=?,
          ~underlinePosition: option(string)=?,
          ~underlineThickness: option(string)=?,
          ~unicode: option(string)=?,
          ~unicodeBidi: option(string)=?,
          ~unicodeRange: option(string)=?,
          ~unitsPerEm: option(string)=?,
          ~useMap: option(string)=?,
          ~vAlphabetic: option(string)=?,
          ~value: option(string)=?,
          ~values: option(string)=?,
          ~vectorEffect: option(string)=?,
          ~version: option(string)=?,
          ~vertAdvX: option(string)=?,
          ~vertAdvY: option(string)=?,
          ~vertOriginX: option(string)=?,
          ~vertOriginY: option(string)=?,
          ~vHanging: option(string)=?,
          ~vIdeographic: option(string)=?,
          ~viewBox: option(string)=?,
          ~viewTarget: option(string)=?,
          ~visibility: option(string)=?,
          ~vMathematical: option(string)=?,
          ~vocab: option(string)=?,
          ~width: option(string)=?,
          ~widths: option(string)=?,
          ~wordSpacing: option(string)=?,
          ~wrap: option(string)=?,
          ~writingMode: option(string)=?,
          ~x: option(string)=?,
          ~x1: option(string)=?,
          ~x2: option(string)=?,
          ~xChannelSelector: option(string)=?,
          ~xHeight: option(string)=?,
          ~xlinkActuate: option(string)=?,
          ~xlinkArcrole: option(string)=?,
          ~xlinkHref: option(string)=?,
          ~xlinkRole: option(string)=?,
          ~xlinkShow: option(string)=?,
          ~xlinkTitle: option(string)=?,
          ~xlinkType: option(string)=?,
          ~xmlBase: option(string)=?,
          ~xmlLang: option(string)=?,
          ~xmlns: option(string)=?,
          ~xmlnsXlink: option(string)=?,
          ~xmlSpace: option(string)=?,
          ~y: option(string)=?,
          ~y1: option(string)=?,
          ~y2: option(string)=?,
          ~yChannelSelector: option(string)=?,
          ~z: option(string)=?,
          ~zoomAndPan: option(string)=?,
          ~onAbort: option(React.Event.Media.t => unit)=?,
          ~onAnimationEnd: option(React.Event.Animation.t => unit)=?,
          ~onAnimationIteration: option(React.Event.Animation.t => unit)=?,
          ~onAnimationStart: option(React.Event.Animation.t => unit)=?,
          ~onBlur: option(React.Event.Focus.t => unit)=?,
          ~onCanPlay: option(React.Event.Media.t => unit)=?,
          ~onCanPlayThrough: option(React.Event.Media.t => unit)=?,
          ~onChange: option(React.Event.Form.t => unit)=?,
          ~onClick: option(React.Event.Mouse.t => unit)=?,
          ~onCompositionEnd: option(React.Event.Composition.t => unit)=?,
          ~onCompositionStart: option(React.Event.Composition.t => unit)=?,
          ~onCompositionUpdate: option(React.Event.Composition.t => unit)=?,
          ~onContextMenu: option(React.Event.Mouse.t => unit)=?,
          ~onCopy: option(React.Event.Clipboard.t => unit)=?,
          ~onCut: option(React.Event.Clipboard.t => unit)=?,
          ~onDoubleClick: option(React.Event.Mouse.t => unit)=?,
          ~onDrag: option(React.Event.Mouse.t => unit)=?,
          ~onDragEnd: option(React.Event.Mouse.t => unit)=?,
          ~onDragEnter: option(React.Event.Mouse.t => unit)=?,
          ~onDragExit: option(React.Event.Mouse.t => unit)=?,
          ~onDragLeave: option(React.Event.Mouse.t => unit)=?,
          ~onDragOver: option(React.Event.Mouse.t => unit)=?,
          ~onDragStart: option(React.Event.Mouse.t => unit)=?,
          ~onDrop: option(React.Event.Mouse.t => unit)=?,
          ~onDurationChange: option(React.Event.Media.t => unit)=?,
          ~onEmptied: option(React.Event.Media.t => unit)=?,
          ~onEncrypetd: option(React.Event.Media.t => unit)=?,
          ~onEnded: option(React.Event.Media.t => unit)=?,
          ~onError: option(React.Event.Media.t => unit)=?,
          ~onFocus: option(React.Event.Focus.t => unit)=?,
          ~onInput: option(React.Event.Form.t => unit)=?,
          ~onKeyDown: option(React.Event.Keyboard.t => unit)=?,
          ~onKeyPress: option(React.Event.Keyboard.t => unit)=?,
          ~onKeyUp: option(React.Event.Keyboard.t => unit)=?,
          ~onLoadedData: option(React.Event.Media.t => unit)=?,
          ~onLoadedMetadata: option(React.Event.Media.t => unit)=?,
          ~onLoadStart: option(React.Event.Media.t => unit)=?,
          ~onMouseDown: option(React.Event.Mouse.t => unit)=?,
          ~onMouseEnter: option(React.Event.Mouse.t => unit)=?,
          ~onMouseLeave: option(React.Event.Mouse.t => unit)=?,
          ~onMouseMove: option(React.Event.Mouse.t => unit)=?,
          ~onMouseOut: option(React.Event.Mouse.t => unit)=?,
          ~onMouseOver: option(React.Event.Mouse.t => unit)=?,
          ~onMouseUp: option(React.Event.Mouse.t => unit)=?,
          ~onPaste: option(React.Event.Clipboard.t => unit)=?,
          ~onPause: option(React.Event.Media.t => unit)=?,
          ~onPlay: option(React.Event.Media.t => unit)=?,
          ~onPlaying: option(React.Event.Media.t => unit)=?,
          ~onProgress: option(React.Event.Media.t => unit)=?,
          ~onRateChange: option(React.Event.Media.t => unit)=?,
          ~onScroll: option(React.Event.UI.t => unit)=?,
          ~onSeeked: option(React.Event.Media.t => unit)=?,
          ~onSeeking: option(React.Event.Media.t => unit)=?,
          ~onSelect: option(React.Event.Selection.t => unit)=?,
          ~onStalled: option(React.Event.Media.t => unit)=?,
          ~onSubmit: option(React.Event.Form.t => unit)=?,
          ~onSuspend: option(React.Event.Media.t => unit)=?,
          ~onTimeUpdate: option(React.Event.Media.t => unit)=?,
          ~onTouchCancel: option(React.Event.Touch.t => unit)=?,
          ~onTouchEnd: option(React.Event.Touch.t => unit)=?,
          ~onTouchMove: option(React.Event.Touch.t => unit)=?,
          ~onTouchStart: option(React.Event.Touch.t => unit)=?,
          ~onTransitionEnd: option(React.Event.Transition.t => unit)=?,
          ~onVolumeChange: option(React.Event.Media.t => unit)=?,
          ~onWaiting: option(React.Event.Media.t => unit)=?,
          ~onWheel: option(React.Event.Wheel.t => unit)=?,
          ~var=?,
          (),
        ) => {
      let className = styles(~var?, ()) ++ getOrEmpty(className);
      React.createElement(
        switch (as_) {
        | Some(v) => v
        | None => "div"
        },
        ReactDOM.domProps(
          ~className,
          ~ref=?innerRef,
          ~about?,
          ~accentHeight?,
          ~accept?,
          ~acceptCharset?,
          ~accessKey?,
          ~accumulate?,
          ~action?,
          ~additive?,
          ~alignmentBaseline?,
          ~allowFullScreen?,
          ~allowReorder?,
          ~alphabetic?,
          ~alt?,
          ~amplitude?,
          ~arabicForm?,
          ~ariaActivedescendant?,
          ~ariaAtomic?,
          ~ariaBusy?,
          ~ariaColcount?,
          ~ariaColindex?,
          ~ariaColspan?,
          ~ariaControls?,
          ~ariaDescribedby?,
          ~ariaDetails?,
          ~ariaDisabled?,
          ~ariaErrormessage?,
          ~ariaExpanded?,
          ~ariaFlowto?,
          ~ariaGrabbed?,
          ~ariaHidden?,
          ~ariaKeyshortcuts?,
          ~ariaLabel?,
          ~ariaLabelledby?,
          ~ariaLevel?,
          ~ariaModal?,
          ~ariaMultiline?,
          ~ariaMultiselectable?,
          ~ariaOwns?,
          ~ariaPlaceholder?,
          ~ariaPosinset?,
          ~ariaReadonly?,
          ~ariaRelevant?,
          ~ariaRequired?,
          ~ariaRoledescription?,
          ~ariaRowcount?,
          ~ariaRowindex?,
          ~ariaRowspan?,
          ~ariaSelected?,
          ~ariaSetsize?,
          ~ariaSort?,
          ~ariaValuemax?,
          ~ariaValuemin?,
          ~ariaValuenow?,
          ~ariaValuetext?,
          ~ascent?,
          ~async?,
          ~attributeName?,
          ~attributeType?,
          ~autoComplete?,
          ~autoFocus?,
          ~autoPlay?,
          ~autoReverse?,
          ~azimuth?,
          ~baseFrequency?,
          ~baselineShift?,
          ~baseProfile?,
          ~bbox?,
          ~begin_?,
          ~bias?,
          ~by?,
          ~calcMode?,
          ~capHeight?,
          ~challenge?,
          ~charSet?,
          ~checked?,
          ~cite?,
          ~clip?,
          ~clipPath?,
          ~clipPathUnits?,
          ~clipRule?,
          ~colorInterpolation?,
          ~colorInterpolationFilters?,
          ~colorProfile?,
          ~colorRendering?,
          ~cols?,
          ~colSpan?,
          ~content?,
          ~contentEditable?,
          ~contentScriptType?,
          ~contentStyleType?,
          ~contextMenu?,
          ~controls?,
          ~coords?,
          ~crossOrigin?,
          ~cursor?,
          ~cx?,
          ~cy?,
          ~d?,
          ~data?,
          ~datatype?,
          ~dateTime?,
          ~decelerate?,
          ~default?,
          ~defaultChecked?,
          ~defaultValue?,
          ~defer?,
          ~descent?,
          ~diffuseConstant?,
          ~dir?,
          ~direction?,
          ~disabled?,
          ~display?,
          ~divisor?,
          ~dominantBaseline?,
          ~download?,
          ~draggable?,
          ~dur?,
          ~dx?,
          ~dy?,
          ~edgeMode?,
          ~elevation?,
          ~enableBackground?,
          ~encType?,
          ~end_?,
          ~exponent?,
          ~externalResourcesRequired?,
          ~fill?,
          ~fillOpacity?,
          ~fillRule?,
          ~filter?,
          ~filterRes?,
          ~filterUnits?,
          ~floodColor?,
          ~floodOpacity?,
          ~focusable?,
          ~fomat?,
          ~fontFamily?,
          ~fontSize?,
          ~fontSizeAdjust?,
          ~fontStretch?,
          ~fontStyle?,
          ~fontVariant?,
          ~fontWeight?,
          ~form?,
          ~formAction?,
          ~formMethod?,
          ~formTarget?,
          ~from?,
          ~fx?,
          ~fy?,
          ~g1?,
          ~g2?,
          ~glyphName?,
          ~glyphOrientationHorizontal?,
          ~glyphOrientationVertical?,
          ~glyphRef?,
          ~gradientTransform?,
          ~gradientUnits?,
          ~hanging?,
          ~headers?,
          ~height?,
          ~hidden?,
          ~high?,
          ~horizAdvX?,
          ~horizOriginX?,
          ~href?,
          ~hrefLang?,
          ~htmlFor?,
          ~httpEquiv?,
          ~icon?,
          ~id?,
          ~ideographic?,
          ~imageRendering?,
          ~in_?,
          ~in2?,
          ~inlist?,
          ~inputMode?,
          ~integrity?,
          ~intercept?,
          ~itemID?,
          ~itemProp?,
          ~itemRef?,
          ~itemScope?,
          ~itemType?,
          ~k?,
          ~k1?,
          ~k2?,
          ~k3?,
          ~k4?,
          ~kernelMatrix?,
          ~kernelUnitLength?,
          ~kerning?,
          ~keyPoints?,
          ~keySplines?,
          ~keyTimes?,
          ~keyType?,
          ~kind?,
          ~label?,
          ~lang?,
          ~lengthAdjust?,
          ~letterSpacing?,
          ~lightingColor?,
          ~limitingConeAngle?,
          ~list?,
          ~local?,
          ~loop?,
          ~low?,
          ~manifest?,
          ~markerEnd?,
          ~markerHeight?,
          ~markerMid?,
          ~markerStart?,
          ~markerUnits?,
          ~markerWidth?,
          ~mask?,
          ~maskContentUnits?,
          ~maskUnits?,
          ~mathematical?,
          ~max?,
          ~maxLength?,
          ~media?,
          ~mediaGroup?,
          ~min?,
          ~minLength?,
          ~mode?,
          ~multiple?,
          ~muted?,
          ~name?,
          ~nonce?,
          ~noValidate?,
          ~numOctaves?,
          ~offset?,
          ~opacity?,
          ~open_?,
          ~operator?,
          ~optimum?,
          ~order?,
          ~orient?,
          ~orientation?,
          ~origin?,
          ~overflow?,
          ~overflowX?,
          ~overflowY?,
          ~overlinePosition?,
          ~overlineThickness?,
          ~paintOrder?,
          ~panose1?,
          ~pathLength?,
          ~pattern?,
          ~patternContentUnits?,
          ~patternTransform?,
          ~patternUnits?,
          ~placeholder?,
          ~pointerEvents?,
          ~points?,
          ~pointsAtX?,
          ~pointsAtY?,
          ~pointsAtZ?,
          ~poster?,
          ~prefix?,
          ~preload?,
          ~preserveAlpha?,
          ~preserveAspectRatio?,
          ~primitiveUnits?,
          ~property?,
          ~r?,
          ~radioGroup?,
          ~radius?,
          ~readOnly?,
          ~refX?,
          ~refY?,
          ~rel?,
          ~renderingIntent?,
          ~repeatCount?,
          ~repeatDur?,
          ~required?,
          ~requiredExtensions?,
          ~requiredFeatures?,
          ~resource?,
          ~restart?,
          ~result?,
          ~reversed?,
          ~role?,
          ~rotate?,
          ~rows?,
          ~rowSpan?,
          ~rx?,
          ~ry?,
          ~sandbox?,
          ~scale?,
          ~scope?,
          ~scoped?,
          ~scrolling?,
          ~seed?,
          ~selected?,
          ~shape?,
          ~shapeRendering?,
          ~size?,
          ~sizes?,
          ~slope?,
          ~spacing?,
          ~span?,
          ~specularConstant?,
          ~specularExponent?,
          ~speed?,
          ~spellCheck?,
          ~spreadMethod?,
          ~src?,
          ~srcDoc?,
          ~srcLang?,
          ~srcSet?,
          ~start?,
          ~startOffset?,
          ~stdDeviation?,
          ~stemh?,
          ~stemv?,
          ~step?,
          ~stitchTiles?,
          ~stopColor?,
          ~stopOpacity?,
          ~strikethroughPosition?,
          ~strikethroughThickness?,
          ~stroke?,
          ~strokeDasharray?,
          ~strokeDashoffset?,
          ~strokeLinecap?,
          ~strokeLinejoin?,
          ~strokeMiterlimit?,
          ~strokeOpacity?,
          ~strokeWidth?,
          ~style?,
          ~summary?,
          ~suppressContentEditableWarning?,
          ~surfaceScale?,
          ~systemLanguage?,
          ~tabIndex?,
          ~tableValues?,
          ~target?,
          ~targetX?,
          ~targetY?,
          ~textAnchor?,
          ~textDecoration?,
          ~textLength?,
          ~textRendering?,
          ~title?,
          ~to_?,
          ~transform?,
          ~type_?,
          ~typeof?,
          ~u1?,
          ~u2?,
          ~underlinePosition?,
          ~underlineThickness?,
          ~unicode?,
          ~unicodeBidi?,
          ~unicodeRange?,
          ~unitsPerEm?,
          ~useMap?,
          ~vAlphabetic?,
          ~value?,
          ~values?,
          ~vectorEffect?,
          ~version?,
          ~vertAdvX?,
          ~vertAdvY?,
          ~vertOriginX?,
          ~vertOriginY?,
          ~vHanging?,
          ~vIdeographic?,
          ~viewBox?,
          ~viewTarget?,
          ~visibility?,
          ~vMathematical?,
          ~vocab?,
          ~width?,
          ~widths?,
          ~wordSpacing?,
          ~wrap?,
          ~writingMode?,
          ~x?,
          ~x1?,
          ~x2?,
          ~xChannelSelector?,
          ~xHeight?,
          ~xlinkActuate?,
          ~xlinkArcrole?,
          ~xlinkHref?,
          ~xlinkRole?,
          ~xlinkShow?,
          ~xlinkTitle?,
          ~xlinkType?,
          ~xmlBase?,
          ~xmlLang?,
          ~xmlns?,
          ~xmlnsXlink?,
          ~xmlSpace?,
          ~y?,
          ~y1?,
          ~y2?,
          ~yChannelSelector?,
          ~z?,
          ~zoomAndPan?,
          ~onAbort?,
          ~onAnimationEnd?,
          ~onAnimationIteration?,
          ~onAnimationStart?,
          ~onBlur?,
          ~onCanPlay?,
          ~onCanPlayThrough?,
          ~onChange?,
          ~onClick?,
          ~onCompositionEnd?,
          ~onCompositionStart?,
          ~onCompositionUpdate?,
          ~onContextMenu?,
          ~onCopy?,
          ~onCut?,
          ~onDoubleClick?,
          ~onDrag?,
          ~onDragEnd?,
          ~onDragEnter?,
          ~onDragExit?,
          ~onDragLeave?,
          ~onDragOver?,
          ~onDragStart?,
          ~onDrop?,
          ~onDurationChange?,
          ~onEmptied?,
          ~onEncrypetd?,
          ~onEnded?,
          ~onError?,
          ~onFocus?,
          ~onInput?,
          ~onKeyDown?,
          ~onKeyPress?,
          ~onKeyUp?,
          ~onLoadedData?,
          ~onLoadedMetadata?,
          ~onLoadStart?,
          ~onMouseDown?,
          ~onMouseEnter?,
          ~onMouseLeave?,
          ~onMouseMove?,
          ~onMouseOut?,
          ~onMouseOver?,
          ~onMouseUp?,
          ~onPaste?,
          ~onPause?,
          ~onPlay?,
          ~onPlaying?,
          ~onProgress?,
          ~onRateChange?,
          ~onScroll?,
          ~onSeeked?,
          ~onSeeking?,
          ~onSelect?,
          ~onStalled?,
          ~onSubmit?,
          ~onSuspend?,
          ~onTimeUpdate?,
          ~onTouchCancel?,
          ~onTouchEnd?,
          ~onTouchMove?,
          ~onTouchStart?,
          ~onTransitionEnd?,
          ~onVolumeChange?,
          ~onWaiting?,
          ~onWheel?,
          (),
        ),
        [children],
      );
    };
  };
