The two-stylesheet shape (`tableContainer`, monorepo report "Round 3
analysis"): the SAME `overflow-x: auto` atom is emitted by two different
generated stylesheets (the "static" sheet, which also narrows it under
`@media (min-width:1280px)`, and an unrelated "toolkit" sheet, which
doesn't). Each stylesheet comes from its OWN `styled-ppx.generate`
invocation - dune builds them separately, and a real page loads both
`<link>`s.

Round 7 gave every sheet the SAME three, always-in-this-order layer names
(`styled-ppx.global` < `.base` < `.conditional`), so no matter which
`<link>` the browser loaded first, every sheet's `base` rule outranked
every sheet's `conditional` rule - fixing this exact case. Round 7b
(see `layers-descendant-tier.t`'s "Round 7b" case) found that having
`base` and `conditional` as separate CSS layers also broke real,
higher-specificity `base` rules losing to unrelated, less specific
`conditional` ones, and fixed it by collapsing `base` and `conditional`
into ONE shared `styled-ppx.atoms` layer, ordering them by emission
position instead (`styled-ppx.global` keeps its own, separate, lower
layer, unaffected - see `layers-global-tier.t`). That fix is necessarily
per STYLESHEET, not per page: CSS layers are cumulative BY NAME, so two
different sheets both writing `@layer styled-ppx.atoms { ... }` still
contribute to the SAME one layer, but their relative position inside it
now depends on which sheet the browser parses first - exactly like
plain, unlayered CSS, and exactly the dependency this shape originally
exposed. `styled-ppx.global`'s own priority over `styled-ppx.atoms` is
UNAFFECTED - both layer names are fixed and always declared in this
order regardless of load order, same as round 7 already guaranteed;
only the position of one sheet's `atoms` rules relative to ANOTHER
sheet's is no longer fixed. Accepted, not fixed: closing this gap for
real needs one aggregated stylesheet (every input file passed to a
single `styled-ppx.generate` invocation, so `generate.ml`'s own
tier-ordering can see every rule at once), not something a
per-invocation fix can restore without giving back the round-7b
correctness fix.

The static sheet: its own `overflow-x: auto` plus its own narrowing
override.

  $ cat > static.ml <<EOF
  > [@@@css "._a_8r001shjd{overflow-x:auto;}"]
  > [@@@css "@media (min-width:1280px){._a_9xoverfl{overflow-x:initial;}}"]
  > EOF

  $ styled-ppx.generate static.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_8r001shjd{overflow-x:auto;}
  @media (min-width:1280px){._a_9xoverfl{overflow-x:initial;}}
  }

The toolkit sheet: the SAME base atom (independently re-minted - same
property, same context, same value - by a different library), no
override of its own.

  $ cat > toolkit.ml <<EOF
  > [@@@css "._a_8r001shjd{overflow-x:auto;}"]
  > EOF

  $ styled-ppx.generate toolkit.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_8r001shjd{overflow-x:auto;}
  }

Both outputs declare the IDENTICAL `@layer styled-ppx.global,
styled-ppx.atoms;` statement - neither sheet contributes anything to
`styled-ppx.global` here, so it is the `styled-ppx.atoms` name that is
exactly the problem now: what the browser does depends on which
`<link>` it loads first, since CSS accumulates same-named layers in
first-occurrence order. If the static sheet loads first, its own rules
(base then conditional) are followed by the toolkit sheet's rule, so the
static sheet's OWN `@media` override still beats its own base atom (each
sheet still orders its OWN tiers correctly - that part of the round-7b
fix holds per sheet), and the toolkit atom, being later than everything
static contributed, would even beat static's own `@media` override on
that shared property. If the toolkit sheet loads first instead, its
plain `overflow-x: auto` comes before all of static's rules, so static's
own `@media` override - now later than the toolkit atom too - wins.
Either way, ONE sheet's rule always ends up textually after the other's,
but WHICH one depends entirely on `<link>` order, a page-authoring
detail this aggregator has no visibility into. This is the accepted,
current behavior: a real, known limitation of ordering `base`/
`conditional` by per-invocation emission position instead of two
separate layer names - not a new bug, but a real trade against round 7's
cross-sheet guarantee for this one pair, made deliberately to fix round
7b's more common, same-sheet specificity regression instead.
