The two-stylesheet shape (`tableContainer`, monorepo report "Round 3
analysis"): the SAME `overflow-x: auto` atom is emitted by two different
generated stylesheets (the "static" sheet, which also narrows it under
`@media (min-width:1280px)`, and an unrelated "toolkit" sheet, which
doesn't). Each stylesheet comes from its OWN `styled-ppx.generate`
invocation - dune builds them separately, and a real page loads both
`<link>`s. In a real build, two DIFFERENT libraries never share an atom
class this way - `--namespace` salts each one's classes - so this shape
only arises for a native/Melange twin pair sharing one explicit
`--namespace`, or for two runs with no namespace at all; this fixture
uses hand-written `[@@@css ...]` rules directly, skipping the PPX, to
isolate `generate.ml`'s own behavior once two sheets DO share a class.

`base` and `conditional` (and `global`) are ordinary, unlayered rules,
each sheet ordering its OWN tiers by plain emission position, the same
as `tiers-slider.t` shows for one sheet alone. That ordering is per
STYLESHEET, not per page: two different `<link>`s just concatenate their
rule text on the page in load order, the same as any two plain CSS files
always have - so a tie between two DIFFERENT sheets' rules depends on
which `<link>` the browser loads first, exactly like plain CSS with no
tiers at all.

The static sheet: its own `overflow-x: auto` plus its own narrowing
override.

  $ cat > static.ml <<EOF
  > [@@@css "._a_8r001shjd{overflow-x:auto;}"]
  > [@@@css "@media (min-width:1280px){._a_9xoverfl{overflow-x:initial;}}"]
  > EOF

  $ styled-ppx.generate static.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_8r001shjd{overflow-x:auto;}
  @media (min-width:1280px){._a_9xoverfl{overflow-x:initial;}}

The toolkit sheet: the SAME base atom (independently re-minted - same
property, same context, same value - by a different library), no
override of its own.

  $ cat > toolkit.ml <<EOF
  > [@@@css "._a_8r001shjd{overflow-x:auto;}"]
  > EOF

  $ styled-ppx.generate toolkit.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_8r001shjd{overflow-x:auto;}

Neither output wraps anything in a layer, so what the browser does
depends entirely on which `<link>` it loads first, since the two sheets'
rules simply concatenate on the page in that order. If the static sheet
loads first, its own rules (base then conditional) are followed by the
toolkit sheet's rule, so the static sheet's OWN `@media` override still
beats its own base atom (each sheet orders its OWN tiers correctly), and
the toolkit atom, being later than everything static contributed, would
even beat static's own `@media` override on that shared property. If the
toolkit sheet loads first instead, its plain `overflow-x: auto` comes
before all of static's rules, so static's own `@media` override - now
later than the toolkit atom too - wins. Either way, ONE sheet's rule
always ends up textually after the other's, but WHICH one depends
entirely on `<link>` order, a page-authoring detail this aggregator has
no visibility into - the accepted, current limitation of ordering
`base`/`conditional` by per-invocation emission position instead of one
guarantee spanning every sheet on the page.
