The two-stylesheet shape (`tableContainer`, monorepo report "Round 3
analysis"): the SAME `overflow-x: auto` atom is emitted by two different
generated stylesheets (the "static" sheet, which also narrows it under
`@media (min-width:1280px)`, and an unrelated "toolkit" sheet, which
doesn't). Each stylesheet comes from its OWN `styled-ppx.generate`
invocation - dune builds them separately, and a real page loads both
`<link>`s. Without cascade tiers, whichever sheet's `<link>` the browser
loads LAST wins the tie on the shared `overflow-x: auto` rule against the
OTHER sheet's `@media` override, since both rules share one class's
specificity and only LOAD ORDER (a page-authoring detail, not a CSS
author's intent) decides between two different stylesheets' same-
specificity rules.

The static sheet: its own `overflow-x: auto` plus its own narrowing
override.

  $ cat > static.ml <<EOF
  > [@@@css "._a_8r001shjd{overflow-x:auto;}"]
  > [@@@css "@media (min-width:1280px){._a_9xoverfl{overflow-x:initial;}}"]
  > EOF

  $ styled-ppx.generate static.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_8r001shjd{overflow-x:auto;}
  }
  @layer styled-ppx.conditional {
  @media (min-width:1280px){._a_9xoverfl{overflow-x:initial;}}
  }

The toolkit sheet: the SAME base atom (independently re-minted - same
property, same context, same value - by a different library), no
override of its own.

  $ cat > toolkit.ml <<EOF
  > [@@@css "._a_8r001shjd{overflow-x:auto;}"]
  > EOF

  $ styled-ppx.generate toolkit.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_8r001shjd{overflow-x:auto;}
  }

Both outputs declare the IDENTICAL `@layer styled-ppx.base,
styled-ppx.conditional;` statement, in the same order, and the toolkit
sheet - having nothing to contribute to `styled-ppx.conditional` - emits
no block for it at all (an empty block would say nothing a bare
`@layer name;` statement doesn't already say - see `--layers`'s own
"no rule, no block" precedent). What the browser does now, and why: CSS
layer order is fixed by each layer's FIRST OCCURRENCE across every
stylesheet on the page, cumulatively, not per stylesheet - so whichever
of these two `<link>`s the browser loads first, `styled-ppx.base` is
created before `styled-ppx.conditional` exactly once, and every
`styled-ppx.base` rule from EITHER sheet outranks every
`styled-ppx.conditional` rule from EITHER sheet. The toolkit sheet's
`overflow-x: auto` (base) can no longer beat the static sheet's
`@media` override (conditional), regardless of which `<link>` tag comes
first in the page's `<head>`.
