One block sets `color` under two overlapping `@media (min-width: ...)`
conditions (both true at >=900px). The last one written must win at
>=900px: the earlier (600px) rule is rewritten to exclude the later
(900px) condition; the last rule is untouched.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css
    "@media (min-width: 600px) and (not (min-width: 900px)){._a_8eqd34e6zo5{color:red;}}"]
  [@@@css "@media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}"]
  [@@@css.bindings
    [("Output.block", "_id_ovbeuh", "_a_8eqd34e6zo5 _a_mp5mk4et4n8")]]
  let block =
    CSS.make "label:block _id_ovbeuh _a_8eqd34e6zo5 _a_mp5mk4et4n8" []
  let _ = block

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 600px) and (not (min-width: 900px)){._a_8eqd34e6zo5{color:red;}}
  @media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}
