Regression guard for the CSS custom-property hash collision in [%css] static
extraction (the /dashboard "header renders with no background" bug).

Two modules in different files share the *identical* interpolated
declaration `background-color: $(Color.Background.Alt.box)` under the same
`header` label, differing only in one sibling declaration (`display: flex`
vs `padding: 8px`).

Atomic CSS requires the invariant "one class name <=> one exact declaration
body". The class name is a pure hash of the declaration content
(`generate_class_from_content`), so both modules mint the same atom for the
shared declaration. The substituted `var(--...)` name must be a pure function
of that same content too (`class_and_namespace`, Css_file.re), NOT of the
binding's sibling declarations or label. Before the fix the var was hashed
from the sibling class-name join, so the two modules disagreed on the
variable baked into that identical atom -> a class/var mismatch.

  $ refmt --parse re --print ml a.re > a.ml
  $ standalone --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ standalone --impl b.ml -o b.ml

The background-color atom has the SAME class name in both modules AND the
same `var(--var-...)` target despite the differing sibling. These two lines
must stay byte-identical:

  $ grep -ho 'css-[0-9a-z]*-header{background-color:var(--var-[0-9a-z]*);}' a.ml b.ml
  [1]

Each module's runtime binding sets the same custom property:

  $ grep -ho '"--var-[0-9a-z]*"' a.ml b.ml
  [1]

Aggregating both modules into one stylesheet dedupes by the FULL rule text
(generate.ml:280). Because both modules now emit a byte-identical
`css-8rqac1-header` rule, dedup collapses them to one -> the selector appears
exactly once with the variable every `header` element actually sets. Before
the fix the two rules had different bodies, both survived, and the cascade
left one module's element referencing an undefined variable (missing
background).

  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-8rqac1-header{background-color:var(--box-11ifi3f);}
  .css-k008qs-header{display:flex;}
  .css-hpgf8j-header{padding:8px;}
