Cross-module [%css] selector interpolation: the PPX emits a sentinel-bearing
CSS rule plus a `[@@@css.refs ...]` descriptor and a synthetic `let _ = M.x`
dependency. The aggregator builds an index across both modules and resolves
the sentinel to `M.marker`'s identity class.

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

The post-PPX `n.ml` carries the unresolved sentinel as an opaque NUL-delimited
string in `[@@@css ...]`, plus a `[@@@css.refs ...]` attribute with the
location and a synthetic dep-tracking `let`.

  $ cat n.ml
  [@@@css ".a-393u2l{background:red;}"]
  [@@@css ".a-gnp5r39ddnj.\000M.marker\000{background:blue;}"]
  [@@@css.bindings [("N.container", "id-1ov2ckq", "a-393u2l a-gnp5r39ddnj")]]
  [@@@css.refs [("M.marker", "n.ml", 6, 6, 14)]]
  let _ = M.marker
  let container =
    CSS.make "label:container id-1ov2ckq a-393u2l a-gnp5r39ddnj" []

The aggregator resolves the sentinel against `M.marker`'s identity class.
`M.marker` is an empty `[%css {||}]`, so it has no atoms and emits no rule
of its own; the resolved selector carries only its identity class.

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-393u2l{background:red;}
  .a-gnp5r39ddnj.id-12qpfnx{background:blue;}
  }
