This test ensures the ppx generates minified CSS output when --minify flag is used

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-14ksm7b{color:blue;}.css-eaeacs{margin:10px;}.css-k008qs{display:flex;}.css-1tyndxa{justify-content:center;}.css-zcxndt{align-items:center;}.css-f5yfbg{background-color:red;}.css-v1pg77{padding:20px 15px;}.css-e42auv{border:1px solid black;}

