Two bindings, each with a single `@media (min-width: ...)` condition for
the same property, reaching one element (however they get composed - plain
concatenation, or `CSS.merge`, since a different `@media` condition is a
different context and `merge` never drops either side here). `q` (900px,
blue) is declared before `p` (600px, red) in the source, so if the sort
falls back to declaration order the sheet keeps `q` before `p` and, at
`>=900px`, `p` (textually last) wins - the wrong, position-dependent
result the sort's own width tie-break exists to remove: the sheet should
be ascending by width (`p` before `q`) regardless of declaration order, so
`q` (900px, wider, textually last) wins at `>=900px` instead.

The real PPX renders the prelude with a space after the colon
(`@media (min-width: 900px)`), unlike this package's own hand-written
`[@@@css "..."]` cram fixtures, which never have one - this test goes
through the real `refmt` -> ppx -> `styled-ppx.generate` pipeline instead
of a hand-written fixture, so it catches a width reader that only handles
the no-space spelling.

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css "@media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}"]
  [@@@css "@media (min-width: 600px) {._a_izob04e698n{color:red;}}"]
  [@@@css.bindings
    [("Input.q", "_id_f1usid", "_a_mp5mk4et4n8");
    ("Input.p", "_id_1hp88j8", "_a_izob04e698n")]]
  let q = CSS.make "label:q _id_f1usid _a_mp5mk4et4n8" []
  let p = CSS.make "label:p _id_1hp88j8 _a_izob04e698n" []
  let _ = (p, q)

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 600px) {._a_izob04e698n{color:red;}}
  @media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}
