  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --output=./$TEST_OUTPUT/generated
  $ refmt --parse ml --print re output.ml
  let css = main =>
    CSS.make(
      "css-3tpy8b css-1uzc9um css-17vxl0k css-1lr2y8",
      [
        ("--var-19ja411", CSS.get_value_from_rule(CSS.color(main))),
        (
          "--var-1xt8d8f",
          CSS.get_value_from_rule(CSS.backgroundColor(CSS.black)),
        ),
      ],
    );
  <div className={css(CSS.red)} />;

Show the generated CSS file:
  $ cat generated/styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  
  .css-3tpy8b { color: var(--var-19ja411); }
  .css-1uzc9um { background-color: var(--var-1xt8d8f); }
  .css-17vxl0k { display: flex; }
  .css-1lr2y8 .lola { display: flex; }
  

  $ rm input.re

  $ cat > input.re << 'EOF'
  > let styles = main => [%cx
  >   {|
  >   color: $(main);
  >   background-color: $(CSS.black);
  >   display: flex;
  > |}
  > ];
  > 
  > <div className={styles(CSS.red)} />;
  > EOF

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --debug
  [styled-ppx] No CSS content to generate
  $ refmt --parse ml --print re output.ml
  let styles = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
    |]);
  <div className={styles(CSS.red)} />;

Test 2: Add new rule - file should be updated:
  $ cat > input.re << 'EOF'
  > let styles = main => [%cx
  >   {|
  >   color: $(main);
  >   background-color: $(CSS.black);
  >   display: flex;
  >   padding: 10px;
  > |}
  > ];
  > 
  > <div className={styles(CSS.red)} />;
  > EOF
  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --debug --output=./generated
  [styled-ppx] No CSS content to generate
  $ refmt --parse ml --print re output.ml
  let styles = main =>
    CSS.style([|
      (CSS.color(main): CSS.rule),
      CSS.backgroundColor(CSS.black),
      CSS.display(`flex),
      CSS.padding(`pxFloat(10.)),
    |]);
  <div className={styles(CSS.red)} />;

  $ cat generated/styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  
  .css-3tpy8b { color: var(--var-19ja411); }
  .css-1uzc9um { background-color: var(--var-1xt8d8f); }
  .css-17vxl0k { display: flex; }
  .css-1lr2y8 .lola { display: flex; }
  
