A cross-module selector reference (`$(Shared.row)`) names one specific
binding by its fully-qualified path, unlike a local `$(row)` reference,
which can mean a different binding in every file that uses it. Two
DIFFERENT files (N1, N2) that both reference the SAME `Shared.row` with the
identical selector shape must still dedup to one shared atom class - the
selector-resolution fix that gives ambiguous local references different
classes must not stop this unambiguous, genuinely-shared reference from
deduping.

  $ refmt --parse re --print ml shared.re > shared.ml
  $ ../../standalone.exe --impl shared.ml -o shared.ml
  $ refmt --parse re --print ml n1.re > n1.ml
  $ ../../standalone.exe --impl n1.ml -o n1.ml
  $ refmt --parse re --print ml n2.re > n2.ml
  $ ../../standalone.exe --impl n2.ml -o n2.ml

  $ cat n1.ml
  [@@@css
    ".a-9nd225rj253 > div:not(:last-child).\000Shared.row\000{display:flex;}"]
  [@@@css.bindings [("N1.list", "id-16l4e1q", "a-9nd225rj253")]]
  [@@@css.refs [("Shared.row", "n1.ml", 1, 45, 55)]]
  let _ = Shared.row
  let list = CSS.make "label:list id-16l4e1q a-9nd225rj253" []

  $ cat n2.ml
  [@@@css
    ".a-9nd225rj253 > div:not(:last-child).\000Shared.row\000{display:flex;}"]
  [@@@css.bindings [("N2.list", "id-j3g9qa", "a-9nd225rj253")]]
  [@@@css.refs [("Shared.row", "n2.ml", 1, 45, 55)]]
  let _ = Shared.row
  let list = CSS.make "label:list id-j3g9qa a-9nd225rj253" []

  $ styled-ppx.generate shared.ml n1.ml n2.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .a-4ekvmb{color:red;}
  .a-9nd225rj253 > div:not(:last-child).id-1kc5rqd{display:flex;}
