CssJs.backgroundRepeat(`space);
CssJs.backgroundRepeat(`round);
CssJs.backgroundRepeat(`hv((`repeat, `repeat)));
CssJs.backgroundRepeat(`hv((`space, `repeat)));
CssJs.backgroundRepeat(`hv((`round, `repeat)));
CssJs.backgroundRepeat(`hv((`noRepeat, `repeat)));
CssJs.backgroundRepeat(`hv((`repeat, `space)));
CssJs.backgroundRepeat(`hv((`space, `space)));
CssJs.backgroundRepeat(`hv((`round, `space)));
CssJs.backgroundRepeat(`hv((`noRepeat, `space)));
CssJs.backgroundRepeat(`hv((`repeat, `round)));
CssJs.backgroundRepeat(`hv((`space, `round)));
CssJs.backgroundRepeat(`hv((`round, `round)));
CssJs.backgroundRepeat(`hv((`noRepeat, `round)));
CssJs.backgroundRepeat(`hv((`repeat, `noRepeat)));
CssJs.backgroundRepeat(`hv((`space, `noRepeat)));
CssJs.backgroundRepeat(`hv((`round, `noRepeat)));
CssJs.backgroundRepeat(`hv((`noRepeat, `noRepeat)));
CssJs.backgroundAttachment(`local);
CssJs.backgroundPosition(
  `hv((`hv((`center, `pxFloat(20.))), `hv((`center, `pxFloat(10.))))),
);
CssJs.backgroundPosition(`hv((`center, `hv((`center, `pxFloat(10.))))));
CssJs.backgroundPosition(`hv((`hv((`center, `pxFloat(10.))), `center)));
CssJs.backgroundClip(`borderBox);
CssJs.backgroundClip(`padding_box);
CssJs.backgroundClip(`contentBox);
CssJs.backgroundOrigin(`borderBox);
CssJs.backgroundOrigin(`padding_box);
CssJs.backgroundOrigin(`contentBox);
CssJs.backgroundSize(`auto);
CssJs.backgroundSize(`cover);
CssJs.backgroundSize(`contain);
CssJs.unsafe("backgroundSize", "10px");
CssJs.unsafe("backgroundSize", "50%");
CssJs.unsafe("backgroundSize", "10px auto");
CssJs.unsafe("backgroundSize", "auto 10%");
CssJs.backgroundSize(`size((`em(50.), `percent(50.))));
CssJs.unsafe("background", "url(foo.png), url(bar.svg)");
CssJs.unsafe("background", "top left / 50% 60%");
CssJs.origin(`borderBox);
CssJs.backgroundColor(CssJs.blue);
CssJs.backgroundColor(CssJs.red);
CssJs.backgroundRepeat(`fixed);
CssJs.clip(`padding_box);
CssJs.unsafe(
  "background",
  "url(foo.png) bottom right / cover padding-box content-box",
);
CssJs.borderTopLeftRadius(`zero);
CssJs.borderTopLeftRadius(`percent(50.));
CssJs.unsafe("borderTopLeftRadius", "250px 100px");
CssJs.borderTopRightRadius(`zero);
CssJs.borderTopRightRadius(`percent(50.));
CssJs.unsafe("borderTopRightRadius", "250px 100px");
CssJs.borderBottomRightRadius(`zero);
CssJs.borderBottomRightRadius(`percent(50.));
CssJs.unsafe("borderBottomRightRadius", "250px 100px");
CssJs.borderBottomLeftRadius(`zero);
CssJs.borderBottomLeftRadius(`percent(50.));
CssJs.unsafe("borderBottomLeftRadius", "250px 100px");
CssJs.borderRadius(`pxFloat(10.));
CssJs.borderRadius(`percent(50.));
CssJs.unsafe("borderImageSource", "none");
CssJs.unsafe("borderImageSource", "url(foo.png)");
CssJs.unsafe("borderImageSlice", "10");
CssJs.unsafe("borderImageSlice", "30%");
CssJs.unsafe("borderImageSlice", "10 10");
CssJs.unsafe("borderImageSlice", "30% 10");
CssJs.unsafe("borderImageSlice", "10 30%");
CssJs.unsafe("borderImageSlice", "30% 30%");
CssJs.unsafe("borderImageSlice", "10 10 10");
CssJs.unsafe("borderImageSlice", "30% 10 10");
CssJs.unsafe("borderImageSlice", "10 30% 10");
CssJs.unsafe("borderImageSlice", "30% 30% 10");
CssJs.unsafe("borderImageSlice", "10 10 30%");
CssJs.unsafe("borderImageSlice", "30% 10 30%");
CssJs.unsafe("borderImageSlice", "10 30% 30%");
CssJs.unsafe("borderImageSlice", "30% 30% 30%");
CssJs.unsafe("borderImageSlice", "10 10 10 10");
CssJs.unsafe("borderImageSlice", "30% 10 10 10");
CssJs.unsafe("borderImageSlice", "10 30% 10 10");
CssJs.unsafe("borderImageSlice", "30% 30% 10 10");
CssJs.unsafe("borderImageSlice", "10 10 30% 10");
CssJs.unsafe("borderImageSlice", "30% 10 30% 10");
CssJs.unsafe("borderImageSlice", "10 30% 30% 10");
CssJs.unsafe("borderImageSlice", "30% 30% 30% 10");
CssJs.unsafe("borderImageSlice", "10 10 10 30%");
CssJs.unsafe("borderImageSlice", "30% 10 10 30%");
CssJs.unsafe("borderImageSlice", "10 30% 10 30%");
CssJs.unsafe("borderImageSlice", "30% 30% 10 30%");
CssJs.unsafe("borderImageSlice", "10 10 30% 30%");
CssJs.unsafe("borderImageSlice", "30% 10 30% 30%");
CssJs.unsafe("borderImageSlice", "10 30% 30% 30%");
CssJs.unsafe("borderImageSlice", "30% 30% 30% 30%");
CssJs.unsafe("borderImageSlice", "fill 30%");
CssJs.unsafe("borderImageSlice", "fill 10");
CssJs.unsafe("borderImageSlice", "fill 2 4 8% 16%");
CssJs.unsafe("borderImageSlice", "30% fill");
CssJs.unsafe("borderImageSlice", "10 fill");
CssJs.unsafe("borderImageSlice", "2 4 8% 16% fill");
CssJs.unsafe("borderImageWidth", "10px");
CssJs.unsafe("borderImageWidth", "5%");
CssJs.unsafe("borderImageWidth", "28");
CssJs.unsafe("borderImageWidth", "auto");
CssJs.unsafe("borderImageWidth", "10px 10px");
CssJs.unsafe("borderImageWidth", "5% 10px");
CssJs.unsafe("borderImageWidth", "28 10px");
CssJs.unsafe("borderImageWidth", "auto 10px");
CssJs.unsafe("borderImageWidth", "10px 5%");
CssJs.unsafe("borderImageWidth", "5% 5%");
CssJs.unsafe("borderImageWidth", "28 5%");
CssJs.unsafe("borderImageWidth", "auto 5%");
CssJs.unsafe("borderImageWidth", "10px 28");
CssJs.unsafe("borderImageWidth", "5% 28");
CssJs.unsafe("borderImageWidth", "28 28");
CssJs.unsafe("borderImageWidth", "auto 28");
CssJs.unsafe("borderImageWidth", "10px auto");
CssJs.unsafe("borderImageWidth", "5% auto");
CssJs.unsafe("borderImageWidth", "28 auto");
CssJs.unsafe("borderImageWidth", "auto auto");
CssJs.unsafe("borderImageWidth", "10px 10% 10");
CssJs.unsafe("borderImageWidth", "5% 10px 20 auto");
CssJs.unsafe("borderImageOutset", "10px");
CssJs.unsafe("borderImageOutset", "20");
CssJs.unsafe("borderImageOutset", "10px 20");
CssJs.unsafe("borderImageOutset", "10px 20px");
CssJs.unsafe("borderImageOutset", "20 30");
CssJs.unsafe("borderImageOutset", "2px 3px 4");
CssJs.unsafe("borderImageOutset", "1 2px 3px 4");
CssJs.unsafe("borderImageRepeat", "stretch");
CssJs.unsafe("borderImageRepeat", "repeat");
CssJs.unsafe("borderImageRepeat", "round");
CssJs.unsafe("borderImageRepeat", "space");
CssJs.unsafe("borderImageRepeat", "stretch stretch");
CssJs.unsafe("borderImageRepeat", "repeat stretch");
CssJs.unsafe("borderImageRepeat", "round stretch");
CssJs.unsafe("borderImageRepeat", "space stretch");
CssJs.unsafe("borderImageRepeat", "stretch repeat");
CssJs.unsafe("borderImageRepeat", "repeat repeat");
CssJs.unsafe("borderImageRepeat", "round repeat");
CssJs.unsafe("borderImageRepeat", "space repeat");
CssJs.unsafe("borderImageRepeat", "stretch round");
CssJs.unsafe("borderImageRepeat", "repeat round");
CssJs.unsafe("borderImageRepeat", "round round");
CssJs.unsafe("borderImageRepeat", "space round");
CssJs.unsafe("borderImageRepeat", "stretch space");
CssJs.unsafe("borderImageRepeat", "repeat space");
CssJs.unsafe("borderImageRepeat", "round space");
CssJs.unsafe("borderImageRepeat", "space space");
CssJs.unsafe("borderImage", "url(foo.png) 10");
CssJs.unsafe("borderImage", "url(foo.png) 10%");
CssJs.unsafe("borderImage", "url(foo.png) 10% fill");
CssJs.unsafe("borderImage", "url(foo.png) 10 round");
CssJs.unsafe("borderImage", "url(foo.png) 10 stretch repeat");
CssJs.unsafe("borderImage", "url(foo.png) 10 / 10px");
CssJs.unsafe("borderImage", "url(foo.png) 10 / 10% / 10px");
CssJs.unsafe("borderImage", "url(foo.png) fill 10 / 10% / 10px");
CssJs.unsafe("borderImage", "url(foo.png) fill 10 / 10% / 10px space");
CssJs.boxShadows([|
  CssJs.Shadow.box(
    ~x=`pxFloat(1.),
    ~y=`pxFloat(2.),
    ~blur=`pxFloat(3.),
    ~spread=`pxFloat(4.),
    CssJs.black,
  ),
|]);
CssJs.boxShadows([|
  CssJs.Shadow.box(
    ~x=`pxFloat(1.),
    ~y=`pxFloat(2.),
    ~blur=`pxFloat(3.),
    ~spread=`pxFloat(4.),
    ~inset=true,
    CssJs.black,
  ),
|]);
CssJs.boxShadows([|
  CssJs.Shadow.box(
    ~x=`pxFloat(1.),
    ~y=`pxFloat(2.),
    ~blur=`pxFloat(3.),
    ~spread=`pxFloat(4.),
    ~inset=true,
    CssJs.black,
  ),
  CssJs.Shadow.box(
    ~x=`pxFloat(1.),
    ~y=`pxFloat(2.),
    ~blur=`pxFloat(3.),
    ~spread=`pxFloat(4.),
    CssJs.black,
  ),
|]);
CssJs.unsafe("backgroundPositionX", "right");
CssJs.unsafe("backgroundPositionX", "center");
CssJs.unsafe("backgroundPositionX", "50%");
CssJs.unsafe("backgroundPositionX", "left, left");
CssJs.unsafe("backgroundPositionX", "left, right");
CssJs.unsafe("backgroundPositionX", "right, left");
CssJs.unsafe("backgroundPositionX", "left, 0%");
CssJs.unsafe("backgroundPositionX", "10%, 20%, 40%");
CssJs.unsafe("backgroundPositionX", "0px");
CssJs.unsafe("backgroundPositionX", "30px");
CssJs.unsafe("backgroundPositionX", "0%, 10%, 20%, 30%");
CssJs.unsafe("backgroundPositionX", "left, left, left, left, left");
CssJs.unsafe("backgroundPositionX", "right 20px");
CssJs.unsafe("backgroundPositionX", "left 20px");
CssJs.unsafe("backgroundPositionX", "right -50px");
CssJs.unsafe("backgroundPositionX", "left -50px");
CssJs.unsafe("backgroundPositionX", "right 20px");
CssJs.unsafe("backgroundPositionY", "bottom");
CssJs.unsafe("backgroundPositionY", "center");
CssJs.unsafe("backgroundPositionY", "50%");
CssJs.unsafe("backgroundPositionY", "top, top");
CssJs.unsafe("backgroundPositionY", "top, bottom");
CssJs.unsafe("backgroundPositionY", "bottom, top");
CssJs.unsafe("backgroundPositionY", "top, 0%");
CssJs.unsafe("backgroundPositionY", "10%, 20%, 40%");
CssJs.unsafe("backgroundPositionY", "0px");
CssJs.unsafe("backgroundPositionY", "30px");
CssJs.unsafe("backgroundPositionY", "0%, 10%, 20%, 30%");
CssJs.unsafe("backgroundPositionY", "top, top, top, top, top");
CssJs.unsafe("backgroundPositionY", "bottom 20px");
CssJs.unsafe("backgroundPositionY", "top 20px");
CssJs.unsafe("backgroundPositionY", "bottom -50px");
CssJs.unsafe("backgroundPositionY", "top -50px");
CssJs.unsafe("backgroundPositionY", "bottom 20px");
CssJs.boxSizing(`borderBox);
CssJs.boxSizing(`contentBox);
CssJs.unsafe("outlineStyle", "auto");
CssJs.unsafe("outlineOffset", "-5px");
CssJs.unsafe("outlineOffset", "0");
CssJs.unsafe("outlineOffset", "5px");
CssJs.unsafe("resize", "none");
CssJs.unsafe("resize", "both");
CssJs.unsafe("resize", "horizontal");
CssJs.unsafe("resize", "vertical");
CssJs.unsafe("textOverflow", "clip");
CssJs.unsafe("textOverflow", "ellipsis");
CssJs.unsafe("cursor", "url(foo.png) 2 2, auto");
CssJs.unsafe("cursor", "default");
CssJs.unsafe("cursor", "none");
CssJs.unsafe("cursor", "context-menu");
CssJs.unsafe("cursor", "cell");
CssJs.unsafe("cursor", "vertical-text");
CssJs.unsafe("cursor", "alias");
CssJs.unsafe("cursor", "copy");
CssJs.unsafe("cursor", "no-drop");
CssJs.unsafe("cursor", "not-allowed");
CssJs.unsafe("cursor", "grab");
CssJs.unsafe("cursor", "grabbing");
CssJs.unsafe("cursor", "ew-resize");
CssJs.unsafe("cursor", "ns-resize");
CssJs.unsafe("cursor", "nesw-resize");
CssJs.unsafe("cursor", "nwse-resize");
CssJs.unsafe("cursor", "col-resize");
CssJs.unsafe("cursor", "row-resize");
CssJs.unsafe("cursor", "all-scroll");
CssJs.unsafe("cursor", "zoom-in");
CssJs.unsafe("cursor", "zoom-out");
CssJs.unsafe("caretColor", "auto");
CssJs.unsafe("caretColor", "green");
CssJs.unsafe("appearance", "auto");
CssJs.unsafe("appearance", "none");
CssJs.unsafe("textOverflow", "clip");
CssJs.unsafe("textOverflow", "ellipsis");
CssJs.unsafe("textOverflow", "'foo'");
CssJs.unsafe("textOverflow", "clip clip");
CssJs.unsafe("textOverflow", "ellipsis clip");
CssJs.unsafe("userSelect", "auto");
CssJs.unsafe("userSelect", "text");
CssJs.unsafe("userSelect", "none");
CssJs.unsafe("userSelect", "contain");
CssJs.unsafe("userSelect", "all");
CssJs.unsafe("transitionProperty", "none");
CssJs.unsafe("transitionProperty", "all");
CssJs.unsafe("transitionProperty", "width");
CssJs.unsafe("transitionProperty", "width, height");
CssJs.unsafe("transitionDuration", "0s");
CssJs.unsafe("transitionDuration", "1s");
CssJs.unsafe("transitionDuration", "100ms");
CssJs.unsafe("transitionTimingFunction", "ease");
CssJs.unsafe("transitionTimingFunction", "linear");
CssJs.unsafe("transitionTimingFunction", "ease-in");
CssJs.unsafe("transitionTimingFunction", "ease-out");
CssJs.unsafe("transitionTimingFunction", "ease-in-out");
CssJs.unsafe("transitionTimingFunction", "cubic-bezier(.5, .5, .5, .5)");
CssJs.unsafe("transitionTimingFunction", "cubic-bezier(.5, 1.5, .5, -2.5)");
CssJs.unsafe("transitionTimingFunction", "step-start");
CssJs.unsafe("transitionTimingFunction", "step-end");
CssJs.unsafe("transitionTimingFunction", "steps(3, start)");
CssJs.unsafe("transitionTimingFunction", "steps(5, end)");
CssJs.unsafe("transitionDelay", "1s");
CssJs.unsafe("transitionDelay", "-1s");
CssJs.unsafe("transition", "1s 2s width linear");
CssJs.unsafe("transitionTimingFunction", "steps(2, jump-start)");
CssJs.unsafe("transitionTimingFunction", "steps(2, jump-end)");
CssJs.unsafe("transitionTimingFunction", "steps(1, jump-both)");
CssJs.unsafe("transitionTimingFunction", "steps(2, jump-none)");
CssJs.unsafe("animationName", "foo");
CssJs.unsafe("animationName", "foo, bar");
CssJs.unsafe("animationDuration", "0s");
CssJs.unsafe("animationDuration", "1s");
CssJs.unsafe("animationDuration", "100ms");
CssJs.unsafe("animationTimingFunction", "ease");
CssJs.unsafe("animationTimingFunction", "linear");
CssJs.unsafe("animationTimingFunction", "ease-in");
CssJs.unsafe("animationTimingFunction", "ease-out");
CssJs.unsafe("animationTimingFunction", "ease-in-out");
CssJs.unsafe("animationTimingFunction", "cubic-bezier(.5, .5, .5, .5)");
CssJs.unsafe("animationTimingFunction", "cubic-bezier(.5, 1.5, .5, -2.5)");
CssJs.unsafe("animationTimingFunction", "step-start");
CssJs.unsafe("animationTimingFunction", "step-end");
CssJs.unsafe("animationTimingFunction", "steps(3, start)");
CssJs.unsafe("animationTimingFunction", "steps(5, end)");
CssJs.unsafe("animationIterationCount", "infinite");
CssJs.unsafe("animationIterationCount", "8");
CssJs.unsafe("animationIterationCount", "4.35");
CssJs.unsafe("animationDirection", "normal");
CssJs.unsafe("animationDirection", "alternate");
CssJs.unsafe("animationDirection", "reverse");
CssJs.unsafe("animationDirection", "alternate-reverse");
CssJs.unsafe("animationPlayState", "running");
CssJs.unsafe("animationPlayState", "paused");
CssJs.unsafe("animationDelay", "1s");
CssJs.unsafe("animationDelay", "-1s");
CssJs.unsafe("animationFillMode", "none");
CssJs.unsafe("animationFillMode", "forwards");
CssJs.unsafe("animationFillMode", "backwards");
CssJs.unsafe("animationFillMode", "both");
CssJs.unsafe("animation", "foo 1s 2s infinite linear alternate both");
CssJs.transform(`none);
CssJs.transform(CssJs.translate(`pxFloat(5.), 0));
CssJs.transform(CssJs.translate(`pxFloat(5.), `pxFloat(10.)));
CssJs.transform(CssJs.translateY(`pxFloat(5.)));
CssJs.transform(CssJs.translateX(`pxFloat(5.)));
CssJs.transform(CssJs.translateY(`percent(5.)));
CssJs.transform(CssJs.translateX(`percent(5.)));
CssJs.transform(CssJs.scale(2., 2.));
CssJs.transform(CssJs.scale(2., -1.));
CssJs.transform(CssJs.scaleX(2.));
CssJs.transform(CssJs.scaleY(2.5));
CssJs.transform(CssJs.rotate(`deg(45.)));
CssJs.transform(CssJs.skew(`deg(45.), 0));
CssJs.transform(CssJs.skew(`deg(45.), `deg(15.)));
CssJs.transform(CssJs.skewX(`deg(45.)));
CssJs.transform(CssJs.skewY(`deg(45.)));
CssJs.transforms([|
  CssJs.translate(`pxFloat(50.), `pxFloat(-24.)),
  CssJs.skew(`deg(0.), `deg(22.5)),
|]);
CssJs.transform(CssJs.translate3d(`zero, `zero, `pxFloat(5.)));
CssJs.transform(CssJs.translateZ(`pxFloat(5.)));
CssJs.transform(CssJs.scale3d(1., 0., -1.));
CssJs.transform(CssJs.scaleZ(1.5));
CssJs.transform(CssJs.rotate3d(1., 1., 1., `deg(45.)));
CssJs.transform(CssJs.rotateX(`deg(-45.)));
CssJs.transform(CssJs.rotateY(`deg(-45.)));
CssJs.transform(CssJs.rotateZ(`deg(-45.)));
CssJs.transforms([|
  CssJs.translate3d(`pxFloat(50.), `pxFloat(-24.), `pxFloat(5.)),
  CssJs.rotate3d(1., 2., 3., `deg(180.)),
  CssJs.scale3d(-1., 0., 0.5),
|]);
CssJs.unsafe("transform", "perspective(600px)");
CssJs.unsafe("transformOrigin", "10px");
CssJs.unsafe("transformOrigin", "top");
CssJs.unsafe("transformOrigin", "top left");
CssJs.unsafe("transformOrigin", "50% 100%");
CssJs.unsafe("transformOrigin", "left 0%");
CssJs.unsafe("transformOrigin", "left 50% 0");
CssJs.unsafe("transformBox", "border-box");
CssJs.unsafe("transformBox", "fill-box");
CssJs.unsafe("transformBox", "view-box");
CssJs.unsafe("translate", "none");
CssJs.unsafe("translate", "50%");
CssJs.unsafe("translate", "50% 50%");
CssJs.unsafe("translate", "50% 50% 10px");
CssJs.unsafe("scale", "none");
CssJs.unsafe("scale", "2");
CssJs.unsafe("scale", "2 2");
CssJs.unsafe("scale", "2 2 2");
CssJs.unsafe("rotate", "none");
CssJs.unsafe("rotate", "45deg");
CssJs.unsafe("rotate", "x 45deg");
CssJs.unsafe("rotate", "y 45deg");
CssJs.unsafe("rotate", "z 45deg");
CssJs.unsafe("rotate", "-1 0 2 45deg");
CssJs.unsafe("rotate", "45deg x");
CssJs.unsafe("rotate", "45deg y");
CssJs.unsafe("rotate", "45deg z");
CssJs.unsafe("rotate", "45deg -1 0 2");
CssJs.unsafe("transformStyle", "flat");
CssJs.unsafe("transformStyle", "preserve-3d");
CssJs.unsafe("perspective", "none");
CssJs.unsafe("perspective", "600px");
CssJs.unsafe("perspectiveOrigin", "10px");
CssJs.unsafe("perspectiveOrigin", "top");
CssJs.unsafe("perspectiveOrigin", "top left");
CssJs.unsafe("perspectiveOrigin", "50% 100%");
CssJs.unsafe("perspectiveOrigin", "left 0%");
CssJs.unsafe("backfaceVisibility", "visible");
CssJs.unsafe("backfaceVisibility", "hidden");
CssJs.unsafe("offset", "none");
CssJs.unsafe("offset", "auto");
CssJs.unsafe("offset", "center");
CssJs.unsafe("offset", "200px 100px");
CssJs.unsafe("offset", "margin-box");
CssJs.unsafe("offset", "border-box");
CssJs.unsafe("offset", "padding-box");
CssJs.unsafe("offset", "content-box");
CssJs.unsafe("offset", "fill-box");
CssJs.unsafe("offset", "stroke-box");
CssJs.unsafe("offset", "view-box");
CssJs.unsafe("offset", "path('M 20 20 H 80 V 30')");
CssJs.unsafe("offset", "url(image.png)");
CssJs.unsafe("textTransform", "full-width");
CssJs.unsafe("textTransform", "full-size-kana");
CssJs.unsafe("tabSize", "4");
CssJs.unsafe("tabSize", "1em");
CssJs.unsafe("lineBreak", "auto");
CssJs.unsafe("lineBreak", "loose");
CssJs.unsafe("lineBreak", "normal");
CssJs.unsafe("lineBreak", "strict");
CssJs.unsafe("lineBreak", "anywhere");
CssJs.wordBreak(`normal);
CssJs.wordBreak(`keepAll);
CssJs.wordBreak(`breakAll);
CssJs.whiteSpace(`breakSpaces);
CssJs.unsafe("hyphens", "auto");
CssJs.unsafe("hyphens", "manual");
CssJs.unsafe("hyphens", "none");
CssJs.overflowWrap(`normal);
CssJs.unsafe("overflowWrap", "break-word");
CssJs.overflowWrap(`anywhere);
CssJs.wordWrap(`normal);
CssJs.unsafe("wordWrap", "break-word");
CssJs.wordWrap(`anywhere);
CssJs.textAlign(`start);
CssJs.textAlign(`end_);
CssJs.textAlign(`left);
CssJs.textAlign(`right);
CssJs.textAlign(`center);
CssJs.textAlign(`justify);
CssJs.unsafe("textAlign", "match-parent");
CssJs.unsafe("textJustify", "auto");
CssJs.unsafe("textJustify", "none");
CssJs.unsafe("textJustify", "inter-word");
CssJs.unsafe("textJustify", "inter-character");
CssJs.wordSpacing(`percent(50.));
CssJs.unsafe("textIndent", "1em hanging");
CssJs.unsafe("textIndent", "1em each-line");
CssJs.unsafe("textIndent", "1em hanging each-line");
CssJs.unsafe("hangingPunctuation", "none");
CssJs.unsafe("hangingPunctuation", "first");
CssJs.unsafe("hangingPunctuation", "last");
CssJs.unsafe("hangingPunctuation", "force-end");
CssJs.unsafe("hangingPunctuation", "allow-end");
CssJs.unsafe("hangingPunctuation", "first last");
CssJs.unsafe("hangingPunctuation", "first force-end");
CssJs.unsafe("hangingPunctuation", "first force-end last");
CssJs.unsafe("hangingPunctuation", "first allow-end last");
CssJs.unsafe("textDecoration", "underline dotted green");
CssJs.unsafe("textDecorationLine", "none");
CssJs.unsafe("textDecorationLine", "underline");
CssJs.unsafe("textDecorationLine", "overline");
CssJs.unsafe("textDecorationLine", "line-through");
CssJs.unsafe("textDecorationLine", "underline overline");
CssJs.textDecorationColor(CssJs.white);
CssJs.unsafe("textDecorationStyle", "solid");
CssJs.unsafe("textDecorationStyle", "double");
CssJs.unsafe("textDecorationStyle", "dotted");
CssJs.unsafe("textDecorationStyle", "dashed");
CssJs.unsafe("textDecorationStyle", "wavy");
CssJs.unsafe("textUnderlinePosition", "auto");
CssJs.unsafe("textUnderlinePosition", "under");
CssJs.unsafe("textUnderlinePosition", "left");
CssJs.unsafe("textUnderlinePosition", "right");
CssJs.unsafe("textUnderlinePosition", "under left");
CssJs.unsafe("textUnderlinePosition", "under right");
CssJs.unsafe("textEmphasisStyle", "none");
CssJs.unsafe("textEmphasisStyle", "filled");
CssJs.unsafe("textEmphasisStyle", "open");
CssJs.unsafe("textEmphasisStyle", "dot");
CssJs.unsafe("textEmphasisStyle", "circle");
CssJs.unsafe("textEmphasisStyle", "double-circle");
CssJs.unsafe("textEmphasisStyle", "triangle");
CssJs.unsafe("textEmphasisStyle", "sesame");
CssJs.unsafe("textEmphasisStyle", "open dot");
CssJs.unsafe("textEmphasisStyle", "'foo'");
CssJs.unsafe("textEmphasisColor", "green");
CssJs.unsafe("textEmphasis", "open dot green");
CssJs.unsafe("textEmphasisPosition", "over left");
CssJs.unsafe("textEmphasisPosition", "over right");
CssJs.unsafe("textEmphasisPosition", "under left");
CssJs.unsafe("textEmphasisPosition", "under right");
CssJs.unsafe("textShadow", "none");
CssJs.unsafe("textShadow", "1px 2px 3px black");
CssJs.unsafe("textDecoration", "underline solid blue 1px");
CssJs.unsafe("textDecorationSkip", "none");
CssJs.unsafe("textDecorationSkip", "objects");
CssJs.unsafe("textDecorationSkip", "objects spaces");
CssJs.unsafe("textDecorationSkip", "objects leading-spaces");
CssJs.unsafe("textDecorationSkip", "objects trailing-spaces");
CssJs.unsafe("textDecorationSkip", "objects leading-spaces trailing-spaces");
CssJs.unsafe(
  "textDecorationSkip",
  "objects leading-spaces trailing-spaces edges",
);
CssJs.unsafe(
  "textDecorationSkip",
  "objects leading-spaces trailing-spaces edges box-decoration",
);
CssJs.unsafe("textDecorationSkip", "objects edges");
CssJs.unsafe("textDecorationSkip", "objects box-decoration");
CssJs.unsafe("textDecorationSkip", "spaces");
CssJs.unsafe("textDecorationSkip", "spaces edges");
CssJs.unsafe("textDecorationSkip", "spaces edges box-decoration");
CssJs.unsafe("textDecorationSkip", "spaces box-decoration");
CssJs.unsafe("textDecorationSkip", "leading-spaces");
CssJs.unsafe("textDecorationSkip", "leading-spaces trailing-spaces edges");
CssJs.unsafe(
  "textDecorationSkip",
  "leading-spaces trailing-spaces edges box-decoration",
);
CssJs.unsafe("textDecorationSkip", "edges");
CssJs.unsafe("textDecorationSkip", "edges box-decoration");
CssJs.unsafe("textDecorationSkip", "box-decoration");
CssJs.unsafe("textDecorationSkipInk", "none");
CssJs.unsafe("textDecorationSkipInk", "auto");
CssJs.unsafe("textUnderlineOffset", "auto");
CssJs.unsafe("textUnderlineOffset", "3px");
CssJs.unsafe("textUnderlineOffset", "10%");
CssJs.unsafe("textDecorationThickness", "auto");
CssJs.unsafe("textDecorationThickness", "from-font");
CssJs.unsafe("textDecorationThickness", "3px");
CssJs.unsafe("textDecorationThickness", "10%");
CssJs.unsafe("quotes", "auto");
CssJs.unsafe("content", "url(./img/star.png) / \"New!\"");
CssJs.unsafe("content", "\"\\25BA\" / \"\"");
CssJs.unsafe("fontStretch", "normal");
CssJs.unsafe("fontStretch", "ultra-condensed");
CssJs.unsafe("fontStretch", "extra-condensed");
CssJs.unsafe("fontStretch", "condensed");
CssJs.unsafe("fontStretch", "semi-condensed");
CssJs.unsafe("fontStretch", "semi-expanded");
CssJs.unsafe("fontStretch", "expanded");
CssJs.unsafe("fontStretch", "extra-expanded");
CssJs.unsafe("fontStretch", "ultra-expanded");
CssJs.unsafe("fontSizeAdjust", "none");
CssJs.unsafe("fontSizeAdjust", ".5");
CssJs.unsafe("fontSynthesis", "none");
CssJs.unsafe("fontSynthesis", "weight");
CssJs.unsafe("fontSynthesis", "style");
CssJs.unsafe("fontSynthesis", "weight style");
CssJs.unsafe("fontSynthesis", "style weight");
CssJs.unsafe("fontKerning", "auto");
CssJs.unsafe("fontKerning", "normal");
CssJs.unsafe("fontKerning", "none");
CssJs.unsafe("fontVariantPosition", "normal");
CssJs.unsafe("fontVariantPosition", "sub");
CssJs.unsafe("fontVariantPosition", "super");
CssJs.unsafe("fontVariantLigatures", "normal");
CssJs.unsafe("fontVariantLigatures", "none");
CssJs.unsafe("fontVariantLigatures", "common-ligatures");
CssJs.unsafe("fontVariantLigatures", "no-common-ligatures");
CssJs.unsafe("fontVariantLigatures", "discretionary-ligatures");
CssJs.unsafe("fontVariantLigatures", "no-discretionary-ligatures");
CssJs.unsafe("fontVariantLigatures", "historical-ligatures");
CssJs.unsafe("fontVariantLigatures", "no-historical-ligatures");
CssJs.unsafe("fontVariantLigatures", "contextual");
CssJs.unsafe("fontVariantLigatures", "no-contextual");
CssJs.unsafe(
  "fontVariantLigatures",
  "common-ligatures discretionary-ligatures historical-ligatures contextual",
);
CssJs.unsafe("fontVariantCaps", "normal");
CssJs.unsafe("fontVariantCaps", "small-caps");
CssJs.unsafe("fontVariantCaps", "all-small-caps");
CssJs.unsafe("fontVariantCaps", "petite-caps");
CssJs.unsafe("fontVariantCaps", "all-petite-caps");
CssJs.unsafe("fontVariantCaps", "titling-caps");
CssJs.unsafe("fontVariantCaps", "unicase");
CssJs.unsafe("fontVariantNumeric", "normal");
CssJs.unsafe("fontVariantNumeric", "lining-nums");
CssJs.unsafe("fontVariantNumeric", "oldstyle-nums");
CssJs.unsafe("fontVariantNumeric", "proportional-nums");
CssJs.unsafe("fontVariantNumeric", "tabular-nums");
CssJs.unsafe("fontVariantNumeric", "diagonal-fractions");
CssJs.unsafe("fontVariantNumeric", "stacked-fractions");
CssJs.unsafe("fontVariantNumeric", "ordinal");
CssJs.unsafe("fontVariantNumeric", "slashed-zero");
CssJs.unsafe(
  "fontVariantNumeric",
  "lining-nums proportional-nums diagonal-fractions",
);
CssJs.unsafe(
  "fontVariantNumeric",
  "oldstyle-nums tabular-nums stacked-fractions ordinal slashed-zero",
);
CssJs.unsafe(
  "fontVariantNumeric",
  "slashed-zero ordinal tabular-nums stacked-fractions oldstyle-nums",
);
CssJs.unsafe("fontVariantEastAsian", "normal");
CssJs.unsafe("fontVariantEastAsian", "jis78");
CssJs.unsafe("fontVariantEastAsian", "jis83");
CssJs.unsafe("fontVariantEastAsian", "jis90");
CssJs.unsafe("fontVariantEastAsian", "jis04");
CssJs.unsafe("fontVariantEastAsian", "simplified");
CssJs.unsafe("fontVariantEastAsian", "traditional");
CssJs.unsafe("fontVariantEastAsian", "full-width");
CssJs.unsafe("fontVariantEastAsian", "proportional-width");
CssJs.unsafe("fontVariantEastAsian", "ruby");
CssJs.unsafe("fontVariantEastAsian", "simplified full-width ruby");
CssJs.unsafe("fontFeatureSettings", "normal");
CssJs.unsafe("fontFeatureSettings", "'c2sc'");
CssJs.unsafe("fontFeatureSettings", "'smcp' on");
CssJs.unsafe("fontFeatureSettings", "'liga' off");
CssJs.unsafe("fontFeatureSettings", "'smcp', 'swsh' 2");
CssJs.fontSize(`xxx_large);
CssJs.unsafe("fontVariant", "none");
CssJs.unsafe("fontVariant", "normal");
CssJs.unsafe("fontVariant", "all-petite-caps");
CssJs.unsafe("fontVariant", "historical-forms");
CssJs.unsafe("fontVariantAlternates", "normal");
CssJs.unsafe("fontVariantAlternates", "historical-forms");
CssJs.unsafe("fontVariantAlternates", "styleset(ss01)");
CssJs.unsafe("fontVariantAlternates", "styleset(stacked-g, geometric-m)");
CssJs.unsafe("fontVariantAlternates", "character-variant(cv02)");
CssJs.unsafe("fontVariantAlternates", "character-variant(beta-3, gamma)");
CssJs.unsafe("fontVariantAlternates", "swash(flowing)");
CssJs.unsafe("fontVariantAlternates", "ornaments(leaves)");
CssJs.unsafe("fontVariantAlternates", "annotation(blocky)");
CssJs.unsafe("fontFeatureSettings", "normal");
CssJs.unsafe("fontFeatureSettings", "'swsh' 2");
CssJs.unsafe("fontLanguageOverride", "normal");
CssJs.unsafe("fontLanguageOverride", "'SRB'");
CssJs.unsafe("fontWeight", "1");
CssJs.unsafe("fontWeight", "90");
CssJs.unsafe("fontWeight", "750");
CssJs.unsafe("fontWeight", "1000");
CssJs.unsafe("fontStyle", "oblique 15deg");
CssJs.unsafe("fontStyle", "oblique -15deg");
CssJs.unsafe("fontStyle", "oblique 0deg");
CssJs.unsafe("fontOpticalSizing", "none");
CssJs.unsafe("fontOpticalSizing", "auto");
CssJs.unsafe("direction", "ltr");
CssJs.unsafe("direction", "rtl");
CssJs.unsafe("unicodeBidi", "normal");
CssJs.unsafe("unicodeBidi", "embed");
CssJs.unsafe("unicodeBidi", "isolate");
CssJs.unsafe("unicodeBidi", "bidi-override");
CssJs.unsafe("unicodeBidi", "isolate-override");
CssJs.unsafe("unicodeBidi", "plaintext");
CssJs.unsafe("writingMode", "horizontal-tb");
CssJs.unsafe("writingMode", "vertical-rl");
CssJs.unsafe("writingMode", "vertical-lr");
CssJs.unsafe("textOrientation", "mixed");
CssJs.unsafe("textOrientation", "upright");
CssJs.unsafe("textOrientation", "sideways");
CssJs.unsafe("textCombineUpright", "none");
CssJs.unsafe("textCombineUpright", "all");
CssJs.unsafe("writingMode", "sideways-rl");
CssJs.unsafe("writingMode", "sideways-lr");
CssJs.unsafe("textCombineUpright", "digits 2");
CssJs.color(`rgba((0, 0, 0, `num(0.5))));
CssJs.color(`hex("F06"));
CssJs.color(`hex("FF0066"));
CssJs.unsafe("color", "hsl(0,0%,0%)");
CssJs.unsafe("color", "hsl(0,0%,0%,.5)");
CssJs.color(`transparent);
CssJs.color(`currentColor);
CssJs.backgroundColor(`rgba((0, 0, 0, `num(0.5))));
CssJs.backgroundColor(`hex("F06"));
CssJs.backgroundColor(`hex("FF0066"));
CssJs.unsafe("backgroundColor", "hsl(0,0%,0%)");
CssJs.unsafe("backgroundColor", "hsl(0,0%,0%,.5)");
CssJs.backgroundColor(`transparent);
CssJs.backgroundColor(`currentColor);
CssJs.borderColor(`rgba((0, 0, 0, `num(0.5))));
CssJs.borderColor(`hex("F06"));
CssJs.borderColor(`hex("FF0066"));
CssJs.unsafe("borderColor", "hsl(0,0%,0%)");
CssJs.unsafe("borderColor", "hsl(0,0%,0%,.5)");
CssJs.borderColor(`transparent);
CssJs.borderColor(`currentColor);
CssJs.textDecorationColor(`rgba((0, 0, 0, `num(0.5))));
CssJs.textDecorationColor(`hex("F06"));
CssJs.textDecorationColor(`hex("FF0066"));
CssJs.unsafe("textDecorationColor", "hsl(0,0%,0%)");
CssJs.unsafe("textDecorationColor", "hsl(0,0%,0%,.5)");
CssJs.textDecorationColor(`transparent);
CssJs.textDecorationColor(`currentColor);
CssJs.unsafe("columnRuleColor", "rgba(0,0,0,.5)");
CssJs.unsafe("columnRuleColor", "#F06");
CssJs.unsafe("columnRuleColor", "#FF0066");
CssJs.unsafe("columnRuleColor", "hsl(0,0%,0%)");
CssJs.unsafe("columnRuleColor", "hsl(0,0%,0%,.5)");
CssJs.unsafe("columnRuleColor", "transparent");
CssJs.unsafe("columnRuleColor", "currentColor");
CssJs.color(`rgb((0, 51, 178)));
CssJs.color(`rgb((0, 64, 185)));
CssJs.color(`hsl((`deg(0.), `percent(0.), `percent(0.))));
CssJs.color(`rgba((0, 51, 178, `percent(0.5))));
CssJs.color(`rgba((0, 51, 178, `num(0.5))));
CssJs.color(`rgba((0, 64, 185, `percent(0.5))));
CssJs.color(`rgba((0, 64, 185, `num(0.5))));
CssJs.unsafe("color", "hsla(0 0% 0% /.5)");
CssJs.color(`rgba((0, 51, 178, `percent(0.5))));
CssJs.color(`rgba((0, 51, 178, `num(0.5))));
CssJs.color(`rgba((0, 64, 185, `percent(0.5))));
CssJs.color(`rgba((0, 64, 185, `num(0.5))));
CssJs.color(`hsla((`deg(0.), `percent(0.), `percent(0.), `num(0.5))));
CssJs.color(`hex("000F"));
CssJs.color(`hex("000000FF"));
CssJs.color(CssJs.rebeccapurple);
CssJs.backgroundColor(`rgb((0, 51, 178)));
CssJs.backgroundColor(`rgb((0, 64, 185)));
CssJs.backgroundColor(`hsl((`deg(0.), `percent(0.), `percent(0.))));
CssJs.backgroundColor(`rgba((0, 51, 178, `percent(0.5))));
CssJs.backgroundColor(`rgba((0, 51, 178, `num(0.5))));
CssJs.backgroundColor(`rgba((0, 64, 185, `percent(0.5))));
CssJs.backgroundColor(`rgba((0, 64, 185, `num(0.5))));
CssJs.unsafe("backgroundColor", "hsla(0 0% 0% /.5)");
CssJs.backgroundColor(`rgba((0, 51, 178, `percent(0.5))));
CssJs.backgroundColor(`rgba((0, 51, 178, `num(0.5))));
CssJs.backgroundColor(`rgba((0, 64, 185, `percent(0.5))));
CssJs.backgroundColor(`rgba((0, 64, 185, `num(0.5))));
CssJs.backgroundColor(
  `hsla((`deg(0.), `percent(0.), `percent(0.), `num(0.5))),
);
CssJs.backgroundColor(`hex("000F"));
CssJs.backgroundColor(`hex("000000FF"));
CssJs.backgroundColor(CssJs.rebeccapurple);
CssJs.borderColor(`rgb((0, 51, 178)));
CssJs.borderColor(`rgb((0, 64, 185)));
CssJs.borderColor(`hsl((`deg(0.), `percent(0.), `percent(0.))));
CssJs.borderColor(`rgba((0, 51, 178, `percent(0.5))));
CssJs.borderColor(`rgba((0, 51, 178, `num(0.5))));
CssJs.borderColor(`rgba((0, 64, 185, `percent(0.5))));
CssJs.borderColor(`rgba((0, 64, 185, `num(0.5))));
CssJs.unsafe("borderColor", "hsla(0 0% 0% /.5)");
CssJs.borderColor(`rgba((0, 51, 178, `percent(0.5))));
CssJs.borderColor(`rgba((0, 51, 178, `num(0.5))));
CssJs.borderColor(`rgba((0, 64, 185, `percent(0.5))));
CssJs.borderColor(`rgba((0, 64, 185, `num(0.5))));
CssJs.borderColor(
  `hsla((`deg(0.), `percent(0.), `percent(0.), `num(0.5))),
);
CssJs.borderColor(`hex("000F"));
CssJs.borderColor(`hex("000000FF"));
CssJs.borderColor(CssJs.rebeccapurple);
CssJs.textDecorationColor(`rgb((0, 51, 178)));
CssJs.textDecorationColor(`rgb((0, 64, 185)));
CssJs.textDecorationColor(`hsl((`deg(0.), `percent(0.), `percent(0.))));
CssJs.textDecorationColor(`rgba((0, 51, 178, `percent(0.5))));
CssJs.textDecorationColor(`rgba((0, 51, 178, `num(0.5))));
CssJs.textDecorationColor(`rgba((0, 64, 185, `percent(0.5))));
CssJs.textDecorationColor(`rgba((0, 64, 185, `num(0.5))));
CssJs.unsafe("textDecorationColor", "hsla(0 0% 0% /.5)");
CssJs.textDecorationColor(`rgba((0, 51, 178, `percent(0.5))));
CssJs.textDecorationColor(`rgba((0, 51, 178, `num(0.5))));
CssJs.textDecorationColor(`rgba((0, 64, 185, `percent(0.5))));
CssJs.textDecorationColor(`rgba((0, 64, 185, `num(0.5))));
CssJs.textDecorationColor(
  `hsla((`deg(0.), `percent(0.), `percent(0.), `num(0.5))),
);
CssJs.textDecorationColor(`hex("000F"));
CssJs.textDecorationColor(`hex("000000FF"));
CssJs.textDecorationColor(CssJs.rebeccapurple);
CssJs.unsafe("columnRuleColor", "rgb(0% 20% 70%)");
CssJs.unsafe("columnRuleColor", "rgb(0 64 185)");
CssJs.unsafe("columnRuleColor", "hsl(0 0% 0%)");
CssJs.unsafe("columnRuleColor", "rgba(0% 20% 70% / 50%)");
CssJs.unsafe("columnRuleColor", "rgba(0% 20% 70% / .5)");
CssJs.unsafe("columnRuleColor", "rgba(0 64 185 / 50%)");
CssJs.unsafe("columnRuleColor", "rgba(0 64 185 / .5)");
CssJs.unsafe("columnRuleColor", "hsla(0 0% 0% /.5)");
CssJs.unsafe("columnRuleColor", "rgb(0% 20% 70% / 50%)");
CssJs.unsafe("columnRuleColor", "rgb(0% 20% 70% / .5)");
CssJs.unsafe("columnRuleColor", "rgb(0 64 185 / 50%)");
CssJs.unsafe("columnRuleColor", "rgb(0 64 185 / .5)");
CssJs.unsafe("columnRuleColor", "hsl(0 0% 0% / .5)");
CssJs.unsafe("columnRuleColor", "#000F");
CssJs.unsafe("columnRuleColor", "#000000FF");
CssJs.unsafe("columnRuleColor", "rebeccapurple");
CssJs.unsafe("columnWidth", "10em");
CssJs.unsafe("columnWidth", "auto");
CssJs.unsafe("columnCount", "2");
CssJs.unsafe("columnCount", "auto");
CssJs.unsafe("columns", "100px");
CssJs.unsafe("columns", "3");
CssJs.unsafe("columns", "10em 2");
CssJs.unsafe("columns", "auto auto");
CssJs.unsafe("columns", "2 10em");
CssJs.unsafe("columns", "auto 10em");
CssJs.unsafe("columns", "2 auto");
CssJs.unsafe("columnRuleColor", "red");
CssJs.unsafe("columnRuleStyle", "none");
CssJs.unsafe("columnRuleStyle", "solid");
CssJs.unsafe("columnRuleStyle", "dotted");
CssJs.unsafe("columnRuleWidth", "1px");
CssJs.unsafe("columnRule", "transparent");
CssJs.unsafe("columnRule", "1px solid black");
CssJs.unsafe("columnSpan", "none");
CssJs.unsafe("columnSpan", "all");
CssJs.unsafe("columnFill", "auto");
CssJs.unsafe("columnFill", "balance");
CssJs.unsafe("columnFill", "balance-all");
CssJs.width(`rem(5.));
CssJs.width(`ch(5.));
CssJs.width(`vw(5.));
CssJs.width(`vh(5.));
CssJs.width(`vmin(5.));
CssJs.width(`vmax(5.));
CssJs.padding(`rem(5.));
CssJs.padding(`ch(5.));
CssJs.padding(`vw(5.));
CssJs.padding(`vh(5.));
CssJs.padding(`vmin(5.));
CssJs.padding(`vmax(5.));
CssJs.unsafe("alignContent", "flex-start");
CssJs.unsafe("alignContent", "flex-end");
CssJs.unsafe("alignContent", "space-between");
CssJs.unsafe("alignContent", "space-around");
CssJs.unsafe("alignItems", "flex-start");
CssJs.unsafe("alignItems", "flex-end");
CssJs.unsafe("alignSelf", "flex-start");
CssJs.unsafe("alignSelf", "flex-end");
CssJs.display(`flex);
CssJs.display(`inlineFlex);
CssJs.flex(`none);
CssJs.flexGrow(5.);
CssJs.flexBasis(`auto);
CssJs.flexBasis(`content);
CssJs.flexBasis(`pxFloat(1.));
CssJs.flexDirection(`row);
CssJs.flexDirection(`rowReverse);
CssJs.flexDirection(`column);
CssJs.flexDirection(`columnReverse);
CssJs.flexDirection(`row);
CssJs.flexDirection(`rowReverse);
CssJs.flexDirection(`column);
CssJs.flexDirection(`columnReverse);
CssJs.flexWrap(`wrap);
CssJs.flexWrap(`wrapReverse);
CssJs.flexGrow(0.);
CssJs.flexGrow(5.);
CssJs.flexShrink(1.);
CssJs.flexShrink(10.);
CssJs.flexWrap(`nowrap);
CssJs.flexWrap(`wrap);
CssJs.flexWrap(`wrapReverse);
CssJs.unsafe("justifyContent", "flex-start");
CssJs.unsafe("justifyContent", "flex-end");
CssJs.unsafe("justifyContent", "space-between");
CssJs.unsafe("justifyContent", "space-around");
CssJs.minHeight(`auto);
CssJs.minWidth(`auto);
CssJs.order(0);
CssJs.order(1);
CssJs.display(`grid);
CssJs.display(`inlineGrid);
CssJs.unsafe("gridTemplateColumns", "100px");
CssJs.unsafe("gridTemplateColumns", "1fr");
CssJs.unsafe("gridTemplateColumns", "100px 1fr auto");
CssJs.unsafe("gridTemplateColumns", "repeat(2, 100px 1fr)");
CssJs.unsafe(
  "gridTemplateColumns",
  "100px 1fr max-content minmax(min-content, 1fr)",
);
CssJs.unsafe("gridTemplateColumns", "repeat(auto-fill, minmax(25ch, 1fr))");
CssJs.unsafe("gridTemplateRows", "none");
CssJs.unsafe("gridTemplateRows", "auto");
CssJs.unsafe("gridTemplateRows", "100px");
CssJs.unsafe("gridTemplateRows", "1fr");
CssJs.unsafe("gridTemplateRows", "100px 1fr auto");
CssJs.unsafe("gridTemplateRows", "repeat(2, 100px 1fr)");
CssJs.unsafe(
  "gridTemplateRows",
  "100px 1fr max-content minmax(min-content, 1fr)",
);
CssJs.unsafe("gridTemplateRows", "10px [row-start] 250px [row-end]");
CssJs.unsafe(
  "gridTemplateRows",
  "[first header-start] 50px [main-start] 1fr [footer-start] 50px [last]",
);
CssJs.unsafe("gridTemplateAreas", "none");
CssJs.unsafe("gridTemplateAreas", "'articles'");
CssJs.unsafe("gridTemplateAreas", "'head head'");
CssJs.unsafe("gridTemplateAreas", "'head head' 'nav main' 'foot ....'");
CssJs.unsafe("gridTemplate", "none");
CssJs.unsafe("gridTemplate", "auto 1fr auto / auto 1fr");
CssJs.unsafe(
  "gridTemplate",
  "[header-top] 'a   a   a' [header-bottom] [main-top] 'b   b   b' 1fr [main-bottom] / auto 1fr auto",
);
CssJs.unsafe("gridAutoColumns", "auto");
CssJs.unsafe("gridAutoColumns", "1fr");
CssJs.unsafe("gridAutoColumns", "100px");
CssJs.unsafe("gridAutoColumns", "max-content");
CssJs.unsafe("gridAutoColumns", "minmax(min-content, 1fr)");
CssJs.unsafe("gridAutoColumns", "min-content max-content auto");
CssJs.unsafe("gridAutoColumns", "100px 150px 390px");
CssJs.unsafe(
  "gridAutoColumns",
  "100px minmax(100px, auto) 10% 0.5fr fit-content(400px)",
);
CssJs.unsafe("gridAutoRows", "auto");
CssJs.unsafe("gridAutoRows", "1fr");
CssJs.unsafe("gridAutoRows", "100px");
CssJs.unsafe("gridAutoRows", "100px 30%");
CssJs.unsafe("gridAutoRows", "100px 30% 1em");
CssJs.unsafe("gridAutoRows", "min-content");
CssJs.unsafe("gridAutoRows", "minmax(min-content, 1fr)");
CssJs.unsafe("gridAutoRows", "min-content max-content auto");
CssJs.unsafe(
  "gridAutoRows",
  "100px minmax(100px, auto) 10% 0.5fr fit-content(400px)",
);
CssJs.unsafe("gridAutoFlow", "row");
CssJs.unsafe("gridAutoFlow", "column");
CssJs.unsafe("gridAutoFlow", "row dense");
CssJs.unsafe("gridAutoFlow", "column dense");
CssJs.unsafe("gridRowStart", "auto");
CssJs.unsafe("gridRowStart", "4");
CssJs.unsafe("gridRowStart", "C");
CssJs.unsafe("gridRowStart", "C 2");
CssJs.unsafe("gridRowStart", "span 1");
CssJs.unsafe("gridColumnStart", "auto");
CssJs.unsafe("gridColumnStart", "4");
CssJs.unsafe("gridColumnStart", "C");
CssJs.unsafe("gridColumnStart", "C 2");
CssJs.unsafe("gridColumnStart", "span 1");
CssJs.unsafe("gridRowEnd", "auto");
CssJs.unsafe("gridRowEnd", "4");
CssJs.unsafe("gridRowEnd", "C");
CssJs.unsafe("gridRowEnd", "C 2");
CssJs.unsafe("gridRowEnd", "span 1");
CssJs.unsafe("gridColumnEnd", "auto");
CssJs.unsafe("gridColumnEnd", "4");
CssJs.unsafe("gridColumnEnd", "C");
CssJs.unsafe("gridColumnEnd", "C 2");
CssJs.unsafe("gridColumnEnd", "span 1");
CssJs.unsafe("gridColumn", "auto");
CssJs.unsafe("gridColumn", "1");
CssJs.unsafe("gridColumn", "-1");
CssJs.unsafe("gridRow", "auto");
CssJs.unsafe("gridRow", "1");
CssJs.unsafe("gridRow", "-1");
CssJs.unsafe("gridColumnGap", "0");
CssJs.unsafe("gridColumnGap", "1em");
CssJs.unsafe("gridRowGap", "0");
CssJs.unsafe("gridRowGap", "1em");
CssJs.unsafe("gridGap", "0 0");
CssJs.unsafe("gridGap", "0 1em");
CssJs.unsafe("gridGap", "1em");
CssJs.unsafe("gridGap", "1em 1em");
CssJs.unsafe("alignSelf", "auto");
CssJs.unsafe("alignSelf", "normal");
CssJs.unsafe("alignSelf", "stretch");
CssJs.unsafe("alignSelf", "baseline");
CssJs.unsafe("alignSelf", "first baseline");
CssJs.unsafe("alignSelf", "last baseline");
CssJs.unsafe("alignSelf", "center");
CssJs.unsafe("alignSelf", "start");
CssJs.unsafe("alignSelf", "end");
CssJs.unsafe("alignSelf", "self-start");
CssJs.unsafe("alignSelf", "self-end");
CssJs.unsafe("alignSelf", "unsafe start");
CssJs.unsafe("alignSelf", "safe start");
CssJs.unsafe("alignItems", "normal");
CssJs.unsafe("alignItems", "stretch");
CssJs.unsafe("alignItems", "baseline");
CssJs.unsafe("alignItems", "first baseline");
CssJs.unsafe("alignItems", "last baseline");
CssJs.unsafe("alignItems", "center");
CssJs.unsafe("alignItems", "start");
CssJs.unsafe("alignItems", "end");
CssJs.unsafe("alignItems", "self-start");
CssJs.unsafe("alignItems", "self-end");
CssJs.unsafe("alignItems", "unsafe start");
CssJs.unsafe("alignItems", "safe start");
CssJs.unsafe("alignContent", "normal");
CssJs.unsafe("alignContent", "baseline");
CssJs.unsafe("alignContent", "first baseline");
CssJs.unsafe("alignContent", "last baseline");
CssJs.unsafe("alignContent", "space-between");
CssJs.unsafe("alignContent", "space-around");
CssJs.unsafe("alignContent", "space-evenly");
CssJs.unsafe("alignContent", "stretch");
CssJs.unsafe("alignContent", "center");
CssJs.unsafe("alignContent", "start");
CssJs.unsafe("alignContent", "end");
CssJs.unsafe("alignContent", "flex-start");
CssJs.unsafe("alignContent", "flex-end");
CssJs.unsafe("alignContent", "unsafe start");
CssJs.unsafe("alignContent", "safe start");
CssJs.unsafe("justifySelf", "auto");
CssJs.unsafe("justifySelf", "normal");
CssJs.unsafe("justifySelf", "stretch");
CssJs.unsafe("justifySelf", "baseline");
CssJs.unsafe("justifySelf", "first baseline");
CssJs.unsafe("justifySelf", "last baseline");
CssJs.unsafe("justifySelf", "center");
CssJs.unsafe("justifySelf", "start");
CssJs.unsafe("justifySelf", "end");
CssJs.unsafe("justifySelf", "self-start");
CssJs.unsafe("justifySelf", "self-end");
CssJs.unsafe("justifySelf", "unsafe start");
CssJs.unsafe("justifySelf", "safe start");
CssJs.unsafe("justifySelf", "left");
CssJs.unsafe("justifySelf", "right");
CssJs.unsafe("justifySelf", "safe right");
CssJs.unsafe("justifyItems", "normal");
CssJs.unsafe("justifyItems", "stretch");
CssJs.unsafe("justifyItems", "baseline");
CssJs.unsafe("justifyItems", "first baseline");
CssJs.unsafe("justifyItems", "last baseline");
CssJs.unsafe("justifyItems", "center");
CssJs.unsafe("justifyItems", "start");
CssJs.unsafe("justifyItems", "end");
CssJs.unsafe("justifyItems", "self-start");
CssJs.unsafe("justifyItems", "self-end");
CssJs.unsafe("justifyItems", "unsafe start");
CssJs.unsafe("justifyItems", "safe start");
CssJs.unsafe("justifyItems", "left");
CssJs.unsafe("justifyItems", "right");
CssJs.unsafe("justifyItems", "safe right");
CssJs.unsafe("justifyItems", "legacy");
CssJs.unsafe("justifyItems", "legacy left");
CssJs.unsafe("justifyItems", "legacy right");
CssJs.unsafe("justifyItems", "legacy center");
CssJs.unsafe("justifyContent", "normal");
CssJs.unsafe("justifyContent", "space-between");
CssJs.unsafe("justifyContent", "space-around");
CssJs.unsafe("justifyContent", "space-evenly");
CssJs.unsafe("justifyContent", "stretch");
CssJs.unsafe("justifyContent", "center");
CssJs.unsafe("justifyContent", "start");
CssJs.unsafe("justifyContent", "end");
CssJs.unsafe("justifyContent", "flex-start");
CssJs.unsafe("justifyContent", "flex-end");
CssJs.unsafe("justifyContent", "unsafe start");
CssJs.unsafe("justifyContent", "safe start");
CssJs.unsafe("justifyContent", "left");
CssJs.unsafe("justifyContent", "right");
CssJs.unsafe("justifyContent", "safe right");
CssJs.unsafe("placeContent", "normal");
CssJs.unsafe("placeContent", "baseline");
CssJs.unsafe("placeContent", "first baseline");
CssJs.unsafe("placeContent", "last baseline");
CssJs.unsafe("placeContent", "space-between");
CssJs.unsafe("placeContent", "space-around");
CssJs.unsafe("placeContent", "space-evenly");
CssJs.unsafe("placeContent", "stretch");
CssJs.unsafe("placeContent", "center");
CssJs.unsafe("placeContent", "start");
CssJs.unsafe("placeContent", "end");
CssJs.unsafe("placeContent", "flex-start");
CssJs.unsafe("placeContent", "flex-end");
CssJs.unsafe("placeContent", "unsafe start");
CssJs.unsafe("placeContent", "safe start");
CssJs.unsafe("placeContent", "normal normal");
CssJs.unsafe("placeContent", "baseline normal");
CssJs.unsafe("placeContent", "first baseline normal");
CssJs.unsafe("placeContent", "space-between normal");
CssJs.unsafe("placeContent", "center normal");
CssJs.unsafe("placeContent", "unsafe start normal");
CssJs.unsafe("placeContent", "normal stretch");
CssJs.unsafe("placeContent", "baseline stretch");
CssJs.unsafe("placeContent", "first baseline stretch");
CssJs.unsafe("placeContent", "space-between stretch");
CssJs.unsafe("placeContent", "center stretch");
CssJs.unsafe("placeContent", "unsafe start stretch");
CssJs.unsafe("placeContent", "normal safe right");
CssJs.unsafe("placeContent", "baseline safe right");
CssJs.unsafe("placeContent", "first baseline safe right");
CssJs.unsafe("placeContent", "space-between safe right");
CssJs.unsafe("placeContent", "center safe right");
CssJs.unsafe("placeContent", "unsafe start safe right");
CssJs.unsafe("placeItems", "normal");
CssJs.unsafe("placeItems", "stretch");
CssJs.unsafe("placeItems", "baseline");
CssJs.unsafe("placeItems", "first baseline");
CssJs.unsafe("placeItems", "last baseline");
CssJs.unsafe("placeItems", "center");
CssJs.unsafe("placeItems", "start");
CssJs.unsafe("placeItems", "end");
CssJs.unsafe("placeItems", "self-start");
CssJs.unsafe("placeItems", "self-end");
CssJs.unsafe("placeItems", "unsafe start");
CssJs.unsafe("placeItems", "safe start");
CssJs.unsafe("placeItems", "normal normal");
CssJs.unsafe("placeItems", "stretch normal");
CssJs.unsafe("placeItems", "baseline normal");
CssJs.unsafe("placeItems", "first baseline normal");
CssJs.unsafe("placeItems", "self-start normal");
CssJs.unsafe("placeItems", "unsafe start normal");
CssJs.unsafe("placeItems", "normal stretch");
CssJs.unsafe("placeItems", "stretch stretch");
CssJs.unsafe("placeItems", "baseline stretch");
CssJs.unsafe("placeItems", "first baseline stretch");
CssJs.unsafe("placeItems", "self-start stretch");
CssJs.unsafe("placeItems", "unsafe start stretch");
CssJs.unsafe("placeItems", "normal last baseline");
CssJs.unsafe("placeItems", "stretch last baseline");
CssJs.unsafe("placeItems", "baseline last baseline");
CssJs.unsafe("placeItems", "first baseline last baseline");
CssJs.unsafe("placeItems", "self-start last baseline");
CssJs.unsafe("placeItems", "unsafe start last baseline");
CssJs.unsafe("placeItems", "normal legacy left");
CssJs.unsafe("placeItems", "stretch legacy left");
CssJs.unsafe("placeItems", "baseline legacy left");
CssJs.unsafe("placeItems", "first baseline legacy left");
CssJs.unsafe("placeItems", "self-start legacy left");
CssJs.unsafe("placeItems", "unsafe start legacy left");
CssJs.unsafe("gap", "0 0");
CssJs.unsafe("gap", "0 1em");
CssJs.unsafe("gap", "1em");
CssJs.unsafe("gap", "1em 1em");
CssJs.unsafe("columnGap", "0");
CssJs.unsafe("columnGap", "1em");
CssJs.unsafe("columnGap", "normal");
CssJs.unsafe("rowGap", "0");
CssJs.unsafe("rowGap", "1em");
CssJs.unsafe("marginTrim", "none");
CssJs.unsafe("marginTrim", "in-flow");
CssJs.unsafe("marginTrim", "all");
CssJs.unsafe("color", "unset");
CssJs.unsafe("font-weight", "unset");
CssJs.unsafe("background-image", "unset");
CssJs.unsafe("width", "unset");
CssJs.unsafe("clipPath", "url('#clip')");
CssJs.unsafe("clipPath", "inset(50%)");
CssJs.unsafe("clipPath", "circle()");
CssJs.unsafe("clipPath", "ellipse()");
CssJs.unsafe("clipPath", "border-box");
CssJs.unsafe("clipPath", "padding-box");
CssJs.unsafe("clipPath", "content-box");
CssJs.unsafe("clipPath", "margin-box");
CssJs.unsafe("clipPath", "fill-box");
CssJs.unsafe("clipPath", "stroke-box");
CssJs.unsafe("clipPath", "view-box");
CssJs.unsafe("clipPath", "none");
CssJs.unsafe("clipRule", "nonzero");
CssJs.unsafe("clipRule", "evenodd");
CssJs.unsafe("maskImage", "none");
CssJs.unsafe("maskImage", "url(image.png)");
CssJs.unsafe("maskMode", "alpha");
CssJs.unsafe("maskMode", "luminance");
CssJs.unsafe("maskMode", "match-source");
CssJs.unsafe("maskRepeat", "repeat-x");
CssJs.unsafe("maskRepeat", "repeat-y");
CssJs.unsafe("maskRepeat", "repeat");
CssJs.unsafe("maskRepeat", "space");
CssJs.unsafe("maskRepeat", "round");
CssJs.unsafe("maskRepeat", "no-repeat");
CssJs.unsafe("maskRepeat", "repeat repeat");
CssJs.unsafe("maskRepeat", "space repeat");
CssJs.unsafe("maskRepeat", "round repeat");
CssJs.unsafe("maskRepeat", "no-repeat repeat");
CssJs.unsafe("maskRepeat", "repeat space");
CssJs.unsafe("maskRepeat", "space space");
CssJs.unsafe("maskRepeat", "round space");
CssJs.unsafe("maskRepeat", "no-repeat space");
CssJs.unsafe("maskRepeat", "repeat round");
CssJs.unsafe("maskRepeat", "space round");
CssJs.unsafe("maskRepeat", "round round");
CssJs.unsafe("maskRepeat", "no-repeat round");
CssJs.unsafe("maskRepeat", "repeat no-repeat");
CssJs.unsafe("maskRepeat", "space no-repeat");
CssJs.unsafe("maskRepeat", "round no-repeat");
CssJs.unsafe("maskRepeat", "no-repeat no-repeat");
CssJs.unsafe("maskPosition", "center");
CssJs.unsafe("maskPosition", "left 50%");
CssJs.unsafe("maskClip", "border-box");
CssJs.unsafe("maskClip", "padding-box");
CssJs.unsafe("maskClip", "content-box");
CssJs.unsafe("maskClip", "margin-box");
CssJs.unsafe("maskClip", "fill-box");
CssJs.unsafe("maskClip", "stroke-box");
CssJs.unsafe("maskClip", "view-box");
CssJs.unsafe("maskClip", "no-clip");
CssJs.unsafe("maskOrigin", "border-box");
CssJs.unsafe("maskOrigin", "padding-box");
CssJs.unsafe("maskOrigin", "content-box");
CssJs.unsafe("maskOrigin", "margin-box");
CssJs.unsafe("maskOrigin", "fill-box");
CssJs.unsafe("maskOrigin", "stroke-box");
CssJs.unsafe("maskOrigin", "view-box");
CssJs.unsafe("maskSize", "auto");
CssJs.unsafe("maskSize", "10px");
CssJs.unsafe("maskSize", "cover");
CssJs.unsafe("maskSize", "contain");
CssJs.unsafe("maskSize", "10px");
CssJs.unsafe("maskSize", "50%");
CssJs.unsafe("maskSize", "10px auto");
CssJs.unsafe("maskSize", "auto 10%");
CssJs.unsafe("maskSize", "50em 50%");
CssJs.unsafe("maskComposite", "add");
CssJs.unsafe("maskComposite", "subtract");
CssJs.unsafe("maskComposite", "intersect");
CssJs.unsafe("maskComposite", "exclude");
CssJs.unsafe("mask", "top");
CssJs.unsafe("mask", "space");
CssJs.unsafe("mask", "url(image.png)");
CssJs.unsafe("mask", "url(image.png) luminance");
CssJs.unsafe("mask", "url(image.png) luminance top space");
CssJs.unsafe("maskBorderSource", "none");
CssJs.unsafe("maskBorderSlice", "0 fill");
CssJs.unsafe("maskBorderSlice", "50% fill");
CssJs.unsafe("maskBorderSlice", "1.1 fill");
CssJs.unsafe("maskBorderSlice", "0 1 fill");
CssJs.unsafe("maskBorderSlice", "0 1 2 fill");
CssJs.unsafe("maskBorderSlice", "0 1 2 3 fill");
CssJs.unsafe("maskBorderWidth", "auto");
CssJs.unsafe("maskBorderWidth", "10px");
CssJs.unsafe("maskBorderWidth", "50%");
CssJs.unsafe("maskBorderWidth", "1");
CssJs.unsafe("maskBorderWidth", "1.0");
CssJs.unsafe("maskBorderWidth", "auto 1");
CssJs.unsafe("maskBorderWidth", "auto 1 50%");
CssJs.unsafe("maskBorderWidth", "auto 1 50% 1.1");
CssJs.unsafe("maskBorderOutset", "0");
CssJs.unsafe("maskBorderOutset", "1.1");
CssJs.unsafe("maskBorderOutset", "0 1");
CssJs.unsafe("maskBorderOutset", "0 1 2");
CssJs.unsafe("maskBorderOutset", "0 1 2 3");
CssJs.unsafe("maskBorderRepeat", "stretch");
CssJs.unsafe("maskBorderRepeat", "repeat");
CssJs.unsafe("maskBorderRepeat", "round");
CssJs.unsafe("maskBorderRepeat", "space");
CssJs.unsafe("maskBorderRepeat", "stretch stretch");
CssJs.unsafe("maskBorderRepeat", "repeat stretch");
CssJs.unsafe("maskBorderRepeat", "round stretch");
CssJs.unsafe("maskBorderRepeat", "space stretch");
CssJs.unsafe("maskBorderRepeat", "stretch repeat");
CssJs.unsafe("maskBorderRepeat", "repeat repeat");
CssJs.unsafe("maskBorderRepeat", "round repeat");
CssJs.unsafe("maskBorderRepeat", "space repeat");
CssJs.unsafe("maskBorderRepeat", "stretch round");
CssJs.unsafe("maskBorderRepeat", "repeat round");
CssJs.unsafe("maskBorderRepeat", "round round");
CssJs.unsafe("maskBorderRepeat", "space round");
CssJs.unsafe("maskBorderRepeat", "stretch space");
CssJs.unsafe("maskBorderRepeat", "repeat space");
CssJs.unsafe("maskBorderRepeat", "round space");
CssJs.unsafe("maskBorderRepeat", "space space");
CssJs.unsafe("maskType", "luminance");
CssJs.unsafe("maskType", "alpha");
CssJs.unsafe("mixBlendMode", "normal");
CssJs.unsafe("mixBlendMode", "multiply");
CssJs.unsafe("mixBlendMode", "screen");
CssJs.unsafe("mixBlendMode", "overlay");
CssJs.unsafe("mixBlendMode", "darken");
CssJs.unsafe("mixBlendMode", "lighten");
CssJs.unsafe("mixBlendMode", "color-dodge");
CssJs.unsafe("mixBlendMode", "color-burn");
CssJs.unsafe("mixBlendMode", "hard-light");
CssJs.unsafe("mixBlendMode", "soft-light");
CssJs.unsafe("mixBlendMode", "difference");
CssJs.unsafe("mixBlendMode", "exclusion");
CssJs.unsafe("mixBlendMode", "hue");
CssJs.unsafe("mixBlendMode", "saturation");
CssJs.unsafe("mixBlendMode", "color");
CssJs.unsafe("mixBlendMode", "luminosity");
CssJs.unsafe("isolation", "auto");
CssJs.unsafe("isolation", "isolate");
CssJs.unsafe("backgroundBlendMode", "normal");
CssJs.unsafe("backgroundBlendMode", "multiply");
CssJs.unsafe("backgroundBlendMode", "screen");
CssJs.unsafe("backgroundBlendMode", "overlay");
CssJs.unsafe("backgroundBlendMode", "darken");
CssJs.unsafe("backgroundBlendMode", "lighten");
CssJs.unsafe("backgroundBlendMode", "color-dodge");
CssJs.unsafe("backgroundBlendMode", "color-burn");
CssJs.unsafe("backgroundBlendMode", "hard-light");
CssJs.unsafe("backgroundBlendMode", "soft-light");
CssJs.unsafe("backgroundBlendMode", "difference");
CssJs.unsafe("backgroundBlendMode", "exclusion");
CssJs.unsafe("backgroundBlendMode", "hue");
CssJs.unsafe("backgroundBlendMode", "saturation");
CssJs.unsafe("backgroundBlendMode", "color");
CssJs.unsafe("backgroundBlendMode", "luminosity");
CssJs.unsafe("backgroundBlendMode", "normal, multiply");
CssJs.unsafe("display", "run-in");
CssJs.unsafe("display", "flow");
CssJs.unsafe("display", "flow-root");
CssJs.unsafe("filter", "none");
CssJs.unsafe("filter", "url(#id)");
CssJs.unsafe("filter", "url(image.svg#id)");
CssJs.unsafe("filter", "blur(5px)");
CssJs.unsafe("filter", "brightness(0.5)");
CssJs.unsafe("filter", "contrast(150%)");
CssJs.unsafe("filter", "drop-shadow(15px 15px 15px black)");
CssJs.unsafe("filter", "grayscale(50%)");
CssJs.unsafe("filter", "hue-rotate(50deg)");
CssJs.unsafe("filter", "invert(50%)");
CssJs.unsafe("filter", "opacity(50%)");
CssJs.unsafe("filter", "sepia(50%)");
CssJs.unsafe("filter", "saturate(150%)");
CssJs.unsafe("filter", "grayscale(100%) sepia(100%)");
CssJs.unsafe("backdropFilter", "none");
CssJs.unsafe("backdropFilter", "url(#id)");
CssJs.unsafe("backdropFilter", "url(image.svg#id)");
CssJs.unsafe("backdropFilter", "blur(5px)");
CssJs.unsafe("backdropFilter", "brightness(0.5)");
CssJs.unsafe("backdropFilter", "contrast(150%)");
CssJs.unsafe("backdropFilter", "drop-shadow(15px 15px 15px black)");
CssJs.unsafe("backdropFilter", "grayscale(50%)");
CssJs.unsafe("backdropFilter", "hue-rotate(50deg)");
CssJs.unsafe("backdropFilter", "invert(50%)");
CssJs.unsafe("backdropFilter", "opacity(50%)");
CssJs.unsafe("backdropFilter", "sepia(50%)");
CssJs.unsafe("backdropFilter", "saturate(150%)");
CssJs.unsafe("backdropFilter", "grayscale(100%) sepia(100%)");
CssJs.unsafe("touchAction", "auto");
CssJs.unsafe("touchAction", "none");
CssJs.unsafe("touchAction", "pan-x");
CssJs.unsafe("touchAction", "pan-y");
CssJs.unsafe("touchAction", "pan-x pan-y");
CssJs.unsafe("touchAction", "manipulation");
CssJs.unsafe("touchAction", "pan-left");
CssJs.unsafe("touchAction", "pan-right");
CssJs.unsafe("touchAction", "pan-up");
CssJs.unsafe("touchAction", "pan-down");
CssJs.unsafe("touchAction", "pan-left pan-up");
CssJs.unsafe("touchAction", "pinch-zoom");
CssJs.unsafe("touchAction", "pan-x pinch-zoom");
CssJs.unsafe("touchAction", "pan-y pinch-zoom");
CssJs.unsafe("touchAction", "pan-x pan-y pinch-zoom");
CssJs.unsafe("breakBefore", "auto");
CssJs.unsafe("breakBefore", "avoid");
CssJs.unsafe("breakBefore", "avoid-page");
CssJs.unsafe("breakBefore", "page");
CssJs.unsafe("breakBefore", "left");
CssJs.unsafe("breakBefore", "right");
CssJs.unsafe("breakBefore", "recto");
CssJs.unsafe("breakBefore", "verso");
CssJs.unsafe("breakBefore", "avoid-column");
CssJs.unsafe("breakBefore", "column");
CssJs.unsafe("breakBefore", "avoid-region");
CssJs.unsafe("breakBefore", "region");
CssJs.unsafe("breakAfter", "auto");
CssJs.unsafe("breakAfter", "avoid");
CssJs.unsafe("breakAfter", "avoid-page");
CssJs.unsafe("breakAfter", "page");
CssJs.unsafe("breakAfter", "left");
CssJs.unsafe("breakAfter", "right");
CssJs.unsafe("breakAfter", "recto");
CssJs.unsafe("breakAfter", "verso");
CssJs.unsafe("breakAfter", "avoid-column");
CssJs.unsafe("breakAfter", "column");
CssJs.unsafe("breakAfter", "avoid-region");
CssJs.unsafe("breakAfter", "region");
CssJs.unsafe("breakInside", "auto");
CssJs.unsafe("breakInside", "avoid");
CssJs.unsafe("breakInside", "avoid-page");
CssJs.unsafe("breakInside", "avoid-column");
CssJs.unsafe("breakInside", "avoid-region");
CssJs.unsafe("boxDecorationBreak", "slice");
CssJs.unsafe("boxDecorationBreak", "clone");
CssJs.unsafe("orphans", "1");
CssJs.unsafe("orphans", "2");
CssJs.widows(1);
CssJs.widows(2);
CssJs.unsafe("position", "sticky");
CssJs.unsafe("willChange", "scroll-position");
CssJs.unsafe("willChange", "contents");
CssJs.unsafe("willChange", "transform");
CssJs.unsafe("willChange", "top, left");
CssJs.unsafe("scrollBehavior", "auto");
CssJs.unsafe("scrollBehavior", "smooth");
CssJs.unsafe("display", "ruby");
CssJs.unsafe("display", "ruby-base");
CssJs.unsafe("display", "ruby-text");
CssJs.unsafe("display", "ruby-base-container");
CssJs.unsafe("display", "ruby-text-container");
CssJs.unsafe("scrollMargin", "0px");
CssJs.unsafe("scrollMargin", "6px 5px");
CssJs.unsafe("scrollMargin", "10px 20px 30px");
CssJs.unsafe("scrollMargin", "10px 20px 30px 40px");
CssJs.unsafe("scrollMargin", "20px 3em 1in 5rem");
CssJs.unsafe("scrollMarginBlock", "10px");
CssJs.unsafe("scrollMarginBlock", "10px 10px");
CssJs.unsafe("scrollMarginBlockEnd", "10px");
CssJs.unsafe("scrollMarginBlockStart", "10px");
CssJs.unsafe("scrollMarginBottom", "10px");
CssJs.unsafe("scrollMarginInline", "10px");
CssJs.unsafe("scrollMarginInline", "10px 10px");
CssJs.unsafe("scrollMarginInlineStart", "10px");
CssJs.unsafe("scrollMarginInlineEnd", "10px");
CssJs.unsafe("scrollMarginLeft", "10px");
CssJs.unsafe("scrollMarginRight", "10px");
CssJs.unsafe("scrollMarginTop", "10px");
CssJs.unsafe("scrollPadding", "auto");
CssJs.unsafe("scrollPadding", "0px");
CssJs.unsafe("scrollPadding", "6px 5px");
CssJs.unsafe("scrollPadding", "10px 20px 30px");
CssJs.unsafe("scrollPadding", "10px 20px 30px 40px");
CssJs.unsafe("scrollPadding", "10px auto 30px auto");
CssJs.unsafe("scrollPadding", "10%");
CssJs.unsafe("scrollPadding", "20% 3em 1in 5rem");
CssJs.unsafe("scrollPaddingBlock", "10px");
CssJs.unsafe("scrollPaddingBlock", "50%");
CssJs.unsafe("scrollPaddingBlock", "10px 50%");
CssJs.unsafe("scrollPaddingBlock", "50% 50%");
CssJs.unsafe("scrollPaddingBlockEnd", "10px");
CssJs.unsafe("scrollPaddingBlockEnd", "50%");
CssJs.unsafe("scrollPaddingBlockStart", "10px");
CssJs.unsafe("scrollPaddingBlockStart", "50%");
CssJs.unsafe("scrollPaddingBottom", "10px");
CssJs.unsafe("scrollPaddingBottom", "50%");
CssJs.unsafe("scrollPaddingInline", "10px");
CssJs.unsafe("scrollPaddingInline", "50%");
CssJs.unsafe("scrollPaddingInline", "10px 50%");
CssJs.unsafe("scrollPaddingInline", "50% 50%");
CssJs.unsafe("scrollPaddingInlineEnd", "10px");
CssJs.unsafe("scrollPaddingInlineEnd", "50%");
CssJs.unsafe("scrollPaddingInlineStart", "10px");
CssJs.unsafe("scrollPaddingInlineStart", "50%");
CssJs.unsafe("scrollPaddingLeft", "10px");
CssJs.unsafe("scrollPaddingLeft", "50%");
CssJs.unsafe("scrollPaddingRight", "10px");
CssJs.unsafe("scrollPaddingRight", "50%");
CssJs.unsafe("scrollPaddingTop", "10px");
CssJs.unsafe("scrollPaddingTop", "50%");
CssJs.unsafe("scrollSnapAlign", "none");
CssJs.unsafe("scrollSnapAlign", "start");
CssJs.unsafe("scrollSnapAlign", "end");
CssJs.unsafe("scrollSnapAlign", "center");
CssJs.unsafe("scrollSnapAlign", "none start");
CssJs.unsafe("scrollSnapAlign", "end center");
CssJs.unsafe("scrollSnapAlign", "center start");
CssJs.unsafe("scrollSnapAlign", "end none");
CssJs.unsafe("scrollSnapAlign", "center center");
CssJs.unsafe("scrollSnapStop", "normal");
CssJs.unsafe("scrollSnapStop", "always");
CssJs.unsafe("scrollSnapType", "none");
CssJs.unsafe("scrollSnapType", "x mandatory");
CssJs.unsafe("scrollSnapType", "y mandatory");
CssJs.unsafe("scrollSnapType", "block mandatory");
CssJs.unsafe("scrollSnapType", "inline mandatory");
CssJs.unsafe("scrollSnapType", "both mandatory");
CssJs.unsafe("scrollSnapType", "x proximity");
CssJs.unsafe("scrollSnapType", "y proximity");
CssJs.unsafe("scrollSnapType", "block proximity");
CssJs.unsafe("scrollSnapType", "inline proximity");
CssJs.unsafe("scrollSnapType", "both proximity");
CssJs.unsafe("overflowAnchor", "none");
CssJs.unsafe("overflowAnchor", "auto");
CssJs.unsafe("captionSide", "inline-start");
CssJs.unsafe("captionSide", "inline-end");
CssJs.unsafe("float", "inline-start");
CssJs.unsafe("float", "inline-end");
CssJs.unsafe("clear", "inline-start");
CssJs.unsafe("clear", "inline-end");
CssJs.textAlign(`start);
CssJs.textAlign(`end_);
CssJs.unsafe("resize", "block");
CssJs.unsafe("resize", "inline");
CssJs.unsafe("blockSize", "100px");
CssJs.unsafe("inlineSize", "100px");
CssJs.unsafe("minBlockSize", "100px");
CssJs.unsafe("minInlineSize", "100px");
CssJs.unsafe("maxBlockSize", "100px");
CssJs.unsafe("maxInlineSize", "100px");
CssJs.unsafe("marginBlock", "10px");
CssJs.unsafe("marginBlock", "10px 10px");
CssJs.unsafe("marginBlockStart", "10px");
CssJs.unsafe("marginBlockEnd", "10px");
CssJs.unsafe("marginInline", "10px");
CssJs.unsafe("marginInline", "10px 10px");
CssJs.unsafe("marginInlineStart", "10px");
CssJs.unsafe("marginInlineEnd", "10px");
CssJs.unsafe("inset", "10px");
CssJs.unsafe("inset", "10px 10px");
CssJs.unsafe("inset", "10px 10px 10px");
CssJs.unsafe("inset", "10px 10px 10px 10px");
CssJs.unsafe("insetBlock", "10px");
CssJs.unsafe("insetBlock", "10px 10px");
CssJs.unsafe("insetBlockStart", "10px");
CssJs.unsafe("insetBlockEnd", "10px");
CssJs.unsafe("insetInline", "10px");
CssJs.unsafe("insetInline", "10px 10px");
CssJs.unsafe("insetInlineStart", "10px");
CssJs.unsafe("insetInlineEnd", "10px");
CssJs.unsafe("paddingBlock", "10px");
CssJs.unsafe("paddingBlock", "10px 10px");
CssJs.unsafe("paddingBlockStart", "10px");
CssJs.unsafe("paddingBlockEnd", "10px");
CssJs.unsafe("paddingInline", "10px");
CssJs.unsafe("paddingInline", "10px 10px");
CssJs.unsafe("paddingInlineStart", "10px");
CssJs.unsafe("paddingInlineEnd", "10px");
CssJs.unsafe("borderBlock", "1px");
CssJs.unsafe("borderBlock", "2px dotted");
CssJs.unsafe("borderBlock", "medium dashed green");
CssJs.unsafe("borderBlockStart", "1px");
CssJs.unsafe("borderBlockStart", "2px dotted");
CssJs.unsafe("borderBlockStart", "medium dashed green");
CssJs.unsafe("borderBlockStartWidth", "thin");
CssJs.unsafe("borderBlockStartStyle", "dotted");
CssJs.unsafe("borderBlockStartColor", "navy");
CssJs.unsafe("borderBlockEnd", "1px");
CssJs.unsafe("borderBlockEnd", "2px dotted");
CssJs.unsafe("borderBlockEnd", "medium dashed green");
CssJs.unsafe("borderBlockEndWidth", "thin");
CssJs.unsafe("borderBlockEndStyle", "dotted");
CssJs.unsafe("borderBlockEndColor", "navy");
CssJs.unsafe("borderBlockColor", "navy blue");
CssJs.unsafe("borderInline", "1px");
CssJs.unsafe("borderInline", "2px dotted");
CssJs.unsafe("borderInline", "medium dashed green");
CssJs.unsafe("borderInlineStart", "1px");
CssJs.unsafe("borderInlineStart", "2px dotted");
CssJs.unsafe("borderInlineStart", "medium dashed green");
CssJs.unsafe("borderInlineStartWidth", "thin");
CssJs.unsafe("borderInlineStartStyle", "dotted");
CssJs.unsafe("borderInlineStartColor", "navy");
CssJs.unsafe("borderInlineEnd", "1px");
CssJs.unsafe("borderInlineEnd", "2px dotted");
CssJs.unsafe("borderInlineEnd", "medium dashed green");
CssJs.unsafe("borderInlineEndWidth", "thin");
CssJs.unsafe("borderInlineEndStyle", "dotted");
CssJs.unsafe("borderInlineEndColor", "navy");
CssJs.unsafe("borderInlineColor", "navy blue");
CssJs.unsafe("borderStartStartRadius", "0");
CssJs.unsafe("borderStartStartRadius", "50%");
CssJs.unsafe("borderStartStartRadius", "250px 100px");
CssJs.unsafe("borderStartEndRadius", "0");
CssJs.unsafe("borderStartEndRadius", "50%");
CssJs.unsafe("borderStartEndRadius", "250px 100px");
CssJs.unsafe("borderEndStartRadius", "0");
CssJs.unsafe("borderEndStartRadius", "50%");
CssJs.unsafe("borderEndStartRadius", "250px 100px");
CssJs.unsafe("borderEndEndRadius", "0");
CssJs.unsafe("borderEndEndRadius", "50%");
CssJs.unsafe("borderEndEndRadius", "250px 100px");
CssJs.unsafe("listStyleType", "disclosure-closed");
CssJs.unsafe("listStyleType", "disclosure-open");
CssJs.unsafe("listStyleType", "hebrew");
CssJs.unsafe("listStyleType", "cjk-decimal");
CssJs.unsafe("listStyleType", "cjk-ideographic");
CssJs.unsafe("listStyleType", "hiragana");
CssJs.unsafe("listStyleType", "katakana");
CssJs.unsafe("listStyleType", "hiragana-iroha");
CssJs.unsafe("listStyleType", "katakana-iroha");
CssJs.unsafe("listStyleType", "japanese-informal");
CssJs.unsafe("listStyleType", "japanese-formal");
CssJs.unsafe("listStyleType", "korean-hangul-formal");
CssJs.unsafe("listStyleType", "korean-hanja-informal");
CssJs.unsafe("listStyleType", "korean-hanja-formal");
CssJs.unsafe("listStyleType", "simp-chinese-informal");
CssJs.unsafe("listStyleType", "simp-chinese-formal");
CssJs.unsafe("listStyleType", "trad-chinese-informal");
CssJs.unsafe("listStyleType", "trad-chinese-formal");
CssJs.unsafe("listStyleType", "cjk-heavenly-stem");
CssJs.unsafe("listStyleType", "cjk-earthly-branch");
CssJs.unsafe("listStyleType", "trad-chinese-informal");
CssJs.unsafe("listStyleType", "trad-chinese-formal");
CssJs.unsafe("listStyleType", "simp-chinese-informal");
CssJs.unsafe("listStyleType", "simp-chinese-formal");
CssJs.unsafe("listStyleType", "japanese-informal");
CssJs.unsafe("listStyleType", "japanese-formal");
CssJs.unsafe("listStyleType", "arabic-indic");
CssJs.unsafe("listStyleType", "persian");
CssJs.unsafe("listStyleType", "urdu");
CssJs.unsafe("listStyleType", "devanagari");
CssJs.unsafe("listStyleType", "gurmukhi");
CssJs.unsafe("listStyleType", "gujarati");
CssJs.unsafe("listStyleType", "oriya");
CssJs.unsafe("listStyleType", "kannada");
CssJs.unsafe("listStyleType", "malayalam");
CssJs.unsafe("listStyleType", "bengali");
CssJs.unsafe("listStyleType", "tamil");
CssJs.unsafe("listStyleType", "telugu");
CssJs.unsafe("listStyleType", "thai");
CssJs.unsafe("listStyleType", "lao");
CssJs.unsafe("listStyleType", "myanmar");
CssJs.unsafe("listStyleType", "khmer");
CssJs.unsafe("listStyleType", "hangul");
CssJs.unsafe("listStyleType", "hangul-consonant");
CssJs.unsafe("listStyleType", "ethiopic-halehame");
CssJs.unsafe("listStyleType", "ethiopic-numeric");
CssJs.unsafe("listStyleType", "ethiopic-halehame-am");
CssJs.unsafe("listStyleType", "ethiopic-halehame-ti-er");
CssJs.unsafe("listStyleType", "ethiopic-halehame-ti-et");
CssJs.unsafe("listStyleType", "other-style");
CssJs.unsafe("listStyleType", "inside");
CssJs.unsafe("listStyleType", "outside");
CssJs.unsafe("listStyleType", "\\32 style");
CssJs.unsafe("listStyleType", "\"-\"");
CssJs.unsafe("listStyleType", "'-'");
CssJs.unsafe("counterReset", "foo");
CssJs.unsafe("counterReset", "foo 1");
CssJs.unsafe("counterReset", "foo 1 bar");
CssJs.unsafe("counterReset", "foo 1 bar 2");
CssJs.unsafe("counterReset", "none");
CssJs.unsafe("counterSet", "foo");
CssJs.unsafe("counterSet", "foo 1");
CssJs.unsafe("counterSet", "foo 1 bar");
CssJs.unsafe("counterSet", "foo 1 bar 2");
CssJs.unsafe("counterSet", "none");
CssJs.unsafe("counterIncrement", "foo");
CssJs.unsafe("counterIncrement", "foo 1");
CssJs.unsafe("counterIncrement", "foo 1 bar");
CssJs.unsafe("counterIncrement", "foo 1 bar 2");
CssJs.unsafe("counterIncrement", "none");
CssJs.unsafe("lineClamp", "none");
CssJs.unsafe("lineClamp", "1");
CssJs.unsafe("maxLines", "none");
CssJs.unsafe("maxLines", "1");
CssJs.overflowX(`visible);
CssJs.overflowX(`hidden);
CssJs.unsafe("overflowX", "clip");
CssJs.overflowX(`scroll);
CssJs.overflowX(`auto);
CssJs.overflowY(`visible);
CssJs.overflowY(`hidden);
CssJs.overflowY(`clip);
CssJs.overflowY(`scroll);
CssJs.overflowY(`auto);
CssJs.unsafe("overflowInline", "visible");
CssJs.unsafe("overflowInline", "hidden");
CssJs.unsafe("overflowInline", "clip");
CssJs.unsafe("overflowInline", "scroll");
CssJs.unsafe("overflowInline", "auto");
CssJs.unsafe("overflowBlock", "visible");
CssJs.unsafe("overflowBlock", "hidden");
CssJs.unsafe("overflowBlock", "clip");
CssJs.unsafe("overflowBlock", "scroll");
CssJs.unsafe("overflowBlock", "auto");
CssJs.unsafe("contain", "none");
CssJs.unsafe("contain", "strict");
CssJs.unsafe("contain", "content");
CssJs.unsafe("contain", "size");
CssJs.unsafe("contain", "layout");
CssJs.unsafe("contain", "paint");
CssJs.unsafe("contain", "size layout");
CssJs.unsafe("contain", "size paint");
CssJs.unsafe("contain", "size layout paint");
CssJs.unsafe("contain", "style");
CssJs.unsafe("contain", "size style");
CssJs.unsafe("contain", "size layout style");
CssJs.unsafe("contain", "size layout style paint");
CssJs.width(`maxContent);
CssJs.width(`minContent);
CssJs.unsafe("width", "fit-content(10%)");
CssJs.minWidth(`maxContent);
CssJs.minWidth(`minContent);
CssJs.unsafe("minWidth", "fit-content(10%)");
CssJs.maxWidth(`maxContent);
CssJs.maxWidth(`minContent);
CssJs.unsafe("maxWidth", "fit-content(10%)");
CssJs.height(`maxContent);
CssJs.height(`minContent);
CssJs.unsafe("height", "fit-content(10%)");
CssJs.minHeight(`maxContent);
CssJs.minHeight(`minContent);
CssJs.unsafe("minHeight", "fit-content(10%)");
CssJs.maxHeight(`maxContent);
CssJs.maxHeight(`minContent);
CssJs.unsafe("maxHeight", "fit-content(10%)");
CssJs.unsafe("aspectRatio", "auto");
CssJs.width(`fitContent);
CssJs.minWidth(`fitContent);
CssJs.maxWidth(`fitContent);
CssJs.height(`fitContent);
CssJs.minHeight(`fitContent);
CssJs.maxHeight(`fitContent);
CssJs.unsafe("overscrollBehavior", "contain");
CssJs.unsafe("overscrollBehavior", "none");
CssJs.unsafe("overscrollBehavior", "auto");
CssJs.unsafe("overscrollBehavior", "contain contain");
CssJs.unsafe("overscrollBehavior", "none contain");
CssJs.unsafe("overscrollBehavior", "auto contain");
CssJs.unsafe("overscrollBehavior", "contain none");
CssJs.unsafe("overscrollBehavior", "none none");
CssJs.unsafe("overscrollBehavior", "auto none");
CssJs.unsafe("overscrollBehavior", "contain auto");
CssJs.unsafe("overscrollBehavior", "none auto");
CssJs.unsafe("overscrollBehavior", "auto auto");
CssJs.unsafe("overscrollBehaviorX", "contain");
CssJs.unsafe("overscrollBehaviorX", "none");
CssJs.unsafe("overscrollBehaviorX", "auto");
CssJs.unsafe("overscrollBehaviorY", "contain");
CssJs.unsafe("overscrollBehaviorY", "none");
CssJs.unsafe("overscrollBehaviorY", "auto");
CssJs.unsafe("overscrollBehaviorInline", "contain");
CssJs.unsafe("overscrollBehaviorInline", "none");
CssJs.unsafe("overscrollBehaviorInline", "auto");
CssJs.unsafe("overscrollBehaviorBlock", "contain");
CssJs.unsafe("overscrollBehaviorBlock", "none");
CssJs.unsafe("overscrollBehaviorBlock", "auto");
CssJs.unsafe("scrollbarColor", "auto");
CssJs.unsafe("scrollbarColor", "dark");
CssJs.unsafe("scrollbarColor", "light");
CssJs.unsafe("scrollbarColor", "red blue");
CssJs.unsafe("scrollbarWidth", "auto");
CssJs.unsafe("scrollbarWidth", "thin");
CssJs.unsafe("scrollbarWidth", "none");
CssJs.unsafe("pointerEvents", "auto");
CssJs.unsafe("pointerEvents", "visiblePainted");
CssJs.unsafe("pointerEvents", "visibleFill");
CssJs.unsafe("pointerEvents", "visibleStroke");
CssJs.unsafe("pointerEvents", "visible");
CssJs.unsafe("pointerEvents", "painted");
CssJs.unsafe("pointerEvents", "fill");
CssJs.unsafe("pointerEvents", "stroke");
CssJs.unsafe("pointerEvents", "all");
CssJs.unsafe("pointerEvents", "none");
CssJs.lineHeightStep(`pxFloat(30.));
CssJs.lineHeightStep(`em(2.));
CssJs.width(`calc((`add, `percent(50.), `pxFloat(4.))));
CssJs.width(`calc((`sub, `pxFloat(20.), `pxFloat(10.))));
CssJs.width(
  `calc((`sub, `vh(100.), `calc((`add, `rem(2.), `pxFloat(120.))))),
);
CssJs.width(
  `calc((
    `sub,
    `vh(100.),
    `calc((
      `add,
      `rem(2.),
      `calc((
        `add,
        `rem(2.),
        `calc((`add, `rem(2.), `calc((`add, `rem(2.), `pxFloat(120.))))),
      )),
    )),
  )),
);
