Regression guard for the label-sensitivity facet of the [%css] var hash
collision.

One module, two bindings (`header` and `bar`) carrying the *identical*
interpolated declaration `background-color: $(Color.Background.Alt.box)`.
They differ only by their `let` label.

The class name embeds the label (`css-<content-hash>-<label>`), so the two
bindings get distinct class names. But the interpolation `var(--var-...)`
name is derived from the label-independent namespace (`css-<content-hash>`,
`class_and_namespace` in Css_file.re), so byte-identical declarations
collapse to the SAME variable regardless of label. Before the fix the
namespace was the label-bearing class-name join, so `header` and `bar`
hashed to different variables for the same declaration.

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css

The same declaration body resolves to a single variable across both labels:

  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-8rqac1-header{background-color:var(--var-11ifi3f);}
  .css-8rqac1-bar{background-color:var(--var-11ifi3f);}
