`--layers` wraps each library's rules in a named `@layer`, in the same
dependency order as the default (unlayered) output. `@property` and
`@keyframes` rules are global registrations and stay outside every layer,
ahead of the `@layer` order statement. Both rules here are unconditional,
so both land in the `styled-ppx.base` cascade tier - see `tiers-with-
layers.t` for a library's rules split across tiers.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base")]]
  > [@@@css "@property --z-base-color { syntax: '<color>'; inherits: false; initial-value: red; }"]
  > [@@@css "@keyframes z-base-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }"]
  > [@@@css ".a-basewidget{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app")]]
  > [@@@css ".a-appmain{color:blue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate --layers a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --z-base-color { syntax: '<color>'; inherits: false; initial-value: red; }
  @keyframes z-base-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  @layer z_base, a_app;
  @layer z_base {
  .a-basewidget{color:red;}
  }
  @layer a_app {
  .a-appmain{color:blue;}
  }
  }
