A NUL-delimited sentinel `\000LONGIDENT\000` in a CSS rule string is
substituted with the resolved class name from the index. The sentinel
delimiter is byte 0x00, which cannot appear in valid CSS or in OCaml
string literals as plain text, so collisions are impossible.

  $ cat > a.ml <<EOF
  > [@@@css.bindings [("A.x", "resolved")]]
  > let x = CSS.make "resolved" []
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".container.\000A.x\000{color:red;}"]
  > [@@@css.refs [("A.x", "b.ml", 1, 0, 5)]]
  > let _ = A.x
  > EOF

  $ styled-ppx.generate a.ml b.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .container.resolved{color:red;}
