The `/gbp-monitor` shape (monorepo report "Round 3 analysis", cause #4): a
wrapper's descendant rule (`.in-j8vuse * { color }`, a bundle - no class
of its own on the subject, a bare `*`) sits textually AFTER the span's own
class (`.a-4esjgz{color}`). Same specificity (one class each, no
qualifiers beyond the bare-`*`/`.wrapper` selector for the first rule), so
without a third, lower tier the browser applies whichever is textually
LAST among the two that match - here the wrapper's blind reach, which is
backwards: the span's own class should always win over "whatever happens
to be under this wrapper".

  $ cat > gbp.ml <<EOF
  > [@@@css ".a-4esjgz{color:black;}"]
  > [@@@css ".in-j8vuse * {color:white;}"]
  > EOF

  $ styled-ppx.generate gbp.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.descendant {
  .in-j8vuse * {color:white;}
  }
  @layer styled-ppx.base {
  .a-4esjgz{color:black;}
  }

What the browser does now, and why: `styled-ppx.descendant` is declared
BEFORE `styled-ppx.base` in the `@layer` statement, so a `styled-ppx.
descendant` rule never beats a `styled-ppx.base` rule that also matches,
regardless of which one is textually later - the span's own `color:black`
now wins over the wrapper's `color:white`, restoring "an element's own
class beats an ancestor's blind reach for `*`/an unclassed descendant"
regardless of stylesheet position.

A subject WITH its own class - `.tiptap` here, or an `.id-...` class a
`$(binding)` reference would resolve to - is not this shape: it targets a
specific, identified element, not "whatever happens to be under here", so
it stays in `styled-ppx.base` exactly as before the descendant tier
existed.

  $ cat > classed_descendant.ml <<EOF
  > [@@@css ".a-wrap9k .tiptap{color:navy;}"]
  > EOF

  $ styled-ppx.generate classed_descendant.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-wrap9k .tiptap{color:navy;}
  }

A descendant rule that is ALSO wrapped in `@media` is still `descendant`,
not `conditional`: descendant-ness is a question of WHAT ELEMENT the rule
reaches for, independent of WHEN it applies, so an ancestor's blind reach
must lose to the child's own rule - conditional or not - regardless of
whether that ancestor's own reach also happens to be behind a media
query.

  $ cat > media_descendant.ml <<EOF
  > [@@@css "@media (min-width:600px){.in-k9x0pl > span{color:teal;}}"]
  > [@@@css ".a-childown:hover{color:maroon;}"]
  > EOF

  $ styled-ppx.generate media_descendant.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.descendant {
  @media (min-width:600px){.in-k9x0pl > span{color:teal;}}
  }
  @layer styled-ppx.conditional {
  .a-childown:hover{color:maroon;}
  }

`!important` on a descendant rule is the documented escape hatch: CSS
compares importance BEFORE layer order, so an `!important` descendant
declaration still beats a normal (non-`!important`) base declaration on
the same property, even though `styled-ppx.descendant` is the lowest
layer for everything else. `styled-ppx.generate` only decides which LAYER
a rule goes in - it does not, and cannot, change how the browser weighs
`!important` against layer order.

  $ cat > important_descendant.ml <<EOF
  > [@@@css ".in-zz001 * {color:red !important;}"]
  > [@@@css ".a-www002{color:blue;}"]
  > EOF

  $ styled-ppx.generate important_descendant.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.descendant {
  .in-zz001 * {color:red !important;}
  }
  @layer styled-ppx.base {
  .a-www002{color:blue;}
  }

What the browser does here, and why: normal declarations compare layer
order first (`descendant` loses to `base`), but `!important` declarations
compare importance FIRST and, among important declarations, the
EARLIEST-declared layer wins (the reverse of the normal-declaration rule) -
so `.in-zz001 * {color:red !important;}`, despite sitting in the lowest
layer, still beats `.a-www002{color:blue;}`'s plain declaration. This is
an intentional, CSS-spec-level escape hatch, not a gap in this design: an
author who needs a descendant override to truly win uses `!important`,
same as they always could to beat any other unconditional rule.
