Round 5 (monorepo report "Round 5 analysis"): the separate `styled-ppx.descendant`
tier is gone. It sat below `styled-ppx.base` unconditionally, so an ancestor's
descendant-shaped rule (see `is_descendant_shape` - a combinator reaching for
an unclassed subject: a bare element type, `*`, or a pseudo-class chain with
no class of its own) always lost to a child's own atom regardless of
specificity - fixing the one real tie (`/gbp-monitor` below) by breaking five
more patterns where the ancestor's rule is genuinely MORE specific and should
win, same as it did before tiers existed. Now a descendant-shaped rule stays
in the tier of its own CONTEXT - `conditional` if wrapped in `@media`/
`@supports`/`@container` or carrying a pseudo-class directly on its own
compound, `base` otherwise - exactly like any other rule, so real
specificity (or real layer order, for a conditional-vs-base pair) decides.
Within whichever tier it lands in, a descendant-shaped rule is still emitted
BEFORE own-element rules (the shorthand-before-longhand sort's new primary
key), so the one case that needed the old tier - a genuine specificity TIE -
still resolves to the child, since the later rule in a tie wins.

`/gbp-monitor` (monorepo report "Round 3 analysis", cause #4): a wrapper's
descendant rule (`._in_j8vuse * { color }`, a bundle - no class of its own on
the subject, a bare `*`) and the span's own class (`._a_4esjgz { color }`)
are genuinely TIED: one class selector each ((0,1,0) - `*` and the wrapper's
own class both contribute nothing beyond the one class), so without
something to break the tie the browser applies whichever is textually LAST.

  $ cat > gbp.ml <<EOF
  > [@@@css "._a_4esjgz{color:black;}"]
  > [@@@css "._in_j8vuse * {color:white;}"]
  > EOF

  $ styled-ppx.generate gbp.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._in_j8vuse * {color:white;}
  ._a_4esjgz{color:black;}
  }

What the browser does now, and why: both rules are unconditional and neither
carries a pseudo-class of its own, so both land in the same `styled-ppx.base`
layer - no layer-order tiebreak available, same as before tiers existed. The
descendant-shaped wrapper rule is emitted FIRST (the sort's new primary key),
so on the (0,1,0) vs (0,1,0) tie the span's own `color:black`, being LATER,
wins - restoring "an element's own class beats an ancestor's blind reach for
`*`/an unclassed descendant" without needing a dedicated lower layer for it.

A subject WITH its own class - `.tiptap` here, or an `.id-...` class a
`$(binding)` reference would resolve to - is not this shape: it targets a
specific, identified element, not "whatever happens to be under here", so it
is not reordered and stays wherever the shorthand-sort (or plain source
order) would otherwise put it.

  $ cat > classed_descendant.ml <<EOF
  > [@@@css "._a_wrap9k .tiptap{color:navy;}"]
  > EOF

  $ styled-ppx.generate classed_descendant.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_wrap9k .tiptap{color:navy;}
  }

Round 5 pattern: `.list li { display: grid }`. The wrapper's rule
(`._a_listwrap li`, one class + one type selector, specificity (0,1,1)) is
MORE specific than the li's own atom (`._a_liblock`, (0,1,0)) - real CSS
specificity, not stylesheet position, decides once both share the same
`base` layer, so the wrapper wins regardless of which one the sort emits
first (unlike the tied `/gbp-monitor` case above).

  $ cat > list_li.ml <<EOF
  > [@@@css "._a_listwrap li{display:grid;}"]
  > [@@@css "._a_liblock{display:block;}"]
  > EOF

  $ styled-ppx.generate list_li.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_listwrap li{display:grid;}
  ._a_liblock{display:block;}
  }

Round 5 pattern: `.field input { font-size: 16px }`. Same shape as
`.list li` above - `._a_fieldwrap input` is (0,1,1), the input's own atom
`._a_inputfs` is (0,1,0) - the wrapper wins by specificity, both in `base`.

  $ cat > field_input.ml <<EOF
  > [@@@css "._a_fieldwrap input{font-size:16px;}"]
  > [@@@css "._a_inputfs{font-size:14px;}"]
  > EOF

  $ styled-ppx.generate field_input.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_fieldwrap input{font-size:16px;}
  ._a_inputfs{font-size:14px;}
  }

Round 5 pattern: `@media (min-width:1280px) { .menu > :last-child {
margin-right: 0 } }` versus the item's own, unconditional `margin-right`
atom. The wrapper's rule is wrapped in `@media`, so it lands in
`styled-ppx.conditional`; the item's own atom is unconditional, so it lands
in `styled-ppx.base`. This is not a specificity question at all: `base` and
`conditional` are DIFFERENT layers, and `conditional` is declared AFTER
`base` in the `@layer` statement, so it always outranks `base` regardless of
either rule's specificity - the wrapper wins at that breakpoint.

  $ cat > media_menu.ml <<EOF
  > [@@@css "@media (min-width:1280px){._a_menuwrap > :last-child{margin-right:0;}}"]
  > [@@@css "._a_marginright{margin-right:24px;}"]
  > EOF

  $ styled-ppx.generate media_menu.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_marginright{margin-right:24px;}
  }
  @layer styled-ppx.conditional {
  @media (min-width:1280px){._a_menuwrap > :last-child{margin-right:0;}}
  }

Round 5 pattern: `.sameLineBadge > :first-child:not(:last-child) { display:
inline }`. The wrapper's rule is `.sameLineBadge` (one class) plus
`:first-child` plus `:not(:last-child)` (a negation pseudo-class's own
specificity is its argument's - here another pseudo-class), so three
pseudo-class-equivalents: specificity (0,3,0). The badge's own atom
(`._a_displaydesktop`) is (0,1,0). The wrapper is more specific, so it wins,
both unconditional and both in `base`.

  $ cat > same_line_badge.ml <<EOF
  > [@@@css "._a_badgewrap > :first-child:not(:last-child){display:inline;}"]
  > [@@@css "._a_displaydesktop{display:block;}"]
  > EOF

  $ styled-ppx.generate same_line_badge.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_badgewrap > :first-child:not(:last-child){display:inline;}
  ._a_displaydesktop{display:block;}
  }
