Round 5 (monorepo report "Round 5 analysis"): the separate `styled-ppx.descendant`
tier is gone. It sat below `styled-ppx.base` unconditionally, so an ancestor's
descendant-shaped rule (see `is_descendant_shape` - a combinator reaching for
an unclassed subject: a bare element type, `*`, or a pseudo-class chain with
no class of its own) always lost to a child's own atom regardless of
specificity - fixing the one real tie (`/gbp-monitor` below) by breaking five
more patterns where the ancestor's rule is genuinely MORE specific and should
win, same as it did before tiers existed. Now a descendant-shaped rule stays
in the tier of its own CONTEXT - `conditional` if wrapped in `@media`/
`@supports`/`@container` or carrying a pseudo-class directly on its own
compound, `base` otherwise - exactly like any other rule, so real
specificity decides, whichever of the two a rule lands in (`base` and
`conditional` share the one `styled-ppx.atoms` layer - see "Round 7b" at
the end of this file for a conditional-vs-base pair specificity has to
decide between; a `[%styled.global]` rule is a separate case, its own
lower `styled-ppx.global` layer, see `layers-global-tier.t`). Within
whichever tier it lands in, a descendant-shaped rule is still emitted
BEFORE own-element rules (the shorthand-before-longhand sort's new primary
key), so the one case that needed the old tier - a genuine specificity TIE -
still resolves to the child, since the later rule in a tie wins.

`/gbp-monitor` (monorepo report "Round 3 analysis", cause #4): a wrapper's
descendant rule (`._in_j8vuse * { color }`, a bundle - no class of its own on
the subject, a bare `*`) and the span's own class (`._a_4esjgz { color }`)
are genuinely TIED: one class selector each ((0,1,0) - `*` and the wrapper's
own class both contribute nothing beyond the one class), so without
something to break the tie the browser applies whichever is textually LAST.

  $ cat > gbp.ml <<EOF
  > [@@@css "._a_4esjgz{color:black;}"]
  > [@@@css "._in_j8vuse * {color:white;}"]
  > EOF

  $ styled-ppx.generate gbp.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._in_j8vuse * {color:white;}
  ._a_4esjgz{color:black;}
  }

What the browser does now, and why: both rules are unconditional and neither
carries a pseudo-class of its own, so both are classified `base` and land in
the same `styled-ppx.atoms` layer - no tier-order tiebreak available, same as
before tiers existed. The descendant-shaped wrapper rule is emitted FIRST
(the sort's own primary key, unrelated to tier order),
so on the (0,1,0) vs (0,1,0) tie the span's own `color:black`, being LATER,
wins - restoring "an element's own class beats an ancestor's blind reach for
`*`/an unclassed descendant" without needing a dedicated lower layer for it.

A subject WITH its own class - `.tiptap` here, or an `.id-...` class a
`$(binding)` reference would resolve to - is not this shape: it targets a
specific, identified element, not "whatever happens to be under here", so it
is not reordered and stays wherever the shorthand-sort (or plain source
order) would otherwise put it.

  $ cat > classed_descendant.ml <<EOF
  > [@@@css "._a_wrap9k .tiptap{color:navy;}"]
  > EOF

  $ styled-ppx.generate classed_descendant.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_wrap9k .tiptap{color:navy;}
  }

Round 5 pattern: `.list li { display: grid }`. The wrapper's rule
(`._a_listwrap li`, one class + one type selector, specificity (0,1,1)) is
MORE specific than the li's own atom (`._a_liblock`, (0,1,0)) - real CSS
specificity, not stylesheet position, decides once both share the same
`styled-ppx.atoms` layer, so the wrapper wins regardless of which one the
sort emits first (unlike the tied `/gbp-monitor` case above).

  $ cat > list_li.ml <<EOF
  > [@@@css "._a_listwrap li{display:grid;}"]
  > [@@@css "._a_liblock{display:block;}"]
  > EOF

  $ styled-ppx.generate list_li.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_listwrap li{display:grid;}
  ._a_liblock{display:block;}
  }

Round 5 pattern: `.field input { font-size: 16px }`. Same shape as
`.list li` above - `._a_fieldwrap input` is (0,1,1), the input's own atom
`._a_inputfs` is (0,1,0) - the wrapper wins by specificity; both classified
`base`, both in the one `styled-ppx.atoms` layer.

  $ cat > field_input.ml <<EOF
  > [@@@css "._a_fieldwrap input{font-size:16px;}"]
  > [@@@css "._a_inputfs{font-size:14px;}"]
  > EOF

  $ styled-ppx.generate field_input.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_fieldwrap input{font-size:16px;}
  ._a_inputfs{font-size:14px;}
  }

Round 5 pattern: `@media (min-width:1280px) { .menu > :last-child {
margin-right: 0 } }` versus the item's own, unconditional `margin-right`
atom. The wrapper's rule is wrapped in `@media`, so it is classified
`conditional`; the item's own atom is unconditional, so it is `base`. Both
share the one `styled-ppx.atoms` layer, so this IS a specificity question:
`._a_menuwrap > :last-child` is one class plus one pseudo-class, (0,1,1),
strictly more specific than the plain atom's (0,1,0) - the wrapper wins at
that breakpoint by specificity, same as it would with no tiers at all;
`generate.ml` also emits `conditional`-tier rules after `base`-tier ones
(see "Cascade tiers" in `generate.ml`), which would settle a genuine tie
the same way, but specificity alone already decides this pair.

  $ cat > media_menu.ml <<EOF
  > [@@@css "@media (min-width:1280px){._a_menuwrap > :last-child{margin-right:0;}}"]
  > [@@@css "._a_marginright{margin-right:24px;}"]
  > EOF

  $ styled-ppx.generate media_menu.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_marginright{margin-right:24px;}
  @media (min-width:1280px){._a_menuwrap > :last-child{margin-right:0;}}
  }

Round 5 pattern: `.sameLineBadge > :first-child:not(:last-child) { display:
inline }`. The wrapper's rule is `.sameLineBadge` (one class) plus
`:first-child` plus `:not(:last-child)` (a negation pseudo-class's own
specificity is its argument's - here another pseudo-class), so three
pseudo-class-equivalents: specificity (0,3,0). The badge's own atom
(`._a_displaydesktop`) is (0,1,0). The wrapper is more specific, so it wins;
both unconditional, both classified `base`, both in the one
`styled-ppx.atoms` layer.

  $ cat > same_line_badge.ml <<EOF
  > [@@@css "._a_badgewrap > :first-child:not(:last-child){display:inline;}"]
  > [@@@css "._a_displaydesktop{display:block;}"]
  > EOF

  $ styled-ppx.generate same_line_badge.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_badgewrap > :first-child:not(:last-child){display:inline;}
  ._a_displaydesktop{display:block;}
  }

Round 7b pattern (`sameLineBadge`, monorepo report "Round 7b"): the round-5
pattern above, but the badge's own override is narrower under
`@media` instead of unconditional: `._a_ancestor > :first-child:not
(:last-child) { display: inline }` (0,3,0, `base` - unconditional, no
pseudo-class on the wrapper's OWN compound) versus `@media
(max-width:1000px) { ._a_badgeblock { display: block } }` (0,1,0,
`conditional`). Round 7 (three SEPARATE CSS layers, `styled-ppx.base` <
`styled-ppx.conditional`) made every `conditional` rule outrank every
`base` rule regardless of specificity - so this less specific, narrower
override incorrectly beat the more specific ancestor rule at every
viewport width, making the badge `block` on narrow screens when it should
stay `inline` (163 of 167 monorepo pages differed at 375/1000px). This is
the real bug "Cascade tiers" in `generate.ml` (above) exists to fix:
putting `base` and `conditional` in the SAME `styled-ppx.atoms` layer
restores specificity between them, exactly like the
`media_menu.ml`/`same_line_badge.ml` cases above - the only difference
from `media_menu.ml` is which SIDE is more specific.

  $ cat > same_line_badge_media.ml <<EOF
  > [@@@css "._a_ancestor > :first-child:not(:last-child){display:inline;}"]
  > [@@@css "@media (max-width:1000px){._a_badgeblock{display:block;}}"]
  > EOF

  $ styled-ppx.generate same_line_badge_media.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_ancestor > :first-child:not(:last-child){display:inline;}
  @media (max-width:1000px){._a_badgeblock{display:block;}}
  }

What the browser does now, and why: both rules share the one
`styled-ppx.atoms` layer, so specificity is compared directly - (0,3,0)
beats (0,1,0),
whatever the viewport width and regardless of which rule is textually
later. The ancestor's `display:inline` wins even under 1000px, where the
media query matches and the round-7 design would have (wrongly) let the
less specific `._a_badgeblock` win by tier/layer order alone.
