The aggregator builds its (longident -> identity) index by collecting
every `[@@@css.bindings [...]]` attribute payload. The PPX emits these
attributes directly with fully-qualified longidents and each binding's
identity class, so the aggregator does not parse `CSS.make` calls or
infer module names from filenames.

  $ cat > a.ml <<EOF
  > [@@@css ".css-a-marker{}"]
  > [@@@css.bindings [("A.marker", "cid-a-marker", "css-a-marker")]]
  > let marker = CSS.make "cid-a-marker css-a-marker" []
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".css-b-container.\000A.marker\000{padding:1rem;}"]
  > [@@@css.refs [("A.marker", "b.ml", 1, 0, 8)]]
  > [@@@css.bindings [("B.container", "cid-b-container", "css-b-container")]]
  > let _ = A.marker
  > let container = CSS.make "cid-b-container css-b-container" []
  > EOF

  $ styled-ppx.generate a.ml b.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-a-marker{}
  .css-b-container.cid-a-marker{padding:1rem;}
