This test ensures the ppx generates minified CSS output when --minify flag is used

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .a-14ksm7b{color:blue;}.a-eaeacs{margin:10px;}.a-k008qs{display:flex;}.a-1tyndxa{justify-content:center;}.a-zcxndt{align-items:center;}.a-f5yfbg{background-color:red;}.a-v1pg77{padding:20px 15px;}.a-e42auv{border:1px solid black;}

