This test ensures the ppx generates minified CSS output when --minify flag is used

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;@layer styled-ppx.base{._a_4esm7b{color:blue;}._a_7peacs{margin:10px;}._a_5r08qs{display:flex;}._a_9h002ndxa{justify-content:center;}._a_9i001xndt{align-items:center;}._a_39004yfbg{background-color:red;}._a_94pg77{padding:20px 15px;}._a_3h2auv{border:1px solid black;}}

