This test ensures the ppx generates minified CSS output when --minify flag is used

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-14jcta0{color:blue;}.css-1oedmff{margin:10px;}.css-17vxl0k{display:flex;}.css-w5s1ik{justify-content:center;}.css-17m4bmy{align-items:center;}.css-xm7cbz{background-color:red;}.css-7tfrl3{padding:20px 15px;}.css-18htonh{border:1px solid black;}

