Test content-property interpolation support in cx2.
Exercises all four counter-related gaps: single/multi Content.t interpolation,
inline argument interpolation, counters() in content-list, and single-arg
counter().

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-sikia9{content:var(--var-1nqzk4j);}
  .css-1tainop{content:var(--var-1usmzk5);}
  .css-10brgn5{content:var(--var-xgh2f5);}
  .css-zh4bht{content:var(--var-bqhjp7);}
  .css-ffxo1r{content:var(--var-1w7vz0s);}
  .css-e7wury{content:var(--var-1dsls0m);}
  .css-16jow5p{content:var(--var-3dh4pt);}
  .css-8nx65k-getListItemDecorationContent{content:var(--var-1wxdcn0);}
  .css-ymi9m2{content:counter(var(--var-1838dwt), lower-alpha);}
  .css-1hqoizr{content:counter(chapter, var(--var-1eyxcqb));}
  .css-1uqb9bz{content:counter(var(--var-1838dwt), var(--var-1eyxcqb));}
  .css-1ghcaxs{content:counters(var(--var-1838dwt), ".", var(--var-1eyxcqb));}
  .css-x7dhko{content:counter(ol);}
  .css-1igtirf{content:counter(chapter);}
  .css-ufyh7z{content:counters(section, ".");}
  .css-j8o8sv{content:counters(section, ".", decimal-leading-zero);}
  .css-p698h{content:var(--var-u1bkd);}
  .css-1e3j96l{content:var(--var-8u2acb);}
