`@media screen and (min-width: ...)` is the dominant real shape for a
`min-width`/`max-width` query (a leading media type before the feature),
not the bare `@media (min-width: ...)` this package's own earlier fixtures
use. The type clause's own `and` must not be mistaken for a compound
feature query's `and` (`(min-width:...) and (max-width:...)`, which
genuinely has no single width to sort by) - both are just the substring
`" and "` once lowercased.

`q` (900px, blue) is declared BEFORE `p` (600px, red) in the source. If
the width reader bails out on the type clause's `and`, both rules read as
`None` and the sheet falls back to declaration order - `q` (900) then `p`
(600), so at `>=900px` `p` (textually last) wins, the wrong,
declaration-order-dependent result. The fixed reader strips the leading
`screen and ` clause before checking for a real compound query, resolves
both widths, and sorts ascending regardless of declaration order: `p`
(600) first, `q` (900) last, so `q` (blue) wins at `>=900px` instead.

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css
    "@media screen and (min-width: 900px) {._a_le6ro4et3o2{color:blue;}}"]
  [@@@css "@media screen and (min-width: 600px) {._a_3x2xo4eri2s{color:red;}}"]
  [@@@css.bindings
    [("Input.q", "_id_f1usid", "_a_le6ro4et3o2");
    ("Input.p", "_id_1hp88j8", "_a_3x2xo4eri2s")]]
  let q = CSS.make "label:q _id_f1usid _a_le6ro4et3o2" []
  let p = CSS.make "label:p _id_1hp88j8 _a_3x2xo4eri2s" []
  let _ = (p, q)

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media screen and (min-width: 600px) {._a_3x2xo4eri2s{color:red;}}
  @media screen and (min-width: 900px) {._a_le6ro4et3o2{color:blue;}}
