The --log flag controls generator diagnostics on stderr; every message is
prefixed with `styled-ppx:`. The --debug flag is a shorthand for --log debug
and additionally dumps the generated stylesheet.

  $ cat > a.ml <<EOF
  > [@@@css ".a-widget{color:red;}"]
  > EOF

By default (--log warning), nothing is logged here: there are no errors
and no warnings to report.

  $ styled-ppx.generate --output out.css a.ml
  $ cat out.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-widget{color:red;}
  }

--log error stays quiet too.

  $ styled-ppx.generate --log error --output out.css a.ml

--log info prints the output file.

  $ styled-ppx.generate --log info --output out.css a.ml
  styled-ppx: output file: out.css
  styled-ppx: library order: .
  styled-ppx: order: .: A
  styled-ppx: environment: development

  $ styled-ppx.generate --log info a.ml
  styled-ppx: output file: stdout
  styled-ppx: library order: .
  styled-ppx: order: .: A
  styled-ppx: environment: development
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-widget{color:red;}
  }

--debug (same as --log debug) prints the output file and the whole stylesheet.

  $ styled-ppx.generate --debug --output out.css a.ml
  styled-ppx: output file: out.css
  styled-ppx: library order: .
  styled-ppx: order: .: A
  styled-ppx: environment: development
  styled-ppx: stylesheet:
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-widget{color:red;}
  }
  

  $ styled-ppx.generate --log debug --output out.css a.ml
  styled-ppx: output file: out.css
  styled-ppx: library order: .
  styled-ppx: order: .: A
  styled-ppx: environment: development
  styled-ppx: stylesheet:
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .a-widget{color:red;}
  }
  


--layers adds a "layers (<tier>): ..." line after the order lines, once per
cascade tier that owns a rule, listing the sanitized cascade-layer names in
library order.

  $ styled-ppx.generate --layers --log info --output out.css a.ml
  styled-ppx: output file: out.css
  styled-ppx: library order: .
  styled-ppx: order: .: A
  styled-ppx: environment: development
  styled-ppx: layers (styled-ppx.base): _

An unknown level is rejected up front.

  $ styled-ppx.generate --log silly a.ml
  styled-ppx: invalid --log level "silly" (expected "error", "warning", "info" or "debug")
  [2]

Errors are always printed, whatever the level.

  $ cat > broken.ml <<EOF
  > [@@@css 1]
  > EOF

  $ styled-ppx.generate --log error broken.ml
  styled-ppx: broken.ml: malformed [@@@css]: expected [@@@css] payload to be a string literal
  [1]
