/**
 * Generates the CSS coverage report (maintainer-facing: explicit missing
 * lists) by diffing the css-grammar registry (registry_dump.exe) against
 * the vendored @webref/css spec inventory. Data loading and derivations
 * live in scripts/css-oracle/data.mjs, shared with support-page.mjs.
 *
 * Usage: node scripts/css-oracle/report.mjs <registry-dump-file>
 * Output: packages/css-grammar/data/coverage.md (committed; CI checks it is
 * in sync via `make css-oracle-check`).
 */
import { writeFileSync } from "node:fs";
import { loadOracle, pageMargin, coveragePath } from "./data.mjs";

const {
  webref, atRuleStatus,
  stdProps, aliasProps, missing, missingAliases, extra,
  fnNames, missingFns,
  specMediaFeatures, missingMedia,
  specAtRules, handledAtRules,
} = loadOracle(process.argv[2]);

const lines = [];
const put = (s = "") => lines.push(s);

put("# CSS spec coverage");
put();
put("<!-- Generated by `make css-oracle`. Do not edit by hand. -->");
put(`<!-- Oracle: ${webref.source} ${webref.version} (${webref.updated}) -->`);
put();
put("Diff of styled-ppx's css-grammar registry against the machine-readable");
put(`W3C spec inventory (${webref.source} ${webref.version}). Regenerate with`);
put("`make css-oracle`; refresh the vendored spec data with");
put("`make css-oracle-update`.");
put();

put("## Summary");
put();
put("| Category | Spec | Covered | Missing |");
put("|---|---:|---:|---:|");
put(
  `| Properties (standard) | ${stdProps.length} | ${
    stdProps.length - missing.length
  } | ${missing.length} |`,
);
put(
  `| Properties (legacy aliases) | ${aliasProps.length} | ${
    aliasProps.length - missingAliases.length
  } | ${missingAliases.length} |`,
);
put(
  `| Functions | ${fnNames.length} | ${fnNames.length - missingFns.length} | ${
    missingFns.length
  } |`,
);
put(
  `| Media features (name inventory) | ${specMediaFeatures.length} | ${
    specMediaFeatures.length - missingMedia.length
  } | ${missingMedia.length} |`,
);
put(
  `| At-rules | ${specAtRules.length} | ${handledAtRules.length} | ${
    specAtRules.length - handledAtRules.length
  } |`,
);
put();

const section = (title, items, render = (x) => x) => {
  put(`## ${title}`);
  put();
  if (items.length === 0) {
    put("None.");
  } else {
    for (const item of items) put(`- ${render(item)}`);
  }
  put();
};

section(
  `Missing properties (${missing.length})`,
  missing,
  ([name, v]) =>
    `\`${name}\` (${v.spec})${v.syntax ? `: \`${v.syntax}\`` : ""}`,
);
section(
  `Missing legacy aliases (${missingAliases.length})`,
  missingAliases,
  ([name, v]) => `\`${name}\` → \`${v.legacyAliasOf}\``,
);
section(`Missing functions (${missingFns.length})`, missingFns, (f) => `\`${f}\``);
section(
  `Missing media features (${missingMedia.length})`,
  missingMedia,
  (f) => `\`${f}\``,
);

put("## At-rules");
put();
put("| At-rule | Status |");
put("|---|---|");
for (const name of specAtRules) {
  put(`| \`${name}\` | ${atRuleStatus(name)} |`);
}
put();
put(
  `Page-margin at-rules (${[...pageMargin].filter((a) => a in webref.atrules).length}, e.g. \`@top-left\`) and vendor-prefixed at-rules are grouped out of the table; see documents/at-rules.md.`,
);
put();

put("## Registry extras");
put();
put(
  `${extra.length} registered names are not in the spec inventory (vendor-prefixed properties, at-rule descriptors registered as properties, and legacy/compat entries). They are listed for audit only; they do not count against coverage.`,
);
put();
put("<details><summary>Show</summary>");
put();
for (const name of extra.sort()) put(`- \`${name}\``);
put();
put("</details>");

writeFileSync(coveragePath, lines.join("\n") + "\n");
console.log(
  `coverage: ${stdProps.length - missing.length}/${stdProps.length} standard properties, ` +
    `${missing.length} missing; report at packages/css-grammar/data/coverage.md`,
);
