/**
 * Generates the user-facing CSS support tables for the website from the
 * same oracle data as coverage.md (shared loaders in data.mjs, single
 * derivation chain from the css-grammar registry + @webref/css).
 *
 * Usage: node scripts/css-oracle/support-page.mjs <registry-dump-file>
 * Output: packages/website/src/generated/css-support-tables.mdx
 * (committed; imported by packages/website/content/css-support.mdx; CI
 * checks it is in sync via `make css-oracle-check`).
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { loadOracle, specUrl, supportFragmentPath } from "./data.mjs";

const {
  webref, atRuleStatus,
  stdProps, missing, propertiesBySpec,
  fnNames, missingFns,
  specMediaFeatures, missingMedia, mediaFeatures,
  specAtRules, handledAtRules,
} = loadOracle(process.argv[2]);

const coverageUrl =
  "https://github.com/davesnx/styled-ppx/blob/main/packages/css-grammar/data/coverage.md";

const lines = [];
const put = (s = "") => lines.push(s);

put("{/* Generated by `make css-oracle`. Do not edit by hand. */}");
put(`{/* Oracle: ${webref.source} ${webref.version} (${webref.updated}) */}`);
put();

/* ---- Summary ---- */
put("## Coverage summary");
put();
put(
  `Measured against the machine-readable W3C spec inventory ` +
    `([${webref.source}](https://github.com/w3c/webref) ${webref.version}, ${webref.updated}):`,
);
put();
put("| Category | Supported | In spec |");
put("|---|---:|---:|");
put(
  `| Properties | ${stdProps.length - missing.length} | ${stdProps.length} |`,
);
put(`| Functions | ${fnNames.length - missingFns.length} | ${fnNames.length} |`);
put(
  `| Media features | ${specMediaFeatures.length - missingMedia.length} | ${
    specMediaFeatures.length
  } |`,
);
put(`| At-rules | ${handledAtRules.length} | ${specAtRules.length} |`);
put();
put(
  `The full name-by-name diff, including every missing property and ` +
    `function, lives in the [coverage report](${coverageUrl}).`,
);
put();

/* ---- Properties by spec module ---- */
put("## Properties by spec module");
put();
put("✅ every property in the module parses, 🟠 some do, 🔴 none do yet.");
put();
put("| Spec module | Properties | Support |");
put("|---|---:|:---:|");
const statusEmoji = ({ covered, total }) =>
  covered === total ? "✅" : covered === 0 ? "🔴" : "🟠";
for (const spec of [...propertiesBySpec.keys()].sort()) {
  const { covered, total } = propertiesBySpec.get(spec);
  const url = specUrl(spec);
  const label =
    spec === "unknown" ? "SVG and MathML properties" : `\`${spec}\``;
  const cell = url ? `[${label}](${url})` : label;
  put(`| ${cell} | ${covered}/${total} | ${statusEmoji({ covered, total })} |`);
}
put();

/* ---- At-rules ---- */
put("## At-rules");
put();
put("| At-rule | Support |");
put("|---|---|");
for (const name of specAtRules) {
  put(`| \`${name}\` | ${atRuleStatus(name)} |`);
}
put();

/* ---- Media features ---- */
put("## Media features");
put();
const supportedMedia = specMediaFeatures.filter((f) => mediaFeatures.has(f));
put(
  `${supportedMedia.length} of the ${specMediaFeatures.length} media ` +
    `feature names from Media Queries 3–5 are recognized in \`@media\` preludes:`,
);
put();
put(supportedMedia.map((f) => `\`${f}\``).join(", "));
put();
if (missingMedia.length > 0) {
  put(`Not yet recognized: ${missingMedia.map((f) => `\`${f}\``).join(", ")}.`);
  put();
}

mkdirSync(dirname(supportFragmentPath), { recursive: true });
writeFileSync(supportFragmentPath, lines.join("\n") + "\n");
console.log(
  `support tables: ${specAtRules.length} at-rules, ${propertiesBySpec.size} spec modules; ` +
    `fragment at packages/website/src/generated/css-support-tables.mdx`,
);
