`hoverParent`'s own condition is `:hover`, but the rule reaches past it,
via a descendant combinator, to a referenced child (`.$(child)`) with its
own identity class: `._a_...:hover ._id_...{color:red;}`. Only the leading
`:hover` is this atom's own condition - the space and `._id_...` after it
are unrelated selector text for a DIFFERENT element (this rule styles the
referenced child, not `hoverParent`'s own element), and must not be
folded into the pseudo chain the priority key reads.

`linkOther`'s condition is `:link`, with no combinator at all:
`._a_...:link{color:blue;}`. This pins the SHEET ORDER `sort_conditional_
rules` produces for these two rules, driven by `pseudo_rank` alone
(both tie on descendant-shape, depth and at-rule rank, so pseudo rank is
what decides their relative position in the output) - not a claim about
which one "wins" on a shared element. The two rules have different
specificity (`.x:hover ._id_y` is (0,3,0); `.z:link` is (0,2,0)) and style
different elements (`hoverParent`'s own class never appears on
`linkOther`'s), so there is no real cascade tie between them to resolve
either way; sheet position is simply not a factor for either rule's own,
real winner. Before this fix, `hoverParent`'s mangled chain
(`":hover ._id_y"`) fell back to the shared default weight (40), which
happens to be LOWER than `:link`'s real weight (80), so `hoverParent`'s
rule sorted first; the fix reads `:hover`'s real weight (130), higher than
`:link`'s 80, so `hoverParent`'s rule now sorts LAST instead - the order
this test pins.

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css "._a_gkxe14ecml2:hover ._id_lzhoyz{color:red;}"]
  [@@@css "._a_6diiq4e3si2:link{color:blue;}"]
  [@@@css.bindings
    [("Input.child", "_id_lzhoyz", "");
    ("Input.hoverParent", "_id_c4o3cw", "_a_gkxe14ecml2");
    ("Input.linkOther", "_id_1ymz9gf", "_a_6diiq4e3si2")]]
  let child = CSS.make "label:child _id_lzhoyz" []
  let hoverParent = CSS.make "label:hoverParent _id_c4o3cw _a_gkxe14ecml2" []
  let linkOther = CSS.make "label:linkOther _id_1ymz9gf _a_6diiq4e3si2" []
  let _ = (child, hoverParent, linkOther)

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_6diiq4e3si2:link{color:blue;}
  ._a_gkxe14ecml2:hover ._id_lzhoyz{color:red;}
