The slider shape (`sliderMenuWrapper`, monorepo report "Round 3 analysis"):
one binding sets a base, always-on padding/margin via two interpolated
declarations (`padding: 0 $(px24); margin-left: $(px8);` - a genuine
two-declaration `in-` bundle, since both interpolate) and ALSO narrows that
padding under `@media (min-width:1280px)` with a literal, non-interpolated
override (`padding: 0 120px;` - its own real `a-` atom, a different
context). Dedup/emission order placed the base bundle AFTER the media
atom in the raw stylesheet (rule 3963 vs 3961 in the real sheet); same
specificity (one class each, no qualifiers), so without cascade tiers the
browser applies whichever rule is textually LAST among the two that
currently match - at a >=1280px viewport BOTH the base rule and the media
rule match, and the base rule, being later, incorrectly wins: the desktop
120px override never actually applies.

  $ cat > slider.ml <<EOF
  > [@@@css "@media (min-width:1280px){.a-desktop120{padding:0 120px;}}"]
  > [@@@css ".in-c09yqu{padding:0 24px;}"]
  > [@@@css ".in-c09yqu{margin-left:8px;}"]
  > EOF

  $ styled-ppx.generate slider.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  .in-c09yqu{padding:0 24px;}
  .in-c09yqu{margin-left:8px;}
  }
  @layer styled-ppx.conditional {
  @media (min-width:1280px){.a-desktop120{padding:0 120px;}}
  }

What the browser does now, and why: `styled-ppx.base` is declared before
`styled-ppx.conditional` in the `@layer` statement, so a `styled-ppx.base`
rule NEVER beats a `styled-ppx.conditional` rule that also matches,
regardless of which one is textually later within its own layer (CSS layer
order strictly outranks source order, and both rules keep the same, single-
class specificity they always had). At a >=1280px viewport, the media
atom (`styled-ppx.conditional`) now wins over the always-on bundle
(`styled-ppx.base`) even though the bundle's own two rules still render
textually after it, fixing the bug without needing `CSS.merge` to see
inside the bundle at all - the fix is stylesheet POSITION (by layer), not a
merge decision.
