The slider shape (`sliderMenuWrapper`):
one binding sets a base, always-on padding/margin via two interpolated
declarations (`padding: 0 $(px24); margin-left: $(px8);` - a genuine
two-declaration `_in_` bundle, since both interpolate) and ALSO narrows that
padding under `@media (min-width:1280px)` with a literal, non-interpolated
override (`padding: 0 120px;` - its own real `_a_` atom, a different
context). Dedup/emission order placed the base bundle AFTER the media
atom in the raw stylesheet (rule 3963 vs 3961 in the real sheet); same
specificity (one class each, no qualifiers), so without cascade tiers the
browser applies whichever rule is textually LAST among the two that
currently match - at a >=1280px viewport BOTH the base rule and the media
rule match, and the base rule, being later, incorrectly wins: the desktop
120px override never actually applies.

  $ cat > slider.ml <<EOF
  > [@@@css "@media (min-width:1280px){._a_desktop120{padding:0 120px;}}"]
  > [@@@css "._in_c09yqu{padding:0 24px;}"]
  > [@@@css "._in_c09yqu{margin-left:8px;}"]
  > EOF

  $ styled-ppx.generate slider.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._in_c09yqu{padding:0 24px;}
  ._in_c09yqu{margin-left:8px;}
  @media (min-width:1280px){._a_desktop120{padding:0 120px;}}

What the browser does now, and why: neither rule is layered, and both keep
the same, single-class specificity they always had, so the winner is still
whichever one is textually LAST - but `generate.ml` now controls that
position directly, emitting every `base`-tier rule before every
`conditional`-tier one (see `rule_tier`), regardless of dedup/emission
order in the raw, pre-sort rule list. The media atom, being a
`conditional`-tier rule, is emitted AFTER the always-on bundle no matter
which one dedup happened to produce first, so at a >=1280px viewport it
now wins - fixing the bug without needing `CSS.merge` to see inside the
bundle at all, and without needing a CSS layer to do it: ordering by TIER
is enough here because both rules are equally specific; see
`descendant-tier.t`'s `media_menu.ml` case for a pair where specificity, not
tier order, has to decide.
