When the indexed binding minted multiple atomized classes (space-
separated in the `[@@@css.bindings ...]` payload), the aggregator
converts them to a dot-chain on substitution: `"a b c"` becomes
`a.b.c`. This preserves "AND" semantics across atoms.

  $ cat > a.ml <<EOF
  > [@@@css.bindings [("A.multi", "atom1 atom2 atom3")]]
  > let multi = CSS.make "atom1 atom2 atom3" []
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".target.\000A.multi\000{color:red;}"]
  > [@@@css.refs [("A.multi", "b.ml", 1, 0, 7)]]
  > let _ = A.multi
  > EOF

  $ styled-ppx.generate a.ml b.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .target.atom1.atom2.atom3{color:red;}
