Statement at-rules (`@import`, `@namespace`) must precede every other rule
for a browser to honor them, and CSS Cascade 5 additionally requires every
`@import` to precede every `@namespace`. The aggregator hoists these two
kinds to the front of the output, `@import` block then `@namespace` block,
each keeping its own relative order, regardless of which module emitted them
or in what order: here `z_statements.ml` is ordered *after* `a_styles.ml`
(plain alphabetical order, no dependency edge between them), yet its
statements still come first.

`@charset` is dropped instead: the generated file always opens with its own
comment, so `@charset` could never be honored as the first bytes of the
stylesheet, and the output is UTF-8 regardless of what a module declares.
Dropping it is reported as a warning naming the input file.

Statement-form `@layer a, b;` is NOT hoisted with `@import`/`@namespace`:
CSS allows it anywhere in a stylesheet, and a layer's priority is fixed by
its name's first occurrence across the whole page, so moving it could
silently change which layer it introduces first - a hazard independent of
whether this aggregator wraps anything in a layer of its own. A literal
`@layer`-starting rule takes no part in tiering for exactly this reason,
the same as an `@property`/`@keyframes`/`@font-face` registration (see
"Cascade tiers" in the docs): it stays wherever dedup/ordering already
placed it relative to the style rules around it (`a_styles.ml`'s
`._a_styles`, tiered, ends up after it here).

  $ cat > a_styles.ml <<EOF
  > [@@@css "._a_styles{color:red;}"]
  > EOF

  $ cat > z_statements.ml <<EOF
  > [@@@css "@charset \"utf-8\";"]
  > [@@@css "@import url(\"reset.css\");"]
  > [@@@css "@namespace svg url(\"http://www.w3.org/2000/svg\");"]
  > [@@@css "@layer utilities, base;"]
  > EOF

  $ styled-ppx.generate a_styles.ml z_statements.ml
  styled-ppx: z_statements.ml: dropping @charset: the output already starts with a leading comment, so @charset could never be the first bytes of the stylesheet; output is UTF-8 regardless.
  /* This file is generated by styled-ppx, do not edit manually */
  @import url("reset.css");
  @namespace svg url("http://www.w3.org/2000/svg");
  @layer utilities, base;
  ._a_styles{color:red;}

`@import` before `@namespace` is required even when a module writes them in
the opposite order: here `b_reversed.ml` declares `@namespace` first, but
the aggregator still emits `@import` first.

  $ cat > b_reversed.ml <<EOF
  > [@@@css "@namespace svg url(\"urn:svg\");"]
  > [@@@css "@import url(\"reset.css\");"]
  > EOF

  $ styled-ppx.generate b_reversed.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @import url("reset.css");
  @namespace svg url("urn:svg");

A statement-form `@layer x, y;` that follows a block-form `@layer x { ... }`
stays after it: hoisting it ahead (as the old `{`-search classifier did,
since neither rule string contains a lone `{` outside the block) would move
`x`'s first occurrence, and with it the layer's cascade position.

  $ cat > c_layer_order.ml <<EOF
  > [@@@css "@layer base {.plain{color:red;}}"]
  > [@@@css "@layer theme, base;"]
  > EOF

  $ styled-ppx.generate c_layer_order.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer base {.plain{color:red;}}
  @layer theme, base;

An `@import` URL that itself contains `{` must still be classified by its
`@import ... ;` text, not by scanning for a literal `{`: the old classifier
took any `{` as proof of a block rule and would have emitted this `@import`
after the tiered rules instead of hoisting it.

  $ cat > d_import_brace.ml <<EOF
  > [@@@css "@import url(\"a{b.css\");"]
  > [@@@css "._a_dgreen{color:green;}"]
  > EOF

  $ styled-ppx.generate d_import_brace.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @import url("a{b.css");
  ._a_dgreen{color:green;}
