Statement at-rules (`@import`, `@namespace`, statement-form `@layer`) must
precede every other rule for a browser to honor them. The aggregator hoists
them to the front of the output regardless of which module emitted them, and
regardless of module order: here `z_statements.ml` is ordered *after*
`a_styles.ml` (plain alphabetical order, no dependency edge between them),
yet its statements still come first.

`@charset` is dropped instead: the generated file always opens with its own
comment, so `@charset` could never be honored as the first bytes of the
stylesheet, and the output is UTF-8 regardless of what a module declares.
Dropping it is reported as a warning naming the input file.

  $ cat > a_styles.ml <<EOF
  > [@@@css ".a{color:red;}"]
  > EOF

  $ cat > z_statements.ml <<EOF
  > [@@@css "@charset \"utf-8\";"]
  > [@@@css "@import url(\"reset.css\");"]
  > [@@@css "@namespace svg url(\"http://www.w3.org/2000/svg\");"]
  > [@@@css "@layer utilities, base;"]
  > EOF

  $ styled-ppx.generate a_styles.ml z_statements.ml
  styled-ppx: z_statements.ml: dropping @charset: the output already starts with a leading comment, so @charset could never be the first bytes of the stylesheet; output is UTF-8 regardless.
  /* This file is generated by styled-ppx, do not edit manually */
  @import url("reset.css");
  @namespace svg url("http://www.w3.org/2000/svg");
  @layer utilities, base;
  .a{color:red;}

`--layers` wraps each library's rules in a named `@layer`. Author statement
at-rules must precede both the aggregator's own `@layer <libraries>;`
statement and every wrapped block.

  $ styled-ppx.generate --layers a_styles.ml z_statements.ml
  styled-ppx: z_statements.ml: dropping @charset: the output already starts with a leading comment, so @charset could never be the first bytes of the stylesheet; output is UTF-8 regardless.
  /* This file is generated by styled-ppx, do not edit manually */
  @import url("reset.css");
  @namespace svg url("http://www.w3.org/2000/svg");
  @layer utilities, base;
  @layer _;
  @layer _ {
  .a{color:red;}
  }
