Statement at-rules must be hoisted to the top of the stylesheet.

[%styled.global] passes @charset, @import, @namespace, and statement-form
@layer through to the aggregator, but browsers only honor them at the top
of a stylesheet: a mid-sheet @import is silently ignored. The aggregator
concatenates rules in file order, so an @import contributed by a "late"
module would otherwise land mid-stylesheet (issue #581).

The emitted partition is: statement @layer, then @import, then @namespace
(the spec order: @import must precede @namespace, and @layer statements
that establish layer order are legal before @import), then everything else
— including block-form @layer, which must NOT move. @charset is dropped
with a warning: the generated asset is UTF-8, and a @charset anywhere but
the very first bytes of a file is invalid anyway.

  $ cat > early.ml <<EOF
  > [@@@css ".early{color:red;}"]
  > [@@@css "@layer base{.early-layered{color:blue;}}"]
  > EOF

  $ cat > late.ml <<EOF
  > [@@@css ".late{color:green;}"]
  > [@@@css "@import \"theme.css\";"]
  > [@@@css "@namespace svg url(http://www.w3.org/2000/svg);"]
  > [@@@css "@layer reset,base,components;"]
  > [@@@css "@charset \"utf-8\";"]
  > [@@@css "@media print{.late{color:black;}}"]
  > EOF

  $ styled-ppx.generate early.ml late.ml
  styled-ppx: dropping "@charset \"utf-8\";" from module Late: the generated stylesheet is UTF-8, and @charset is only honored as the very first bytes of a CSS file. Remove the @charset rule from [%styled.global].
  /* This file is generated by styled-ppx, do not edit manually */
  @layer reset,base,components;
  @import "theme.css";
  @namespace svg url(http://www.w3.org/2000/svg);
  .early{color:red;}
  @layer base{.early-layered{color:blue;}}
  .late{color:green;}
  @media print{.late{color:black;}}

Relative file order is preserved within each hoisted kind: two modules each
contributing @layer statements and @imports keep their order among
themselves, even though the kinds are partitioned.

  $ cat > one.ml <<EOF
  > [@@@css "@import \"one.css\";"]
  > [@@@css ".one{color:red;}"]
  > [@@@css "@layer one;"]
  > EOF

  $ cat > two.ml <<EOF
  > [@@@css "@layer two;"]
  > [@@@css "@import \"two.css\";"]
  > [@@@css ".two{color:blue;}"]
  > EOF

  $ styled-ppx.generate one.ml two.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer one;
  @layer two;
  @import "one.css";
  @import "two.css";
  .one{color:red;}
  .two{color:blue;}

Hoisted rules still dedup by exact string, keeping the first occurrence.

  $ cat > dup1.ml <<EOF
  > [@@@css "@import \"shared.css\";"]
  > [@@@css ".dup1{color:red;}"]
  > EOF

  $ cat > dup2.ml <<EOF
  > [@@@css "@import \"shared.css\";"]
  > [@@@css ".dup2{color:blue;}"]
  > EOF

  $ styled-ppx.generate dup1.ml dup2.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @import "shared.css";
  .dup1{color:red;}
  .dup2{color:blue;}

The @charset warning respects --log error, and the rule stays dropped.

  $ cat > cs.ml <<EOF
  > [@@@css "@charset \"utf-8\";"]
  > [@@@css ".cs{color:red;}"]
  > EOF

  $ styled-ppx.generate --log error cs.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .cs{color:red;}
