  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --output=./$TEST_OUTPUT/generated
  $ refmt --parse ml --print re output.ml
  let css = (right, bottom, left) =>
    CSS.make(
      "css-17vxl0k css-1641h1j css-1uzc9um",
      [
        ("--right", CSS.get_value_from_rule(CSS.margin(right))),
        ("--bottom", CSS.get_value_from_rule(CSS.margin(bottom))),
        ("--left", CSS.get_value_from_rule(CSS.margin(left))),
        (
          "--css-black",
          CSS.get_value_from_rule(CSS.backgroundColor(CSS.black)),
        ),
      ],
    );
  <div
    className={fst(css(CSS.px(10), CSS.px(10), CSS.px(10)))}
    style={snd(css(CSS.px(10), CSS.px(10), CSS.px(10)))}
  />;
  <span
    className={fst(CSS.make("css-17vxl0k", []))}
    style={snd(CSS.make("css-17vxl0k", []))}
  />;

  $ cat generated/styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  
  .css-17vxl0k { display: flex; }
  .css-1641h1j { margin: 8px var(--right) var(--bottom) var(--left); }
  .css-1uzc9um { background-color: var(--css-black); }
  
