  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml --output=./generated
  $ refmt --parse ml --print re output.ml
  let css = (right, bottom, left) =>
    CSS.make(
      "css-13ggymn",
      [
        ("--right", CSS.get_value_from_rule(CSS.margin(right))),
        ("--bottom", CSS.get_value_from_rule(CSS.margin(bottom))),
        ("--left", CSS.get_value_from_rule(CSS.margin(left))),
        (
          "--css-black",
          CSS.get_value_from_rule(CSS.backgroundColor(CSS.black)),
        ),
      ],
    );
  <div
    className={fst(css(CSS.px(10), CSS.px(10), CSS.px(10)))}
    style={snd(css(CSS.px(10), CSS.px(10), CSS.px(10)))}
  />;
  <span
    className={fst(CSS.make("css-17vxl0k", []))}
    style={snd(CSS.make("css-17vxl0k", []))}
  />;

  $ cat generated/styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  
  .css-13ggymn {display:flex;margin:8px var(--right) var(--bottom) var(--left);background-color:var(--css-black);}
  .css-17vxl0k {display:flex;}
  
