Test content-property interpolation support in cx2.
Exercises all four counter-related gaps: single/multi Content.t interpolation,
inline argument interpolation, counters() in content-list, and single-arg
counter().

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --singleCounter-ek68js{syntax:"*";inherits:false;}
  @property --singleCounterNoStyle-2521aj{syntax:"*";inherits:false;}
  @property --singleText-5c1v76{syntax:"*";inherits:false;}
  @property --counterDot-17rsat4{syntax:"*";inherits:false;}
  @property --counterSpace-jvqeh9{syntax:"*";inherits:false;}
  @property --counterRoman-16oxrf4{syntax:"*";inherits:false;}
  @property --bracketed-1vvjf8x{syntax:"*";inherits:false;}
  @property --content_value-jr2773{syntax:"*";inherits:false;}
  @property --myCounterName-dew6fb{syntax:"*";inherits:false;}
  @property --myCounterStyle-o4ly7x{syntax:"*";inherits:false;}
  @property --myCounterName-1re0z52{syntax:"*";inherits:false;}
  @property --myCounterStyle-1lfdsp0{syntax:"*";inherits:false;}
  @property --myCounterName-hs66zo{syntax:"*";inherits:false;}
  @property --myCounterStyle-5pdc5a{syntax:"*";inherits:false;}
  @property --countersNoStyle-g89gy3{syntax:"*";inherits:false;}
  @property --countersStyled-x8q6x3{syntax:"*";inherits:false;}
  .csv-sikia9{content:var(--singleCounter-ek68js);}
  .csv-1tainop{content:var(--singleCounterNoStyle-2521aj);}
  .csv-10brgn5{content:var(--singleText-5c1v76);}
  .csv-zh4bht{content:var(--counterDot-17rsat4);}
  .csv-ffxo1r{content:var(--counterSpace-jvqeh9);}
  .csv-e7wury{content:var(--counterRoman-16oxrf4);}
  .csv-16jow5p{content:var(--bracketed-1vvjf8x);}
  .csv-8nx65k{content:var(--content_value-jr2773);}
  .csv-ymi9m2{content:counter(var(--myCounterName-dew6fb), lower-alpha);}
  .csv-1hqoizr{content:counter(chapter, var(--myCounterStyle-o4ly7x));}
  .csv-1uqb9bz{content:counter(var(--myCounterName-1re0z52), var(--myCounterStyle-1lfdsp0));}
  .csv-1ghcaxs{content:counters(var(--myCounterName-hs66zo), ".", var(--myCounterStyle-5pdc5a));}
  .css-x7dhko{content:counter(ol);}
  .css-1igtirf{content:counter(chapter);}
  .css-ufyh7z{content:counters(section, ".");}
  .css-j8o8sv{content:counters(section, ".", decimal-leading-zero);}
  .csv-p698h{content:var(--countersNoStyle-g89gy3);}
  .csv-1e3j96l{content:var(--countersStyled-x8q6x3);}
