Test content-property interpolation support in cx2.
Exercises all four counter-related gaps: single/multi Content.t interpolation,
inline argument interpolation, counters() in content-list, and single-arg
counter().

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-sikia9{content:var(--var-ek68js);}
  .css-1tainop{content:var(--var-2521aj);}
  .css-10brgn5{content:var(--var-5c1v76);}
  .css-zh4bht{content:var(--var-17rsat4);}
  .css-ffxo1r{content:var(--var-jvqeh9);}
  .css-e7wury{content:var(--var-16oxrf4);}
  .css-16jow5p{content:var(--var-1vvjf8x);}
  .css-8nx65k-getListItemDecorationContent{content:var(--var-jr2773);}
  .css-ymi9m2{content:counter(var(--var-dew6fb), lower-alpha);}
  .css-1hqoizr{content:counter(chapter, var(--var-o4ly7x));}
  .css-1uqb9bz{content:counter(var(--var-1re0z52), var(--var-1lfdsp0));}
  .css-1ghcaxs{content:counters(var(--var-hs66zo), ".", var(--var-5pdc5a));}
  .css-x7dhko{content:counter(ol);}
  .css-1igtirf{content:counter(chapter);}
  .css-ufyh7z{content:counters(section, ".");}
  .css-j8o8sv{content:counters(section, ".", decimal-leading-zero);}
  .css-p698h{content:var(--var-g89gy3);}
  .css-1e3j96l{content:var(--var-x8q6x3);}
