The canonical empty-marker idiom: cross-module refs to bindings whose
[%cx2] body is empty. The marker classes carry no rules of their own,
they only serve as "tags" that consumers chain into selectors.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

The PPX records two distinct cross-module refs and one synthetic dep per
distinct longident.

  $ grep "let _ = M" n.ml
  let _ = M.isOpen
  let _ = M.isHovered

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-1d03ie-modal.css-0-isHovered{background:rgba(0, 0, 0, 0.1);}
  .css-1hyfx7x-modal{display:none;}
  .css-pznzdi-modal.css-0-isOpen{display:block;}
