When the indexed binding minted multiple atomized classes (space-separated
in the `class_string` field of the `[@@@css.bindings ...]` triple), a
cross-module reference to it still resolves to ONE class on substitution:
the binding's identity, not a dot-chain of its atoms. A reference means
"carries that binding", not "reproduces its exact declarations".

  $ cat > a.ml <<EOF
  > [@@@css.bindings [("A.multi", "cid-multi", "atom1 atom2 atom3")]]
  > let multi = CSS.make "cid-multi atom1 atom2 atom3" []
  > EOF

  $ cat > b.ml <<EOF
  > [@@@css ".target.\000A.multi\000{color:red;}"]
  > [@@@css.refs [("A.multi", "b.ml", 1, 0, 7)]]
  > let _ = A.multi
  > EOF

  $ styled-ppx.generate a.ml b.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .target.cid-multi{color:red;}
