The -<label> suffix is dev-only sugar. [%styled.<tag>] components (static and
dynamic) must drop it under --minify exactly like [%css] does; otherwise the
same declaration forks into per-binding atoms (e.g. css-k008qs-Card vs
css-k008qs) and cross-binding dedup breaks in the extracted stylesheet.

  $ refmt --parse re --print ml input.re > input.ml

In development, [%css] and both styled component forms keep their labels.

  $ ../../standalone.exe --impl input.ml -o dev.ml
  $ styled-ppx.generate dev.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --size-zo1hfq{syntax:"*";inherits:false;}
  .css-k008qs-stack{display:flex;}
  .css-38zrbw-stack{padding:12px;}
  .css-k008qs-Card{display:flex;}
  .css-eaeacs-Card{margin:10px;}
  .css-k008qs-Badge{display:flex;}
  .css-18ozkbs-Badge{gap:var(--size-zo1hfq);}

With --minify all three bindings share the same `display:flex` atom: it is
emitted once and no class carries a label suffix.

  $ ../../standalone.exe --minify --impl input.ml -o prod.ml
  $ styled-ppx.generate prod.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --size-zo1hfq{syntax:"*";inherits:false;}.css-k008qs{display:flex;}.css-38zrbw{padding:12px;}.css-eaeacs{margin:10px;}.css-18ozkbs{gap:var(--size-zo1hfq);}
  $ grep -c "\-stack\|\-Card\|\-Badge" prod.ml
  0
  [1]
