--sort source preserves the legacy first-occurrence order (one-release
escape hatch for bisecting rendering regressions). --sort buckets is the
default and needs no flag; an invalid mode errors out.

  $ cat > input.ml <<EOF
  > [@@@css "@media (min-width: 400px) {.css-m{color:red;}}"]
  > [@@@css ".css-base{color:black;}"]
  > EOF

  $ styled-ppx.generate --sort source input.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 400px) {.css-m{color:red;}}
  .css-base{color:black;}

  $ styled-ppx.generate --sort buckets input.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-base{color:black;}
  @media (min-width: 400px) {.css-m{color:red;}}

  $ styled-ppx.generate input.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .css-base{color:black;}
  @media (min-width: 400px) {.css-m{color:red;}}

  $ styled-ppx.generate --sort alphabetical input.ml
  styled-ppx: invalid --sort mode "alphabetical" (expected "buckets" or "source")
  [2]

  $ styled-ppx.generate --sort
  styled-ppx: missing value for flag "--sort"
  [2]
