The regression cascade tiers were almost shipped with: a `[%styled.global]`
rule (`*{box-sizing:inherit;}` here - `html`/`body`/`*`/`*::before` are the
same shape) carries no atom class, so it stayed OUTSIDE every layer while
atoms went inside them. CSS lets an UNLAYERED normal declaration beat ANY
layered one, regardless of specificity - so the moment atoms went inside
`styled-ppx.atoms` and globals did not, a global default like
`*{box-sizing:inherit}` would have started beating an atom's own
`._a_box9k{box-sizing:content-box;}` on the same element, `!important`
aside. Before cascade tiers existed at all, both were unlayered and
competed by ordinary specificity/order, where the atom's one-class
selector already beat `*`'s zero-specificity universal selector - so this
would have been a real regression, not a pre-existing limitation.

  $ cat > box_sizing.ml <<EOF
  > [@@@css "*{box-sizing:inherit;}"]
  > [@@@css "._a_box9k{box-sizing:content-box;}"]
  > EOF

  $ styled-ppx.generate box_sizing.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.global {
  *{box-sizing:inherit;}
  }
  @layer styled-ppx.atoms {
  ._a_box9k{box-sizing:content-box;}
  }

What the browser does now, and why: `styled-ppx.global` is declared FIRST
(lower priority) in the `@layer styled-ppx.global, styled-ppx.atoms;`
statement, so its `*{box-sizing:inherit;}` never beats
`styled-ppx.atoms`'s `._a_box9k{box-sizing:content-box;}` -
`styled-ppx.global`'s own specificity or stylesheet position no longer
matters at all once it is the lower layer, restoring "an element's own
atom always beats a global default" unconditionally. This is an
established, deliberate decision, independent of round 7b below: an
author's global default must never silently win over a component's own
atom, whatever either selector's specificity happens to be.

A real, documented behavior change: a global selector with HIGHER
specificity than an atom used to win outright (specificity is compared
before source order, and unlayered vs. unlayered never considers layers
at all). Now that `styled-ppx.global` is its own, lower layer, layer
order beats specificity entirely: the atom wins regardless of how
specific the global selector is.

  $ cat > specificity.ml <<EOF
  > [@@@css ".theme-dark .card{color:green;}"]
  > [@@@css "._a_cardown{color:blue;}"]
  > EOF

  $ styled-ppx.generate specificity.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.global {
  .theme-dark .card{color:green;}
  }
  @layer styled-ppx.atoms {
  ._a_cardown{color:blue;}
  }

Before this change, `.theme-dark .card` (specificity 0,2,0) beat
`._a_cardown` (specificity 0,1,0) outright, regardless of which one came
later in the stylesheet - a real, if perhaps unintended, way for a theme
class to override a component's own atom. Now `._a_cardown` always wins,
specificity no longer enters into it at all: an author whose global
STILL needs to win uses `!important` (below), which beats a
non-`!important` declaration in a higher layer.

Round 7b (`layers-descendant-tier.t`'s own "Round 7b" case) found a
DIFFERENT problem with separate layers - a `base` rule's own specificity
losing to an unrelated, less specific `conditional` atom - and fixed it
by putting `base` and `conditional` in the SAME `styled-ppx.atoms` layer.
That fix does not extend to `global`: an element's own atom must always
beat a global default regardless of specificity, a decision made before
round 7b and unaffected by it, which is exactly why `global` keeps its
own, separate, lower layer instead of joining `styled-ppx.atoms` too.

`!important` on a `styled-ppx.global` declaration is the documented
escape hatch: CSS compares importance BEFORE layer order, and among
`!important` declarations the EARLIEST-declared layer wins (the reverse
of the normal-declaration rule) - `styled-ppx.global` is declared FIRST
of the two names, so an `!important` global declaration still beats a
plain, non-`!important` atom on the same property, despite `global`
being the lower layer for everything else.

  $ cat > important_global.ml <<EOF
  > [@@@css "*{box-sizing:inherit !important;}"]
  > [@@@css "._a_box9k2{box-sizing:content-box;}"]
  > EOF

  $ styled-ppx.generate important_global.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.global {
  *{box-sizing:inherit !important;}
  }
  @layer styled-ppx.atoms {
  ._a_box9k2{box-sizing:content-box;}
  }

What the browser does here, and why: normal declarations compare layer
order first (`global` loses to `atoms`), but `!important` declarations
compare importance FIRST and, among important declarations, the
EARLIEST-declared layer wins - so `*{box-sizing:inherit !important;}`,
despite sitting in the lower layer, still beats
`._a_box9k2{box-sizing:content-box;}`'s plain declaration. This is the
same intentional, CSS-spec-level escape hatch every layer design
documents, not a gap: an author whose global default must truly win
uses `!important`, same as they always could to beat any unconditional
rule.

The same reversal holds even when the atom is ALSO `!important` - the
earliest-declared layer wins among `!important` declarations regardless
of which side carries it, unlike the normal-declaration case where the
LATER layer (`atoms`) always wins.

  $ cat > important_both.ml <<EOF
  > [@@@css "*{box-sizing:inherit !important;}"]
  > [@@@css "._a_box9k3{box-sizing:content-box !important;}"]
  > EOF

  $ styled-ppx.generate important_both.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.global {
  *{box-sizing:inherit !important;}
  }
  @layer styled-ppx.atoms {
  ._a_box9k3{box-sizing:content-box !important;}
  }

What the browser does here, and why: both declarations are `!important`,
so importance alone does not decide - among `!important` declarations
`styled-ppx.global`, the EARLIEST-declared of the two names, wins, so the
global default beats even an `!important` atom on the same property. An
atom can never out-`!important` a global default this way; the escape
hatch only ever runs in the global rule's favor, the same asymmetry
round 7 always documented for this pair.

`@property`/`@keyframes`/`@font-face` registrations are unaffected -
still outside both layers entirely, never competing for an element at
all, so they need no layer of their own.

  $ cat > registration.ml <<EOF
  > [@@@css "@property --brand{syntax:\"<color>\";inherits:false;initial-value:red;}"]
  > [@@@css "@keyframes spin{to{transform:rotate(360deg);}}"]
  > [@@@css "@font-face{font-family:\"Body\";src:url(\"body.woff2\");}"]
  > [@@@css "._a_registered{color:blue;}"]
  > EOF

  $ styled-ppx.generate registration.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @property --brand{syntax:"<color>";inherits:false;initial-value:red;}
  @keyframes spin{to{transform:rotate(360deg);}}
  @font-face{font-family:"Body";src:url("body.woff2");}
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_registered{color:blue;}
  }
