/* CSS Overscroll Behavior Module Level 1 */
[%css {|overscroll-behavior: contain|}];
[%css {|overscroll-behavior: none|}];
[%css {|overscroll-behavior: auto|}];
[%css {|overscroll-behavior: contain contain|}];
[%css {|overscroll-behavior: none contain|}];
[%css {|overscroll-behavior: auto contain|}];
[%css {|overscroll-behavior: contain none|}];
[%css {|overscroll-behavior: none none|}];
[%css {|overscroll-behavior: auto none|}];
[%css {|overscroll-behavior: contain auto|}];
[%css {|overscroll-behavior: none auto|}];
[%css {|overscroll-behavior: auto auto|}];
[%css {|overscroll-behavior-x: contain|}];
[%css {|overscroll-behavior-x: none|}];
[%css {|overscroll-behavior-x: auto|}];
[%css {|overscroll-behavior-y: contain|}];
[%css {|overscroll-behavior-y: none|}];
[%css {|overscroll-behavior-y: auto|}];
[%css {|overscroll-behavior-inline: contain|}];
[%css {|overscroll-behavior-inline: none|}];
[%css {|overscroll-behavior-inline: auto|}];
[%css {|overscroll-behavior-block: contain|}];
[%css {|overscroll-behavior-block: none|}];
[%css {|overscroll-behavior-block: auto|}];
