  $ dune build
  File "app.re", lines 18-36, characters 0-1:
  18 | [@react.component]
  19 | let make = () => {
  20 |   let (containerStyles, titleStyles) =
  21 |     Mylib.makeThemeStyles(~primary=CSS.blue, ~secondary=CSS.white);
  22 | 
  ...
  33 |     </div>
  34 |     <footer styles=footerStyles> {React.string("© 2025 My App")} </footer>
  35 |   </div>;
  36 | }.
  Alert unprocessed: `[@mel.*]' attributes found in external declaration. Did you forget to preprocess with `melange.ppx'?

  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-105do1p { max-width: 1200px; }
  .css-zgw7tn { margin: 0 auto; }
  .css-1i4osrx { padding: 20px; }
  .css-1g98i58 { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
  .css-7yrlh0 { background-color: #f5f5f5; }
  .css-18ke5zg { padding: 25px; }
  .css-1vom6fw { border-top: 1px solid #ddd; }
  .css-2vs1df { background-color: var(--var-1f99o1w); }
  .css-g7owro { padding: 10px 20px; }
  .css-beqw7r { border: none; }
  .css-1u5x7y9 { border-radius: 4px; }
  .css-vydl29 { color: white; }
  .css-1onkw2o { cursor: pointer; }
  .css-3yit0z { font-size: 16px; }
  .css-1w1pndv { background-color: #333; }
  .css-1i4osrx { padding: 20px; }
  .css-w7yhn1 { text-align: center; }
  .css-nqmzpy { border-width: 1px; }
  .css-xa8wr5 { border-style: solid; }
  .css-1aukh1j { border-color: var(--var-1eesnn6); }
  .css-172kuzh { padding: 15px; }
  .css-1oedmff { margin: 10px; }
  .css-1dhn4ef { background: white; }
  .css-hr3mxp { background-color: var(--var-bxenxf); }
  .css-jdaydm { color: var(--var-1czls49); }
  .css-ogjh4c { padding: 30px; }
  .css-myo4lj { font-size: 24px; }
  .css-1b1bivf { font-weight: bold; }
  .css-lx60ht { margin-bottom: 10px; }
