Cross-module reference nested inside a `:not(...)` pseudo-class payload.
The recursion through `transform_pseudoclass_kind` carries the sentinel
into the nested selector position, and the aggregator's substitution
pass operates on rendered strings so it doesn't care about CSS structure.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-ibeux7-button:disabled:not(.css-ibeux7-button.css-0-loadingState){background:gray;}
  .css-ky2d75-button{background:blue;}
