Two libraries, `z_base` and `a_app` (`a_app` depends on `z_base`, so
`z_base`'s rules come first in dependency order), one invocation - each
has one base atom and one conditional (`:hover`) atom. Tiering applies
GLOBALLY across the whole output, not per library: every base atom (both
libraries, in dependency order) comes before every conditional atom (both
libraries, in dependency order), not library-by-library.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base")]]
  > [@@@css "._a_zbase{color:red;}"]
  > [@@@css "._a_zbasehover:hover{color:darkred;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app")]]
  > [@@@css "._a_aapp{color:blue;}"]
  > [@@@css "._a_aapphover:hover{color:darkblue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_zbase{color:red;}
  ._a_aapp{color:blue;}
  ._a_zbasehover:hover{color:darkred;}
  ._a_aapphover:hover{color:darkblue;}
