Two directories each define a module named Util. A consumer in dir1
references "Util"; the reference resolves to dir1's own sibling (longest
common directory prefix), not dir2's, so dir1's Util rule is the one ordered
before the consumer's.

  $ mkdir dir1 dir2

  $ cat > dir1/util.ml <<EOF
  > [@@@css ".dir1-util{color:red;}"]
  > EOF

  $ cat > dir2/util.ml <<EOF
  > [@@@css ".dir2-util{color:green;}"]
  > EOF

  $ cat > dir1/consumer.ml <<EOF
  > [@@@css ".consumer{color:blue;}"]
  > let _ = Util.x
  > EOF

  $ styled-ppx.generate dir1/consumer.ml dir1/util.ml dir2/util.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .dir1-util{color:red;}
  .consumer{color:blue;}
  .dir2-util{color:green;}
