  $ dune build

  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --borderColor-1on39sz{syntax:"*";inherits:false;}
  @property --shadowX-11ljgmp{syntax:"*";inherits:false;}
  @property --shadowY-1qn6d0z{syntax:"*";inherits:false;}
  @property --blur-1bcbjmk{syntax:"*";inherits:false;}
  @property --spread-xxpef3{syntax:"*";inherits:false;}
  @property --shadowColor-1sod13t{syntax:"*";inherits:false;}
  @property --myShadow-af5fmc{syntax:"*";inherits:false;}
  @property --borderWidth-apl5wd{syntax:"*";inherits:false;}
  @property --bgColor-vilhl2{syntax:"*";inherits:false;}
  @property --shadow-giamln{syntax:"*";inherits:false;}
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_4085tv{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1);}
  ._a_402iep{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1), 0px 4px 8px 0px rgba(0, 0, 0, 0.2);}
  ._a_40fme5{box-shadow:inset 0px 2px 4px 0px rgba(0, 0, 0, 0.1);}
  ._a_40keqi{box-shadow:none;}
  ._a_402o9n{box-shadow:0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -2px rgba(0, 0, 0, 0.1);}
  ._a_3h2auv{border:1px solid black;}
  ._a_3h2qc1{border:2px dashed #ff0000;}
  ._a_3hjkge{border:1px solid transparent;}
  ._a_3hanm4{border:none;}
  ._a_3h257i{border:1px solid #ccc;}
  ._a_3n6otz{border-radius:8px;}
  ._a_405761{box-shadow:0px 4px 6px 0px rgba(0, 0, 0, 0.1);}
  ._a_3hwm2g{border:1px solid #e5e7eb;}
  ._a_3nkn84{border-radius:12px;}
  ._a_4039qm{box-shadow:0px 1px 3px 0px rgba(0, 0, 0, 0.1), 0px 1px 2px -1px rgba(0, 0, 0, 0.1);}
  ._a_3hxi5p{border:1px solid rgba(0, 0, 0, 0.05);}
  ._a_3nezfo{border-radius:16px;}
  ._a_3hstvc{border:2px solid #3b82f6;}
  ._a_40ar9w{box-shadow:0px 0px 0px 0px rgba(59, 130, 246, 0.5);}
  ._a_3hzctv{border:1px solid var(--borderColor-1on39sz);}
  ._a_40u3s3{box-shadow:var(--shadowX-11ljgmp) var(--shadowY-1qn6d0z) var(--blur-1bcbjmk) var(--spread-xxpef3) var(--shadowColor-1sod13t);}
  ._a_40jemk{box-shadow:var(--myShadow-af5fmc);}
  ._a_3hdrfm{border:var(--borderWidth-apl5wd) solid black;}
  ._a_3hlokq43j{border-width:2px;}
  ._a_3hsua8w2v{border-style:solid;}
  ._a_3hef5kaed{border-color:#333;}
  ._a_3hghsmzmu{border-top:1px solid red;}
  ._a_3hb2879q1{border-right:2px dashed blue;}
  ._a_3h00779gh{border-bottom:3px dotted green;}
  ._a_3h1dswvke{border-left:4px double orange;}
  ._a_39004pvpe{background-color:var(--bgColor-vilhl2);}
  ._a_40ae1x{box-shadow:var(--shadow-giamln);}
  }

Pin the runtime bindings so the rule⟺CSS.make binding pairing is covered too.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css "@property --borderColor-1on39sz{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --shadowX-11ljgmp{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --shadowY-1qn6d0z{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --blur-1bcbjmk{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --spread-xxpef3{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --shadowColor-1sod13t{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --myShadow-af5fmc{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --borderWidth-apl5wd{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --bgColor-vilhl2{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --shadow-giamln{syntax:\"*\";inherits:false;}"]
  [@@@css "._a_4085tv{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1);}"]
  [@@@css
    "._a_402iep{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1), 0px 4px 8px 0px rgba(0, 0, 0, 0.2);}"]
  [@@@css "._a_40fme5{box-shadow:inset 0px 2px 4px 0px rgba(0, 0, 0, 0.1);}"]
  [@@@css "._a_40keqi{box-shadow:none;}"]
  [@@@css
    "._a_402o9n{box-shadow:0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -2px rgba(0, 0, 0, 0.1);}"]
  [@@@css "._a_3h2auv{border:1px solid black;}"]
  [@@@css "._a_3h2qc1{border:2px dashed #ff0000;}"]
  [@@@css "._a_3hjkge{border:1px solid transparent;}"]
  [@@@css "._a_3hanm4{border:none;}"]
  [@@@css "._a_3hghsmzmu{border-top:1px solid red;}"]
  [@@@css "._a_3hb2879q1{border-right:2px dashed blue;}"]
  [@@@css "._a_3h00779gh{border-bottom:3px dotted green;}"]
  [@@@css "._a_3h1dswvke{border-left:4px double orange;}"]
  [@@@css "._a_3hlokq43j{border-width:2px;}"]
  [@@@css "._a_3hsua8w2v{border-style:solid;}"]
  [@@@css "._a_3hef5kaed{border-color:#333;}"]
  [@@@css "._a_3h257i{border:1px solid #ccc;}"]
  [@@@css "._a_3n6otz{border-radius:8px;}"]
  [@@@css "._a_405761{box-shadow:0px 4px 6px 0px rgba(0, 0, 0, 0.1);}"]
  [@@@css "._a_3hwm2g{border:1px solid #e5e7eb;}"]
  [@@@css "._a_3nkn84{border-radius:12px;}"]
  [@@@css
    "._a_4039qm{box-shadow:0px 1px 3px 0px rgba(0, 0, 0, 0.1), 0px 1px 2px -1px rgba(0, 0, 0, 0.1);}"]
  [@@@css "._a_3hxi5p{border:1px solid rgba(0, 0, 0, 0.05);}"]
  [@@@css "._a_3nezfo{border-radius:16px;}"]
  [@@@css "._a_3hstvc{border:2px solid #3b82f6;}"]
  [@@@css "._a_40ar9w{box-shadow:0px 0px 0px 0px rgba(59, 130, 246, 0.5);}"]
  [@@@css "._a_3hzctv{border:1px solid var(--borderColor-1on39sz);}"]
  [@@@css
    "._a_40u3s3{box-shadow:var(--shadowX-11ljgmp) var(--shadowY-1qn6d0z) var(--blur-1bcbjmk) var(--spread-xxpef3) var(--shadowColor-1sod13t);}"]
  [@@@css "._a_40jemk{box-shadow:var(--myShadow-af5fmc);}"]
  [@@@css "._a_3hdrfm{border:var(--borderWidth-apl5wd) solid black;}"]
  [@@@css "._a_39004pvpe{background-color:var(--bgColor-vilhl2);}"]
  [@@@css "._a_40ae1x{box-shadow:var(--shadow-giamln);}"]
  [@@@css.bindings
    [("Output.simpleShadow", "_id_1ckmdi6", "_a_4085tv");
    ("Output.multipleShadows", "_id_1urhidx", "_a_402iep");
    ("Output.insetShadow", "_id_18o58m4", "_a_40fme5");
    ("Output.noShadow", "_id_1u21xrq", "_a_40keqi");
    ("Output.spreadShadow", "_id_8d8vql", "_a_402o9n");
    ("Output.simpleBorder", "_id_1kct4wz", "_a_3h2auv");
    ("Output.borderWithColor", "_id_tm1wv6", "_a_3h2qc1");
    ("Output.borderTransparent", "_id_tbotla", "_a_3hjkge");
    ("Output.noBorder", "_id_15bfnai", "_a_3hanm4");
    ("Output.borderStyles", "_id_16nbulq",
      "_a_3hghsmzmu _a_3hb2879q1 _a_3h00779gh _a_3h1dswvke");
    ("Output.borderSeparate", "_id_122xr42",
      "_a_3hlokq43j _a_3hsua8w2v _a_3hef5kaed");
    ("Output.borderWithRadius", "_id_1j83vme", "_a_3h257i _a_3n6otz");
    ("Output.shadowAndBorder", "_id_3k5k4w", "_a_405761 _a_3hwm2g _a_3nkn84");
    ("Output.cardStyle", "_id_1je20li", "_a_4039qm _a_3hxi5p _a_3nezfo");
    ("Output.buttonBase", "_id_9kxo31", "_a_3hstvc _a_40ar9w _a_3n6otz");
    ("Output.borderColorInterp", "_id_16k72sd", "_a_3hzctv");
    ("Output.shadowInterp", "_id_9zd6fn", "_a_40u3s3");
    ("Output.shadowFullInterp", "_id_bg3lpz", "_a_40jemk");
    ("Output.borderWidthInterp", "_id_1h8tvcz", "_a_3hdrfm");
    ("Output.mixedCard", "_id_10wtrx1",
      "_a_39004pvpe _a_3hzctv _a_40ae1x _a_3nkn84")]]
  let simpleShadow = CSS.make "label:simpleShadow _id_1ckmdi6 _a_4085tv" []
  let multipleShadows =
    CSS.make "label:multipleShadows _id_1urhidx _a_402iep" []
  let insetShadow = CSS.make "label:insetShadow _id_18o58m4 _a_40fme5" []
  let noShadow = CSS.make "label:noShadow _id_1u21xrq _a_40keqi" []
  let spreadShadow = CSS.make "label:spreadShadow _id_8d8vql _a_402o9n" []
  let simpleBorder = CSS.make "label:simpleBorder _id_1kct4wz _a_3h2auv" []
  let borderWithColor =
    CSS.make "label:borderWithColor _id_tm1wv6 _a_3h2qc1" []
  let borderTransparent =
    CSS.make "label:borderTransparent _id_tbotla _a_3hjkge" []
  let noBorder = CSS.make "label:noBorder _id_15bfnai _a_3hanm4" []
  let borderStyles =
    CSS.make
      "label:borderStyles _id_16nbulq _a_3hghsmzmu _a_3hb2879q1 _a_3h00779gh _a_3h1dswvke"
      []
  let borderSeparate =
    CSS.make
      "label:borderSeparate _id_122xr42 _a_3hlokq43j _a_3hsua8w2v _a_3hef5kaed"
      []
  let borderWithRadius =
    CSS.make "label:borderWithRadius _id_1j83vme _a_3h257i _a_3n6otz" []
  let shadowAndBorder =
    CSS.make "label:shadowAndBorder _id_3k5k4w _a_405761 _a_3hwm2g _a_3nkn84"
      []
  let cardStyle =
    CSS.make "label:cardStyle _id_1je20li _a_4039qm _a_3hxi5p _a_3nezfo" []
  let buttonBase =
    CSS.make "label:buttonBase _id_9kxo31 _a_3hstvc _a_40ar9w _a_3n6otz" []
  let borderColorInterp borderColor =
    CSS.make "label:borderColorInterp _id_16k72sd _a_3hzctv"
      [("--borderColor-1on39sz", (CSS.Types.Color.toString borderColor))]
  let shadowInterp shadowX =
    fun shadowY ->
      fun blur ->
        fun spread ->
          fun shadowColor ->
            CSS.make "label:shadowInterp _id_9zd6fn _a_40u3s3"
              [("--shadowX-11ljgmp", (CSS.Types.Length.toString shadowX));
              ("--shadowY-1qn6d0z", (CSS.Types.Length.toString shadowY));
              ("--blur-1bcbjmk", (CSS.Types.Length.toString blur));
              ("--spread-xxpef3", (CSS.Types.Length.toString spread));
              ("--shadowColor-1sod13t", (CSS.Types.Color.toString shadowColor))]
  let shadowFullInterp myShadow =
    CSS.make "label:shadowFullInterp _id_bg3lpz _a_40jemk"
      [("--myShadow-af5fmc", (CSS.Types.BoxShadows.toString myShadow))]
  let borderWidthInterp borderWidth =
    CSS.make "label:borderWidthInterp _id_1h8tvcz _a_3hdrfm"
      [("--borderWidth-apl5wd", (CSS.Types.LineWidth.toString borderWidth))]
  let mixedCard bgColor =
    fun borderColor ->
      fun shadow ->
        CSS.make
          "label:mixedCard _id_10wtrx1 _a_39004pvpe _a_3hzctv _a_40ae1x _a_3nkn84"
          [("--bgColor-vilhl2", (CSS.Types.Color.toString bgColor));
          ("--borderColor-1on39sz", (CSS.Types.Color.toString borderColor));
          ("--shadow-giamln", (CSS.Types.BoxShadows.toString shadow))]
