  $ dune build

  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-12b85tv-simpleShadow{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1);}
  .css-bh2iep-multipleShadows{box-shadow:0px 2px 4px 0px rgba(0, 0, 0, 0.1), 0px 4px 8px 0px rgba(0, 0, 0, 0.2);}
  .css-1r1fme5-insetShadow{box-shadow:inset 0px 2px 4px 0px rgba(0, 0, 0, 0.1);}
  .css-gokeqi-noShadow{box-shadow:none;}
  .css-1wp2o9n-spreadShadow{box-shadow:0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -2px rgba(0, 0, 0, 0.1);}
  .css-e42auv-simpleBorder{border:1px solid black;}
  .css-1h02qc1-borderWithColor{border:2px dashed #ff0000;}
  .css-kujkge-borderTransparent{border:1px solid transparent;}
  .css-10ganm4-noBorder{border:none;}
  .css-iqmzmu-borderStyles{border-top:1px solid red;}
  .css-dw79q1-borderStyles{border-right:2px dashed blue;}
  .css-9o79gh-borderStyles{border-bottom:3px dotted green;}
  .css-41wvke-borderStyles{border-left:4px double orange;}
  .css-djq43j-borderSeparate{border-width:2px;}
  .css-xp8w2v-borderSeparate{border-style:solid;}
  .css-1jzkaed-borderSeparate{border-color:#333;}
  .css-1k7257i-borderWithRadius{border:1px solid #ccc;}
  .css-rl6otz-borderWithRadius{border-radius:8px;}
  .css-1465761-shadowAndBorder{box-shadow:0px 4px 6px 0px rgba(0, 0, 0, 0.1);}
  .css-19uwm2g-shadowAndBorder{border:1px solid #e5e7eb;}
  .css-1yfkn84-shadowAndBorder{border-radius:12px;}
  .css-y239qm-cardStyle{box-shadow:0px 1px 3px 0px rgba(0, 0, 0, 0.1), 0px 1px 2px -1px rgba(0, 0, 0, 0.1);}
  .css-11ixi5p-cardStyle{border:1px solid rgba(0, 0, 0, 0.05);}
  .css-1ebezfo-cardStyle{border-radius:16px;}
  .css-1bxstvc-buttonBase{border:2px solid #3b82f6;}
  .css-1vuar9w-buttonBase{box-shadow:0px 0px 0px 0px rgba(59, 130, 246, 0.5);}
  .css-rl6otz-buttonBase{border-radius:8px;}
  .css-hfzctv-borderColorInterp{border:1px solid var(--var-n18ysi);}
  .css-9fu3s3-shadowInterp{box-shadow:var(--var-pat18a) var(--var-qx15c3) var(--var-1kkg6g2) var(--var-1wyrwcc) var(--var-12k2pr8);}
  .css-fkjemk-shadowFullInterp{box-shadow:var(--var-1kiyke4);}
  .css-11hdrfm-borderWidthInterp{border:var(--var-1b1exnn) solid black;}
  .css-v2pvpe-mixedCard{background-color:var(--var-16nna3);}
  .css-hfzctv-mixedCard{border:1px solid var(--var-w0mvl2);}
  .css-phae1x-mixedCard{box-shadow:var(--var-1xyi5y6);}
  .css-1yfkn84-mixedCard{border-radius:12px;}
