Without `--layers`, output is byte-identical to `library-order.t`: the
internal per-rule library tagging added to support `--layers` doesn't
change the default rule list, its dedup, or its separators.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library", "z_base")]]
  > [@@@css ".base-widget{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library", "a_app")]]
  > [@@@css ".app-main{color:blue;}"]
  > let _ = Z_base.widget
  > EOF

  $ styled-ppx.generate a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .base-widget{color:red;}
  .app-main{color:blue;}
