This test ensures the ppx generates the correct output against styled-ppx.native
If this test fail means that the module is not in sync with the ppx
  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > EOF

  $ cat > dune << EOF
  > (executable
  >  (name input)
  >  (libraries styled-ppx.native)
  >  (preprocess (pps styled-ppx)))
  > EOF

  $ dune build

  $ dune describe pp ./input.re | sed '1,/^];$/d'
  [@css ".a-28lqh0{align-self:auto;}"];
  [@css ".a-1oa5str{align-self:normal;}"];
  [@css ".a-fzqoy4{align-self:stretch;}"];
  [@css ".a-chwum8{align-self:baseline;}"];
  [@css ".a-1lz2ze6{align-self:first baseline;}"];
  [@css ".a-ko0zg2{align-self:last baseline;}"];
  [@css ".a-hoe9xz{align-self:center;}"];
  [@css ".a-1hcehcy{align-self:start;}"];
  [@css ".a-1fuqp3k{align-self:end;}"];
  [@css ".a-sobvnc{align-self:self-start;}"];
  [@css ".a-6bhf65{align-self:self-end;}"];
  [@css ".a-lsgsxr{align-self:unsafe start;}"];
  [@css ".a-n6q3l2{align-self:safe start;}"];
  [@css ".a-1l47rk4{align-items:normal;}"];
  [@css ".a-k51ack{align-items:stretch;}"];
  [@css ".a-1y3jl3a{align-items:baseline;}"];
  [@css ".a-1v63wj4{align-items:first baseline;}"];
  [@css ".a-1par88q{align-items:last baseline;}"];
  [@css ".a-zcxndt{align-items:center;}"];
  [@css ".a-thqn8b{align-items:start;}"];
  [@css ".a-h812ai{align-items:end;}"];
  [@css ".a-1iymgp6{align-items:self-start;}"];
  [@css ".a-piyf6q{align-items:self-end;}"];
  [@css ".a-1con9n2{align-items:unsafe start;}"];
  [@css ".a-9x8fld{align-items:safe start;}"];
  [@css ".a-1ph82qi{align-content:normal;}"];
  [@css ".a-m6tf19{align-content:baseline;}"];
  [@css ".a-129e56e{align-content:first baseline;}"];
  [@css ".a-197bvxk{align-content:last baseline;}"];
  [@css ".a-1c5t6ef{align-content:space-between;}"];
  [@css ".a-1okulzr{align-content:space-around;}"];
  [@css ".a-oazzqp{align-content:space-evenly;}"];
  [@css ".a-zssg0i{align-content:stretch;}"];
  [@css ".a-1a5ho4p{align-content:center;}"];
  [@css ".a-zf62g1{align-content:start;}"];
  [@css ".a-1u0otui{align-content:end;}"];
  [@css ".a-1crvgc7{align-content:flex-start;}"];
  [@css ".a-4zx96o{align-content:flex-end;}"];
  [@css ".a-gr6jw8{align-content:unsafe start;}"];
  [@css ".a-5j2jhg{align-content:safe start;}"];
  [@css ".a-mxnscv{justify-self:auto;}"];
  [@css ".a-9a0v6u{justify-self:normal;}"];
  [@css ".a-1j4yvex{justify-self:stretch;}"];
  [@css ".a-ow3z27{justify-self:baseline;}"];
  [@css ".a-1hf5zq0{justify-self:first baseline;}"];
  [@css ".a-18k0186{justify-self:last baseline;}"];
  [@css ".a-tddfjc{justify-self:center;}"];
  [@css ".a-85bxzs{justify-self:start;}"];
  [@css ".a-v1pv54{justify-self:end;}"];
  [@css ".a-rkab6k{justify-self:self-start;}"];
  [@css ".a-e4zxgz{justify-self:self-end;}"];
  [@css ".a-2nobw4{justify-self:unsafe start;}"];
  [@css ".a-le5sda{justify-self:safe start;}"];
  [@css ".a-vv4swf{justify-self:left;}"];
  [@css ".a-9b5rli{justify-self:right;}"];
  [@css ".a-1uhakos{justify-self:safe right;}"];
  [@css ".a-1s3t02p{justify-items:normal;}"];
  [@css ".a-osw19q{justify-items:stretch;}"];
  [@css ".a-178sd3r{justify-items:baseline;}"];
  [@css ".a-g3oxkb{justify-items:first baseline;}"];
  [@css ".a-1d1nqwq{justify-items:last baseline;}"];
  [@css ".a-hghncw{justify-items:center;}"];
  [@css ".a-g27xd1{justify-items:start;}"];
  [@css ".a-c4d6ik{justify-items:end;}"];
  [@css ".a-1rxujby{justify-items:self-start;}"];
  [@css ".a-1npjls5{justify-items:self-end;}"];
  [@css ".a-1lfkxpa{justify-items:unsafe start;}"];
  [@css ".a-u1igov{justify-items:safe start;}"];
  [@css ".a-5whueq{justify-items:left;}"];
  [@css ".a-butw7a{justify-items:right;}"];
  [@css ".a-1uhzryg{justify-items:safe right;}"];
  [@css ".a-1phqp4r{justify-items:legacy;}"];
  [@css ".a-6d6jur{justify-items:legacy left;}"];
  [@css ".a-av1n9p{justify-items:legacy right;}"];
  [@css ".a-b18x1c{justify-items:legacy center;}"];
  [@css ".a-18dm5u{justify-content:normal;}"];
  [@css ".a-x4dmss{justify-content:space-between;}"];
  [@css ".a-kp4oss{justify-content:space-around;}"];
  [@css ".a-1ku462w{justify-content:space-evenly;}"];
  [@css ".a-x208ak{justify-content:stretch;}"];
  [@css ".a-1tyndxa{justify-content:center;}"];
  [@css ".a-k1xozo{justify-content:start;}"];
  [@css ".a-1b1rfkc{justify-content:end;}"];
  [@css ".a-1fn0841{justify-content:flex-start;}"];
  [@css ".a-1a9getn{justify-content:flex-end;}"];
  [@css ".a-t0ygzb{justify-content:unsafe start;}"];
  [@css ".a-1d6pp7h{justify-content:safe start;}"];
  [@css ".a-d5dmac{justify-content:left;}"];
  [@css ".a-dajo9q{justify-content:right;}"];
  [@css ".a-vp89l6{justify-content:safe right;}"];
  [@css ".a-6lqrgx{place-content:normal;}"];
  [@css ".a-1k2zktz{place-content:baseline;}"];
  [@css ".a-kd0k3s{place-content:first baseline;}"];
  [@css ".a-123lpj3{place-content:last baseline;}"];
  [@css ".a-1jag07y{place-content:space-between;}"];
  [@css ".a-fhn9tt{place-content:space-around;}"];
  [@css ".a-1lz8p3p{place-content:space-evenly;}"];
  [@css ".a-auwium{place-content:stretch;}"];
  [@css ".a-gdqw8{place-content:center;}"];
  [@css ".a-16c5dhv{place-content:start;}"];
  [@css ".a-16pnyc7{place-content:end;}"];
  [@css ".a-tdrdu{place-content:flex-start;}"];
  [@css ".a-1v2nttj{place-content:flex-end;}"];
  [@css ".a-bj71ck{place-content:unsafe start;}"];
  [@css ".a-1u7qxqj{place-content:safe start;}"];
  [@css ".a-yo3qoo{place-content:normal normal;}"];
  [@css ".a-ednuac{place-content:baseline normal;}"];
  [@css ".a-1ly0fds{place-content:first baseline normal;}"];
  [@css ".a-1lnhpg7{place-content:space-between normal;}"];
  [@css ".a-6kzrg5{place-content:center normal;}"];
  [@css ".a-ccz0tb{place-content:unsafe start normal;}"];
  [@css ".a-pgi3io{place-content:normal stretch;}"];
  [@css ".a-e1fbzg{place-content:baseline stretch;}"];
  [@css ".a-hf8zlv{place-content:first baseline stretch;}"];
  [@css ".a-1tb4shn{place-content:center stretch;}"];
  [@css ".a-1ogf3b8{place-content:unsafe start stretch;}"];
  [@css ".a-11cb47q{place-content:normal safe right;}"];
  [@css ".a-1e2wp5i{place-content:baseline safe right;}"];
  [@css ".a-1s7pafp{place-content:first baseline safe right;}"];
  [@css ".a-1phtr2b{place-content:space-between safe right;}"];
  [@css ".a-m6hl56{place-content:center safe right;}"];
  [@css ".a-ys288f{place-content:unsafe start safe right;}"];
  [@css ".a-o9u5yn{place-items:normal;}"];
  [@css ".a-dnwgtc{place-items:stretch;}"];
  [@css ".a-yzp3r0{place-items:baseline;}"];
  [@css ".a-u3jtjp{place-items:first baseline;}"];
  [@css ".a-nbmap8{place-items:last baseline;}"];
  [@css ".a-yoym04{place-items:center;}"];
  [@css ".a-racea0{place-items:start;}"];
  [@css ".a-16qqbga{place-items:end;}"];
  [@css ".a-1v9cfae{place-items:self-start;}"];
  [@css ".a-ji4r6c{place-items:self-end;}"];
  [@css ".a-11xk81w{place-items:unsafe start;}"];
  [@css ".a-uhboah{place-items:safe start;}"];
  [@css ".a-117oh71{place-items:normal normal;}"];
  [@css ".a-1mvk8n{place-items:stretch normal;}"];
  [@css ".a-162m489{place-items:baseline normal;}"];
  [@css ".a-11lbjab{place-items:first baseline normal;}"];
  [@css ".a-bdz5p3{place-items:self-start normal;}"];
  [@css ".a-pd2at7{place-items:unsafe start normal;}"];
  [@css ".a-1rt9qwi{place-items:normal stretch;}"];
  [@css ".a-qg7oz{place-items:stretch stretch;}"];
  [@css ".a-asecxz{place-items:baseline stretch;}"];
  [@css ".a-gndtd3{place-items:first baseline stretch;}"];
  [@css ".a-12jtjgd{place-items:self-start stretch;}"];
  [@css ".a-b824mg{place-items:unsafe start stretch;}"];
  [@css ".a-11znfmq{place-items:normal last baseline;}"];
  [@css ".a-u7203s{place-items:stretch last baseline;}"];
  [@css ".a-tbq0j0{place-items:baseline last baseline;}"];
  [@css ".a-1xqsgia{place-items:first baseline last baseline;}"];
  [@css ".a-x25oxa{place-items:self-start last baseline;}"];
  [@css ".a-8rf3bh{place-items:unsafe start last baseline;}"];
  [@css ".a-x3o9xj{place-items:normal legacy left;}"];
  [@css ".a-yuaufw{place-items:stretch legacy left;}"];
  [@css ".a-19o4fdy{place-items:baseline legacy left;}"];
  [@css ".a-1allg27{place-items:first baseline legacy left;}"];
  [@css ".a-1um6nyr{place-items:self-start legacy left;}"];
  [@css ".a-1ogsbzm{place-items:unsafe start legacy left;}"];
  [@css ".a-z39awh{gap:0 0;}"];
  [@css ".a-1m20ra0{gap:0 1em;}"];
  [@css ".a-bd6cki{gap:1em;}"];
  [@css ".a-f0kubh{gap:1em 1em;}"];
  [@css ".a-zqzqln{-webkit-column-gap:0;column-gap:0;}"];
  [@css ".a-602mee{-webkit-column-gap:1em;column-gap:1em;}"];
  [@css ".a-mz5ixr{-webkit-column-gap:normal;column-gap:normal;}"];
  [@css ".a-1j42sqe{row-gap:0;}"];
  [@css ".a-28i0al{row-gap:1em;}"];
  [@css ".a-xyx8z6{margin-trim:none;}"];
  [@css ".a-s28oi1{margin-trim:in-flow;}"];
  [@css ".a-1fk011{margin-trim:all;}"];
  
  CSS.make("a-28lqh0", []);
  CSS.make("a-1oa5str", []);
  CSS.make("a-fzqoy4", []);
  CSS.make("a-chwum8", []);
  CSS.make("a-1lz2ze6", []);
  CSS.make("a-ko0zg2", []);
  CSS.make("a-hoe9xz", []);
  CSS.make("a-1hcehcy", []);
  CSS.make("a-1fuqp3k", []);
  CSS.make("a-sobvnc", []);
  CSS.make("a-6bhf65", []);
  CSS.make("a-lsgsxr", []);
  CSS.make("a-n6q3l2", []);
  CSS.make("a-1l47rk4", []);
  CSS.make("a-k51ack", []);
  CSS.make("a-1y3jl3a", []);
  CSS.make("a-1v63wj4", []);
  CSS.make("a-1par88q", []);
  CSS.make("a-zcxndt", []);
  CSS.make("a-thqn8b", []);
  CSS.make("a-h812ai", []);
  CSS.make("a-1iymgp6", []);
  CSS.make("a-piyf6q", []);
  CSS.make("a-1con9n2", []);
  CSS.make("a-9x8fld", []);
  CSS.make("a-1ph82qi", []);
  CSS.make("a-m6tf19", []);
  CSS.make("a-129e56e", []);
  CSS.make("a-197bvxk", []);
  CSS.make("a-1c5t6ef", []);
  CSS.make("a-1okulzr", []);
  CSS.make("a-oazzqp", []);
  CSS.make("a-zssg0i", []);
  CSS.make("a-1a5ho4p", []);
  CSS.make("a-zf62g1", []);
  CSS.make("a-1u0otui", []);
  CSS.make("a-1crvgc7", []);
  CSS.make("a-4zx96o", []);
  CSS.make("a-gr6jw8", []);
  CSS.make("a-5j2jhg", []);
  CSS.make("a-mxnscv", []);
  CSS.make("a-9a0v6u", []);
  CSS.make("a-1j4yvex", []);
  CSS.make("a-ow3z27", []);
  CSS.make("a-1hf5zq0", []);
  CSS.make("a-18k0186", []);
  CSS.make("a-tddfjc", []);
  CSS.make("a-85bxzs", []);
  CSS.make("a-v1pv54", []);
  CSS.make("a-rkab6k", []);
  CSS.make("a-e4zxgz", []);
  CSS.make("a-2nobw4", []);
  CSS.make("a-le5sda", []);
  CSS.make("a-vv4swf", []);
  CSS.make("a-9b5rli", []);
  CSS.make("a-1uhakos", []);
  CSS.make("a-1s3t02p", []);
  CSS.make("a-osw19q", []);
  CSS.make("a-178sd3r", []);
  CSS.make("a-g3oxkb", []);
  CSS.make("a-1d1nqwq", []);
  CSS.make("a-hghncw", []);
  CSS.make("a-g27xd1", []);
  CSS.make("a-c4d6ik", []);
  CSS.make("a-1rxujby", []);
  CSS.make("a-1npjls5", []);
  CSS.make("a-1lfkxpa", []);
  CSS.make("a-u1igov", []);
  CSS.make("a-5whueq", []);
  CSS.make("a-butw7a", []);
  CSS.make("a-1uhzryg", []);
  CSS.make("a-1phqp4r", []);
  CSS.make("a-6d6jur", []);
  CSS.make("a-av1n9p", []);
  CSS.make("a-b18x1c", []);
  CSS.make("a-18dm5u", []);
  CSS.make("a-x4dmss", []);
  CSS.make("a-kp4oss", []);
  CSS.make("a-1ku462w", []);
  CSS.make("a-x208ak", []);
  CSS.make("a-1tyndxa", []);
  CSS.make("a-k1xozo", []);
  CSS.make("a-1b1rfkc", []);
  CSS.make("a-1fn0841", []);
  CSS.make("a-1a9getn", []);
  CSS.make("a-t0ygzb", []);
  CSS.make("a-1d6pp7h", []);
  CSS.make("a-d5dmac", []);
  CSS.make("a-dajo9q", []);
  CSS.make("a-vp89l6", []);
  CSS.make("a-6lqrgx", []);
  CSS.make("a-1k2zktz", []);
  CSS.make("a-kd0k3s", []);
  CSS.make("a-123lpj3", []);
  CSS.make("a-1jag07y", []);
  CSS.make("a-fhn9tt", []);
  CSS.make("a-1lz8p3p", []);
  CSS.make("a-auwium", []);
  CSS.make("a-gdqw8", []);
  CSS.make("a-16c5dhv", []);
  CSS.make("a-16pnyc7", []);
  CSS.make("a-tdrdu", []);
  CSS.make("a-1v2nttj", []);
  CSS.make("a-bj71ck", []);
  CSS.make("a-1u7qxqj", []);
  CSS.make("a-yo3qoo", []);
  CSS.make("a-ednuac", []);
  CSS.make("a-1ly0fds", []);
  CSS.make("a-1lnhpg7", []);
  CSS.make("a-6kzrg5", []);
  CSS.make("a-ccz0tb", []);
  CSS.make("a-pgi3io", []);
  CSS.make("a-e1fbzg", []);
  CSS.make("a-hf8zlv", []);
  CSS.make("a-1tb4shn", []);
  CSS.make("a-1ogf3b8", []);
  CSS.make("a-11cb47q", []);
  CSS.make("a-1e2wp5i", []);
  CSS.make("a-1s7pafp", []);
  CSS.make("a-1phtr2b", []);
  CSS.make("a-m6hl56", []);
  CSS.make("a-ys288f", []);
  CSS.make("a-o9u5yn", []);
  CSS.make("a-dnwgtc", []);
  CSS.make("a-yzp3r0", []);
  CSS.make("a-u3jtjp", []);
  CSS.make("a-nbmap8", []);
  CSS.make("a-yoym04", []);
  CSS.make("a-racea0", []);
  CSS.make("a-16qqbga", []);
  CSS.make("a-1v9cfae", []);
  CSS.make("a-ji4r6c", []);
  CSS.make("a-11xk81w", []);
  CSS.make("a-uhboah", []);
  CSS.make("a-117oh71", []);
  CSS.make("a-1mvk8n", []);
  CSS.make("a-162m489", []);
  CSS.make("a-11lbjab", []);
  CSS.make("a-bdz5p3", []);
  CSS.make("a-pd2at7", []);
  CSS.make("a-1rt9qwi", []);
  CSS.make("a-qg7oz", []);
  CSS.make("a-asecxz", []);
  CSS.make("a-gndtd3", []);
  CSS.make("a-12jtjgd", []);
  CSS.make("a-b824mg", []);
  CSS.make("a-11znfmq", []);
  CSS.make("a-u7203s", []);
  CSS.make("a-tbq0j0", []);
  CSS.make("a-1xqsgia", []);
  CSS.make("a-x25oxa", []);
  CSS.make("a-8rf3bh", []);
  CSS.make("a-x3o9xj", []);
  CSS.make("a-yuaufw", []);
  CSS.make("a-19o4fdy", []);
  CSS.make("a-1allg27", []);
  CSS.make("a-1um6nyr", []);
  CSS.make("a-1ogsbzm", []);
  
  CSS.make("a-z39awh", []);
  CSS.make("a-1m20ra0", []);
  CSS.make("a-bd6cki", []);
  CSS.make("a-f0kubh", []);
  CSS.make("a-zqzqln", []);
  CSS.make("a-602mee", []);
  CSS.make("a-mz5ixr", []);
  CSS.make("a-1j42sqe", []);
  CSS.make("a-28i0al", []);
  
  CSS.make("a-xyx8z6", []);
  CSS.make("a-s28oi1", []);
  CSS.make("a-1fk011", []);
