This test ensures the ppx generates the correct output against styled-ppx.native
If this test fail means that the module is not in sync with the ppx
  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > EOF

  $ cat > dune << EOF
  > (executable
  >  (name input)
  >  (libraries styled-ppx.native)
  >  (preprocess (pps styled-ppx)))
  > EOF

  $ dune build

  $ dune describe pp ./input.re | sed '1,/^];$/d'
  [@css "._a_9j001lqh0{align-self:auto;}"];
  [@css "._a_9j0015str{align-self:normal;}"];
  [@css "._a_9j001qoy4{align-self:stretch;}"];
  [@css "._a_9j001wum8{align-self:baseline;}"];
  [@css "._a_9j0012ze6{align-self:first baseline;}"];
  [@css "._a_9j0010zg2{align-self:last baseline;}"];
  [@css "._a_9j001e9xz{align-self:center;}"];
  [@css "._a_9j001ehcy{align-self:start;}"];
  [@css "._a_9j001qp3k{align-self:end;}"];
  [@css "._a_9j001bvnc{align-self:self-start;}"];
  [@css "._a_9j001hf65{align-self:self-end;}"];
  [@css "._a_9j001gsxr{align-self:unsafe start;}"];
  [@css "._a_9j001q3l2{align-self:safe start;}"];
  [@css "._a_9i0017rk4{align-items:normal;}"];
  [@css "._a_9i0011ack{align-items:stretch;}"];
  [@css "._a_9i001jl3a{align-items:baseline;}"];
  [@css "._a_9i0013wj4{align-items:first baseline;}"];
  [@css "._a_9i001r88q{align-items:last baseline;}"];
  [@css "._a_9i001xndt{align-items:center;}"];
  [@css "._a_9i001qn8b{align-items:start;}"];
  [@css "._a_9i00112ai{align-items:end;}"];
  [@css "._a_9i001mgp6{align-items:self-start;}"];
  [@css "._a_9i001yf6q{align-items:self-end;}"];
  [@css "._a_9i001n9n2{align-items:unsafe start;}"];
  [@css "._a_9i0018fld{align-items:safe start;}"];
  [@css "._a_9h00182qi{align-content:normal;}"];
  [@css "._a_9h001tf19{align-content:baseline;}"];
  [@css "._a_9h001e56e{align-content:first baseline;}"];
  [@css "._a_9h001bvxk{align-content:last baseline;}"];
  [@css "._a_9h001t6ef{align-content:space-between;}"];
  [@css "._a_9h001ulzr{align-content:space-around;}"];
  [@css "._a_9h001zzqp{align-content:space-evenly;}"];
  [@css "._a_9h001sg0i{align-content:stretch;}"];
  [@css "._a_9h001ho4p{align-content:center;}"];
  [@css "._a_9h00162g1{align-content:start;}"];
  [@css "._a_9h001otui{align-content:end;}"];
  [@css "._a_9h001vgc7{align-content:flex-start;}"];
  [@css "._a_9h001x96o{align-content:flex-end;}"];
  [@css "._a_9h0016jw8{align-content:unsafe start;}"];
  [@css "._a_9h0012jhg{align-content:safe start;}"];
  [@css "._a_9j002nscv{justify-self:auto;}"];
  [@css "._a_9j0020v6u{justify-self:normal;}"];
  [@css "._a_9j002yvex{justify-self:stretch;}"];
  [@css "._a_9j0023z27{justify-self:baseline;}"];
  [@css "._a_9j0025zq0{justify-self:first baseline;}"];
  [@css "._a_9j0020186{justify-self:last baseline;}"];
  [@css "._a_9j002dfjc{justify-self:center;}"];
  [@css "._a_9j002bxzs{justify-self:start;}"];
  [@css "._a_9j002pv54{justify-self:end;}"];
  [@css "._a_9j002ab6k{justify-self:self-start;}"];
  [@css "._a_9j002zxgz{justify-self:self-end;}"];
  [@css "._a_9j002obw4{justify-self:unsafe start;}"];
  [@css "._a_9j0025sda{justify-self:safe start;}"];
  [@css "._a_9j0024swf{justify-self:left;}"];
  [@css "._a_9j0025rli{justify-self:right;}"];
  [@css "._a_9j002akos{justify-self:safe right;}"];
  [@css "._a_9i002t02p{justify-items:normal;}"];
  [@css "._a_9i002w19q{justify-items:stretch;}"];
  [@css "._a_9i002sd3r{justify-items:baseline;}"];
  [@css "._a_9i002oxkb{justify-items:first baseline;}"];
  [@css "._a_9i002nqwq{justify-items:last baseline;}"];
  [@css "._a_9i002hncw{justify-items:center;}"];
  [@css "._a_9i0027xd1{justify-items:start;}"];
  [@css "._a_9i002d6ik{justify-items:end;}"];
  [@css "._a_9i002ujby{justify-items:self-start;}"];
  [@css "._a_9i002jls5{justify-items:self-end;}"];
  [@css "._a_9i002kxpa{justify-items:unsafe start;}"];
  [@css "._a_9i002igov{justify-items:safe start;}"];
  [@css "._a_9i002hueq{justify-items:left;}"];
  [@css "._a_9i002tw7a{justify-items:right;}"];
  [@css "._a_9i002zryg{justify-items:safe right;}"];
  [@css "._a_9i002qp4r{justify-items:legacy;}"];
  [@css "._a_9i0026jur{justify-items:legacy left;}"];
  [@css "._a_9i0021n9p{justify-items:legacy right;}"];
  [@css "._a_9i0028x1c{justify-items:legacy center;}"];
  [@css "._a_9h002dm5u{justify-content:normal;}"];
  [@css "._a_9h002dmss{justify-content:space-between;}"];
  [@css "._a_9h0024oss{justify-content:space-around;}"];
  [@css "._a_9h002462w{justify-content:space-evenly;}"];
  [@css "._a_9h00208ak{justify-content:stretch;}"];
  [@css "._a_9h002ndxa{justify-content:center;}"];
  [@css "._a_9h002xozo{justify-content:start;}"];
  [@css "._a_9h002rfkc{justify-content:end;}"];
  [@css "._a_9h0020841{justify-content:flex-start;}"];
  [@css "._a_9h002getn{justify-content:flex-end;}"];
  [@css "._a_9h002ygzb{justify-content:unsafe start;}"];
  [@css "._a_9h002pp7h{justify-content:safe start;}"];
  [@css "._a_9h002dmac{justify-content:left;}"];
  [@css "._a_9h002jo9q{justify-content:right;}"];
  [@css "._a_9h00289l6{justify-content:safe right;}"];
  [@css "._a_9hqrgx{place-content:normal;}"];
  [@css "._a_9hzktz{place-content:baseline;}"];
  [@css "._a_9h0k3s{place-content:first baseline;}"];
  [@css "._a_9hlpj3{place-content:last baseline;}"];
  [@css "._a_9hg07y{place-content:space-between;}"];
  [@css "._a_9hn9tt{place-content:space-around;}"];
  [@css "._a_9h8p3p{place-content:space-evenly;}"];
  [@css "._a_9hwium{place-content:stretch;}"];
  [@css "._a_9hdqw8{place-content:center;}"];
  [@css "._a_9h5dhv{place-content:start;}"];
  [@css "._a_9hnyc7{place-content:end;}"];
  [@css "._a_9hdrdu{place-content:flex-start;}"];
  [@css "._a_9hnttj{place-content:flex-end;}"];
  [@css "._a_9h71ck{place-content:unsafe start;}"];
  [@css "._a_9hqxqj{place-content:safe start;}"];
  [@css "._a_9h3qoo{place-content:normal normal;}"];
  [@css "._a_9hnuac{place-content:baseline normal;}"];
  [@css "._a_9h0fds{place-content:first baseline normal;}"];
  [@css "._a_9hhpg7{place-content:space-between normal;}"];
  [@css "._a_9hzrg5{place-content:center normal;}"];
  [@css "._a_9hz0tb{place-content:unsafe start normal;}"];
  [@css "._a_9hi3io{place-content:normal stretch;}"];
  [@css "._a_9hfbzg{place-content:baseline stretch;}"];
  [@css "._a_9h8zlv{place-content:first baseline stretch;}"];
  [@css "._a_9h4shn{place-content:center stretch;}"];
  [@css "._a_9hf3b8{place-content:unsafe start stretch;}"];
  [@css "._a_9hb47q{place-content:normal safe right;}"];
  [@css "._a_9hwp5i{place-content:baseline safe right;}"];
  [@css "._a_9hpafp{place-content:first baseline safe right;}"];
  [@css "._a_9htr2b{place-content:space-between safe right;}"];
  [@css "._a_9hhl56{place-content:center safe right;}"];
  [@css "._a_9h288f{place-content:unsafe start safe right;}"];
  [@css "._a_9iu5yn{place-items:normal;}"];
  [@css "._a_9iwgtc{place-items:stretch;}"];
  [@css "._a_9ip3r0{place-items:baseline;}"];
  [@css "._a_9ijtjp{place-items:first baseline;}"];
  [@css "._a_9imap8{place-items:last baseline;}"];
  [@css "._a_9iym04{place-items:center;}"];
  [@css "._a_9icea0{place-items:start;}"];
  [@css "._a_9iqbga{place-items:end;}"];
  [@css "._a_9icfae{place-items:self-start;}"];
  [@css "._a_9i4r6c{place-items:self-end;}"];
  [@css "._a_9ik81w{place-items:unsafe start;}"];
  [@css "._a_9iboah{place-items:safe start;}"];
  [@css "._a_9ioh71{place-items:normal normal;}"];
  [@css "._a_9ivk8n{place-items:stretch normal;}"];
  [@css "._a_9im489{place-items:baseline normal;}"];
  [@css "._a_9ibjab{place-items:first baseline normal;}"];
  [@css "._a_9iz5p3{place-items:self-start normal;}"];
  [@css "._a_9i2at7{place-items:unsafe start normal;}"];
  [@css "._a_9i9qwi{place-items:normal stretch;}"];
  [@css "._a_9ig7oz{place-items:stretch stretch;}"];
  [@css "._a_9iecxz{place-items:baseline stretch;}"];
  [@css "._a_9idtd3{place-items:first baseline stretch;}"];
  [@css "._a_9itjgd{place-items:self-start stretch;}"];
  [@css "._a_9i24mg{place-items:unsafe start stretch;}"];
  [@css "._a_9infmq{place-items:normal last baseline;}"];
  [@css "._a_9i203s{place-items:stretch last baseline;}"];
  [@css "._a_9iq0j0{place-items:baseline last baseline;}"];
  [@css "._a_9isgia{place-items:first baseline last baseline;}"];
  [@css "._a_9i5oxa{place-items:self-start last baseline;}"];
  [@css "._a_9if3bh{place-items:unsafe start last baseline;}"];
  [@css "._a_9io9xj{place-items:normal legacy left;}"];
  [@css "._a_9iaufw{place-items:stretch legacy left;}"];
  [@css "._a_9i4fdy{place-items:baseline legacy left;}"];
  [@css "._a_9ilg27{place-items:first baseline legacy left;}"];
  [@css "._a_9i6nyr{place-items:self-start legacy left;}"];
  [@css "._a_9isbzm{place-items:unsafe start legacy left;}"];
  [@css "._a_6f9awh{gap:0 0;}"];
  [@css "._a_6f0ra0{gap:0 1em;}"];
  [@css "._a_6f6cki{gap:1em;}"];
  [@css "._a_6fkubh{gap:1em 1em;}"];
  [@css "._a_6f001zqln{-webkit-column-gap:0;column-gap:0;}"];
  [@css "._a_6f0012mee{-webkit-column-gap:1em;column-gap:1em;}"];
  [@css "._a_6f0015ixr{-webkit-column-gap:normal;column-gap:normal;}"];
  [@css "._a_6f0022sqe{row-gap:0;}"];
  [@css "._a_6f002i0al{row-gap:1em;}"];
  [@css "._a_7sx8z6{margin-trim:none;}"];
  [@css "._a_7s8oi1{margin-trim:in-flow;}"];
  [@css "._a_7sk011{margin-trim:all;}"];
  
  CSS.make("_a_9j001lqh0", []);
  CSS.make("_a_9j0015str", []);
  CSS.make("_a_9j001qoy4", []);
  CSS.make("_a_9j001wum8", []);
  CSS.make("_a_9j0012ze6", []);
  CSS.make("_a_9j0010zg2", []);
  CSS.make("_a_9j001e9xz", []);
  CSS.make("_a_9j001ehcy", []);
  CSS.make("_a_9j001qp3k", []);
  CSS.make("_a_9j001bvnc", []);
  CSS.make("_a_9j001hf65", []);
  CSS.make("_a_9j001gsxr", []);
  CSS.make("_a_9j001q3l2", []);
  CSS.make("_a_9i0017rk4", []);
  CSS.make("_a_9i0011ack", []);
  CSS.make("_a_9i001jl3a", []);
  CSS.make("_a_9i0013wj4", []);
  CSS.make("_a_9i001r88q", []);
  CSS.make("_a_9i001xndt", []);
  CSS.make("_a_9i001qn8b", []);
  CSS.make("_a_9i00112ai", []);
  CSS.make("_a_9i001mgp6", []);
  CSS.make("_a_9i001yf6q", []);
  CSS.make("_a_9i001n9n2", []);
  CSS.make("_a_9i0018fld", []);
  CSS.make("_a_9h00182qi", []);
  CSS.make("_a_9h001tf19", []);
  CSS.make("_a_9h001e56e", []);
  CSS.make("_a_9h001bvxk", []);
  CSS.make("_a_9h001t6ef", []);
  CSS.make("_a_9h001ulzr", []);
  CSS.make("_a_9h001zzqp", []);
  CSS.make("_a_9h001sg0i", []);
  CSS.make("_a_9h001ho4p", []);
  CSS.make("_a_9h00162g1", []);
  CSS.make("_a_9h001otui", []);
  CSS.make("_a_9h001vgc7", []);
  CSS.make("_a_9h001x96o", []);
  CSS.make("_a_9h0016jw8", []);
  CSS.make("_a_9h0012jhg", []);
  CSS.make("_a_9j002nscv", []);
  CSS.make("_a_9j0020v6u", []);
  CSS.make("_a_9j002yvex", []);
  CSS.make("_a_9j0023z27", []);
  CSS.make("_a_9j0025zq0", []);
  CSS.make("_a_9j0020186", []);
  CSS.make("_a_9j002dfjc", []);
  CSS.make("_a_9j002bxzs", []);
  CSS.make("_a_9j002pv54", []);
  CSS.make("_a_9j002ab6k", []);
  CSS.make("_a_9j002zxgz", []);
  CSS.make("_a_9j002obw4", []);
  CSS.make("_a_9j0025sda", []);
  CSS.make("_a_9j0024swf", []);
  CSS.make("_a_9j0025rli", []);
  CSS.make("_a_9j002akos", []);
  CSS.make("_a_9i002t02p", []);
  CSS.make("_a_9i002w19q", []);
  CSS.make("_a_9i002sd3r", []);
  CSS.make("_a_9i002oxkb", []);
  CSS.make("_a_9i002nqwq", []);
  CSS.make("_a_9i002hncw", []);
  CSS.make("_a_9i0027xd1", []);
  CSS.make("_a_9i002d6ik", []);
  CSS.make("_a_9i002ujby", []);
  CSS.make("_a_9i002jls5", []);
  CSS.make("_a_9i002kxpa", []);
  CSS.make("_a_9i002igov", []);
  CSS.make("_a_9i002hueq", []);
  CSS.make("_a_9i002tw7a", []);
  CSS.make("_a_9i002zryg", []);
  CSS.make("_a_9i002qp4r", []);
  CSS.make("_a_9i0026jur", []);
  CSS.make("_a_9i0021n9p", []);
  CSS.make("_a_9i0028x1c", []);
  CSS.make("_a_9h002dm5u", []);
  CSS.make("_a_9h002dmss", []);
  CSS.make("_a_9h0024oss", []);
  CSS.make("_a_9h002462w", []);
  CSS.make("_a_9h00208ak", []);
  CSS.make("_a_9h002ndxa", []);
  CSS.make("_a_9h002xozo", []);
  CSS.make("_a_9h002rfkc", []);
  CSS.make("_a_9h0020841", []);
  CSS.make("_a_9h002getn", []);
  CSS.make("_a_9h002ygzb", []);
  CSS.make("_a_9h002pp7h", []);
  CSS.make("_a_9h002dmac", []);
  CSS.make("_a_9h002jo9q", []);
  CSS.make("_a_9h00289l6", []);
  CSS.make("_a_9hqrgx", []);
  CSS.make("_a_9hzktz", []);
  CSS.make("_a_9h0k3s", []);
  CSS.make("_a_9hlpj3", []);
  CSS.make("_a_9hg07y", []);
  CSS.make("_a_9hn9tt", []);
  CSS.make("_a_9h8p3p", []);
  CSS.make("_a_9hwium", []);
  CSS.make("_a_9hdqw8", []);
  CSS.make("_a_9h5dhv", []);
  CSS.make("_a_9hnyc7", []);
  CSS.make("_a_9hdrdu", []);
  CSS.make("_a_9hnttj", []);
  CSS.make("_a_9h71ck", []);
  CSS.make("_a_9hqxqj", []);
  CSS.make("_a_9h3qoo", []);
  CSS.make("_a_9hnuac", []);
  CSS.make("_a_9h0fds", []);
  CSS.make("_a_9hhpg7", []);
  CSS.make("_a_9hzrg5", []);
  CSS.make("_a_9hz0tb", []);
  CSS.make("_a_9hi3io", []);
  CSS.make("_a_9hfbzg", []);
  CSS.make("_a_9h8zlv", []);
  CSS.make("_a_9h4shn", []);
  CSS.make("_a_9hf3b8", []);
  CSS.make("_a_9hb47q", []);
  CSS.make("_a_9hwp5i", []);
  CSS.make("_a_9hpafp", []);
  CSS.make("_a_9htr2b", []);
  CSS.make("_a_9hhl56", []);
  CSS.make("_a_9h288f", []);
  CSS.make("_a_9iu5yn", []);
  CSS.make("_a_9iwgtc", []);
  CSS.make("_a_9ip3r0", []);
  CSS.make("_a_9ijtjp", []);
  CSS.make("_a_9imap8", []);
  CSS.make("_a_9iym04", []);
  CSS.make("_a_9icea0", []);
  CSS.make("_a_9iqbga", []);
  CSS.make("_a_9icfae", []);
  CSS.make("_a_9i4r6c", []);
  CSS.make("_a_9ik81w", []);
  CSS.make("_a_9iboah", []);
  CSS.make("_a_9ioh71", []);
  CSS.make("_a_9ivk8n", []);
  CSS.make("_a_9im489", []);
  CSS.make("_a_9ibjab", []);
  CSS.make("_a_9iz5p3", []);
  CSS.make("_a_9i2at7", []);
  CSS.make("_a_9i9qwi", []);
  CSS.make("_a_9ig7oz", []);
  CSS.make("_a_9iecxz", []);
  CSS.make("_a_9idtd3", []);
  CSS.make("_a_9itjgd", []);
  CSS.make("_a_9i24mg", []);
  CSS.make("_a_9infmq", []);
  CSS.make("_a_9i203s", []);
  CSS.make("_a_9iq0j0", []);
  CSS.make("_a_9isgia", []);
  CSS.make("_a_9i5oxa", []);
  CSS.make("_a_9if3bh", []);
  CSS.make("_a_9io9xj", []);
  CSS.make("_a_9iaufw", []);
  CSS.make("_a_9i4fdy", []);
  CSS.make("_a_9ilg27", []);
  CSS.make("_a_9i6nyr", []);
  CSS.make("_a_9isbzm", []);
  
  CSS.make("_a_6f9awh", []);
  CSS.make("_a_6f0ra0", []);
  CSS.make("_a_6f6cki", []);
  CSS.make("_a_6fkubh", []);
  CSS.make("_a_6f001zqln", []);
  CSS.make("_a_6f0012mee", []);
  CSS.make("_a_6f0015ixr", []);
  CSS.make("_a_6f0022sqe", []);
  CSS.make("_a_6f002i0al", []);
  
  CSS.make("_a_7sx8z6", []);
  CSS.make("_a_7s8oi1", []);
  CSS.make("_a_7sk011", []);
