This test ensures the ppx generates the correct output against styled-ppx.native
If this test fail means that the module is not in sync with the ppx
  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > EOF

  $ cat > dune << EOF
  > (executable
  >  (name input)
  >  (libraries styled-ppx.native)
  >  (preprocess (pps styled-ppx)))
  > EOF

  $ dune build

  $ dune describe pp ./input.re | sed '1,/^];$/d'
  [@css ".a-9j001lqh0{align-self:auto;}"];
  [@css ".a-9j0015str{align-self:normal;}"];
  [@css ".a-9j001qoy4{align-self:stretch;}"];
  [@css ".a-9j001wum8{align-self:baseline;}"];
  [@css ".a-9j0012ze6{align-self:first baseline;}"];
  [@css ".a-9j0010zg2{align-self:last baseline;}"];
  [@css ".a-9j001e9xz{align-self:center;}"];
  [@css ".a-9j001ehcy{align-self:start;}"];
  [@css ".a-9j001qp3k{align-self:end;}"];
  [@css ".a-9j001bvnc{align-self:self-start;}"];
  [@css ".a-9j001hf65{align-self:self-end;}"];
  [@css ".a-9j001gsxr{align-self:unsafe start;}"];
  [@css ".a-9j001q3l2{align-self:safe start;}"];
  [@css ".a-9i0017rk4{align-items:normal;}"];
  [@css ".a-9i0011ack{align-items:stretch;}"];
  [@css ".a-9i001jl3a{align-items:baseline;}"];
  [@css ".a-9i0013wj4{align-items:first baseline;}"];
  [@css ".a-9i001r88q{align-items:last baseline;}"];
  [@css ".a-9i001xndt{align-items:center;}"];
  [@css ".a-9i001qn8b{align-items:start;}"];
  [@css ".a-9i00112ai{align-items:end;}"];
  [@css ".a-9i001mgp6{align-items:self-start;}"];
  [@css ".a-9i001yf6q{align-items:self-end;}"];
  [@css ".a-9i001n9n2{align-items:unsafe start;}"];
  [@css ".a-9i0018fld{align-items:safe start;}"];
  [@css ".a-9h00182qi{align-content:normal;}"];
  [@css ".a-9h001tf19{align-content:baseline;}"];
  [@css ".a-9h001e56e{align-content:first baseline;}"];
  [@css ".a-9h001bvxk{align-content:last baseline;}"];
  [@css ".a-9h001t6ef{align-content:space-between;}"];
  [@css ".a-9h001ulzr{align-content:space-around;}"];
  [@css ".a-9h001zzqp{align-content:space-evenly;}"];
  [@css ".a-9h001sg0i{align-content:stretch;}"];
  [@css ".a-9h001ho4p{align-content:center;}"];
  [@css ".a-9h00162g1{align-content:start;}"];
  [@css ".a-9h001otui{align-content:end;}"];
  [@css ".a-9h001vgc7{align-content:flex-start;}"];
  [@css ".a-9h001x96o{align-content:flex-end;}"];
  [@css ".a-9h0016jw8{align-content:unsafe start;}"];
  [@css ".a-9h0012jhg{align-content:safe start;}"];
  [@css ".a-9j002nscv{justify-self:auto;}"];
  [@css ".a-9j0020v6u{justify-self:normal;}"];
  [@css ".a-9j002yvex{justify-self:stretch;}"];
  [@css ".a-9j0023z27{justify-self:baseline;}"];
  [@css ".a-9j0025zq0{justify-self:first baseline;}"];
  [@css ".a-9j0020186{justify-self:last baseline;}"];
  [@css ".a-9j002dfjc{justify-self:center;}"];
  [@css ".a-9j002bxzs{justify-self:start;}"];
  [@css ".a-9j002pv54{justify-self:end;}"];
  [@css ".a-9j002ab6k{justify-self:self-start;}"];
  [@css ".a-9j002zxgz{justify-self:self-end;}"];
  [@css ".a-9j002obw4{justify-self:unsafe start;}"];
  [@css ".a-9j0025sda{justify-self:safe start;}"];
  [@css ".a-9j0024swf{justify-self:left;}"];
  [@css ".a-9j0025rli{justify-self:right;}"];
  [@css ".a-9j002akos{justify-self:safe right;}"];
  [@css ".a-9i002t02p{justify-items:normal;}"];
  [@css ".a-9i002w19q{justify-items:stretch;}"];
  [@css ".a-9i002sd3r{justify-items:baseline;}"];
  [@css ".a-9i002oxkb{justify-items:first baseline;}"];
  [@css ".a-9i002nqwq{justify-items:last baseline;}"];
  [@css ".a-9i002hncw{justify-items:center;}"];
  [@css ".a-9i0027xd1{justify-items:start;}"];
  [@css ".a-9i002d6ik{justify-items:end;}"];
  [@css ".a-9i002ujby{justify-items:self-start;}"];
  [@css ".a-9i002jls5{justify-items:self-end;}"];
  [@css ".a-9i002kxpa{justify-items:unsafe start;}"];
  [@css ".a-9i002igov{justify-items:safe start;}"];
  [@css ".a-9i002hueq{justify-items:left;}"];
  [@css ".a-9i002tw7a{justify-items:right;}"];
  [@css ".a-9i002zryg{justify-items:safe right;}"];
  [@css ".a-9i002qp4r{justify-items:legacy;}"];
  [@css ".a-9i0026jur{justify-items:legacy left;}"];
  [@css ".a-9i0021n9p{justify-items:legacy right;}"];
  [@css ".a-9i0028x1c{justify-items:legacy center;}"];
  [@css ".a-9h002dm5u{justify-content:normal;}"];
  [@css ".a-9h002dmss{justify-content:space-between;}"];
  [@css ".a-9h0024oss{justify-content:space-around;}"];
  [@css ".a-9h002462w{justify-content:space-evenly;}"];
  [@css ".a-9h00208ak{justify-content:stretch;}"];
  [@css ".a-9h002ndxa{justify-content:center;}"];
  [@css ".a-9h002xozo{justify-content:start;}"];
  [@css ".a-9h002rfkc{justify-content:end;}"];
  [@css ".a-9h0020841{justify-content:flex-start;}"];
  [@css ".a-9h002getn{justify-content:flex-end;}"];
  [@css ".a-9h002ygzb{justify-content:unsafe start;}"];
  [@css ".a-9h002pp7h{justify-content:safe start;}"];
  [@css ".a-9h002dmac{justify-content:left;}"];
  [@css ".a-9h002jo9q{justify-content:right;}"];
  [@css ".a-9h00289l6{justify-content:safe right;}"];
  [@css ".a-9hqrgx{place-content:normal;}"];
  [@css ".a-9hzktz{place-content:baseline;}"];
  [@css ".a-9h0k3s{place-content:first baseline;}"];
  [@css ".a-9hlpj3{place-content:last baseline;}"];
  [@css ".a-9hg07y{place-content:space-between;}"];
  [@css ".a-9hn9tt{place-content:space-around;}"];
  [@css ".a-9h8p3p{place-content:space-evenly;}"];
  [@css ".a-9hwium{place-content:stretch;}"];
  [@css ".a-9hdqw8{place-content:center;}"];
  [@css ".a-9h5dhv{place-content:start;}"];
  [@css ".a-9hnyc7{place-content:end;}"];
  [@css ".a-9hdrdu{place-content:flex-start;}"];
  [@css ".a-9hnttj{place-content:flex-end;}"];
  [@css ".a-9h71ck{place-content:unsafe start;}"];
  [@css ".a-9hqxqj{place-content:safe start;}"];
  [@css ".a-9h3qoo{place-content:normal normal;}"];
  [@css ".a-9hnuac{place-content:baseline normal;}"];
  [@css ".a-9h0fds{place-content:first baseline normal;}"];
  [@css ".a-9hhpg7{place-content:space-between normal;}"];
  [@css ".a-9hzrg5{place-content:center normal;}"];
  [@css ".a-9hz0tb{place-content:unsafe start normal;}"];
  [@css ".a-9hi3io{place-content:normal stretch;}"];
  [@css ".a-9hfbzg{place-content:baseline stretch;}"];
  [@css ".a-9h8zlv{place-content:first baseline stretch;}"];
  [@css ".a-9h4shn{place-content:center stretch;}"];
  [@css ".a-9hf3b8{place-content:unsafe start stretch;}"];
  [@css ".a-9hb47q{place-content:normal safe right;}"];
  [@css ".a-9hwp5i{place-content:baseline safe right;}"];
  [@css ".a-9hpafp{place-content:first baseline safe right;}"];
  [@css ".a-9htr2b{place-content:space-between safe right;}"];
  [@css ".a-9hhl56{place-content:center safe right;}"];
  [@css ".a-9h288f{place-content:unsafe start safe right;}"];
  [@css ".a-9iu5yn{place-items:normal;}"];
  [@css ".a-9iwgtc{place-items:stretch;}"];
  [@css ".a-9ip3r0{place-items:baseline;}"];
  [@css ".a-9ijtjp{place-items:first baseline;}"];
  [@css ".a-9imap8{place-items:last baseline;}"];
  [@css ".a-9iym04{place-items:center;}"];
  [@css ".a-9icea0{place-items:start;}"];
  [@css ".a-9iqbga{place-items:end;}"];
  [@css ".a-9icfae{place-items:self-start;}"];
  [@css ".a-9i4r6c{place-items:self-end;}"];
  [@css ".a-9ik81w{place-items:unsafe start;}"];
  [@css ".a-9iboah{place-items:safe start;}"];
  [@css ".a-9ioh71{place-items:normal normal;}"];
  [@css ".a-9ivk8n{place-items:stretch normal;}"];
  [@css ".a-9im489{place-items:baseline normal;}"];
  [@css ".a-9ibjab{place-items:first baseline normal;}"];
  [@css ".a-9iz5p3{place-items:self-start normal;}"];
  [@css ".a-9i2at7{place-items:unsafe start normal;}"];
  [@css ".a-9i9qwi{place-items:normal stretch;}"];
  [@css ".a-9ig7oz{place-items:stretch stretch;}"];
  [@css ".a-9iecxz{place-items:baseline stretch;}"];
  [@css ".a-9idtd3{place-items:first baseline stretch;}"];
  [@css ".a-9itjgd{place-items:self-start stretch;}"];
  [@css ".a-9i24mg{place-items:unsafe start stretch;}"];
  [@css ".a-9infmq{place-items:normal last baseline;}"];
  [@css ".a-9i203s{place-items:stretch last baseline;}"];
  [@css ".a-9iq0j0{place-items:baseline last baseline;}"];
  [@css ".a-9isgia{place-items:first baseline last baseline;}"];
  [@css ".a-9i5oxa{place-items:self-start last baseline;}"];
  [@css ".a-9if3bh{place-items:unsafe start last baseline;}"];
  [@css ".a-9io9xj{place-items:normal legacy left;}"];
  [@css ".a-9iaufw{place-items:stretch legacy left;}"];
  [@css ".a-9i4fdy{place-items:baseline legacy left;}"];
  [@css ".a-9ilg27{place-items:first baseline legacy left;}"];
  [@css ".a-9i6nyr{place-items:self-start legacy left;}"];
  [@css ".a-9isbzm{place-items:unsafe start legacy left;}"];
  [@css ".a-6f9awh{gap:0 0;}"];
  [@css ".a-6f0ra0{gap:0 1em;}"];
  [@css ".a-6f6cki{gap:1em;}"];
  [@css ".a-6fkubh{gap:1em 1em;}"];
  [@css ".a-6f001zqln{-webkit-column-gap:0;column-gap:0;}"];
  [@css ".a-6f0012mee{-webkit-column-gap:1em;column-gap:1em;}"];
  [@css ".a-6f0015ixr{-webkit-column-gap:normal;column-gap:normal;}"];
  [@css ".a-6f0022sqe{row-gap:0;}"];
  [@css ".a-6f002i0al{row-gap:1em;}"];
  [@css ".a-7sx8z6{margin-trim:none;}"];
  [@css ".a-7s8oi1{margin-trim:in-flow;}"];
  [@css ".a-7sk011{margin-trim:all;}"];
  
  CSS.make("a-9j001lqh0", []);
  CSS.make("a-9j0015str", []);
  CSS.make("a-9j001qoy4", []);
  CSS.make("a-9j001wum8", []);
  CSS.make("a-9j0012ze6", []);
  CSS.make("a-9j0010zg2", []);
  CSS.make("a-9j001e9xz", []);
  CSS.make("a-9j001ehcy", []);
  CSS.make("a-9j001qp3k", []);
  CSS.make("a-9j001bvnc", []);
  CSS.make("a-9j001hf65", []);
  CSS.make("a-9j001gsxr", []);
  CSS.make("a-9j001q3l2", []);
  CSS.make("a-9i0017rk4", []);
  CSS.make("a-9i0011ack", []);
  CSS.make("a-9i001jl3a", []);
  CSS.make("a-9i0013wj4", []);
  CSS.make("a-9i001r88q", []);
  CSS.make("a-9i001xndt", []);
  CSS.make("a-9i001qn8b", []);
  CSS.make("a-9i00112ai", []);
  CSS.make("a-9i001mgp6", []);
  CSS.make("a-9i001yf6q", []);
  CSS.make("a-9i001n9n2", []);
  CSS.make("a-9i0018fld", []);
  CSS.make("a-9h00182qi", []);
  CSS.make("a-9h001tf19", []);
  CSS.make("a-9h001e56e", []);
  CSS.make("a-9h001bvxk", []);
  CSS.make("a-9h001t6ef", []);
  CSS.make("a-9h001ulzr", []);
  CSS.make("a-9h001zzqp", []);
  CSS.make("a-9h001sg0i", []);
  CSS.make("a-9h001ho4p", []);
  CSS.make("a-9h00162g1", []);
  CSS.make("a-9h001otui", []);
  CSS.make("a-9h001vgc7", []);
  CSS.make("a-9h001x96o", []);
  CSS.make("a-9h0016jw8", []);
  CSS.make("a-9h0012jhg", []);
  CSS.make("a-9j002nscv", []);
  CSS.make("a-9j0020v6u", []);
  CSS.make("a-9j002yvex", []);
  CSS.make("a-9j0023z27", []);
  CSS.make("a-9j0025zq0", []);
  CSS.make("a-9j0020186", []);
  CSS.make("a-9j002dfjc", []);
  CSS.make("a-9j002bxzs", []);
  CSS.make("a-9j002pv54", []);
  CSS.make("a-9j002ab6k", []);
  CSS.make("a-9j002zxgz", []);
  CSS.make("a-9j002obw4", []);
  CSS.make("a-9j0025sda", []);
  CSS.make("a-9j0024swf", []);
  CSS.make("a-9j0025rli", []);
  CSS.make("a-9j002akos", []);
  CSS.make("a-9i002t02p", []);
  CSS.make("a-9i002w19q", []);
  CSS.make("a-9i002sd3r", []);
  CSS.make("a-9i002oxkb", []);
  CSS.make("a-9i002nqwq", []);
  CSS.make("a-9i002hncw", []);
  CSS.make("a-9i0027xd1", []);
  CSS.make("a-9i002d6ik", []);
  CSS.make("a-9i002ujby", []);
  CSS.make("a-9i002jls5", []);
  CSS.make("a-9i002kxpa", []);
  CSS.make("a-9i002igov", []);
  CSS.make("a-9i002hueq", []);
  CSS.make("a-9i002tw7a", []);
  CSS.make("a-9i002zryg", []);
  CSS.make("a-9i002qp4r", []);
  CSS.make("a-9i0026jur", []);
  CSS.make("a-9i0021n9p", []);
  CSS.make("a-9i0028x1c", []);
  CSS.make("a-9h002dm5u", []);
  CSS.make("a-9h002dmss", []);
  CSS.make("a-9h0024oss", []);
  CSS.make("a-9h002462w", []);
  CSS.make("a-9h00208ak", []);
  CSS.make("a-9h002ndxa", []);
  CSS.make("a-9h002xozo", []);
  CSS.make("a-9h002rfkc", []);
  CSS.make("a-9h0020841", []);
  CSS.make("a-9h002getn", []);
  CSS.make("a-9h002ygzb", []);
  CSS.make("a-9h002pp7h", []);
  CSS.make("a-9h002dmac", []);
  CSS.make("a-9h002jo9q", []);
  CSS.make("a-9h00289l6", []);
  CSS.make("a-9hqrgx", []);
  CSS.make("a-9hzktz", []);
  CSS.make("a-9h0k3s", []);
  CSS.make("a-9hlpj3", []);
  CSS.make("a-9hg07y", []);
  CSS.make("a-9hn9tt", []);
  CSS.make("a-9h8p3p", []);
  CSS.make("a-9hwium", []);
  CSS.make("a-9hdqw8", []);
  CSS.make("a-9h5dhv", []);
  CSS.make("a-9hnyc7", []);
  CSS.make("a-9hdrdu", []);
  CSS.make("a-9hnttj", []);
  CSS.make("a-9h71ck", []);
  CSS.make("a-9hqxqj", []);
  CSS.make("a-9h3qoo", []);
  CSS.make("a-9hnuac", []);
  CSS.make("a-9h0fds", []);
  CSS.make("a-9hhpg7", []);
  CSS.make("a-9hzrg5", []);
  CSS.make("a-9hz0tb", []);
  CSS.make("a-9hi3io", []);
  CSS.make("a-9hfbzg", []);
  CSS.make("a-9h8zlv", []);
  CSS.make("a-9h4shn", []);
  CSS.make("a-9hf3b8", []);
  CSS.make("a-9hb47q", []);
  CSS.make("a-9hwp5i", []);
  CSS.make("a-9hpafp", []);
  CSS.make("a-9htr2b", []);
  CSS.make("a-9hhl56", []);
  CSS.make("a-9h288f", []);
  CSS.make("a-9iu5yn", []);
  CSS.make("a-9iwgtc", []);
  CSS.make("a-9ip3r0", []);
  CSS.make("a-9ijtjp", []);
  CSS.make("a-9imap8", []);
  CSS.make("a-9iym04", []);
  CSS.make("a-9icea0", []);
  CSS.make("a-9iqbga", []);
  CSS.make("a-9icfae", []);
  CSS.make("a-9i4r6c", []);
  CSS.make("a-9ik81w", []);
  CSS.make("a-9iboah", []);
  CSS.make("a-9ioh71", []);
  CSS.make("a-9ivk8n", []);
  CSS.make("a-9im489", []);
  CSS.make("a-9ibjab", []);
  CSS.make("a-9iz5p3", []);
  CSS.make("a-9i2at7", []);
  CSS.make("a-9i9qwi", []);
  CSS.make("a-9ig7oz", []);
  CSS.make("a-9iecxz", []);
  CSS.make("a-9idtd3", []);
  CSS.make("a-9itjgd", []);
  CSS.make("a-9i24mg", []);
  CSS.make("a-9infmq", []);
  CSS.make("a-9i203s", []);
  CSS.make("a-9iq0j0", []);
  CSS.make("a-9isgia", []);
  CSS.make("a-9i5oxa", []);
  CSS.make("a-9if3bh", []);
  CSS.make("a-9io9xj", []);
  CSS.make("a-9iaufw", []);
  CSS.make("a-9i4fdy", []);
  CSS.make("a-9ilg27", []);
  CSS.make("a-9i6nyr", []);
  CSS.make("a-9isbzm", []);
  
  CSS.make("a-6f9awh", []);
  CSS.make("a-6f0ra0", []);
  CSS.make("a-6f6cki", []);
  CSS.make("a-6fkubh", []);
  CSS.make("a-6f001zqln", []);
  CSS.make("a-6f0012mee", []);
  CSS.make("a-6f0015ixr", []);
  CSS.make("a-6f0022sqe", []);
  CSS.make("a-6f002i0al", []);
  
  CSS.make("a-7sx8z6", []);
  CSS.make("a-7s8oi1", []);
  CSS.make("a-7sk011", []);
