/* CSS Animations Level 1 */
[%css {|animation-name: foo|}];
[%css {|animation-name: foo, bar|}];
[%css {|animation-duration: 0s|}];
[%css {|animation-duration: 1s|}];
[%css {|animation-duration: 100ms|}];
[%css {|animation-timing-function: ease|}];
[%css {|animation-timing-function: linear|}];
[%css {|animation-timing-function: ease-in|}];
[%css {|animation-timing-function: ease-out|}];
[%css {|animation-timing-function: ease-in-out|}];
[%css {|animation-timing-function: cubic-bezier(.5, .5, .5, .5)|}];
[%css {|animation-timing-function: cubic-bezier(.5, 1.5, .5, -2.5)|}];
[%css {|animation-timing-function: step-start|}];
[%css {|animation-timing-function: step-end|}];
[%css {|animation-timing-function: steps(3, start)|}];
[%css {|animation-timing-function: steps(5, end)|}];
[%css {|animation-iteration-count: infinite|}];
[%css {|animation-iteration-count: 8|}];
[%css {|animation-iteration-count: 4.35|}];
[%css {|animation-direction: normal|}];
[%css {|animation-direction: alternate|}];
[%css {|animation-direction: reverse|}];
[%css {|animation-direction: alternate-reverse|}];
[%css {|animation-play-state: running|}];
[%css {|animation-play-state: paused|}];
[%css {|animation-delay: 1s|}];
[%css {|animation-delay: -1s|}];
[%css {|animation-fill-mode: none|}];
[%css {|animation-fill-mode: forwards|}];
[%css {|animation-fill-mode: backwards|}];
[%css {|animation-fill-mode: both|}];
[%css {|animation: foo 1s 2s infinite linear alternate both|}];
