  $ dune build
  File "input.re", line 102, characters 2-37:
  102 |   "border: 1px solid $(borderColor);"
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Error (warning 5 [ignored-partial-application]): this function application is partial,
  maybe some arguments are missing.
  File "input.re", line 102, characters 2-37:
  102 |   "border: 1px solid $(borderColor);"
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Error: This expression has type
           [< `dashed
            | `dotted
            | `double
            | `groove
            | `hidden
            | `inherit_
            | `initial
            | `inset
            | `none
            | `outset
            | `revert
            | `revertLayer
            | `ridge
            | `solid
            | `unset
            | `var of string
            | `varDefault of string * string ] ->
           Css_types.Color.t -> string
         but an expression was expected of type string
  [1]

  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-1chbfez { box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.1); }
  .css-1xwtd6e { box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.1), 0px 4px 8px 0px rgba(0, 0, 0, 0.2); }
  .css-sh81my { box-shadow: inset 0px 2px 4px 0px rgba(0, 0, 0, 0.1); }
  .css-zic50l { box-shadow: none; }
  .css-5zabwz { box-shadow: 0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -2px rgba(0, 0, 0, 0.1); }
  .css-18htonh { border: 1px solid black; }
  .css-1std6hk { border: 2px dashed #ff0000; }
  .css-1gztx3a { border: 1px solid transparent; }
  .css-beqw7r { border: none; }
  .css-2jt51e { border-top: 1px solid red; }
  .css-3uexsj { border-right: 2px dashed blue; }
  .css-1ptzxri { border-bottom: 3px dotted green; }
  .css-8z3asr { border-left: 4px double orange; }
  .css-7var9k { border-width: 2px; }
  .css-xa8wr5 { border-style: solid; }
  .css-18m2z4p { border-color: #333; }
  .css-3554ws { border: 1px solid #ccc; }
  .css-115dty2 { border-radius: 8px; }
  .css-10r78hf { box-shadow: 0px 4px 6px 0px rgba(0, 0, 0, 0.1); }
  .css-3kvpfc { border: 1px solid #e5e7eb; }
  .css-u2i2l9 { border-radius: 12px; }
  .css-3jntjq { box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.1), 0px 1px 2px -1px rgba(0, 0, 0, 0.1); }
  .css-8e9xhn { border: 1px solid rgba(0, 0, 0, 0.05); }
  .css-h70u1y { border-radius: 16px; }
  .css-s185u4 { border: 2px solid #3b82f6; }
  .css-1ddw9i4 { box-shadow: 0px 0px 0px 0px rgba(59, 130, 246, 0.5); }
  .css-nlnz8u { border: 1px solid var(--var-1eesnn6); }
  .css-wnq6zu { box-shadow: var(--var-gdn5sz) var(--var-104d914) var(--var-dk37bb) var(--var-11b5qtb) var(--var-b6ajx9); }
  .css-uay0z3 { box-shadow: var(--var-w6cvnd); }
  .css-15zzg0l { border: var(--var-1b2z9tl) solid black; }
  .css-1s4q8ih { background-color: var(--var-1aw7857); }
  .css-2gvnfk { box-shadow: var(--var-19o14xv); }
