The canonical empty-marker idiom: cross-module refs to bindings whose
[%css] body is empty. The marker classes carry no rules of their own,
they only serve as "tags" that consumers chain into selectors.

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

The PPX records two distinct cross-module refs and one synthetic dep per
distinct longident.

  $ refmt --parse ml --print re n.ml
  [@css ".a-5rfx7x{display:none;}"];
  [@css ".a-63jxq5rnzdi.\000M.isOpen\000{display:block;}"];
  [@css ".a-i40ek3903ie.\000M.isHovered\000{background:rgba(0, 0, 0, 0.1);}"];
  [@css.bindings
    [("N.modal", "id-1g7stmc", "a-5rfx7x a-63jxq5rnzdi a-i40ek3903ie")]
  ];
  [@css.refs
    [("M.isOpen", "n.ml", 6, 6, 14), ("M.isHovered", "n.ml", 7, 6, 17)]
  ];
  let _ = M.isOpen;
  let _ = M.isHovered;
  let modal =
    CSS.make("label:modal id-1g7stmc a-5rfx7x a-63jxq5rnzdi a-i40ek3903ie", []);

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .a-5rfx7x{display:none;}
  .a-63jxq5rnzdi.id-1fhciug{display:block;}
  .a-i40ek3903ie.id-145hsfw{background:rgba(0, 0, 0, 0.1);}
