The canonical empty-marker idiom: cross-module refs to bindings whose
[%css] body is empty. The marker classes carry no rules of their own,
they only serve as "tags" that consumers chain into selectors.

  $ refmt --parse re --print ml m.re > m.ml
  $ ../../standalone.exe --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ ../../standalone.exe --impl n.ml -o n.ml

The PPX records two distinct cross-module refs and one synthetic dep per
distinct longident.

  $ refmt --parse ml --print re n.ml
  [@css ".a-1hyfx7x{display:none;}"];
  [@css ".a-pznzdi.\000M.isOpen\000{display:block;}"];
  [@css ".a-1d03ie.\000M.isHovered\000{background:rgba(0, 0, 0, 0.1);}"];
  [@css.bindings [("N.modal", "id-1g7stmc", "a-1hyfx7x a-pznzdi a-1d03ie")]];
  [@css.refs
    [("M.isOpen", "n.ml", 6, 6, 14), ("M.isHovered", "n.ml", 7, 6, 17)]
  ];
  let _ = M.isOpen;
  let _ = M.isHovered;
  let modal =
    CSS.make("label:modal id-1g7stmc a-1hyfx7x a-pznzdi a-1d03ie", []);

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .a-1hyfx7x{display:none;}
  .a-pznzdi.id-1fhciug{display:block;}
  .a-1d03ie.id-145hsfw{background:rgba(0, 0, 0, 0.1);}
