A directory-fallback group key becomes a layer name from its last path
segment, with every character outside `[A-Za-z0-9_-]` replaced by `_`.

  $ mkdir -p lib/na.tive

  $ cat > lib/na.tive/x.ml <<EOF
  > [@@@css "._a_nativex{color:teal;}"]
  > let x = 1
  > EOF

  $ styled-ppx.generate --layers lib/na.tive/x.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  @layer na_tive;
  @layer na_tive {
  ._a_nativex{color:teal;}
  }
  }

Two different library keys that sanitize to the same layer name still get
their own `@layer` blocks under that name; CSS itself concatenates
same-named `@layer` blocks into one layer. The `@layer` order statement
lists that name once (first occurrence): repeating a name there doesn't
declare a second layer, it only re-mentions the same slot. A warning names
both libraries once.

  $ mkdir foo.bar foo_bar

  $ cat > foo.bar/a.ml <<EOF
  > [@@@css.config [("library-name", "foo.bar")]]
  > [@@@css "._a_dotlib{color:navy;}"]
  > EOF

  $ cat > foo_bar/b.ml <<EOF
  > [@@@css.config [("library-name", "foo_bar")]]
  > [@@@css "._a_underscorelib{color:maroon;}"]
  > EOF

  $ styled-ppx.generate --layers foo.bar/a.ml foo_bar/b.ml
  styled-ppx: layer name "foo_bar" is shared by libraries foo.bar, foo_bar; their rules merge into one layer
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  @layer foo_bar;
  @layer foo_bar {
  ._a_dotlib{color:navy;}
  }
  @layer foo_bar {
  ._a_underscorelib{color:maroon;}
  }
  }
