// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Emotion = require("@ahrefs/bs-emotion/src/Emotion.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

var emotion = Emotion.css(undefined, /* :: */[
      Emotion.display(/* inline */423610969),
      /* :: */[
        Emotion.color(Emotion.hex("000000")),
        /* :: */[
          Emotion.padding(Emotion.px(10)),
          /* [] */0
        ]
      ]
    ]);

Emotion.css(undefined, /* :: */[
      Emotion.display(/* flex */-1010954439),
      /* [] */0
    ]);

var Style = { };

function Index$Demo(Props) {
  return React.createElement("div", undefined, React.createElement("div", undefined, "React API"));
}

var Demo = {
  make: Index$Demo
};

ReactDOMRe.renderToElementWithId(React.createElement(Index$Demo, { }), "app");

exports.emotion = emotion;
exports.Style = Style;
exports.Demo = Demo;
/* emotion Not a pure module */
