// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Emotion = require("@ahrefs/bs-emotion/src/Emotion.bs.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

var styles = Emotion.css(undefined, /* :: */[
      Emotion.display(/* flex */-1010954439),
      /* :: */[
        Emotion.alignItems(Emotion.center),
        /* :: */[
          Emotion.justifyContent(Emotion.center),
          /* :: */[
            Emotion.width(Emotion.px(200)),
            /* :: */[
              Emotion.height(Emotion.px(200)),
              /* :: */[
                Emotion.borderRadius(Emotion.px(4)),
                /* :: */[
                  Emotion.borderRadius(Emotion.pct(2)),
                  /* :: */[
                    Emotion.fontSize(Emotion.px(24)),
                    /* :: */[
                      Emotion.margin(Emotion.px(5)),
                      /* :: */[
                        Emotion.padding(Emotion.px(5)),
                        /* :: */[
                          Emotion.paddingTop(Emotion.px(2)),
                          /* :: */[
                            Emotion.paddingBottom(Emotion.px(2)),
                            /* :: */[
                              Emotion.color(Emotion.hex("FFFFFF")),
                              /* :: */[
                                Emotion.backgroundColor(Emotion.hex("444")),
                                /* :: */[
                                  Emotion.transitionTimingFunction(Emotion.easeInOut),
                                  /* :: */[
                                    Emotion.alignContent(Emotion.normal),
                                    /* :: */[
                                      Emotion.alignItems(Emotion.center),
                                      /* :: */[
                                        Emotion.alignSelf(Emotion.auto),
                                        /* :: */[
                                          Emotion.animationDelay(Emotion.s(0)),
                                          /* :: */[
                                            Emotion.animationDirection(Emotion.normal),
                                            /* :: */[
                                              Emotion.animationDuration(Emotion.s(0)),
                                              /* :: */[
                                                Emotion.animationFillMode(Emotion.none),
                                                /* :: */[
                                                  Emotion.animationTimingFunction(Emotion.ease),
                                                  /* :: */[
                                                    Emotion.backgroundBlendMode(Emotion.normal),
                                                    /* :: */[
                                                      Emotion.backgroundColor(Emotion.rgb(68, 68, 68)),
                                                      /* :: */[
                                                        Emotion.backgroundImage(Emotion.none),
                                                        /* :: */[
                                                          Emotion.backgroundSize(Emotion.auto),
                                                          /* :: */[
                                                            Emotion.borderBottomColor(Emotion.rgb(255, 255, 255)),
                                                            /* :: */[
                                                              Emotion.borderBottomLeftRadius(Emotion.pct(2)),
                                                              /* :: */[
                                                                Emotion.borderBottomRightRadius(Emotion.pct(2)),
                                                                /* :: */[
                                                                  Emotion.borderBottomStyle(Emotion.none),
                                                                  /* :: */[
                                                                    Emotion.borderBottomWidth(Emotion.px(0)),
                                                                    /* :: */[
                                                                      Emotion.borderLeftColor(Emotion.rgb(255, 255, 255)),
                                                                      /* :: */[
                                                                        Emotion.borderLeftStyle(Emotion.none),
                                                                        /* :: */[
                                                                          Emotion.borderLeftWidth(Emotion.px(0)),
                                                                          /* :: */[
                                                                            Emotion.borderRightColor(Emotion.rgb(255, 255, 255)),
                                                                            /* :: */[
                                                                              Emotion.borderRightStyle(Emotion.none),
                                                                              /* :: */[
                                                                                Emotion.borderRightWidth(Emotion.px(0)),
                                                                                /* :: */[
                                                                                  Emotion.borderTopColor(Emotion.rgb(255, 255, 255)),
                                                                                  /* :: */[
                                                                                    Emotion.borderTopLeftRadius(Emotion.pct(2)),
                                                                                    /* :: */[
                                                                                      Emotion.borderTopRightRadius(Emotion.pct(2)),
                                                                                      /* :: */[
                                                                                        Emotion.borderTopStyle(Emotion.none),
                                                                                        /* :: */[
                                                                                          Emotion.borderTopWidth(Emotion.px(0)),
                                                                                          /* :: */[
                                                                                            Emotion.bottom(Emotion.auto),
                                                                                            /* :: */[
                                                                                              Emotion.clipPath(Emotion.none),
                                                                                              /* :: */[
                                                                                                Emotion.color(Emotion.rgb(255, 255, 255)),
                                                                                                /* :: */[
                                                                                                  Emotion.cursor(Emotion.auto),
                                                                                                  /* :: */[
                                                                                                    Emotion.display(/* flex */-1010954439),
                                                                                                    /* :: */[
                                                                                                      Emotion.fill(Emotion.rgb(0, 0, 0)),
                                                                                                      /* :: */[
                                                                                                        Emotion.filter(Emotion.none),
                                                                                                        /* :: */[
                                                                                                          Emotion.flexBasis(Emotion.auto),
                                                                                                          /* :: */[
                                                                                                            Emotion.flexDirection(Emotion.row),
                                                                                                            /* :: */[
                                                                                                              Emotion.flexGrow(0),
                                                                                                              /* :: */[
                                                                                                                Emotion.flexShrink(1),
                                                                                                                /* :: */[
                                                                                                                  Emotion.flexWrap(Emotion.nowrap),
                                                                                                                  /* :: */[
                                                                                                                    Emotion.$$float(Emotion.none),
                                                                                                                    /* :: */[
                                                                                                                      Emotion.fontKerning(Emotion.auto),
                                                                                                                      /* :: */[
                                                                                                                        Emotion.fontSize(Emotion.px(24)),
                                                                                                                        /* :: */[
                                                                                                                          Emotion.fontStyle(Emotion.normal),
                                                                                                                          /* :: */[
                                                                                                                            Emotion.gridAutoColumns(Emotion.auto),
                                                                                                                            /* :: */[
                                                                                                                              Emotion.gridAutoFlow(Emotion.row),
                                                                                                                              /* :: */[
                                                                                                                                Emotion.gridAutoRows(Emotion.auto),
                                                                                                                                /* :: */[
                                                                                                                                  Emotion.gridColumnEnd(Emotion.auto),
                                                                                                                                  /* :: */[
                                                                                                                                    Emotion.gridColumnStart(Emotion.auto),
                                                                                                                                    /* :: */[
                                                                                                                                      Emotion.gridRowEnd(Emotion.auto),
                                                                                                                                      /* :: */[
                                                                                                                                        Emotion.gridRowStart(Emotion.auto),
                                                                                                                                        /* :: */[
                                                                                                                                          Emotion.gridTemplateAreas(Emotion.none),
                                                                                                                                          /* :: */[
                                                                                                                                            Emotion.gridTemplateColumns(Emotion.none),
                                                                                                                                            /* :: */[
                                                                                                                                              Emotion.gridTemplateRows(Emotion.none),
                                                                                                                                              /* :: */[
                                                                                                                                                Emotion.height(Emotion.px(200)),
                                                                                                                                                /* :: */[
                                                                                                                                                  Emotion.justifyContent(Emotion.center),
                                                                                                                                                  /* :: */[
                                                                                                                                                    Emotion.justifyItems(Emotion.normal),
                                                                                                                                                    /* :: */[
                                                                                                                                                      Emotion.justifySelf(Emotion.auto),
                                                                                                                                                      /* :: */[
                                                                                                                                                        Emotion.left(Emotion.auto),
                                                                                                                                                        /* :: */[
                                                                                                                                                          Emotion.letterSpacing(Emotion.normal),
                                                                                                                                                          /* :: */[
                                                                                                                                                            Emotion.lineHeight(Emotion.normal),
                                                                                                                                                            /* :: */[
                                                                                                                                                              Emotion.listStyleImage(Emotion.none),
                                                                                                                                                              /* :: */[
                                                                                                                                                                Emotion.listStyleType(/* disc */-1033279659),
                                                                                                                                                                /* :: */[
                                                                                                                                                                  Emotion.marginBottom(Emotion.px(5)),
                                                                                                                                                                  /* :: */[
                                                                                                                                                                    Emotion.marginLeft(Emotion.px(5)),
                                                                                                                                                                    /* :: */[
                                                                                                                                                                      Emotion.marginRight(Emotion.px(5)),
                                                                                                                                                                      /* :: */[
                                                                                                                                                                        Emotion.marginTop(Emotion.px(5)),
                                                                                                                                                                        /* :: */[
                                                                                                                                                                          Emotion.maxHeight(Emotion.none),
                                                                                                                                                                          /* :: */[
                                                                                                                                                                            Emotion.maxWidth(Emotion.none),
                                                                                                                                                                            /* :: */[
                                                                                                                                                                              Emotion.minHeight(Emotion.px(0)),
                                                                                                                                                                              /* :: */[
                                                                                                                                                                                Emotion.minWidth(Emotion.px(0)),
                                                                                                                                                                                /* :: */[
                                                                                                                                                                                  Emotion.outlineColor(Emotion.rgb(255, 255, 255)),
                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                    Emotion.outlineOffset(Emotion.px(0)),
                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                      Emotion.outlineStyle(Emotion.none),
                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                        Emotion.outlineWidth(Emotion.px(0)),
                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                          Emotion.overflowWrap(Emotion.normal),
                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                            Emotion.paddingBottom(Emotion.px(2)),
                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                              Emotion.paddingLeft(Emotion.px(5)),
                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                Emotion.paddingRight(Emotion.px(5)),
                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                  Emotion.paddingTop(Emotion.px(2)),
                                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                                    Emotion.perspective(Emotion.none),
                                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                                      Emotion.perspectiveOrigin(Emotion.px(105), Emotion.px(102)),
                                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                                        Emotion.pointerEvents(Emotion.auto),
                                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                                          Emotion.position(Emotion.$$static),
                                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                                            Emotion.right(Emotion.auto),
                                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                                              Emotion.stopColor(Emotion.rgb(0, 0, 0)),
                                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                                Emotion.strokeWidth(Emotion.px(1)),
                                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                                  Emotion.tableLayout(Emotion.auto),
                                                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                                                    Emotion.textDecorationColor(Emotion.rgb(255, 255, 255)),
                                                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                                                      Emotion.textDecorationStyle(Emotion.solid),
                                                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                                                        Emotion.textIndent(Emotion.px(0)),
                                                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                                                          Emotion.textTransform(Emotion.none),
                                                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                                                            Emotion.top(Emotion.auto),
                                                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                                                              Emotion.transform(Emotion.none),
                                                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                                                Emotion.transformStyle(/* flat */-1010955335),
                                                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                                                  Emotion.transitionDelay(Emotion.s(0)),
                                                                                                                                                                                                                                  /* :: */[
                                                                                                                                                                                                                                    Emotion.transitionDuration(Emotion.s(0)),
                                                                                                                                                                                                                                    /* :: */[
                                                                                                                                                                                                                                      Emotion.transitionTimingFunction(Emotion.easeInOut),
                                                                                                                                                                                                                                      /* :: */[
                                                                                                                                                                                                                                        Emotion.userSelect(Emotion.auto),
                                                                                                                                                                                                                                        /* :: */[
                                                                                                                                                                                                                                          Emotion.verticalAlign(Emotion.baseline),
                                                                                                                                                                                                                                          /* :: */[
                                                                                                                                                                                                                                            Emotion.whiteSpace(Emotion.normal),
                                                                                                                                                                                                                                            /* :: */[
                                                                                                                                                                                                                                              Emotion.width(Emotion.px(200)),
                                                                                                                                                                                                                                              /* :: */[
                                                                                                                                                                                                                                                Emotion.wordBreak(Emotion.normal),
                                                                                                                                                                                                                                                /* :: */[
                                                                                                                                                                                                                                                  Emotion.wordSpacing(Emotion.px(0)),
                                                                                                                                                                                                                                                  /* [] */0
                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                          ]
                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                              ]
                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                          ]
                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                      ]
                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                  ]
                                                                                                                                                                                                                ]
                                                                                                                                                                                                              ]
                                                                                                                                                                                                            ]
                                                                                                                                                                                                          ]
                                                                                                                                                                                                        ]
                                                                                                                                                                                                      ]
                                                                                                                                                                                                    ]
                                                                                                                                                                                                  ]
                                                                                                                                                                                                ]
                                                                                                                                                                                              ]
                                                                                                                                                                                            ]
                                                                                                                                                                                          ]
                                                                                                                                                                                        ]
                                                                                                                                                                                      ]
                                                                                                                                                                                    ]
                                                                                                                                                                                  ]
                                                                                                                                                                                ]
                                                                                                                                                                              ]
                                                                                                                                                                            ]
                                                                                                                                                                          ]
                                                                                                                                                                        ]
                                                                                                                                                                      ]
                                                                                                                                                                    ]
                                                                                                                                                                  ]
                                                                                                                                                                ]
                                                                                                                                                              ]
                                                                                                                                                            ]
                                                                                                                                                          ]
                                                                                                                                                        ]
                                                                                                                                                      ]
                                                                                                                                                    ]
                                                                                                                                                  ]
                                                                                                                                                ]
                                                                                                                                              ]
                                                                                                                                            ]
                                                                                                                                          ]
                                                                                                                                        ]
                                                                                                                                      ]
                                                                                                                                    ]
                                                                                                                                  ]
                                                                                                                                ]
                                                                                                                              ]
                                                                                                                            ]
                                                                                                                          ]
                                                                                                                        ]
                                                                                                                      ]
                                                                                                                    ]
                                                                                                                  ]
                                                                                                                ]
                                                                                                              ]
                                                                                                            ]
                                                                                                          ]
                                                                                                        ]
                                                                                                      ]
                                                                                                    ]
                                                                                                  ]
                                                                                                ]
                                                                                              ]
                                                                                            ]
                                                                                          ]
                                                                                        ]
                                                                                      ]
                                                                                    ]
                                                                                  ]
                                                                                ]
                                                                              ]
                                                                            ]
                                                                          ]
                                                                        ]
                                                                      ]
                                                                    ]
                                                                  ]
                                                                ]
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

function Index$Component(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: styles
            }, children);
}

var Component = {
  styles: styles,
  make: Index$Component
};

ReactDOMRe.renderToElementWithId(React.createElement(Index$Component, {
          children: "React API"
        }), "app");

exports.Component = Component;
/* styles Not a pure module */
