Cross-module selector interpolation in [%styled.global2].

The PPX cannot resolve M's classes at PPX time (M compiles separately),
so it emits NUL-delimited sentinels in the extracted [@@@css] strings
plus a [@@@css.refs ...] descriptor and a synthetic `let _ = M.x` for
ocamldep tracking. The aggregator harvests the index from M's post-PPX
file and substitutes the sentinels with the real class chains.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

The post-PPX `n.ml` carries unresolved sentinels in [@@@css ...] and the
synthetic dep markers. The styled.global2 module shell is preserved.

  $ cat n.ml
  [@@@css "body .\000M.marker\000{color:red;}"]
  [@@@css ".\000M.card\000:hover{cursor:pointer;}"]
  [@@@css.refs [("M.marker", "n.ml", 2, 10, 18); ("M.card", "n.ml", 6, 5, 11)]]
  let _ = M.marker
  let _ = M.card
  module Globals =
    struct
      let to_string () = ""
      let to_buffer buf = Buffer.add_string buf (to_string ())
      let make () = CSS.global_style_tag (to_string ())
    end

The aggregator resolves `M.marker` to its single class and `M.card` to
the dotted chain of all atoms (so ` .$(M.card):hover` becomes
`.atom1.atom2:hover`, requiring all atoms on the same element).

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-k008qs-card{display:flex;}
  .css-nk32ej-card{padding:10px;}
  body .css-0-marker{color:red;}
  .css-k008qs-card.css-nk32ej-card:hover{cursor:pointer;}
