The first rule's prelude is a comma (`or`) list. Both branches overlap
the second rule's condition at some widths, so De Morgan distributes
the negation into every branch of the `or` list independently.

  $ refmt --parse re --print ml input.re > output.ml
  $ ../../standalone.exe --impl output.ml -o output.ml
  $ cat output.ml
  [@@@css
    "@media (min-width: 600px) and (not (min-width: 900px)), (min-width: 1200px) and (orientation: landscape) and (not (min-width: 900px)){._a_usgmc4epdat{color:red;}}"]
  [@@@css "@media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}"]
  [@@@css.bindings
    [("Output.block", "_id_ovbeuh", "_a_usgmc4epdat _a_mp5mk4et4n8")]]
  let block =
    CSS.make "label:block _id_ovbeuh _a_usgmc4epdat _a_mp5mk4et4n8" []
  let _ = block

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @media (min-width: 600px) and (not (min-width: 900px)), (min-width: 1200px) and (orientation: landscape) and (not (min-width: 900px)){._a_usgmc4epdat{color:red;}}
  @media (min-width: 900px) {._a_mp5mk4et4n8{color:blue;}}
