Minified [%css] omits labels from class names, but custom-property names still
include the owning style namespace and must not collide across independent
styles that reuse the same local interpolation name.

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --minify --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --backgroundColor-ov3le6{syntax:"*";inherits:false;}
  @property --backgroundColor-7yjmr3{syntax:"*";inherits:false;}
  .css-160vrad{background-color:var(--backgroundColor-ov3le6);}
  .css-10a6meq:hover{background-color:var(--backgroundColor-7yjmr3);}
