Extracted styled components expose React components while their CSS flows
through the static extraction pipeline. They also register selector bindings so
`[%cx2]` can reference the component module names.

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-tokvmb-Box{color:red;}
  .css-149d9vx-Box:hover{color:var(--var-2slnay);}
  .css-kusjgz-Button{color:var(--var-sj55zd);}
  .css-hpgf8j-Button{padding:8px;}
  .css-yr9qag-card .css-tokvmb-Box.css-149d9vx-Box{margin:0;}
  .css-10q7t6m-card .css-kusjgz-Button.css-hpgf8j-Button{display:block;}

  $ refmt --parse ml --print re output.ml | grep "module Box"
  module Box: {
  $ refmt --parse ml --print re output.ml | grep "let make:"
    let make: makeProps => React.element;
    let make: makeProps => React.element;
