Relation to `--layers`: library layers nest one level inside whichever of
the two `styled-ppx` layers a library actually contributes to -
`styled-ppx.atoms` for its base/conditional rules, `styled-ppx.global`
too if it also contributes a `[%styled.global]` rule (see the last
example below) - not one nested library set per tier (round 7's design),
since `base` and `conditional` now share one layer. Two libraries,
`z_base` and `a_app` (`a_app` depends on `z_base`, so `z_base`'s rules
come first in dependency order); each has one base atom and one
conditional (`:hover`) atom.

  $ mkdir a_app z_base

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base")]]
  > [@@@css "._a_zbase{color:red;}"]
  > [@@@css "._a_zbasehover:hover{color:darkred;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app")]]
  > [@@@css "._a_aapp{color:blue;}"]
  > [@@@css "._a_aapphover:hover{color:darkblue;}"]
  > let _ = Z_base.widget
  > EOF

Without `--layers`: the usual two tiers, no library nesting - both
libraries' base atoms share one `styled-ppx.base` block (in dependency
order), both `:hover` atoms share one `styled-ppx.conditional` block.

  $ styled-ppx.generate a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  ._a_zbase{color:red;}
  ._a_aapp{color:blue;}
  ._a_zbasehover:hover{color:darkred;}
  ._a_aapphover:hover{color:darkblue;}
  }

With `--layers`: one `@layer z_base, a_app;` statement nested directly
inside `styled-ppx.atoms`, and one nested block per library - each
library's OWN block holds its base atom before its conditional one, the
same tier order the un-layered case above uses, now applied per library
instead of once overall.

  $ styled-ppx.generate --layers a_app/main.ml z_base/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  @layer z_base, a_app;
  @layer z_base {
  ._a_zbase{color:red;}
  ._a_zbasehover:hover{color:darkred;}
  }
  @layer a_app {
  ._a_aapp{color:blue;}
  ._a_aapphover:hover{color:darkblue;}
  }
  }

What the browser does now, and why: nesting `@layer z_base { ... }` inside
`@layer styled-ppx.atoms { ... }` gives `z_base` its own cascade-layer
identity, separate from `a_app`'s - library dependency order (`z_base` before
`a_app`, both declared in the outer `@layer z_base, a_app;` statement)
gives EVERY one of `z_base`'s rules, base or conditional alike, priority
over EVERY one of `a_app`'s, regardless of specificity - the same
"dependency order beats specificity across libraries" trade `--layers`
has always made, now spanning both tiers at once instead of being
re-decided per tier. TIER order (base before conditional) still holds,
but only WITHIN one library's own nested block, where two rules from the
SAME library, at different tiers, still need position to break an
equal-specificity tie (as `z_base`'s own base-then-conditional order
shows above) - it does not hold ACROSS libraries: this is round-7b's
cross-tier specificity fix, deliberately traded away again at the
library boundary, the one place `--layers` has always meant "give up
specificity for deterministic order" (see `emit_library_layers`'s doc
comment in `generate.ml` for the reasoning in full).

Proof that library order beats specificity across libraries, the same
way round 7's separate tier layers used to beat it across tiers:
`z_base`'s own rule here is MORE specific ((0,2,0), a class plus a
descendant class) than `a_app`'s ((0,1,0), one class), but `a_app`
depends on `z_base`, so `a_app`'s own layer is declared AFTER `z_base`'s
- under `--layers`, `a_app`'s rule wins anyway, despite being less
specific, because it sits in a strictly higher-priority CSS layer.

  $ mkdir a_app2 z_base2

  $ cat > z_base2/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base2")]]
  > [@@@css "._a_wrap9k .item{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app2/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app2")]]
  > [@@@css "._a_item{color:blue;}"]
  > let _ = Z_base2.widget
  > EOF

  $ styled-ppx.generate --layers a_app2/main.ml z_base2/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.atoms {
  @layer z_base2, a_app2;
  @layer z_base2 {
  ._a_wrap9k .item{color:red;}
  }
  @layer a_app2 {
  ._a_item{color:blue;}
  }
  }

Without `--layers` (the default), both rules would share the one
`styled-ppx.atoms` layer and ordinary specificity would decide:
`._a_wrap9k .item` (0,2,0) would beat `._a_item` (0,1,0) regardless of
which is textually later, the round-7b-correct outcome. `--layers` is
opt-in specifically to replace that with deterministic dependency order
instead - a consumer choosing `--layers` accepts this trade knowingly,
the same way they always have.

Library layers nest inside `styled-ppx.global` too, the same way, when a
library contributes a `[%styled.global]` rule - `z_base3` here reaches
`html` directly, alongside its own base atom.

  $ mkdir a_app3 z_base3

  $ cat > z_base3/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base3")]]
  > [@@@css "html{margin:0;}"]
  > [@@@css "._a_zbase3{color:red;}"]
  > let widget () = ()
  > EOF

  $ cat > a_app3/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app3")]]
  > [@@@css "body{padding:0;}"]
  > [@@@css "._a_aapp3{color:blue;}"]
  > let _ = Z_base3.widget
  > EOF

  $ styled-ppx.generate --layers a_app3/main.ml z_base3/z_base.ml
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.atoms;
  @layer styled-ppx.global {
  @layer z_base3, a_app3;
  @layer z_base3 {
  html{margin:0;}
  }
  @layer a_app3 {
  body{padding:0;}
  }
  }
  @layer styled-ppx.atoms {
  @layer z_base3, a_app3;
  @layer z_base3 {
  ._a_zbase3{color:red;}
  }
  @layer a_app3 {
  ._a_aapp3{color:blue;}
  }
  }

Each of the two `styled-ppx` layers gets its OWN, independent
`@layer z_base3, a_app3;` statement and its own nested blocks -
`styled-ppx.global`'s library layers never share identity with
`styled-ppx.atoms`'s same-named ones (a nested layer's identity includes
its enclosing layer), so a library's global rule and its own atoms
never have to negotiate priority against each other through library
order at all; `styled-ppx.global` vs `styled-ppx.atoms` priority is
already fixed by the outer statement, same as the un-layered case.
