Cross-module [%cx2] selector interpolation: the PPX emits a sentinel-bearing
CSS rule plus a `[@@@css.refs ...]` descriptor and a synthetic `let _ = M.x`
dependency. The aggregator builds an index across both modules and resolves
the sentinel to the real class chain that `M.marker` minted.

  $ refmt --parse re --print ml m.re > m.ml
  $ standalone --impl m.ml -o m.ml
  $ refmt --parse re --print ml n.re > n.ml
  $ standalone --impl n.ml -o n.ml

The post-PPX `n.ml` carries the unresolved sentinel as an opaque NUL-delimited
string in `[@@@css ...]`, plus a `[@@@css.refs ...]` attribute with the
location and a synthetic dep-tracking `let`.

  $ cat n.ml
  [@@@css ".css-1443u2l-container{background:red;}"]
  [@@@css ".css-z7z9b9-container.\000M.marker\000{background:blue;}"]
  [@@@css.bindings
    [("N.container", "css-1443u2l-container css-z7z9b9-container")]]
  [@@@css.refs [("M.marker", "n.ml", 4, 6, 14)]]
  let _ = M.marker
  let container = CSS.make "css-1443u2l-container css-z7z9b9-container" []

The aggregator resolves the sentinel against the class minted by `m.ml`.
`M.marker` is an empty `[%cx2 {||}]` so it mints `css-0-marker` and emits
no rule of its own; the resolved selector becomes a chain on the consumer.

  $ styled-ppx.generate m.ml n.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-1443u2l-container{background:red;}
  .css-z7z9b9-container.css-0-marker{background:blue;}
