A [%css] selector can reference another local binding's identity class
(`.$(row)`, `&.$(row)`). Two files that use the same LOCAL binding name in
the same selector shape must still mint different atom classes when the
referenced binding's own identity differs between files (here: A's `row` is
`color:red`, B's is `color:blue`, so `A.row` and `B.row` get different
`id-` classes) - the atom's class must hash the RESOLVED selector text, not
the literal `$(row)` marker, which is identical in both files.

  $ refmt --parse re --print ml a.re > a.ml
  $ ../../standalone.exe --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ ../../standalone.exe --impl b.ml -o b.ml

  $ cat a.ml
  [@@@css "._a_4ekvmb{color:red;}"]
  [@@@css "._a_338dn5r760i > div:not(:last-child)._id_qqjiik{display:flex;}"]
  [@@@css "._a_ggsyq5lb484._id_qqjiik{cursor:pointer;}"]
  [@@@css.bindings
    [("A.row", "_id_qqjiik", "_a_4ekvmb");
    ("A.list", "_id_rvu3wa", "_a_338dn5r760i _a_ggsyq5lb484")]]
  let row = CSS.make "label:row _id_qqjiik _a_4ekvmb" []
  let list = CSS.make "label:list _id_rvu3wa _a_338dn5r760i _a_ggsyq5lb484" []

  $ cat b.ml
  [@@@css "._a_4esm7b{color:blue;}"]
  [@@@css "._a_coyc85r18kg > div:not(:last-child)._id_avtt0b{display:flex;}"]
  [@@@css "._a_bnnt45lmqgv._id_avtt0b{cursor:pointer;}"]
  [@@@css.bindings
    [("B.row", "_id_avtt0b", "_a_4esm7b");
    ("B.list", "_id_11lkn7z", "_a_coyc85r18kg _a_bnnt45lmqgv")]]
  let row = CSS.make "label:row _id_avtt0b _a_4esm7b" []
  let list = CSS.make "label:list _id_11lkn7z _a_coyc85r18kg _a_bnnt45lmqgv" []

  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @layer styled-ppx.global, styled-ppx.descendant, styled-ppx.base, styled-ppx.conditional;
  @layer styled-ppx.base {
  ._a_4ekvmb{color:red;}
  ._a_338dn5r760i > div:not(:last-child)._id_qqjiik{display:flex;}
  ._a_ggsyq5lb484._id_qqjiik{cursor:pointer;}
  ._a_4esm7b{color:blue;}
  ._a_coyc85r18kg > div:not(:last-child)._id_avtt0b{display:flex;}
  ._a_bnnt45lmqgv._id_avtt0b{cursor:pointer;}
  }
