A [%css] selector can reference another local binding's identity class
(`.$(row)`, `&.$(row)`). Two files that use the same LOCAL binding name in
the same selector shape must still mint different atom classes when the
referenced binding's own identity differs between files (here: A's `row` is
`color:red`, B's is `color:blue`, so `A.row` and `B.row` get different
`id-` classes) - the atom's class must hash the RESOLVED selector text, not
the literal `$(row)` marker, which is identical in both files.

  $ refmt --parse re --print ml a.re > a.ml
  $ ../../standalone.exe --impl a.ml -o a.ml
  $ refmt --parse re --print ml b.re > b.ml
  $ ../../standalone.exe --impl b.ml -o b.ml

  $ cat a.ml
  [@@@css ".a-4ekvmb{color:red;}"]
  [@@@css ".a-w369s5rdvbo > div:not(:last-child).id-qqjiik{display:flex;}"]
  [@@@css ".a-8gbp15lp0s7.id-qqjiik{cursor:pointer;}"]
  [@@@css.bindings
    [("A.row", "id-qqjiik", "a-4ekvmb");
    ("A.list", "id-rvu3wa", "a-w369s5rdvbo a-8gbp15lp0s7")]]
  let row = CSS.make "label:row id-qqjiik a-4ekvmb" []
  let list = CSS.make "label:list id-rvu3wa a-w369s5rdvbo a-8gbp15lp0s7" []

  $ cat b.ml
  [@@@css ".a-4esm7b{color:blue;}"]
  [@@@css ".a-d0vwd5rv4vk > div:not(:last-child).id-avtt0b{display:flex;}"]
  [@@@css ".a-e4d375ltli5.id-avtt0b{cursor:pointer;}"]
  [@@@css.bindings
    [("B.row", "id-avtt0b", "a-4esm7b");
    ("B.list", "id-11lkn7z", "a-d0vwd5rv4vk a-e4d375ltli5")]]
  let row = CSS.make "label:row id-avtt0b a-4esm7b" []
  let list = CSS.make "label:list id-11lkn7z a-d0vwd5rv4vk a-e4d375ltli5" []

  $ styled-ppx.generate a.ml b.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .a-4ekvmb{color:red;}
  .a-w369s5rdvbo > div:not(:last-child).id-qqjiik{display:flex;}
  .a-8gbp15lp0s7.id-qqjiik{cursor:pointer;}
  .a-4esm7b{color:blue;}
  .a-d0vwd5rv4vk > div:not(:last-child).id-avtt0b{display:flex;}
  .a-e4d375ltli5.id-avtt0b{cursor:pointer;}
