The condition-priority sort key was tried with a THIRD component - a
media-width tie-break (ascending `min-width`, descending `max-width`,
kind before value) - between at-rule rank and pseudo rank. A monorepo
round found it got 2 of 4 real, shipped ties wrong: a `min-width`/
`max-width` RANGE tied against a plain `max-width` rule for the SAME
property has no reliable width-only answer, since only the generator's
OWN INPUT ORDER can ever encode which side a `CSS.merge`/`+++` call meant
as the override - width alone cannot. The width component is REMOVED.
Two rules tied on at-rule rank and pseudo rank now fall straight through
to `List.stable_sort`'s own guarantee: whichever order they already had
when they reached this sort - library, then module dependency order,
then a module's own DEFINITION order - which is also the order a
`CSS.merge`/`+++` call's right-hand (override) argument needs to win,
since the later-defined rule sorts last.

Three real, shipped pairs, all four checked directly (not simulated),
same file so their relative sheet order is checked together:

  $ refmt --parse re --print ml input.re > input.ml

  $ ../../standalone.exe --impl input.ml -o output.ml
  $ cat output.ml
  [@@@css "@property --pad-g2wfjo{syntax:\"*\";inherits:false;}"]
  [@@@css "@property --pad-160gt2j{syntax:\"*\";inherits:false;}"]
  [@@@css "@media (min-width: 768px) {._a_p6loh5rnofe{display:none;}}"]
  [@@@css
    "@media (min-width: 768px) and (max-width: 1279px) {._a_5kutk5rhjfe{display:block;}}"]
  [@@@css
    "@media (min-width: 768px) and (max-width: 1279px) {._in_yqjybn{padding-top:var(--pad-g2wfjo);}}"]
  [@@@css
    "@media (min-width: 768px) and (max-width: 1279px) {._in_yqjybn{padding-left:var(--pad-g2wfjo);}}"]
  [@@@css
    "@media (max-width: 1279px) {._in_11ru35y{padding-top:var(--pad-160gt2j);}}"]
  [@@@css
    "@media (max-width: 1279px) {._in_11ru35y{padding-left:var(--pad-160gt2j);}}"]
  [@@@css
    "@media (min-width: 768px) and (max-width: 1279px) {._a_5kutk850y8f{max-height:1200px;}}"]
  [@@@css "@media (max-width: 767px) {._a_tlkns85mrev{max-height:2000px;}}"]
  [@@@css "@media (max-width: 1279px) {._a_9yyk885k4cx{max-height:10000px;}}"]
  [@@@css.bindings
    [("Input.toggleButton", "_id_3ymu7f", "_a_p6loh5rnofe");
    ("Input.toggleButtonShowAtTablet", "_id_12oj7bj", "_a_5kutk5rhjfe");
    ("Input.header", "_id_o6yfa8", "_in_yqjybn");
    ("Input.headerWithBanner", "_id_181aa5d", "_in_11ru35y");
    ("Input.praiseViewport", "_id_1qycs1i", "_a_5kutk850y8f");
    ("Input.praiseViewportMobile", "_id_1apfsf0", "_a_tlkns85mrev");
    ("Input.praiseViewportExpanded", "_id_5psizx", "_a_9yyk885k4cx")]]
  let toggleButton = CSS.make "label:toggleButton _id_3ymu7f _a_p6loh5rnofe" []
  let toggleButtonShowAtTablet =
    CSS.make "label:toggleButtonShowAtTablet _id_12oj7bj _a_5kutk5rhjfe" []
  let header ~pad =
    CSS.make "label:header _id_o6yfa8 _in_yqjybn"
      [("--pad-g2wfjo", (CSS.Types.Length.toString pad))]
  let headerWithBanner ~pad =
    CSS.make "label:headerWithBanner _id_181aa5d _in_11ru35y"
      [("--pad-160gt2j", (CSS.Types.Length.toString pad))]
  let praiseViewport =
    CSS.make "label:praiseViewport _id_1qycs1i _a_5kutk850y8f" []
  let praiseViewportMobile =
    CSS.make "label:praiseViewportMobile _id_1apfsf0 _a_tlkns85mrev" []
  let praiseViewportExpanded =
    CSS.make "label:praiseViewportExpanded _id_5psizx _a_9yyk885k4cx" []
  let _ =
    (toggleButton, toggleButtonShowAtTablet, header, headerWithBanner,
      praiseViewport, praiseViewportMobile, praiseViewportExpanded)

  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  @property --pad-g2wfjo{syntax:"*";inherits:false;}
  @property --pad-160gt2j{syntax:"*";inherits:false;}
  @media (min-width: 768px) {._a_p6loh5rnofe{display:none;}}
  @media (min-width: 768px) and (max-width: 1279px) {._a_5kutk5rhjfe{display:block;}}
  @media (min-width: 768px) and (max-width: 1279px) {._a_5kutk850y8f{max-height:1200px;}}
  @media (max-width: 767px) {._a_tlkns85mrev{max-height:2000px;}}
  @media (max-width: 1279px) {._a_9yyk885k4cx{max-height:10000px;}}
  @media (min-width: 768px) and (max-width: 1279px) {._in_yqjybn{padding-top:var(--pad-g2wfjo);}}
  @media (min-width: 768px) and (max-width: 1279px) {._in_yqjybn{padding-left:var(--pad-g2wfjo);}}
  @media (max-width: 1279px) {._in_11ru35y{padding-top:var(--pad-160gt2j);}}
  @media (max-width: 1279px) {._in_11ru35y{padding-left:var(--pad-160gt2j);}}

`toggleButtonShowAtTablet` (declared second) sorts after `toggleButton`
(declared first) - the later-defined rule wins. `praiseViewport`,
`praiseViewportMobile` and `praiseViewportExpanded` sort in EXACTLY their
declaration order, so `praiseViewportExpanded` - declared LAST of the
three - sorts last and wins against BOTH earlier rules, not just the one
declared immediately before it; at a width where all three could apply
(e.g. 700px, inside every one of `max-height:2000px`'s, `max-height:
10000px`'s and - if it were also unbounded below - `max-height:1200px`'s
own range), `max-height:10000px` wins. `header`/`headerWithBanner` sort
in their own, separate cluster (their shared property, `padding-top`/
`padding-left`, is a deeper shorthand family than the plain leaf
properties `display`/`max-height` above, an EARLIER, unrelated key
component the removed width key never touched either) - but WITHIN that
cluster, the same rule applies: `headerWithBanner` (declared second)
sorts after `header` (declared first) and wins, bundle or not.

This is the exact fix for the real regression the removed width key
caused: `praiseViewport`/`praiseViewportExpanded` reached one element via
`CSS.merge`, `praiseViewportExpanded` (the max-width-only rule) as the
intended override - the removed key's max-width-descending rule put the
NARROWER `max-width:767px` (`praiseViewportMobile`, an unrelated third
rule sharing the same property) textually LAST at some widths, so a
button meant to always open past 1279px silently stayed closed at
700px. Stable definition order has no such failure mode: it never
compares two conditions' raw numbers at all.
