A module with no `[%css]` at all still takes part in library dependency
ordering: `middle/middle.ml` carries no rule and no `[@@@css.config]`, but
`a_app` reaches `z_base` only THROUGH it (`a_app` references `Middle`,
`Middle` references `Z_base`), and `z_base`'s rule must still come first.

  $ mkdir a_app z_base middle

  $ cat > z_base/z_base.ml <<EOF
  > [@@@css.config [("library-name", "z_base")]]
  > [@@@css "._a_basewidget{color:red;}"]
  > let widget () = ()
  > EOF

`middle` carries no `[@@@css.config]` either, so its group falls back to
its own directory (`middle`) - a fallback group with zero rules of its own,
existing purely as a reference hop.

  $ cat > middle/middle.ml <<EOF
  > let widget = Z_base.widget
  > EOF

  $ cat > a_app/main.ml <<EOF
  > [@@@css.config [("library-name", "a_app")]]
  > [@@@css "._a_appmain{color:blue;}"]
  > let _ = Middle.widget
  > EOF

  $ styled-ppx.generate --log info a_app/main.ml z_base/z_base.ml middle/middle.ml
  styled-ppx: output file: stdout
  styled-ppx: library order: z_base, middle, a_app
  styled-ppx: order: z_base: Z_base
  styled-ppx: order: middle: Middle
  styled-ppx: order: a_app: Main
  styled-ppx: environment: development
  /* This file is generated by styled-ppx, do not edit manually */
  ._a_basewidget{color:red;}
  ._a_appmain{color:blue;}

`middle` is ordered between the two (`--log info` names it in the library
order), but contributes nothing to the output text - it has no rule to
emit, only a place in the dependency graph.
