Generated by `make css-oracle` (scripts/css-oracle/conformance.mjs).
Do not edit by hand: regenerate and commit; `make css-oracle-check`
gates drift.

Executable form of the coverage report
(packages/css-grammar/data/coverage.md, oracle: @webref/css 8.7.0).

  $ cat > dune-project << EOF
  > (lang dune 3.10)
  > EOF

Every property the css-grammar registry supports compiles with the
simplest expansion of its spec value-definition syntax (349
properties; on failure the compiler error below names the offender, and
`dune describe pp ./supported.re` shows all offenders at once):

  $ cat > dune << EOF
  > (executable
  >  (name supported)
  >  (modules supported)
  >  (libraries styled-ppx.native)
  >  (preprocess (pps styled-ppx)))
  > EOF

  $ dune build

Every spec property the registry does not support fails to compile: each
of the 232 declarations must produce exactly one error node and no
generated style, so undocumented partial support cannot creep in:

  $ cat > dune << EOF
  > (executable
  >  (name unsupported)
  >  (modules unsupported)
  >  (libraries styled-ppx.native)
  >  (preprocess (pps styled-ppx)))
  > EOF

  $ dune describe pp ./unsupported.re | grep -c "ocaml.error"
  232

  $ dune describe pp ./unsupported.re | grep -c "CSS.make"
  0
  [1]
