/* Generated by `make css-oracle` (scripts/css-oracle/conformance.mjs).
   Do not edit by hand: regenerate and commit; `make css-oracle-check`
   gates drift. */

/* 349 properties the registry supports, each with the
   simplest keywords-and-zero-values expansion of its spec syntax.
   217 supported properties have no such expansion and are
   exercised by the hand-written css-support suites instead:
     -webkit-box-orient
     -webkit-text-fill-color
     -webkit-text-stroke
     -webkit-text-stroke-color
     -webkit-text-stroke-width
     animation
     animation-composition
     animation-delay
     animation-direction
     animation-fill-mode
     animation-iteration-count
     animation-play-state
     animation-range
     animation-timeline
     animation-timing-function
     background
     background-attachment
     background-blend-mode
     background-clip
     background-color
     background-image
     background-origin
     background-position
     background-repeat
     background-size
     block-size
     border
     border-block
     border-block-color
     border-block-end
     border-block-end-color
     border-block-end-style
     border-block-end-width
     border-block-start
     border-block-start-color
     border-block-start-style
     border-block-start-width
     border-block-style
     border-block-width
     border-bottom
     border-bottom-color
     border-bottom-left-radius
     border-bottom-right-radius
     border-bottom-style
     border-bottom-width
     border-color
     border-end-end-radius
     border-end-start-radius
     border-image
     border-inline
     border-inline-color
     border-inline-end
     border-inline-end-color
     border-inline-end-style
     border-inline-end-width
     border-inline-start
     border-inline-start-color
     border-inline-start-style
     border-inline-start-width
     border-inline-style
     border-inline-width
     border-left
     border-left-color
     border-left-style
     border-left-width
     border-radius
     border-right
     border-right-color
     border-right-style
     border-right-width
     border-start-end-radius
     border-start-start-radius
     border-style
     border-top
     border-top-color
     border-top-left-radius
     border-top-right-radius
     border-top-style
     border-top-width
     border-width
     box-shadow
     caret
     color
     color-adjust
     column-rule
     column-rule-color
     column-rule-style
     column-rule-width
     columns
     container
     corner-block-end-shape
     corner-block-start-shape
     corner-bottom-left-shape
     corner-bottom-right-shape
     corner-bottom-shape
     corner-end-end-shape
     corner-end-start-shape
     corner-inline-end-shape
     corner-inline-start-shape
     corner-left-shape
     corner-right-shape
     corner-shape
     corner-start-end-shape
     corner-start-start-shape
     corner-top-left-shape
     corner-top-right-shape
     corner-top-shape
     cue
     cursor
     cx
     cy
     fill
     fill-opacity
     flex-flow
     flood-color
     flood-opacity
     font
     font-family
     gap
     grid
     grid-area
     grid-auto-columns
     grid-auto-rows
     grid-column
     grid-column-end
     grid-column-start
     grid-row
     grid-row-end
     grid-row-start
     hyphenate-limit-zone
     initial-letter-align
     inline-size
     inset
     inset-block
     inset-inline
     interest-delay
     isolation
     lighting-color
     list-style
     margin
     margin-block
     margin-block-end
     margin-block-start
     margin-inline
     margin-inline-end
     margin-inline-start
     mask
     mask-border
     mask-border-outset
     mask-border-repeat
     mask-border-slice
     mask-border-source
     mask-border-width
     mask-composite
     mask-image
     mask-mode
     mask-origin
     mask-position
     mask-repeat
     mask-size
     max-block-size
     max-inline-size
     min-block-size
     min-inline-size
     object-position
     offset
     offset-distance
     opacity
     orphans
     outline
     outline-width
     overflow
     padding
     padding-block
     padding-block-end
     padding-block-start
     padding-bottom
     padding-inline
     padding-inline-end
     padding-inline-start
     padding-left
     padding-right
     padding-top
     pause
     perspective-origin
     place-content
     place-items
     place-self
     position-try
     r
     rest
     scroll-timeline
     shape-image-threshold
     shape-margin
     stop-color
     stop-opacity
     stroke
     stroke-color
     stroke-opacity
     text-decoration
     text-decoration-color
     text-emphasis
     text-emphasis-color
     text-indent
     text-wrap
     timeline-trigger-activation-range
     timeline-trigger-active-range
     timeline-trigger-source
     transition
     transition-behavior
     transition-delay
     transition-duration
     transition-timing-function
     view-timeline
     widows
     x
     y
   no properties are currently excluded as known grammar bugs.
*/

[%css {|-webkit-line-clamp: none|}];
[%css {|-webkit-user-select: auto|}];
[%css {|accent-color: auto|}];
[%css {|align-content: normal|}];
[%css {|align-items: normal|}];
[%css {|align-self: auto|}];
[%css {|alignment-baseline: baseline|}];
[%css {|all: initial|}];
[%css {|anchor-name: none|}];
[%css {|anchor-scope: none|}];
[%css {|animation-duration: auto|}];
[%css {|animation-name: none|}];
[%css {|animation-range-end: normal|}];
[%css {|animation-range-start: normal|}];
[%css {|animation-trigger: none|}];
[%css {|appearance: none|}];
[%css {|aspect-ratio: auto|}];
[%css {|backdrop-filter: none|}];
[%css {|backface-visibility: visible|}];
[%css {|background-position-x: center|}];
[%css {|background-position-y: center|}];
[%css {|baseline-shift: sub|}];
[%css {|baseline-source: auto|}];
[%css {|border-collapse: separate|}];
[%css {|border-image-outset: 0|}];
[%css {|border-image-repeat: stretch|}];
[%css {|border-image-slice: 0|}];
[%css {|border-image-source: none|}];
[%css {|border-image-width: 0|}];
[%css {|border-spacing: 0|}];
[%css {|bottom: auto|}];
[%css {|box-decoration-break: slice|}];
[%css {|box-sizing: content-box|}];
[%css {|break-after: auto|}];
[%css {|break-before: auto|}];
[%css {|break-inside: auto|}];
[%css {|caption-side: top|}];
[%css {|caret-animation: auto|}];
[%css {|caret-color: auto|}];
[%css {|caret-shape: auto|}];
[%css {|clear: inline-start|}];
[%css {|clip: auto|}];
[%css {|clip-path: none|}];
[%css {|clip-rule: nonzero|}];
[%css {|color-interpolation: auto|}];
[%css {|color-interpolation-filters: auto|}];
[%css {|color-scheme: normal|}];
[%css {|column-count: auto|}];
[%css {|column-fill: auto|}];
[%css {|column-gap: normal|}];
[%css {|column-height: auto|}];
[%css {|column-span: none|}];
[%css {|column-width: auto|}];
[%css {|column-wrap: auto|}];
[%css {|contain: none|}];
[%css {|contain-intrinsic-block-size: none|}];
[%css {|contain-intrinsic-height: none|}];
[%css {|contain-intrinsic-inline-size: none|}];
[%css {|contain-intrinsic-size: none|}];
[%css {|contain-intrinsic-width: none|}];
[%css {|container-name: none|}];
[%css {|container-type: normal|}];
[%css {|content: normal|}];
[%css {|content-visibility: visible|}];
[%css {|counter-increment: none|}];
[%css {|counter-reset: none|}];
[%css {|counter-set: none|}];
[%css {|cue-after: none|}];
[%css {|cue-before: none|}];
[%css {|d: none|}];
[%css {|direction: ltr|}];
[%css {|display: grid-lanes|}];
[%css {|dominant-baseline: auto|}];
[%css {|dynamic-range-limit: standard|}];
[%css {|empty-cells: show|}];
[%css {|field-sizing: fixed|}];
[%css {|fill-rule: nonzero|}];
[%css {|filter: none|}];
[%css {|flex: none|}];
[%css {|flex-basis: content|}];
[%css {|flex-direction: row|}];
[%css {|flex-grow: 0|}];
[%css {|flex-shrink: 0|}];
[%css {|flex-wrap: nowrap|}];
[%css {|float: block-start|}];
[%css {|font-feature-settings: normal|}];
[%css {|font-kerning: auto|}];
[%css {|font-language-override: normal|}];
[%css {|font-optical-sizing: auto|}];
[%css {|font-palette: normal|}];
[%css {|font-size: math|}];
[%css {|font-size-adjust: none|}];
[%css {|font-style: normal|}];
[%css {|font-synthesis: none|}];
[%css {|font-synthesis-position: auto|}];
[%css {|font-synthesis-small-caps: auto|}];
[%css {|font-synthesis-style: auto|}];
[%css {|font-synthesis-weight: auto|}];
[%css {|font-variant: normal|}];
[%css {|font-variant-alternates: normal|}];
[%css {|font-variant-caps: normal|}];
[%css {|font-variant-east-asian: normal|}];
[%css {|font-variant-emoji: normal|}];
[%css {|font-variant-ligatures: normal|}];
[%css {|font-variant-numeric: normal|}];
[%css {|font-variant-position: normal|}];
[%css {|font-variation-settings: normal|}];
[%css {|font-weight: bolder|}];
[%css {|font-width: normal|}];
[%css {|forced-color-adjust: auto|}];
[%css {|glyph-orientation-vertical: auto|}];
[%css {|grid-auto-flow: row|}];
[%css {|grid-template: none|}];
[%css {|grid-template-areas: none|}];
[%css {|grid-template-columns: none|}];
[%css {|grid-template-rows: none|}];
[%css {|hanging-punctuation: none|}];
[%css {|height: auto|}];
[%css {|hyphenate-character: auto|}];
[%css {|hyphenate-limit-chars: auto|}];
[%css {|hyphenate-limit-last: none|}];
[%css {|hyphenate-limit-lines: no-limit|}];
[%css {|hyphens: none|}];
[%css {|image-orientation: from-image|}];
[%css {|image-rendering: auto|}];
[%css {|image-resolution: from-image|}];
[%css {|initial-letter: normal|}];
[%css {|inset-block-end: auto|}];
[%css {|inset-block-start: auto|}];
[%css {|inset-inline-end: auto|}];
[%css {|inset-inline-start: auto|}];
[%css {|interactivity: auto|}];
[%css {|interest-delay-end: normal|}];
[%css {|interest-delay-start: normal|}];
[%css {|interpolate-size: numeric-only|}];
[%css {|justify-content: normal|}];
[%css {|justify-items: normal|}];
[%css {|justify-self: auto|}];
[%css {|left: auto|}];
[%css {|letter-spacing: normal|}];
[%css {|line-break: auto|}];
[%css {|line-clamp: none|}];
[%css {|line-height: normal|}];
[%css {|line-height-step: 0|}];
[%css {|list-style-image: none|}];
[%css {|list-style-position: inside|}];
[%css {|list-style-type: none|}];
[%css {|margin-bottom: auto|}];
[%css {|margin-left: auto|}];
[%css {|margin-right: auto|}];
[%css {|margin-top: auto|}];
[%css {|margin-trim: none|}];
[%css {|marker: none|}];
[%css {|marker-end: none|}];
[%css {|marker-mid: none|}];
[%css {|marker-start: none|}];
[%css {|mask-border-mode: luminance|}];
[%css {|mask-clip: no-clip|}];
[%css {|mask-type: luminance|}];
[%css {|math-depth: auto-add|}];
[%css {|math-shift: normal|}];
[%css {|math-style: normal|}];
[%css {|max-height: none|}];
[%css {|max-lines: none|}];
[%css {|max-width: none|}];
[%css {|min-height: auto|}];
[%css {|min-width: auto|}];
[%css {|mix-blend-mode: plus-lighter|}];
[%css {|nav-down: auto|}];
[%css {|nav-left: auto|}];
[%css {|nav-right: auto|}];
[%css {|nav-up: auto|}];
[%css {|object-fit: fill|}];
[%css {|object-view-box: none|}];
[%css {|offset-anchor: auto|}];
[%css {|offset-path: none|}];
[%css {|offset-position: normal|}];
[%css {|offset-rotate: auto|}];
[%css {|order: 0|}];
[%css {|outline-color: auto|}];
[%css {|outline-offset: 0|}];
[%css {|outline-style: auto|}];
[%css {|overflow-anchor: auto|}];
[%css {|overflow-block: visible|}];
[%css {|overflow-clip-margin: 0|}];
[%css {|overflow-inline: visible|}];
[%css {|overflow-wrap: normal|}];
[%css {|overflow-x: visible|}];
[%css {|overflow-y: visible|}];
[%css {|overlay: none|}];
[%css {|overscroll-behavior: contain|}];
[%css {|overscroll-behavior-block: contain|}];
[%css {|overscroll-behavior-inline: contain|}];
[%css {|overscroll-behavior-x: contain|}];
[%css {|overscroll-behavior-y: contain|}];
[%css {|page: auto|}];
[%css {|page-break-after: auto|}];
[%css {|page-break-before: auto|}];
[%css {|page-break-inside: avoid|}];
[%css {|paint-order: normal|}];
[%css {|pause-after: none|}];
[%css {|pause-before: none|}];
[%css {|perspective: none|}];
[%css {|pointer-events: auto|}];
[%css {|position: static|}];
[%css {|position-anchor: normal|}];
[%css {|position-area: none|}];
[%css {|position-try-fallbacks: none|}];
[%css {|position-try-order: normal|}];
[%css {|position-visibility: always|}];
[%css {|print-color-adjust: economy|}];
[%css {|quotes: auto|}];
[%css {|reading-flow: normal|}];
[%css {|reading-order: 0|}];
[%css {|resize: none|}];
[%css {|rest-after: none|}];
[%css {|rest-before: none|}];
[%css {|right: auto|}];
[%css {|rotate: none|}];
[%css {|row-gap: normal|}];
[%css {|ruby-align: start|}];
[%css {|ruby-merge: separate|}];
[%css {|ruby-overhang: auto|}];
[%css {|ruby-position: alternate|}];
[%css {|rx: auto|}];
[%css {|ry: auto|}];
[%css {|scale: none|}];
[%css {|scroll-behavior: auto|}];
[%css {|scroll-initial-target: none|}];
[%css {|scroll-margin: 0|}];
[%css {|scroll-margin-block: 0|}];
[%css {|scroll-margin-block-end: 0|}];
[%css {|scroll-margin-block-start: 0|}];
[%css {|scroll-margin-bottom: 0|}];
[%css {|scroll-margin-inline: 0|}];
[%css {|scroll-margin-inline-end: 0|}];
[%css {|scroll-margin-inline-start: 0|}];
[%css {|scroll-margin-left: 0|}];
[%css {|scroll-margin-right: 0|}];
[%css {|scroll-margin-top: 0|}];
[%css {|scroll-marker-group: none|}];
[%css {|scroll-padding: auto|}];
[%css {|scroll-padding-block: auto|}];
[%css {|scroll-padding-block-end: auto|}];
[%css {|scroll-padding-block-start: auto|}];
[%css {|scroll-padding-bottom: auto|}];
[%css {|scroll-padding-inline: auto|}];
[%css {|scroll-padding-inline-end: auto|}];
[%css {|scroll-padding-inline-start: auto|}];
[%css {|scroll-padding-left: auto|}];
[%css {|scroll-padding-right: auto|}];
[%css {|scroll-padding-top: auto|}];
[%css {|scroll-snap-align: none|}];
[%css {|scroll-snap-stop: normal|}];
[%css {|scroll-snap-type: none|}];
[%css {|scroll-target-group: none|}];
[%css {|scroll-timeline-axis: block|}];
[%css {|scroll-timeline-name: none|}];
[%css {|scrollbar-color: auto|}];
[%css {|scrollbar-gutter: auto|}];
[%css {|scrollbar-width: auto|}];
[%css {|shape-outside: none|}];
[%css {|shape-rendering: auto|}];
[%css {|speak: auto|}];
[%css {|speak-as: normal|}];
[%css {|stroke-dasharray: none|}];
[%css {|stroke-dashoffset: 0|}];
[%css {|stroke-linecap: butt|}];
[%css {|stroke-linejoin: crop|}];
[%css {|stroke-miterlimit: 0|}];
[%css {|stroke-width: 0|}];
[%css {|tab-size: 0|}];
[%css {|table-layout: auto|}];
[%css {|text-align: start|}];
[%css {|text-align-all: start|}];
[%css {|text-align-last: auto|}];
[%css {|text-anchor: start|}];
[%css {|text-autospace: normal|}];
[%css {|text-box: normal|}];
[%css {|text-box-edge: auto|}];
[%css {|text-box-trim: none|}];
[%css {|text-combine-upright: none|}];
[%css {|text-decoration-inset: 0|}];
[%css {|text-decoration-line: none|}];
[%css {|text-decoration-skip: none|}];
[%css {|text-decoration-skip-box: none|}];
[%css {|text-decoration-skip-ink: auto|}];
[%css {|text-decoration-skip-self: auto|}];
[%css {|text-decoration-skip-spaces: none|}];
[%css {|text-decoration-style: solid|}];
[%css {|text-decoration-thickness: auto|}];
[%css {|text-emphasis-position: over|}];
[%css {|text-emphasis-style: none|}];
[%css {|text-justify: auto|}];
[%css {|text-orientation: mixed|}];
[%css {|text-overflow: clip|}];
[%css {|text-rendering: auto|}];
[%css {|text-shadow: none|}];
[%css {|text-size-adjust: auto|}];
[%css {|text-spacing-trim: auto|}];
[%css {|text-transform: none|}];
[%css {|text-underline-offset: auto|}];
[%css {|text-underline-position: auto|}];
[%css {|text-wrap-mode: wrap|}];
[%css {|text-wrap-style: auto|}];
[%css {|timeline-scope: none|}];
[%css {|timeline-trigger: none|}];
[%css {|timeline-trigger-activation-range-end: normal|}];
[%css {|timeline-trigger-activation-range-start: normal|}];
[%css {|timeline-trigger-active-range-end: auto|}];
[%css {|timeline-trigger-active-range-start: auto|}];
[%css {|timeline-trigger-name: none|}];
[%css {|top: auto|}];
[%css {|touch-action: auto|}];
[%css {|transform: none|}];
[%css {|transform-box: content-box|}];
[%css {|transform-origin: left|}];
[%css {|transform-style: flat|}];
[%css {|transition-property: none|}];
[%css {|translate: none|}];
[%css {|trigger-scope: none|}];
[%css {|unicode-bidi: normal|}];
[%css {|user-select: auto|}];
[%css {|vector-effect: none|}];
[%css {|vertical-align: first|}];
[%css {|view-timeline-axis: block|}];
[%css {|view-timeline-inset: auto|}];
[%css {|view-timeline-name: none|}];
[%css {|view-transition-class: none|}];
[%css {|view-transition-name: none|}];
[%css {|visibility: visible|}];
[%css {|voice-balance: 0|}];
[%css {|voice-duration: auto|}];
[%css {|voice-family: preserve|}];
[%css {|voice-pitch: x-low|}];
[%css {|voice-range: x-low|}];
[%css {|voice-rate: normal|}];
[%css {|voice-stress: normal|}];
[%css {|voice-volume: silent|}];
[%css {|white-space: normal|}];
[%css {|white-space-collapse: collapse|}];
[%css {|width: auto|}];
[%css {|will-change: auto|}];
[%css {|word-break: normal|}];
[%css {|word-space-transform: none|}];
[%css {|word-spacing: normal|}];
[%css {|writing-mode: horizontal-tb|}];
[%css {|z-index: auto|}];
[%css {|zoom: 0|}];
