Two files declaring the same at-rule atoms in opposite source order must
converge on the same stylesheet: position is a function of the rule, not
of file order. (This is the demo's queryOrder/queryOrderReversed pair.)

  $ cat > forward.ml <<EOF
  > [@@@css ".css-base{color:black;}"]
  > [@@@css "@media (min-width: 400px) {.css-m{color:red;}}"]
  > [@@@css "@container (width > 400px) {.css-c{color:green;}}"]
  > [@@@css "@supports (display: flex) {.css-s{color:blue;}}"]
  > EOF

  $ cat > reversed.ml <<EOF
  > [@@@css "@supports (display: flex) {.css-s{color:blue;}}"]
  > [@@@css "@container (width > 400px) {.css-c{color:green;}}"]
  > [@@@css "@media (min-width: 400px) {.css-m{color:red;}}"]
  > [@@@css ".css-base{color:black;}"]
  > EOF

  $ styled-ppx.generate forward.ml reversed.ml > ab.css
  $ styled-ppx.generate reversed.ml forward.ml > ba.css
  $ diff ab.css ba.css
  $ cat ab.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-base{color:black;}
  @supports (display: flex) {.css-s{color:blue;}}
  @media (min-width: 400px) {.css-m{color:red;}}
  @container (width > 400px) {.css-c{color:green;}}
