Test box-shadow and text-shadow interpolation support in cx2

  $ refmt --parse re --print ml input.re > output.ml
  $ standalone --impl output.ml -o output.ml
  $ styled-ppx.generate output.ml > styles.css
  $ cat styles.css
  /* This file is generated by styled-ppx, do not edit manually */
  .css-* { box-shadow: var(--var-*); } (glob)
  .css-* { box-shadow: var(--var-*); } (glob)
  .css-zic50l { box-shadow: none; }
  .css-1chbfez { box-shadow: 0px 2px 4px 0px rgba(0, 0, 0, 0.1); }
  .css-* { text-shadow: var(--var-*); } (glob)
  .css-* { text-shadow: var(--var-*); } (glob)
  .css-* { text-shadow: none; } (glob)
  .css-* { box-shadow: var(--var-*); } (glob)


