The --minify flag drops the newline separator between rules.

  $ cat > a.ml <<EOF
  > [@@@css ".a{color:red;}"]
  > [@@@css ".b{color:blue;}"]
  > EOF

Without --minify (default), each rule is on its own line.

  $ styled-ppx.generate a.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}
  .b{color:blue;}

With --minify, rules are concatenated with no separator.

  $ styled-ppx.generate --minify a.ml
  /* This file is generated by styled-ppx, do not edit manually */
  .a{color:red;}.b{color:blue;}
