module X = {
  let value = 1.;
  let flex1 = `num(1.);
  let min = `px(500);
};

/* CSS Flexible Box Layout Module Level 1 */
[%cx2 {|align-content: flex-start|}];
[%cx2 {|align-content: flex-end|}];
[%cx2 {|align-content: space-between|}];
[%cx2 {|align-content: space-around|}];
[%cx2 {|align-items: flex-start|}];
[%cx2 {|align-items: flex-end|}];
[%cx2 {|align-self: flex-start|}];
[%cx2 {|align-self: flex-end|}];
[%cx2 {|display: flex|}];
[%cx2 {|display: inline-flex|}];
[%cx2 {|flex: none|}];
[%cx2 {|flex: 5 7 10%|}];
[%cx2 {|flex: 2;|}];
[%cx2 {|flex: 10em;|}];
[%cx2 {|flex: 30%;|}];
[%cx2 {|flex: min-content;|}];
[%cx2 {|flex: 1 30px;|}];
[%cx2 {|flex: 2 2;|}];
[%cx2 {|flex: 2 2 10%;|}];
[%cx2 {|flex: $(X.flex1);|}];
[%cx2 {|flex: $(X.value) $(X.value);|}];
[%cx2 {|flex: $(X.value) $(X.value) $(X.min);|}];
[%cx2 {|flex-basis: auto|}];
[%cx2 {|flex-basis: content|}];
[%cx2 {|flex-basis: 1px|}];
[%cx2 {|flex-direction: row|}];
[%cx2 {|flex-direction: row-reverse|}];
[%cx2 {|flex-direction: column|}];
[%cx2 {|flex-direction: column-reverse|}];
[%cx2 {|flex-flow: row|}];
[%cx2 {|flex-flow: row-reverse|}];
[%cx2 {|flex-flow: column|}];
[%cx2 {|flex-flow: column-reverse|}];
[%cx2 {|flex-flow: wrap|}];
[%cx2 {|flex-flow: wrap-reverse|}];
[%cx2 {|flex-grow: 0|}];
[%cx2 {|flex-grow: 5|}];
[%cx2 {|flex-shrink: 1|}];
[%cx2 {|flex-shrink: 10|}];
[%cx2 {|flex-wrap: nowrap|}];
[%cx2 {|flex-wrap: wrap|}];
[%cx2 {|flex-wrap: wrap-reverse|}];
[%cx2 {|justify-content: flex-start|}];
[%cx2 {|justify-content: flex-end|}];
[%cx2 {|justify-content: space-between|}];
[%cx2 {|justify-content: space-around|}];
[%cx2 {|min-height: auto|}];
[%cx2 {|min-width: auto|}];
[%cx2 {|order: 0|}];
[%cx2 {|order: 1|}];
